### ISSUE TITLE
File names too long for git on windows

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#1009]
### Description

I can't git pull the current flavors 😢 

```
error: unable to create file GE_PCASL_3Dspiral_25.0LX_product_1/sourcedata/sub-001/20000101164456/Series 003 [MR - FSPGR 1mm sag TI450]/1.3.6.1.4.1.5962.99.1.1314016974.1904482511.1611926785742.180.0.dcm: Filename too long
```
With this, I also need to fix ASLcontexts!!
### Release notes

Nothing - this was only about flavor names and updating the references.

**Comment by jan-petr** [comment]
@MichaelStritt this is done. check if you can pull the flavors now. I shortened the names in almost all flavors. This was probably the only one I forgot to do ;)
