### ISSUE TITLE
Merge MoCo settings

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1014]
### Description

We should merge motion correction booleans.

### Requirements

* `bMotionCorrection` inside `xASL_wrp_Realign` should be renamed to `x.asl.module.bMotionCorrection`
* `x.asl.module.motionCorrection` should be renamed in all instances to `x.asl.module.bMotionCorrection`

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here

**Comment by MichaelStritt** [comment]
#1014 - these are two different things
1. is a global user setting
2. is a local data-derived option

These two can't be merged. But I agree that renaming might be necessary to avoid confusion? Agree?
