### ISSUE TITLE
Fix processing of TestDataSet-10

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1030]
### Description

- [x] `Philips_3DGRASE_FLAIR_M0_2ndRun_HiQ` - M0PositionInASL4D was in ASL4D.json despite it should have been removed after ASL/M0 split. Fix this in the dataset.
- [x] `Philips_2DEPI_Lesion_NoFLAIR_NoM0_HiQ` - ASLT1w registration was incorrect in 1.8.0, but is now fixed :D Probably by fixing during 1.9.0 development :)
- [x] `Philips_3DGRASE_MultiSessions_T1wAlreadyDone_LoQ` - there's a drop of contrast in rM0.nii in the frontal lobe.
- [x] `Siemens_2DEPI_noBsup_FLAIR_LoQ` - investigating...
- [x] `Siemens3DGRASE_Structural_AlreadyDone_HiQ` - difference in rM0.nii, but the 1.9.0 version actually looks better

Line 85 in `xASL_im_M0ErodeSmoothExtrapolate.m` the fixed value 0.6 used to be 0.7 creating now differences between 1.8 and 1.9

Also check Flavors processing of the following flavors:

- [x] `Siemens_PCASL_3DGRASE_VD13D_2`
- [x] `GE_PCASL_3Dspiral_25.0LX_ADNI3_027_S_5079_1`
- [x] `Philips_PASL_2DEPI_5.4.0.2-LookLocker_1`
- [x] `Philips_PCASL_2DEPI_PARREC_2`
- [x] `Philips_PCASL_3DGRASE_5.1.7.2_1`
- [x] `Siemens_PASL_3DGRASE_E11_1`
- [x] `Siemens_PASL_3DGRASE_VE11C_2`
- [x] `Siemens_PCASL_3DGRASE_VB17A_multiPLD_1`
- [x] `Missing file catreport_.*.pdf in derivatives...` for `Siemens_PASL_3DGRASE_E11_1`
- [x] `Siemens_PCASL_3DGRASE_VD13A_Hadamard8FME_1`

### Release notes

Required: summarize the changes for the release notes here

**Comment by HenkMutsaerts** [comment]
@jan-petr I suggest to revert the threshold to 0.7 for now, to keep 1.9.0 comparable with 1.8.0. And we later fix this in [issue 1033](https://github.com/ExploreASL/ExploreASL/issues/1033)

**Comment by jan-petr** [comment]
> @jan-petr I suggest to revert the threshold to 0.7 for now, to keep 1.9.0 comparable with 1.8.0. And we later fix this in [issue 1033](https://github.com/ExploreASL/ExploreASL/issues/1033)

Done. Now re-running TestDataSet
