### ISSUE TITLE
Test check process flavors

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1034]
### Description

In xASL_test_CheckProcessedFlavors at line 43, we define what all file should be checked. However, we don't have many of those files for obvious reasons - we can't have `catreport` if no structural image is provides etc.

### Requirements

Optional: add bug requirements here

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Duplicate. Nothing to release

**Comment by MichaelStritt** [comment]
@jan-petr: I created a reference [JSON file](https://github.com/ExploreASL/FlavorDatabase/blob/main/flavors.json) and I also wrote some initial [lines of code]( d42cf7c ) to adapt the derivatives validation. There's like a million things that can be approved here, but I think my implementations could be helpful.
