### ISSUE TITLE
xASL_adm_GzipAllFiles.m improve linux behaviour

### ISSUE THREAD

**Issue by MDijsselhof** [ExploreASL/ExploreASL#1052]
### Description

Requested for by @HenkMutsaerts:

Current `xASL_adm_GipAllFiles.m` behaviour is not optimised in Linux. 

JAN: Might have been fixed in #1164 
HENK: May be addressed in #1285

**Comment by MichaelStritt** [comment]
We should also make sure that Maurice's code for the gzipping on windows works in compiled mode or we default to the slower version right away. Right now it crashes and defaults to the slower version.

**Comment by HenkMutsaerts** [comment]
Is adressed in #1164 and hopefully in #1285
