### ISSUE TITLE
BIDS

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#11]
Preparing the ExploreASL for full BIDS compatibility.

**Comment by HenkMutsaerts** [comment]
One easy thing we can easily do here, is to allow the xASL_init_FileSystem to accept the BIDS structure. This shouldn't change the code too much, as all other code uses the x.P. path definitions from this function. Later we can then add the full interpreter that Pieter built

**Comment by HenkMutsaerts** [comment]
## What we concluded we should do
>This will be a continuous process

* BIDS Directory structure -> find hardcoded paths & make dependent on x.P -> do step by step. This way we only have to change the definitions inside _xASL_init_FileSystem.m_
* Parameter names -> interpret in _xASL_adm_LoadParms_ -> & make sure they are dependent throughout

**Comment by HenkMutsaerts** [comment]
## ToDo
* 1. Create script to go from ExploreASL_Import.m output to ASL-BIDS: ExploreASL_Import2BIDS;
* 2. Create script to go from ASL-BIDS to ExploreASL structure. This will be used temporarily, and we will later make this function obsolete when ExploreASL will be completely BIDS-proof;
* 3. Slowly but steadily make ExploreASL inner structure/nomenclature BIDS;
* 4. ExploreASL output to (ASL-)BIDS derivative structure converter

## We already have
* xASL_adm_Load2Parms: load both ASL-BIDS/dcm2niiX export/ExploreASL old data structure/names and convert them to the ExploreASL internal nomenclature (which will move to BIDS)

**Comment by jan-petr** [comment]
Created new issues #163, #164, #165 that will deal with those issues.
