### ISSUE TITLE
Saving Tanimoto Coefficient of the final ASL-T1w registration

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#112]
Will be saved as one of the QC parameters.
Henk: Name the structure and field for saving this.
Jan: Implement.

**Comment by HenkMutsaerts** [comment]
Looks good. While we're at it, why don't we add the 1) TC computation, 2) printing to screen, 3) adding it to the QC output field, to all registration functions? These should be:

1) _010_LinearReg_T1w2MNI_ -> _TC_T1w2MNI_Perc_
2) _020_LinearReg_FLAIR2T1w_ -> _TC_FLAIR2T1w_Perc_
3) _060_ProcessM0_ -> _TC_M02ASL_Perc_

We could rename _T1_ to _T1w_ throughout (so also in _xASL_wrp_RegisterASL.m_), as _T12MNI_ is less readable then _T1w2MNI_. Although then we should also use _M0w2ASL_ :)

Then we can generate this as PR to the develop branch.

**Comment by jan-petr** [comment]
I have renamed it to TC_ASL2T1w_Perc in the registerASL. I agree and will implement all the other three. But I would use M0 and not M0w.

What about the output of QC values to a table - any hint there?

**Comment by jan-petr** [comment]
OK - I can do that. But I would include it in the population module. We already calculate the motion, dicom and volume statistics. It would be easy (and potentially helpful) to also do the registration statistics (especially if we want to add the other TC_Perc later).

**Comment by HenkMutsaerts** [comment]
* I wouldn't include the xKeep, this is already organized generally, that the x struct gets cleaned in the memory for the next subject, but saved on the disk for retrieval. You should be able to still load it from the x.mat after removal from memory, so I would cancel this last commit
* Fine to include it in the population module, I would just be a bit careful as every new feature can introduce bugs

**Comment by jan-petr** [comment]
The commit fixes other things, so I wouldn't remove it. But I agree to remove the xKeep - that was only provisionary. The TC_ASL2T1w wasn't in the x.mat either - it got completely wiped out.

So we need xKeep, or any other similar solution to keep it from deleting. An alternative would be to call again the function to calculate the overlap in the QC part. I wanted to avoid it to prevent other bugs and to not increase the processing time, but it is perhaps the best solution - what do you think?

OK - I'll include the PrintRegistrationStats to the Population module after enough testing. Just tell me if I should have a new lock for it, or couple it with another one. I'll also test that this works with subjects that doesn't have the TC saved at all.

I can either add it to 060_GetMotionStatistics, or make a 065_GetRegistrationStatistics. Or another solution?

**Comment by HenkMutsaerts** [comment]
* x.Output & x.Output_im should at the beginning of the Structural/ASL module:
1) load x.mat (overwriting only relevant fields)
And at the end of a module:
2) save new x.mat (overwriting only relevant fields)

What we don't have yet, is:
* QC value and image should be generated as the output of each submodule and saved in the x.mat. Now, this is all combined at the end of a module in a QC submodule.
So probably the issue is that at the beginning of the QC submodule, x.Output & x.Output_im are cleared and x.mat is loaded. So the current simplest/best solution is to save the QC_Perc field to x.mat after generating the TC*Perc, don't you agree? When x.mat is loaded from disk, only the pre-existing fields from memory will overwrite those from the disk copy, as this would be a new pipeline run.

* 065_GetRegistrationStatistics is the best idea! Keep things separate. We can merge all these stats later :)

**Comment by jan-petr** [comment]
Still don't perfectly understand. What does mean the first part? Overwriting relevant fields??

I perfectly agree that QC value and image should be generated in each submodule and saved in the x.mat, instead of retrospectively filling all in the QC submodule - I would leave the QC submodule only for some tasks that are not best fitting to be done in the previous submodules.

Yes, the issue is indeed that x.Output is cleared at the beginning of QCsubmodule. I would move this clearing at the beginning of ASL module - this alone will solve all my issues.

I agree that putting TC*Perc to x.Output.ASL.TC* right in the Registration submodule is the best idea. But I don't understand if you mean saving to x.mat or x-struct.

I don't undertand what you mean here "When x.mat is loaded from disk, only the pre-existing fields from memory will overwrite those from the disk copy, as this would be a new pipeline run."

OK about 065 - will do that. Note that right now, that feature branch is really messed up - I hope that pulling and rebasing everything will help here.

**Comment by HenkMutsaerts** [comment]
* The point is it should always save to x.mat, never to x-struct. This ensures that we don't care where in the pipeline you have a crash, or you start again. If the registration submodule has been run, but it crashes after this, and you restart the ASL module which skips the registration submodule, it should find the TC field in the x.mat (as it cannot find it in the x-struct).

So each submodule should:
1) clear x.Output*
2) load existing QC Output from x.mat
3) add new QC Output to x.mat
4) clear x.Output

So you only have to change _xASL_wrp_RegisterASL.m_, not other modules or wrappers...

* Which feature branch is messed up?

**Comment by jan-petr** [comment]
Thanks - this explains it all. BTW: Saving and loading of x.mat can happen just before the running of the submodule or inside it? Or you don't care?

**Comment by jan-petr** [comment]
Messed up: bugs 119 and 120, that are quite unique to my setting, and also I miss all the fixes from the hotfix ;)

**Comment by HenkMutsaerts** [comment]
* I don't think we care at this point if x.mat goes inside or outside the submodule, I would use the option that changes the least for now. We need to get a standard for this. Probably each submodule should have a standard QC output argument, and then the xASL_module_ASL can iterate submodules with loading and saving the x.mat

* Can't see fixes for #119 or #120 but cherry-picking always works fine. See the Git workflow if you need to do this at your location :)

**Comment by jan-petr** [comment]
OK - x.mat saving with least editing...

I did some manual cherry-picking - copy pasted a few things in the branch to have it for testing, but won't commit them.

**Comment by jan-petr** [comment]
I went through the ASL_module. And it seems that the x.mat or x.Output is never saved for any ASL submodule. 
Although there's the xASL_adm_LoadX function and so on.

So I will start working on it. I will clear the Output.ASL at the start of the module instead of in the QCsubmodule. And I'll start adding this x.mat Output loading and saving - for starters to the register module, but will create a new issue for all modules.

**Comment by jan-petr** [comment]
See the latest commit - the TC*Perc saving in ASL module should be to your liking.

I will now run a more complex testing and I will also add the 065_GetRegistrationStatistics feature and then will make a PR.
