### ISSUE TITLE
NII>BIDS conversion if no DICOM exists

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1128]
### Description

If NIfTI is part DICOM source data, then it shouldn't ignore them but include them in the import. This would work similar to having an enhanced DICOM file or PAR/REC, so the token is done on the file instead of folder, and then instead of running `dcm2niiX` the NIfTI files are copied to the new path. A warning may be given if they don't include a .json-file (which is not required for T1w/FLAIR).

Start with structural files only and ignore possible missing JSONs.

Do perf files in a second issue in the future.

JAN: The issue is - how should this work? Because PAR/REC files and enhanced DICOMs are run in a "match-file" mode, and DICOMs in "match-directory" mode. So should work with NII only if we work with files, or also if we work with directories. If we work with directories, then I should simply look for NII+JSON inside a matched directory. Or should I look for files that have the same name as a directory. Because then we would have to implement a mixed file-directory mode. All this would be possible. only more complicated. 

HENK: For now, I would just use NII similar to PAR/REC in a "match-file" mode.

### Release notes

Required: summarize the changes for the release notes here

**Comment by HenkMutsaerts** [comment]
Duplicate with #1300

**Comment by HenkMutsaerts** [comment]
Duplicate with #1300
