### ISSUE TITLE
Duplicate key warning checking TimeEncoded

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1145]
### Description

<img width="749" alt="image" src="https://user-images.githubusercontent.com/27774254/183239787-7149259c-14d0-4760-b97e-a30706c456eb.png">

This warning occurred with the flavor Philips_PCASL_3DGRASE_5.6.1.1_CBFonly_1

### Tasks

- [x] Jan Petr check what goes wrong here

### Release notes

Nothing to report. Error was in studyPar.json, not in the code.

**Comment by jan-petr** [comment]
There was a double entry of LabelingType in studyPar.json - i.e. error in the input data which perfectly justified the warning.
