### ISSUE TITLE
BIDS2Legacy Mutex Error when running in parallel

### ISSUE THREAD

**Issue by MauricePasternak** [ExploreASL/ExploreASL#1173]
### Description

Running ExploreASL (v1.10.0_BETA) in parallel results the BIDS2Legacy module failing in n-1 processes, basically killing any potential for parallel processing. See also #1275 

![BIDS2LegacyMutexError](https://user-images.githubusercontent.com/57411571/186562062-9c0c8076-aa65-45b5-bc84-34b8a009ba8c.png)

### Tasks

- [x] Splitting of subjects across should be done before BIDS2Legacy module is started.

### How to test

Run ExploreASL in parallel with 2 or more subjects.

### Release notes

Fixed a bug in which BIDS2Legacy mutex errored when running ExploreASL in parallel.

**Comment by HenkMutsaerts** [comment]
Duplicate with #1547
