### ISSUE TITLE
-C flag in compilation incompatible with Singularity

### ISSUE THREAD

**Issue by dariusvalevicius** [ExploreASL/ExploreASL#1177]
I was trying to run the xASL official Docker image in Singularity, which produced root access errors (Singularity runs as a non-root user). At runtime, MCR wants to extract the contents of xASL_latest.CTF into a new folder in the same parent directory, under /opt/, which is read-only.

This can be fixed by dropping the '-C' flag during tool compilation, which allows the user to select, via environment variable MCR_CACHE_ROOT, an extraction destination like /tmp/, which has user write access.

Is there any reason for the -C flag to be used in compilation? Could it be dropped in future official releases?

**Comment by HenkMutsaerts** [comment]
Hi Darius, I would have to check, never converted the Docker to Singularity. @maartenhammer can you have a look?

**Comment by maartenhammer** [comment]
Hi @dariusvalevicius Darius, is there a possibility to run extractCTF in singularity/docker before runnin xASL and providing the paths manually to a non-root directory? If I read the MCR/MCC documentation correctly, the extraction should only happen on first runtime.

**Comment by dariusvalevicius** [comment]
Hi @maartenhammer, I tried running extractCTF from my wrapper's dockerfile, but MCR still seems to want to extract at application runtime even if the extracted files are already in the target directory. Not sure if there is a way to disable that?

**Comment by dariusvalevicius** [comment]
My current workaround was to recompile xASL without the -C flag and set MCR_CACHE_ROOT to a subdirectory of /tmp/, and use this image as the base layer instead of the official release. This fixes the CTF extraction permission error in singularity.

I'm now running into a permission error when running the structural module:

```
Running SPM job 'Coregister: Estimate'

SPM12: spm_coreg (v6435)                           11:50:30 - 31/08/2022
========================================================================
Smoothing [2 2 2] into [0 0 0] FWHM resolution
Smoothing [2 2 2] into [0 0 0] FWHM resolution for scan 1
Registering scan 1...  
100%, 
Completed                               :          11:50:40 - 31/08/2022
Error: Permission denied
There was a problem writing to the header of
  "/home/darius/my_cbrain_projects/explore_asl/ExploreASL-CBRAIN/ds000240_xasl_output/derivatives/ExploreASL/sub-02_1/ASL_1/ASL4D_Source.nii"
Failed  'Coregister: Estimate'
Error using nifti/create (line 26)
Unable to write header for "/home/darius/my_cbrain_projects/explore_asl/ExploreASL-CBRAIN/ds000240_xasl_output/derivatives/ExploreASL/sub-02_1/ASL_1/ASL4D_Source.nii".
In file "/tmp/mcr_cache/.mcrCache9.11/xASL_l0/xASL_latest/External/SPMmodified/@nifti/create.m" (???), function "create" at line 26.
In file "/tmp/mcr_cache/.mcrCache9.11/xASL_l0/xASL_latest/External/SPMmodified/spm_get_space.m" (???), function "spm_get_space" at line 51.
In file "/tmp/mcr_cache/.mcrCache9.11/xASL_l0/xASL_latest/External/SPMmodified/config/spm_run_coreg.m" (???), function "spm_run_coreg" at line 30.

The following modules did not run:
Failed: Coregister: Estimate


ERROR: Structural module terminated for subject 2: sub-02_1

ans =

    'Error using MATLABbatch system
     Job execution failed. The full log of this run can be found in MATLAB command window, starting with
     the lines (look for the line showing the exact #job as displayed in this error message)
     ------------------
     Running SPM job #1
     ------------------'
```

In the output directory, .../sub-02_1/ASL_1/ contains the following files:

```
-rw-rw-r-- 1 darius darius      781 Aug 31 11:50 ASL4Dcontext_Source.tsv
-rw-rw-r-- 1 darius darius      712 Aug 31 11:50 ASL4Dcontext.tsv
-rw-rw-r-- 1 darius darius     3565 Aug 31 11:50 ASL4D.json
-rw-rw-r-- 1 darius darius    12992 Aug 31 11:50 ASL4D.mat
-rw-rw-r-- 1 darius darius 10829807 Aug 31 11:50 ASL4D.nii.gz
-rw-rw-r-- 1 darius darius     3565 Aug 31 11:50 ASL4D_Source.json
-r--r--r-- 1 darius darius  8815075 Aug 31 11:50 ASL4D_Source.nii.gz
-rw-rw-r-- 1 darius darius     2749 Aug 31 11:50 M0.json
-rw-rw-r-- 1 darius darius  1465054 Aug 31 11:50 M0.nii.gz
```
When executing in Docker, I have this:
```
-rw-r--r-- 1 root root      781 Aug 31 12:24 ASL4Dcontext_Source.tsv
-rw-r--r-- 1 root root      712 Aug 31 12:24 ASL4Dcontext.tsv
-rw-r--r-- 1 root root     3565 Aug 31 12:24 ASL4D.json
-rw-r--r-- 1 root root 23347552 Aug 31 12:24 ASL4D.nii
-rw-r--r-- 1 root root     3565 Aug 31 12:24 ASL4D_Source.json
-r--r--r-- 1 root root 12841312 Aug 31 12:24 ASL4D_Source.nii
-rw-r--r-- 1 root root     2749 Aug 31 12:24 M0.json
-rw-r--r-- 1 root root  2335072 Aug 31 12:24 M0.nii
```

It seems like the .nii.gz files aren't extracting correctly in Singularity. Any idea why this might be related to permissions?

**Comment by maartenhammer** [comment]
Hi Darius,
I don't think the extraction is the issue here, you can see that in .../sub-02_1/ASL_1/ the rights of the ASL4D_Source.nii(.gz) file are -r--r--r-- in both the docker and the singularity scenario.
This means its read-only for all users including the owner. Tracing back to the error message it opens the files in 'r+' (read and write) or 'w+' (create file with read and write acces) in the function spmModified/private/write_hdr_raw.m. As you acces the file as root user in docker, these permissions are ignored, but in singularity you open it as a user, where permissions are relevant. 

For now you could try `chmod 644 ASL4D_Source.nii.gz` which changes the rights to -rw-r--r-- and the module should continue.

@HenkMutsaerts I assume xASL makes this file read only by default as a matter to protect source data, alternatively, does it copy the rights of the source structure? If the latter is true, this could be changed such that the copy placed in the derivative directory has -rw- acces. If the file shouldn't be modifiable a change has to be implemented that it ignores this file.

**Comment by HenkMutsaerts** [comment]
I believe ExploreASL/Matlab by default keeps permissions when copying these, although I have written a script to check for this and warn (which can take quite a long time; we have it as an option that is disabled by default in the import module).

ExploreASL aims to keep all NIfTI data as `.nii.gz` but at the same time not to zip and unzip iteratively, so at the beginning of the processing it will unzip and only at the very end of the processing pipeline it will zip again. Matlab's gzipping uses JavaVM but I think I fixed this, such that it will also run with JavaVM.

@maartenhammer A nice touch would be if we can check for read- and write-access in the `/derivatives/ExploreASL` processing folder, as well as the copied files there, and issue a specific warning if this is not the case.
