### ISSUE TITLE
Structural Lock files are not created for the last subject

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#119]
At least not in the Craniosynostosis study where dummy T1files are created.

**Comment by HenkMutsaerts** [comment]
We need a little bit more info from you about this issue ;)

**Comment by jan-petr** [comment]
There's not more. Last subject is mean the last there is, not a specific subject.

If I run a study without T1 that uses the dummyT1 parameter, then for the last of the subject, the structural module doesn't not create any lock files. Or the lock files are deleted or something. I have to investigate more what's happening. I have encountered this with the craniostudy, but it will probably happen with any other study with dummyT1.

Does this explain it?

**Comment by HenkMutsaerts** [comment]
Yes, try to see if xASL_adm_CleanUpBeforeRerun is the issue? This function is flexible, meaning that it can be used to cleanup a full ASL population, but inside the modules this is used to clean up if it detects a rerun (by absence of certain lock files). But this stuff assumes that for the structural module you should clean the structural module locks, and vice versa for ASL, perhaps something goes wrong here. But we should be careful with making too many if statements, rather generalize if we can.

**Comment by jan-petr** [comment]
It wasn't the cleanup. The problem was in the main file of the structural module. The lock directory gets locked and is unlocked only upon finishing the whole structural module. This is not done when T1 files are missing. This was not a problem for most patients as the unlocking happened when going for the next patient. But for the last patient, the lock directory of the structural module remained locked and the ASL module was not able to write in it.

Structural module not unlocks the lock directory also when no T1 files are found.

**Comment by HenkMutsaerts** [comment]
Fine to merge this!
