### ISSUE TITLE
Iterate Statistics over multiple DataTypes (E.g., TExch, SD, etc)

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#1197]
### Description

If we had another string to line 230 (see printscreen below), we need to iterate the ROIstatistics through the measures as well (so not only qCBF but also TExch, SD, etc)
![image](https://user-images.githubusercontent.com/73699072/192225737-5448933d-4960-4e59-baa1-9518fc09c529.png)

### Tasks

- [x] Check if x.S.InputDataStr can be a cell array
- [x] Add this option to dataPar.json, so that we don't need to hardcode everytime we need the stats for TExch e.g.

### Release notes
Allow configuring the image contrast for statistics in dataPar.json.

**Comment by HenkMutsaerts** [comment]
@BeatrizPadrela  can you point me to an example dataset that has the `Texch` and other maps already outputted to the population folder?
