### ISSUE TITLE
BIDS to Legacy conversion starts unnecessary

### ISSUE THREAD

**Issue by MDijsselhof** [ExploreASL/ExploreASL#1198]
### Description

While trying to re-run the population module, using `ExploreASL('dataroot', 0, [0 0 1], 0, 1, 1)` the import module starts the BIDS to Legacy conversion automatically.

![image](https://user-images.githubusercontent.com/75380250/192779196-a71bf94c-4c90-45de-99ef-593630f3d698.png)

### Release notes

Report with #1547.

**Comment by HenkMutsaerts** [comment]
Closing this as obsolete
