### ISSUE TITLE
Bug in xASL_im_CreateAnalysisMask in native space mode in parallel execution.

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#120]
Can crash if run in native space mode and in parallel.

The line 170 that creates smoothed version of the templates operates on the original templates directory - creating a conflict when multiple instances are accessing it at once.

This, and potentially other similar parts of the code have to make sure that the file is copied to patient directory and processing is done locally:

Error on line 170:
pathTmpPreSmooth = xASL_im_PreSmooth(x.P.Path_PWI,listMasks{kk},[],x.S.optimFWHM_mm,[],x.P.Path_mean_PWI_Clipped_sn_mat, 1);

**Comment by HenkMutsaerts** [comment]
Are you sure? xASL_im_CreateAnalysisMask shouldn't be run in parallel, this is called inside the population module.

Also, you still need to "unmess" the native space analysis ;) It sounds like an overkill to take the population-based FoV mask back to the native space when it should be there already? Pre-smoothing before downsampling a binary image? ;)

This proper rewriting of the native space part in the population module may become increasingly difficult when we add other new edits...

**Comment by jan-petr** [comment]
I know about the unmess :D
Yes, the population module is not normally run in parallel, unless you are evaluating two studies at once. In that case - it tries to access one file by two programs and can crash.

The population-based FoV mask is not in the native space - because it is created based on all subjects in the standard space. So it has to be taken back. I can remove the pre-smoothing though.

So far, no conflicting features were added... But yes - we have to prioritize this, but we also need to fix all the bugs and do all the urgent features - vicious circle...
