### ISSUE TITLE
Change ReadMe to include exploreasl.lab@gmail.com in 1.10

### ISSUE THREAD

**Issue by maartenhammer** [ExploreASL/ExploreASL#1222]
### Release 1.10
We recently added the exploreasl.lab@gmail.com mailbox as a way to reach out to us, we should add it to the read me instead of/alongside with the email adresses of Jan and Henk-Jan. 
Henk-Jan suggested to also include a link to the discussion section of ExploreAsl as alternative place for questions. 
The Explore ASL website already links to the newly created mailbox.

**Comment by jan-petr** [comment]
Agree. Lets also make sure that the documentation on GitHub has that as well.
