### ISSUE TITLE
Population module error with susceptibility mask

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1230]
### Description

am receiving an error in the population module here. Attached also is the studyPar.json file and one zipped ASL folder with the ASL and structural module done. The version being used is ExploreASL 1.10 beta I believe. Could you kindly see where I may have a parameter missing? I am thinking it would use 3d stack of spiral, but from what I can read from error msg, it thinks otherwise : ERROR: Population module terminated

ans =

    'Operands to the logical and (&&) and or (||) operators must be convertible to logical scalar values.
     
     Error in xASL_im_CreateAnalysisMask>xASL_im_CreateAnalysisMask_LegacySusceptibilityMasking (line 284)
         if isfield(x, 'Q') && isfield(x.Q, 'Sequence') && regexpi(x.Q.Sequence, '2d_epi|3d_grase')
     
     Error in xASL_im_CreateAnalysisMask (line 135)
         xASL_im_CreateAnalysisMask_LegacySusceptibilityMasking(x, PathSusceptibilityMask, Threshold, MaskFoV);
     
     Error in xASL_module_Population (line 114)
         x = xASL_im_CreateAnalysisMask(x);
     
     Error in xASL_init_Iteration>runIteration (line 382)
                        [result, x] = jobfn(x); % [result, x] = jobfn(x, job_ex);
     
     Error in xASL_init_Iteration (line 125)
         [bAborted, xOut] = runIteration(dbSettings);
     
     Error in ExploreASL_Process (line 125)
             [~, x] = xASL_init_Iteration(x,'xASL_module_Population');
     
     Error in ExploreASL (line 97)
             x = ExploreASL_Process(x);'

CONT: but continue with next iteration!

### Release notes

Nothing. Duplicate.

**Comment by mghuescar** [comment]
Hi, I'm getting this same error. Has this been solved?

I'm running ExploreASL version 1.10.1 on a mac.
