### ISSUE TITLE
Unit test import issue

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1253]
### Description

Unit test errors related to the import module.

### Tasks

- [x] xASL_imp_StudyParPriority	function	0 - the problem resolved after fixing the other issue. Or it is at least no longer there on my computer.
- [x] xASL_bids_JsonCheck	function	0 - it was expecting to find ArterialSpinLabelingType, LabelingDuration, and PostLabelingDelay in M0.json, but these should be removed.

### Release notes

Bug fix in Import unit testing

**Comment by maartenhammer** [comment]
xASL_imp_StudyParPriority function 0 
 Fixed by Jan, was a naming issue with 'studyParMultiParameter.json' being incorrectly named in the testing directory.
