### ISSUE TITLE
Multicontext Import - Some studyPar fields carry over into other contexts

### ISSUE THREAD

**Issue by MauricePasternak** [ExploreASL/ExploreASL#1268]
### Description

Tested with the GUI when importing two different contexts:
- GE 3D Spiral; PCASL
- Siemens 3D GRASE; PASL

Import went fine (in this case), but it seems parameters from BIDS ASL sidecars in the GE subset bled over into the Siemens subset. 

![Screenshot from 2022-12-17 13-55-48](https://user-images.githubusercontent.com/57411571/208257597-4ebbf08a-6e09-4cea-bae6-a955c5a88cfe.png)

The 1.45 Labeling Duration you see was defined for the GE subset. It carried on over to the Siemens one (invalidating it because the Siemens is PASL, which shouldn't have LabelingDuration present).

Thankfully common fields to contexts (i.e. Arterial Spin Labeling Type) do not overwrite between contexts, regardless of whether they are present in the DICOM headers or not. 

This issue seems to only occur for fields whose presence/absence is variable (i.e. BackgroundSuppressionPulseTime, LabelingDuration, BolusCutOffDelayTime, etc.)

check also #1279 

### Tasks

- [ ] Perform some minor BIDS validation when switching contexts. Remove incompatible fields from the previous context. Multiple scenarios of this exist, including:
    - PCASL -> PASL switches and vice versa
    - Subsets with background sup -> without bsup (and vice versa)

### How to test

Run any two flavors of ASL with drastically different setups. Notice how parameters from the first flavor will bleed into the second.

### Release notes

- Fixed a bug where parameters from an earlier import context carried over into a latter one

### Attachments

[ExploreASL-Issue1264-MultiContextParsCarryOver.zip](https://github.com/ExploreASL/ExploreASL/files/10252492/ExploreASL-Issue1264-MultiContextParsCarryOver.zip)

**Comment by jan-petr** [comment]
I've checked the studyPar.json and it behaves correctly as described in the documentation: https://exploreasl.github.io/Documentation/1.10.0beta/Tutorials-Import/

That is
1. studyPar is read from top to bottom with overwriting. bottom having the highest priority.
2. Since your first studyPar field has no specific conditions, it means it is applied to all data. 
3. For the Siemens20 patient, the data from the second studyPar field are used to overwrite the first field, but tags like LabelingDuration are not overwritten or removed.

So there are two solutions 
1. Make the first tag specific to certain datasets and not the Siemens20 one.
2. I can test what happens if LabelingDuration is set to empty for Siemens, but it might not lead to a desired effect.

You are of course right that for PASL, LabelingDuration should be ignored. And we can program that behavior because now it probably only issues a warning.

**Comment by MauricePasternak** [comment]
Okay, thanks for the clarification, especially point #2. To clarify, the GUI's first context is meant a default/global/catch-all one, hence the lack of specific conditions. We can perhaps discuss whether that is a valid approach in a dev meeting.

I do believe that sanity checks with an "info" level of logging feedback would still be helpful in cases, given [BIDS Presence/Absence Requirements](https://bids-specification.readthedocs.io/en/stable/appendices/arterial-spin-labeling.html#flowchart-based-on-dependency-table).

In particular, the following seem to be the sanity checks that can be placed in:

- A switch from PASL -> (P)CASL:
    - `BolusCutOffFlag` , `BolusCutOffTechnique` , `BolusCutOffDelayTime`, `PASLType`, `LabelingSlabThickness` must be purged from the current context  
- A switch from (P)CASL -> PASL:
    - `LabelingDuration`, `PCASLType`, `CASLType`, and all the `LabelingPulse**` fields must be purged 
- A switch from 2D -> 3D:
    - `SliceTiming` (or SliceReadoutTime) must be purged
- A switch from Estimate/Separate/Included M0Type to an Absent one:
    - `M0Estimate` must be purged
- A switch from having background suppression as true to false:
    - `BackgroundSuppressionNumberPulses` and `BackgroundSuppressionPulseTime` can be either purged or set to 0 and [], respectively.

I guess this can be left pending/open for now, or closed and the above suggestions can be placed in a new issue.

**Comment by jan-petr** [comment]
I agree that we need the sanity checks. However, I think that we have most of them somewhere in the code. We can for sure check if all are there and if the correct warnings are printed. I have moved that aspect to another issue (#1309) and closed this one.

Indeed, the first GUI field should be (but it doesn't have to) global without catches. So if no conditions are provided, it will propagate to all other contexts as well.
