### ISSUE TITLE
Replace testing subject Philips_2DEPI_Lesion_NoFLAIR_NoM0_HiQ

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#128]
This subject has too low CBF, while correctly image processing. So for clarity, we want another test subject here.

**Comment by jan-petr** [comment]
I have chosen a new subject for this dataset. And by testing it, uncovered some bugs reported elsewhere.

Anyway - now it all seems to run with a new dataset without problems and the CBF numbers are more reasonable.

Can you please add this dataset as a replacement for the current one?
https://cloud.hzdr.de/s/i5ErRPnX7HBWYQR

The password is 'C...e' :)

**Comment by HenkMutsaerts** [comment]
I created a new TestCases set, that has this as change (to keep the versioning intact). We can delete the 1.2.2_and_older probably?

<img width="782" alt="Screenshot 2020-09-23 at 20 44 03" src="https://user-images.githubusercontent.com/27774254/94055618-850c5880-fddd-11ea-903e-8a83e0f0ec86.png">

**Comment by jan-petr** [comment]
OK.
