### ISSUE TITLE
Update MCR releases and Dockerhub to version v1.10.1

### ISSUE THREAD

**Issue by araikes** [ExploreASL/ExploreASL#1299]
Is there any plan to cut a new release on DockerHub? The current version there is still 1.9.0.

Thanks

- [x] Compile 1.10.1 Linux
- [x] Compile 1.10.1 Window
- [x] Compile 1.10.1 Mac
- [x] Prepare docker
- [x] Push to dockerhub xasl-beta
- [x] Push to dockerhub xasl

Compilations can be found at https://drive.google.com/drive/u/0/folders/1z6fbW6GnlmPhicXvXcRtGZQxptujN7o1

### Release notes
Nothing. Just a compilation of latest versions.

**Comment by maartenhammer** [comment]
Hi,

We are working on this!

**Comment by maartenhammer** [comment]
Compilation test summary:
Matlab 2022b -> compilation crashes completely.
Matlab 2021b -> compilation completse, but with missing files & 35000, 35010, 35108 dependencies.
Matlab 2019a -> compilation completes with 35000, 35010 dependencies.

Purely as comparison to last release:
Matlab 2019a + xASL v1.9.0 -> compilation completes wth 35000, 35010 dependencies.

**Comment by jan-petr** [comment]
We are ready with the new compiled versions of everything on 1.10.1 - see link above. The docker will come soon.

**Comment by maartenhammer** [comment]
Version 1.10.1 has been released on [dockerhub ](https://hub.docker.com/repository/docker/exploreasl/xasl/general).
