### ISSUE TITLE
Improved testing

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#130]
Need to improve the ExploreASL testing, at least allowing serial & parallel testing for all OSes.
@Michael: do we want to add more features, as per what we discussed at our last dev-meeting?

**Comment by MichaelStritt** [comment]
> @michael: do we want to add more features, as per what we discussed at our last dev-meeting?

I think the most important part would be a script which calls all individual unit tests as well as a template for an individual test. We should probably agree on a folder structure for this, too.

**Comment by MichaelStritt** [comment]
Hey @HenkMutsaerts what do you think about a structure like the one in f774ff7 ?
