### ISSUE TITLE
Create *.status files also for skipped processing parts

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#137]
If a submodule is skipped explicitly/correctly (e.g. if no FLAIR is available for processing), it should also write a status file.
This is useful for checking of third-party tools such as the Python ExploreASL GUI if processing has been fully completed

**Comment by MauricePasternak** [comment]
If you implement this, let me know so I update things on my end. 

My GUI already checks arguments like "SkipIfNoFLAIR" and adjusts accordingly to which .status files it anticipates. This is why the progressbars are able to reach 100% whether the dataset has FLAIR or not. This proposed change would break that.

**Comment by HenkMutsaerts** [comment]
@MauricePasternak this was fixed in #123, so now these status files are always created.
