### ISSUE TITLE
Release v1.11.0

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1423]
### Release v[1.11.0]

Release issue to document testing and bug fixing. Check out the GitHub wiki workflow for the [drafting of a new release](https://github.com/ExploreASL/ExploreASL/wiki/Drafting-a-new-Release).

### General information
Test within the branch **Jan**.
Don't forget to pull a new version of the following repositories before testing: `Testing`, `FlavorDatabase`, `TestDataSet`!!

### Pre-test before creating release branch

- [x] UnitTest: @jan-petr
- [x] TestDatasets: @jan-petr
- [x] Flavors: @jan-petr
- [x] Test-run docu crawler: @jan-petr
- [x] Fix and close last issues: @jan-petr

### Testing
- [x] Pretesting is done?: @jan-petr 
- [x] Create release branch: @jan-petr 

#### Run UnitTesting — `xASL_test_Unittesting` 
Test relevant tests again after all major fixes. 
A minor bug #1484 had to be fixed, but all should be good now.
- [x] Linux: @jan-petr  R2022b
- [x] Windows: @MDijsselhof R2021b
- [x] Flux: @maartenhammer R2019a
- [x] Luna: @maartenhammer R2019a 
- [x] MacOS-Intel: @maartenhammer R2019a 
- [x] MacOS-Silicon: @BeatrizPadrela - Silicon working with Rossetta

#### Run TestDatasets — `xASL_test_TestExploreASL` — it should reveal no difference between the current results and results from 1.11.0 (that I've just updated)
Test relevant tests again after all major fixes.
- [x] Linux: @jan-petr  R2022b
- [x] Windows: @MDijsselhof R2021b
- [x] Flux: @maartenhammer  R2019a
- [x] Luna: @maartenhammer  R2019a
- [x] MacOS-Intel: @maartenhammer R2019a 
- [x] MacOS-Silicon: @BeatrizPadrela - Silicon working with Rossetta
- [x] MacOS-Silicon: @HenkMutsaerts - Silicon R2023b

#### Run Flavors test - (xASL_test_Flavors([],0,0) - Run only the import part including BIDS2Legacy and stop before processing. Paste the printed errors.
Test relevant tests again after all major fixes.
- [x] Linux: @jan-petr R2022b
- [x] Windows: @MDijsselhof R2021b
- [x] Flux: @maartenhammer  R2019a
- [x] Luna: @maartenhammer  R2019a
- [x] MacOS-Intel: @maartenhammerR2019a   - several errors persist - see below
- [x] MacOS-Silicon: @BeatrizPadrela   - Silicon working with Rossetta only
- [x] Fix the following Flavors on MacOS-Intel and re-run all flavor tests. The issue is with special characters in names and is currently fixed in #1273 and will be released in version 1.12.0
       - ["GE_PCASL_3Dspiral_DV25.0_product_1",
       - "Philips_PCASL_2DEPI_3.2.2.0_glioma_1", 
       - "Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1",
       - "Philips_PCASL_2DEPI_3.2.2.1_1", 
       - "Philips_PCASL_2DEPI_3.2.3.0_BSupN_1", 
       - "Siemens_PASL_3DGRASE_VB17A_1", 
       - "Siemens_PCASL_3DGRASE_XA31_multiPLD_2"]

### First phase of the release
- [x] All above done and we can start the first phase of the release process? @jan-petr 
- [x] Document `CHANGES.md` using release notes of all issues: @jan-petr
- [x] Update `VERSION` file: @jan-petr
- [x] Test-run docu crawler: @jan-petr
- [x] Update reference table in TestDataSet: @jan-petr
- [x] #1403: @maartenhammer 
- [x] #1177: @maartenhammer  

### Second phase of the release
- [x] First phase done and we can start the second phase of the release process? @jan-petr 
- [x] Merge release branch to main: **Jan**
- [x] Rebase develop with latest commits: **Jan**
- [x] Do the release, copy release text, tag, and Zenodo: **Jan**
- [x] Update version to BETA in develop: **Jan**
- [x] #508: @maartenhammer 
- [x] #1437: @maartenhammer  work in progress, more complex than expected. Moved to 1.12.0
- [x] Compile new Linux version
- [x] Compile new Windows version
- [x] Compile new MacOS version
- [x] Merge and close all branches+issues for this version: @jan-petr
- [x] Clean project and milestones: @jan-petr
- [x] Crawl new documentation: **Jan**
- [x] Update online documentation and delete BETA: **Jan**

**Comment by MDijsselhof** [comment]
Results Mathijs 

Unit Testing: 

====================================== TEST RESULTS ======================================

                         name                             unit            tests        passed
    ______________________________________________    ____________    _____________    ______

    {'xASL_adm_CatchNumbersFromString'           }    {'function'}    {1×3  struct}    true  
    {'xASL_adm_CheckFileCount'                   }    {'function'}    {1×2  struct}    true  
    {'xASL_adm_CompareLists'                     }    {'function'}    {1×2  struct}    true  
    {'xASL_adm_CorrectName'                      }    {'function'}    {1×3  struct}    true  
    {'xASL_adm_DeleteFileList'                   }    {'function'}    {1×2  struct}    true  
    {'xASL_adm_OrderFields'                      }    {'function'}    {1×1  struct}    true  
    {'xASL_adm_SortStringNumbers'                }    {'function'}    {1×1  struct}    true  
    {'xASL_bids_CheckDatasetDescription'         }    {'function'}    {1×2  struct}    true  
    {'xASL_bids_CompareStructures'               }    {'function'}    {1×4  struct}    true  
    {'xASL_bids_Config'                          }    {'function'}    {1×1  struct}    true  
    {'xASL_bids_CreateDatasetDescriptionTemplate'}    {'function'}    {1×2  struct}    true  
    {'xASL_bids_JsonCheck'                       }    {'function'}    {1×3  struct}    true  
    {'xASL_bids_VendorFieldCheck'                }    {'function'}    {1×1  struct}    true  
    {'xASL_im_CompareNiftis'                     }    {'function'}    {1×2  struct}    true  
    {'xASL_im_ResampleLinear'                    }    {'function'}    {1×5  struct}    true  
    {'xASL_imp_StudyParPriority'                 }    {'function'}    {1×6  struct}    true  
    {'xASL_io_ExportVTK'                         }    {'function'}    {1×5  struct}    true  
    {'xASL_io_Nifti2Im'                          }    {'function'}    {1×1  struct}    true  
    {'xASL_io_ReadJson'                          }    {'function'}    {1×1  struct}    true  
    {'xASL_io_WriteJson'                         }    {'function'}    {1×2  struct}    true  
    {'xASL_num2str'                              }    {'function'}    {1×2  struct}    true  
    {'xASL_spm_admin'                            }    {'function'}    {1×1  struct}    true  
    {'xASL_spm_reslice'                          }    {'function'}    {1×2  struct}    true  
    {'xASL_spm_smooth'                           }    {'function'}    {1×1  struct}    true  
    {'xASL_stat_PSNR'                            }    {'function'}    {1×2  struct}    true  
    {'xASL_stat_QuantileNan'                     }    {'function'}    {1×1  struct}    true  
    {'xASL_stat_StdNan'                          }    {'function'}    {1×3  struct}    true  
    {'xASL_str2num'                              }    {'function'}    {1×3  struct}    true  
    {'xASL_test_GetLogContent'                   }    {'function'}    {1×2  struct}    true  
    {'xASL_tsvRead'                              }    {'function'}    {1×2  struct}    true  
    {'xASL_tsvWrite'                             }    {'function'}    {1×2  struct}    true  
    {'xASL_wrp_BIDS2Legacy'                      }    {'function'}    {1×2  struct}    true  
    {'xASL_ExploreASL'                           }    {'master'  }    {1×12 struct}    true  
    {'xASL_module_ASL'                           }    {'module'  }    {1×1  struct}    true  
    {'xASL_module_Population'                    }    {'module'  }    {1×1  struct}    true  
    {'xASL_module_Structural'                    }    {'module'  }    {1×1  struct}    true  

==========================================================================================

Flavour testing:



![Image](https://github.com/ExploreASL/ExploreASL/assets/75380250/ff2f814e-ad70-4654-9833-c4d8ef4d4950)

TestingDatasets: 



![Image](https://github.com/ExploreASL/ExploreASL/assets/75380250/2f7f22cb-3804-48a0-90f4-1b544ebde96c)

**Comment by maartenhammer** [comment]
Results Intel Mac:
Unit Tests all passed.

Test dataset

Results
```
Data	mean_qCBF_TotalGM	median_qCBF_TotalGM	median_qCBF_DeepWM	CoV_qCBF_TotalGM	GMvol	WMvol	CSFvol	PipelineCompleted	TC_ASL_Registration	TC_M0_Registration
GE_3Dspiral_T1prefilled_Cyst_M0_noFLAIR_2ndRun_LoQ	65.106	52.5459	32.2436	0.2957	0.63989	0.50518	0.43289	1	0.89977	0.93228
Philips_2DEPI_FEAST_Longitudinal_FLAIR_LGA_ASL_PartlyDone_HiQ	39.3354	27.8883	6.6944	0.71334	0.53492	0.45897	0.40561	1	0.72979	0.81349
Philips_2DEPI_FLAIR_DisabledQuantification_M0_LoQ	73.8912	56.3173	23.055	0.33702	0.54422	0.39205	0.35636	1	0.91948	0.94789
Philips_2DEPI_FLAIR_Segm_PWI4D_Quant_Parameters_LoQ	48.8031	43.2575	20.1315	0.42119	0.69937	0.58158	0.2222	1	0.81304	0.83457
Philips_2DEPI_Lesion_NoFLAIR_NoM0_HiQ	empty	14.233	3.0026	0.89531	0.70986	0.51361	0.19394	1	0.75931	0.89104
Philips_2DEPI_Segmentation_2D_T2_SPM_HiQ	46.1621	41.3495	9.4561	0.36553	0.81669	0.45958	0.15162	1	0.8541	0.8025
Philips_3DGRASE_FLAIR_M0_2ndRun_HiQ	34.4643	25.7164	7.6259	0.65668	0.57092	0.52786	0.42198	1	0.8594	0.75477
Philips_3DGRASE_MultiSessions_T1wAlreadyDone_LoQ	33.0357	25.0264	9.1691	0.43047	0.72393	0.55204	0.35635	1	0.84767	0.89516
Siemens3DGRASE_Structural_AlreadyDone_HiQ	41.7852	42.9833	23.3048	0.75471	0.51909	0.46579	0.40537	1	0.71679	0.49866
Siemens_2DEPI_noBsup_FLAIR_LoQ	68.6564	51.5915	13.8923	0.32113	0.68868	0.60315	0.31014	1	0.87263	0.9589
```
Passed on v1.10 comparison.
Fail on v1.11 comparison.
```
Data	mean_qCBF_TotalGM	median_qCBF_TotalGM	median_qCBF_DeepWM	CoV_qCBF_TotalGM	GMvol	WMvol	CSFvol	PipelineCompleted	TC_ASL_Registration	TC_M0_Registration
GE_3Dspiral_T1prefilled_Cyst_M0_noFLAIR_2ndRun_LoQ	0.171%	0.077%	0.048%	0.003%	0.000%	0.010%	0.058%	0.000%	0.046%	0.074%
Philips_2DEPI_FEAST_Longitudinal_FLAIR_LGA_ASL_PartlyDone_HiQ	0.324%	0.223%	0.802%	0.092%	0.050%	0.039%	0.027%	0.000%	0.030%	0.029%
Philips_2DEPI_FLAIR_DisabledQuantification_M0_LoQ	0.426%	0.053%	0.235%	0.284%	0.321%	0.084%	0.414%	0.000%	0.080%	0.017%
Philips_2DEPI_FLAIR_Segm_PWI4D_Quant_Parameters_LoQ	0.017%	0.205%	0.493%	0.290%	0.163%	0.199%	0.099%	0.000%	0.123%	0.003%
Philips_2DEPI_Lesion_NoFLAIR_NoM0_HiQ	NaN	0.077%	0.862%	0.018%	0.089%	0.004%	0.365%	0.000%	0.043%	0.000%
Philips_2DEPI_Segmentation_2D_T2_SPM_HiQ	0.124%	0.103%	0.281%	0.321%	0.000%	0.000%	0.000%	0.000%	0.037%	0.005%
Philips_3DGRASE_FLAIR_M0_2ndRun_HiQ	0.163%	0.150%	0.522%	1.130%	0.100%	0.030%	0.066%	0.000%	0.036%	0.063%
Philips_3DGRASE_MultiSessions_T1wAlreadyDone_LoQ	0.083%	0.065%	0.306%	0.193%	0.000%	0.000%	0.000%	0.000%	0.046%	0.015%
Siemens3DGRASE_Structural_AlreadyDone_HiQ	0.231%	0.197%	0.012%	0.082%	0.000%	0.000%	0.000%	0.000%	0.053%	0.007%
Siemens_2DEPI_noBsup_FLAIR_LoQ	0.122%	0.117%	0.083%	0.093%	0.351%	0.134%	1.446%	0.000%	0.061%	0.005%
```
====================
Flavor database fail on a few values:
```
"flavorList": ["GE_PCASL_3Dspiral_DV25.0_product_1",
"Philips_PCASL_2DEPI_3.2.2.0_glioma_1", 
"Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1",
"Philips_PCASL_2DEPI_3.2.2.1_1", 
"Philips_PCASL_2DEPI_3.2.3.0_BSupN_1", 
"Siemens_PASL_3DGRASE_VB17A_1", 
"Siemens_PCASL_3DGRASE_XA31_multiPLD_2"]
```
Rerunning these flavours it now.
Issues persist on rerun even after reboot.
```
 flavor                         dataset                 name                                                                  message                                                     
    __________________________________________    _____________    ________________________    ________________________________________________________________________________________________________________

    'GE_PCASL_3Dspiral_DV25.0_product_1'          'rawdata'        'Missing file'              '/sub-001/anat/sub-001_T1w.json'                                                                                
    'GE_PCASL_3Dspiral_DV25.0_product_1'          'rawdata'        'Missing file'              '/sub-001/anat/sub-001_T1w.nii.gz'                                                                              
    'GE_PCASL_3Dspiral_DV25.0_product_1'          'rawdata'        'Missing file'              '/sub-001/perf/sub-001_asl.json'                                                                                
    'GE_PCASL_3Dspiral_DV25.0_product_1'          'rawdata'        'Missing file'              '/sub-001/perf/sub-001_asl.nii.gz'                                                                              
    'GE_PCASL_3Dspiral_DV25.0_product_1'          'rawdata'        'Missing file'              '/sub-001/perf/sub-001_aslcontext.tsv'                                                                          
    'Philips_PCASL_2DEPI_3.2.2.0_glioma_1'        'rawdata'        'Missing file'              '/sub-P01/perf/sub-P01_asl.json'                                                                                
    'Philips_PCASL_2DEPI_3.2.2.0_glioma_1'        'rawdata'        'Missing file'              '/sub-P01/perf/sub-P01_asl.nii.gz'                                                                              
    'Philips_PCASL_2DEPI_3.2.2.0_glioma_1'        'rawdata'        'Missing file'              '/sub-P01/perf/sub-P01_aslcontext.tsv'                                                                          
    'Philips_PCASL_2DEPI_3.2.2.0_glioma_1'        'rawdata'        'Missing file'              '/sub-P01/perf/sub-P01_m0scan.json'                                                                             
    'Philips_PCASL_2DEPI_3.2.2.0_glioma_1'        'rawdata'        'Missing file'              '/sub-P01/perf/sub-P01_m0scan.nii.gz'                                                                           
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'rawdata'        'Missing file'              '/sub-AE001201601221404MRIHERSENEN/perf/sub-AE001201601221404MRIHERSENEN_run-1_asl.json'                        
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'rawdata'        'Missing file'              '/sub-AE001201601221404MRIHERSENEN/perf/sub-AE001201601221404MRIHERSENEN_run-1_asl.nii.gz'                      
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'rawdata'        'Missing file'              '/sub-AE001201601221404MRIHERSENEN/perf/sub-AE001201601221404MRIHERSENEN_run-1_aslcontext.tsv'                  
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'rawdata'        'Missing file'              '/sub-AE001201601221404MRIHERSENEN/perf/sub-AE001201601221404MRIHERSENEN_run-1_m0scan.json'                     
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'rawdata'        'Missing file'              '/sub-AE001201601221404MRIHERSENEN/perf/sub-AE001201601221404MRIHERSENEN_run-1_m0scan.nii.gz'                   
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'rawdata'        'Missing file'              '/sub-AE001201601221404MRIHERSENEN/perf/sub-AE001201601221404MRIHERSENEN_run-2_asl.json'                        
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'rawdata'        'Missing file'              '/sub-AE001201601221404MRIHERSENEN/perf/sub-AE001201601221404MRIHERSENEN_run-2_asl.nii.gz'                      
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'rawdata'        'Missing file'              '/sub-AE001201601221404MRIHERSENEN/perf/sub-AE001201601221404MRIHERSENEN_run-2_aslcontext.tsv'                  
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'rawdata'        'Missing file'              '/sub-AE001201601221404MRIHERSENEN/perf/sub-AE001201601221404MRIHERSENEN_run-2_m0scan.json'                     
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'rawdata'        'Missing file'              '/sub-AE001201601221404MRIHERSENEN/perf/sub-AE001201601221404MRIHERSENEN_run-2_m0scan.nii.gz'                   
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'Both'           'Different file content'    'Different file content: /sub-AE001201601221404MRIHERSENEN/anat/sub-AE001201601221404MRIHERSENEN_run-1_T1w.json'
    'Philips_PCASL_2DEPI_3.2.2.1_1'               'rawdata'        'Missing file'              '/sub-Sub1/perf/sub-Sub1_asl.json'                                                                              
    'Philips_PCASL_2DEPI_3.2.2.1_1'               'rawdata'        'Missing file'              '/sub-Sub1/perf/sub-Sub1_asl.nii.gz'                                                                            
    'Philips_PCASL_2DEPI_3.2.2.1_1'               'rawdata'        'Missing file'              '/sub-Sub1/perf/sub-Sub1_aslcontext.tsv'                                                                        
    'Philips_PCASL_2DEPI_3.2.2.1_1'               'rawdata'        'Missing file'              '/sub-Sub1/perf/sub-Sub1_m0scan.json'                                                                           
    'Philips_PCASL_2DEPI_3.2.2.1_1'               'rawdata'        'Missing file'              '/sub-Sub1/perf/sub-Sub1_m0scan.nii.gz'                                                                         
    'Philips_PCASL_2DEPI_3.2.3.0_BSupN_1'         'rawdata'        'Missing file'              '/sub-Sub1/perf/sub-Sub1_asl.json'                                                                              
    'Philips_PCASL_2DEPI_3.2.3.0_BSupN_1'         'rawdata'        'Missing file'              '/sub-Sub1/perf/sub-Sub1_asl.nii.gz'                                                                            
    'Philips_PCASL_2DEPI_3.2.3.0_BSupN_1'         'rawdata'        'Missing file'              '/sub-Sub1/perf/sub-Sub1_aslcontext.tsv'                                                                        
    'Siemens_PASL_3DGRASE_VB17A_1'                'Both'           'Different file content'    'Different file content: /sub-Sub1/perf/sub-Sub1_asl.json'                                                      
    'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'       'Both'           'Different file content'    'Different file content: /sub-1002/ses-1/perf/sub-1002_ses-1_asl.json'                                          
    'GE_PCASL_3Dspiral_DV25.0_product_1'          'derivatives'    'Missing file'              '/ExploreASL/sub-001_1/ASL_1/ASL4D.json'                                                                        
    'GE_PCASL_3Dspiral_DV25.0_product_1'          'derivatives'    'Missing file'              '/ExploreASL/sub-001_1/ASL_1/ASL4D.nii.gz'                                                                      
    'GE_PCASL_3Dspiral_DV25.0_product_1'          'derivatives'    'Missing file'              '/ExploreASL/sub-001_1/ASL_1/ASL4D_Source.json'                                                                 
    'GE_PCASL_3Dspiral_DV25.0_product_1'          'derivatives'    'Missing file'              '/ExploreASL/sub-001_1/ASL_1/ASL4D_Source.nii.gz'                                                               
    'GE_PCASL_3Dspiral_DV25.0_product_1'          'derivatives'    'Missing file'              '/ExploreASL/sub-001_1/ASL_1/ASL4Dcontext.tsv'                                                                  
    'GE_PCASL_3Dspiral_DV25.0_product_1'          'derivatives'    'Missing file'              '/ExploreASL/sub-001_1/ASL_1/ASL4Dcontext_Source.tsv'                                                           
    'GE_PCASL_3Dspiral_DV25.0_product_1'          'derivatives'    'Missing file'              '/ExploreASL/sub-001_1/ASL_1/M0.json'                                                                           
    'GE_PCASL_3Dspiral_DV25.0_product_1'          'derivatives'    'Missing file'              '/ExploreASL/sub-001_1/ASL_1/M0.nii.gz'                                                                         
    'GE_PCASL_3Dspiral_DV25.0_product_1'          'derivatives'    'Missing file'              '/ExploreASL/sub-001_1/T1.json'                                                                                 
    'GE_PCASL_3Dspiral_DV25.0_product_1'          'derivatives'    'Missing file'              '/ExploreASL/sub-001_1/T1.nii.gz'                                                                               
    'Philips_PCASL_2DEPI_3.2.2.0_glioma_1'        'derivatives'    'Missing file'              '/ExploreASL/sub-P01_1/ASL_1/ASL4D.json'                                                                        
    'Philips_PCASL_2DEPI_3.2.2.0_glioma_1'        'derivatives'    'Missing file'              '/ExploreASL/sub-P01_1/ASL_1/ASL4D.nii.gz'                                                                      
    'Philips_PCASL_2DEPI_3.2.2.0_glioma_1'        'derivatives'    'Missing file'              '/ExploreASL/sub-P01_1/ASL_1/ASL4Dcontext.tsv'                                                                  
    'Philips_PCASL_2DEPI_3.2.2.0_glioma_1'        'derivatives'    'Missing file'              '/ExploreASL/sub-P01_1/ASL_1/M0.json'                                                                           
    'Philips_PCASL_2DEPI_3.2.2.0_glioma_1'        'derivatives'    'Missing file'              '/ExploreASL/sub-P01_1/ASL_1/M0.nii.gz'                                                                         
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'derivatives'    'Missing file'              '/ExploreASL/sub-AE001201601221404MRIHERSENEN_1/ASL_1/ASL4D.json'                                               
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'derivatives'    'Missing file'              '/ExploreASL/sub-AE001201601221404MRIHERSENEN_1/ASL_1/ASL4D.nii.gz'                                             
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'derivatives'    'Missing file'              '/ExploreASL/sub-AE001201601221404MRIHERSENEN_1/ASL_1/ASL4Dcontext.tsv'                                         
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'derivatives'    'Missing file'              '/ExploreASL/sub-AE001201601221404MRIHERSENEN_1/ASL_1/M0.json'                                                  
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'derivatives'    'Missing file'              '/ExploreASL/sub-AE001201601221404MRIHERSENEN_1/ASL_1/M0.nii.gz'                                                
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'derivatives'    'Missing file'              '/ExploreASL/sub-AE001201601221404MRIHERSENEN_1/ASL_2/ASL4D.json'                                               
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'derivatives'    'Missing file'              '/ExploreASL/sub-AE001201601221404MRIHERSENEN_1/ASL_2/ASL4D.nii.gz'                                             
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'derivatives'    'Missing file'              '/ExploreASL/sub-AE001201601221404MRIHERSENEN_1/ASL_2/ASL4Dcontext.tsv'                                         
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'derivatives'    'Missing file'              '/ExploreASL/sub-AE001201601221404MRIHERSENEN_1/ASL_2/M0.json'                                                  
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'derivatives'    'Missing file'              '/ExploreASL/sub-AE001201601221404MRIHERSENEN_1/ASL_2/M0.nii.gz'                                                
    'Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1'    'Both'           'Different file content'    'Different file content: /ExploreASL/sub-AE001201601221404MRIHERSENEN_1/T1.json'                                
    'Philips_PCASL_2DEPI_3.2.2.1_1'               'derivatives'    'Missing file'              '/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                                                                       
    'Philips_PCASL_2DEPI_3.2.2.1_1'               'derivatives'    'Missing file'              '/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.nii.gz'                                                                     
    'Philips_PCASL_2DEPI_3.2.2.1_1'               'derivatives'    'Missing file'              '/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext.tsv'                                                                 
    'Philips_PCASL_2DEPI_3.2.2.1_1'               'derivatives'    'Missing file'              '/ExploreASL/sub-Sub1_1/ASL_1/M0.json'                                                                          
    'Philips_PCASL_2DEPI_3.2.2.1_1'               'derivatives'    'Missing file'              '/ExploreASL/sub-Sub1_1/ASL_1/M0.nii.gz'                                                                        
    'Philips_PCASL_2DEPI_3.2.3.0_BSupN_1'         'derivatives'    'Missing file'              '/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                                                                       
    'Philips_PCASL_2DEPI_3.2.3.0_BSupN_1'         'derivatives'    'Missing file'              '/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.nii.gz'                                                                     
    'Philips_PCASL_2DEPI_3.2.3.0_BSupN_1'         'derivatives'    'Missing file'              '/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext.tsv'                                                                 
    'Siemens_PASL_3DGRASE_VB17A_1'                'Both'           'Different file content'    'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                                               
    'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'       'Both'           'Different file content'    'Different file content: /ExploreASL/sub-1002/ASL_1/ASL4D.json'                                                 
    'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'       'Both'           'Different file content'    'Different file content: /ExploreASL/sub-1002/ASL_1/ASL4D_Source.json'                                          
    'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'       'Both'           'Different file content'    'Different file content: /ExploreASL/sub-1002/ASL_1/M0.json'                                                    
```

**Comment by maartenhammer** [comment]
Luna Passed all without errors except for the 1% difference we discussed on Wednesday on the TestDataSet.

**Comment by maartenhammer** [comment]
Flux passed everything as well.

**Comment by HenkMutsaerts** [comment]
### macOS silicon MacBook Pro M2 2023b beta:

    {'Data'             }    {'mean_qCBF_TotalGM'}    {'median_qCBF_Tota…'}    {'median_qCBF_Deep…'}
    {'GE_3Dspiral_T1pr…'}    {'65.5571'          }    {'52.6736'          }    {'32.2365'          }
    {'Philips_2DEPI_FE…'}    {'39.2038'          }    {'27.8347'          }    {'6.7241'           }
    {'Philips_2DEPI_FL…'}    {'74.1523'          }    {'56.3528'          }    {'22.9594'          }
    {'Philips_2DEPI_FL…'}    {'48.9767'          }    {'43.3191'          }    {'20.2286'          }
    {'Philips_2DEPI_Le…'}    {'empty'            }    {'14.2423'          }    {'3.0602'           }
    {'Philips_2DEPI_Se…'}    {'46.4176'          }    {'41.3939'          }    {'9.466'            }
    {'Philips_3DGRASE_…'}    {'34.4046'          }    {'25.6696'          }    {'7.6076'           }
    {'Philips_3DGRASE_…'}    {'33.3154'          }    {'25.0766'          }    {'9.0798'           }
    {'Siemens3DGRASE_S…'}    {'41.6462'          }    {'42.7831'          }    {'23.2588'          }
    {'Siemens_2DEPI_no…'}    {'68.3988'          }    {'51.1492'          }    {'13.9175'          }

  Columns 5 through 10

    {'CoV_qCBF_TotalGM'}    {'GMvol' }    {'WMvol' }    {'CSFvol'}    {'PipelineCompleted'}    {'TC_ASL_Registrat…'}
    {'0.29529'         }    {[0.6388]}    {[0.5041]}    {[0.4345]}    {[                1]}    {[           0.9004]}
    {'0.71425'         }    {[0.5371]}    {[0.4576]}    {[0.4083]}    {[                1]}    {[           0.7294]}
    {'0.33736'         }    {[0.5414]}    {[0.3894]}    {[0.3299]}    {[                1]}    {[           0.9187]}
    {'0.4203'          }    {[0.7007]}    {[0.5811]}    {[0.2213]}    {[                1]}    {[           0.8143]}
    {'0.89606'         }    {[0.7115]}    {[0.5077]}    {[0.1983]}    {[                1]}    {[           0.7578]}
    {'0.36338'         }    {[0.8176]}    {[0.4597]}    {[0.1509]}    {[                1]}    {[           0.8553]}
    {'0.6511'          }    {[0.5732]}    {[0.5272]}    {[0.4240]}    {[                1]}    {[           0.8591]}
    {'0.42947'         }    {[0.7239]}    {[0.5520]}    {[0.3564]}    {[                1]}    {[           0.8475]}
    {'0.75519'         }    {[0.5191]}    {[0.4658]}    {[0.4054]}    {[                1]}    {[           0.7171]}
    {'0.32206'         }    {[0.6740]}    {[0.6011]}    {[0.3372]}    {[                1]}    {[           0.8700]}

  Column 11

    {'TC_M0_Registrati…'}
    {[           0.9330]}
    {[           0.8132]}
    {[           0.9475]}
    {[           0.8346]}
    {[           0.8915]}
    {[           0.8037]}
    {[           0.7545]}
    {[           0.8962]}
    {[           0.4986]}
    {[           0.9586]}


### Difference table with version 1.11.0:
    {'Data'             }    {'mean_qCBF_TotalGM'}    {'median_qCBF_Tota…'}    {'median_qCBF_Deep…'}
    {'GE_3Dspiral_T1pr…'}    {'0.520%'           }    {'0.166%'           }    {'0.026%'           }
    {'Philips_2DEPI_FE…'}    {'0.011%'           }    {'0.031%'           }    {'0.362%'           }
    {'Philips_2DEPI_FL…'}    {'0.074%'           }    {'0.010%'           }    {'0.649%'           }
    {'Philips_2DEPI_FL…'}    {'0.339%'           }    {'0.063%'           }    {'0.013%'           }
    {'Philips_2DEPI_Le…'}    {'NaN'              }    {'0.012%'           }    {'1.040%'           }
    {'Philips_2DEPI_Se…'}    {'0.428%'           }    {'0.004%'           }    {'0.386%'           }
    {'Philips_3DGRASE_…'}    {'0.335%'           }    {'0.332%'           }    {'0.281%'           }
    {'Philips_3DGRASE_…'}    {'0.762%'           }    {'0.136%'           }    {'0.671%'           }
    {'Siemens3DGRASE_S…'}    {'0.102%'           }    {'0.269%'           }    {'0.185%'           }
    {'Siemens_2DEPI_no…'}    {'0.254%'           }    {'0.741%'           }    {'0.099%'           }

  Columns 5 through 10

    {'CoV_qCBF_TotalGM'}    {'GMvol' }    {'WMvol' }    {'CSFvol'}    {'PipelineCompleted'}    {'TC_ASL_Registrat…'}
    {'0.142%'          }    {'0.164%'}    {'0.230%'}    {'0.423%'}    {'0.000%'           }    {'0.028%'           }
    {'0.035%'          }    {'0.353%'}    {'0.262%'}    {'0.695%'}    {'0.000%'           }    {'0.021%'           }
    {'0.183%'          }    {'0.194%'}    {'0.770%'}    {'7.039%'}    {'0.000%'           }    {'0.161%'           }
    {'0.079%'          }    {'0.352%'}    {'0.285%'}    {'0.495%'}    {'0.000%'           }    {'0.035%'           }
    {'0.066%'          }    {'0.320%'}    {'1.155%'}    {'1.885%'}    {'0.000%'           }    {'0.244%'           }
    {'0.269%'          }    {'0.111%'}    {'0.015%'}    {'0.468%'}    {'0.000%'           }    {'0.107%'           }
    {'0.271%'          }    {'0.296%'}    {'0.091%'}    {'0.543%'}    {'0.000%'           }    {'0.003%'           }
    {'0.040%'          }    {'0.000%'}    {'0.000%'}    {'0.000%'}    {'0.000%'           }    {'0.070%'           }
    {'0.019%'          }    {'0.000%'}    {'0.000%'}    {'0.000%'}    {'0.000%'           }    {'0.100%'           }
    {'0.196%'          }    {'1.792%'}    {'0.203%'}    {'7.137%'}    {'0.000%'           }    {'0.241%'           }

  Column 11

    {'TC_M0_Registrati…'}
    {'0.007%'           }
    {'0.066%'           }
    {'0.026%'           }
    {'0.007%'           }
    {'0.053%'           }
    {'0.150%'           }
    {'0.030%'           }
    {'0.103%'           }
    {'0.026%'           }
    {'0.023%'           }
