### ISSUE TITLE
GE images don't output VBA mask in Population module

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#143]
Perhaps the absence of a susceptibility mask will skip the creation of a VBA mask.

**Comment by MauricePasternak** [comment]
I think I found the issue and it might be present in more than just GE due to the nature of the error...

xASL_module_Population breakpoint line 81.  Files such as 'MaskSusceptibility_bs-mean.nii' or 'FoV_bs-mean_Unmasked.nii' do not exist.

Instead, they are named, for example, FoV_n23_bs-mean_Unmasked.nii

**Comment by HenkMutsaerts** [comment]
* xASL_vis_Imwrite: Manage empty masks:
  * Cosmetics; *Warning instead of crashing when input images are empty or contain NaNs only

* xASL_im_CreateAnalysisMask: Manage susceptibility mask for 3D spiral: 
  * If susceptibility mask is missing for 3D spiral, this is now fine. Create a dummy mask then, and within the complete function the assumption of the presence of a susceptibility mask is now changed accordingly

*xASL_adm_GetFileList: Warning when too few or many files found:
  * When too many or too few files or folders were found, this threw an error, which is now changed to a warning instead

* Load FoV masks using regular expression
* xASL_im_CreateAnalysisMasks: Load masks by regular expression:
  * These masks were previously saved without specifying the number of images averaged in the filename. Now this is mentioned in the filename, the filename of the population-based masks changes with the number of images that were averaged. These new regular expressions should deal with this

**Comment by HenkMutsaerts** [comment]
## **MAURICE PASTERNAK COMMENTED:**

I will re-test with a larger sample size, but from the mini-batch of 4 subjects (2 with ASL and 2 without), the pipeline fails due to the following condition in xASL_wrp_CreatePopulationTemplates starting @ line 108:

```
if x.nSubjectsSessions<6
    % With too small datasets, created templated won't be reliable
    fprintf('%s\n',['Too few images (' num2str(x.nSubjectsSessions) ') for creating templates/parametric images, skipping...']);
    return;
end

Size1 = sum(x.WBmask(:));

x.D.TemplatesStudyDir = fullfile(x.D.PopDir, 'Templates');
xASL_adm_CreateDir(x.D.TemplatesStudyDir);
```

So the snowball effect is this:

1) analysis/Population/Templates is never created (due to early cancellation at low subject number)

2) various filepath variables in xASL_im_CreateAnalysisMask have the value: ""  (an empty string) as a result.

3)  xASL_exist causes the crash when the input is:  xASL_exist("", 'file')

```
    'Array indices must be positive integers or logical values.
     
     Error in xASL_exist (line 43)
     if strcmp(PathIn(end-3:end),'.nii')
```

So, from my observations, we can either go with the philosophy of having xASL_exist have some sort of try-catch method. Or check if the Templates directory exists at the start of xASL_im_CreateAnalysisMask. Or prevent the issue from happening by allowing the Templates directory to exist anyway and have the right files in there, but to forego the actual creation of the analysis mask later.

**Comment by HenkMutsaerts** [comment]
@Maurice, I did the edits below, can you check if it now works satisfactory?

* xASL_im_CreateAnalysisMask: fix isempty bug
  * As I changed fullfile by xASL_adm_GetFileList, we could have empty strings if files didnt exist, which crashed xASL_exist rather than noticing that a template was missing. Now, I replaced this with isempty, which should work
* xASL_exist: Add input check
  * If PathIn is empty, this now issues a warning instead of crashing the function

**Comment by MauricePasternak** [comment]
Yep, looks good.
