### ISSUE TITLE
Fix BASIL parameters

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1447]
### Description

Some BASIL/FABBER parameters are not correctly initialized as they are only initialized for BASIL and not for FABBER.

### Tasks

- [x] Check all parameters in FSL_QUANT and correctly move them for BASIL only or for BASIL+FABBER.

### Release notes

Minor bugfix, report together with #1387

**Comment by BeatrizPadrela** [comment]
Approved! And the Tex map looks super nice!

<img width="1328" alt="image" src="https://github.com/ExploreASL/ExploreASL/assets/73699072/d402dc25-6c6f-4e86-a9ae-cf33a2442798">
