### ISSUE TITLE
CAT12 crashes with matlab R2023b

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1453]
### Description

cat_io_xml checked for `\d.\d` in the Matlab version, and this version needed to be higher than 7.0, otherwise it deemed Matlab too old for creating an xml output.

Version 23.2 became 3.2 and was lower than 7.0

### Tasks

- [x] cat_io_xml: change \d.\d to \d+.\d

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Bugfix of CAT12 crash with newest Matlab version

**Comment by maartenhammer** [comment]
closed with #1454
