### ISSUE TITLE
Running FSL on new Matlab version on macOS

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1458]
### Description

@mervinTEE didn't get ExploreASL to run FSL.

### Tasks

- [x] Henk did a minor bugfix for loading 'ascii' data
 
### How to test
```
x=ExploreASL;
[~, x] = xASL_fsl_SetFSLdir(x, 1);
xASL_fsl_RunFSL('fsleyes', x);
```

### Release notes

#1458 Minor bugfix running FSL on newer Matlab versions

**Comment by mervinTEE** [comment]
I tried again and the FSL ran when directed to the Mac version complied FSL. The issue was with the compiled fsl from linux used on mac.
