### ISSUE TITLE
Error when processing T1 and FLAIR lesions

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#148]
Error in xASL_wrp_VisualQC_Structural>xASL_adm_VisualCheckLesionRemoval (line 301)
FLAIR instead of T1 list.

Moreover, the FLAIR and T1 list can be joined with regular expressions.

**Comment by jan-petr** [comment]
I have fixed the error for Lesion lists and merged the lesion lists.

@HenkMutsaerts 
The same can be done for ROIs. The trouble is that the visualization currently only uses the ROI_T1_List and not the ROI_FLAIR_List. The question is if we join these two ROI lists and display them over T1 (like done for lesions, but somehow forgotten for ROIs). Or if we display T1 ROI over T1 and FLAIR ROI over FLAIR (which could be nicer, but then would be different from what is currently done for Lesions).

**Comment by HenkMutsaerts** [comment]
I would show them all over the T1w, that should be fine for now. We can always change this later. In any case the chances of having a ROI (not a lesion) drawn in a FLAIR is very low :)
