### ISSUE TITLE
Multi-session PDF report

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1522]
### Description

Currently, the QC PDF report has only a single ASL session. We are now making a proper multi-ASL-session QC.json in #1514  and we are doing a new way to export PDFs #1225. Once these two issues are fixed, we should create a proper multi-session PDF report for ASL.

### Release notes
Nothing to release. Closed as duplicate

**Comment by HenkMutsaerts** [comment]
Duplicate with #1552

**Comment by HenkMutsaerts** [comment]
Duplicate with #1552
