### ISSUE TITLE
BIDS2Legacy add sessions

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1538]
### Description

Currently, BIDS2Legacy is done for an entire subject.
We want to make it work visit wise (sessions-wise in BIDS).

### Testing
I tested this with an example with multiple visits.

1. Just before running xASL_module_BIDS2Legacy, these are the "subjects":
        x.SUBJECTS

        ans =

          1×3 cell array

          Columns 1 through 2

        {'sub-012S4093_1'}    {'sub-012S4093_2'}

          Column 3

        {'sub-012S4094_1'}

According to our legacy definition <SUBJECT>_<VISIT> -> so when bLoadingRawdata is true (default), we run bids.layout and translate this to our legacy definitions in x.SUBJECTS.

2. When running xASL_module_BIDS2Legacy, it will iterate this for 3 "subjects", the three "subjects" defined above.

        Running xASL_module_BIDS2Legacy...

        ==============================================================================================
        Subject: sub-012S4093_1, Module: xASL_module_BIDS2Legacy, 24-Dec-2023 09:35:40

        ============================== BIDS to ExploreASL LEGACY CONVERSION ==========================

        Job-iteration 1 stopped at 24-Dec-2023 09:35:55 and took 15 seconds
        ==============================================================================================

        ==============================================================================================
        Subject: sub-012S4093_2, Module: xASL_module_BIDS2Legacy, 24-Dec-2023 09:35:55

        ============================== BIDS to ExploreASL LEGACY CONVERSION ==========================

        Job-iteration 2 stopped at 24-Dec-2023 09:36:07 and took 13 seconds
        ==============================================================================================

        ==============================================================================================
        Subject: sub-012S4094_1, Module: xASL_module_BIDS2Legacy, 24-Dec-2023 09:36:07

        ============================== BIDS to ExploreASL LEGACY CONVERSION ==========================

        Job-iteration 3 stopped at 24-Dec-2023 09:36:18 and took 12 seconds
        ==============================================================================================
        xASL_module_BIDS2Legacy completed 100%

@jan-petr should we add such an example to our testing databases?
FlavorDatabase doesn't have an examples with multiple visits, 
TestDataSets has an example (/TestDataSets/Philips_2DEPI_FEAST_Longitudinal_FLAIR_LGA_ASL_PartlyDone_HiQ) but this doesn't have rawdata, only derivatives.

### Release notes

Nothing. Duplicate.

**Comment by HenkMutsaerts** [comment]
Duplicate with #1547
