### ISSUE TITLE
Accelerate BASIL/FABBER testing

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1549]
### Description

ExploreASL has Quality==0 for testing stuff. But BASIL/FABBER still uses high quality then which takes a lot of time.
Would be helpful if we can downtune BASIL/FABBER quality parameters based on this ExploreASL-wide parameter.

**JAN** I based it on #1551, because we had some changes in the BASIL parameter names that I want to use. And doing that on develop would be possible, but could result in name consistency later.

### Tasks

- [x] With low quality, set the following BASIL/FABBER options
-- infert1 (off)
-- inferart (off)
-- exch=simple
-- disp=none

### Release notes

Faster low-quality mode for FSL.

**Comment by MDijsselhof** [comment]
Options to set:
-- infert1 (off)
-- inferart (off)
-- exch=simple
-- disp=none
