### ISSUE TITLE
Improve error parsing by xASL_Iteration for the GUI

### ISSUE THREAD

**Issue by MauricePasternak** [ExploreASL/ExploreASL#156]
I notice that my GUI cannot determine what subject_run an error occurs for occasionally. I'd like to suggest that the error messages have a small change done which would make things a lot easier.

Instead of 

```
ERROR: Job iteration terminated!
ans =
       A bunch of error text here
CONT: but continue with next iteration! 
```

could we have 
```
ERROR: Job iteration terminated for:  #### subject_run ####
ans =
       A bunch of error text here
CONT: but continue with next iteration! 
```

This would greatly simplify the required regex without having to parse backwards prior to the word ERROR in order to infer a subject_run.

**Comment by jan-petr** [comment]
We have already a similar issue for this - we should merge both. #352

**Comment by MichaelStritt** [comment]
Yep, the format is the main issue regarding the warning/error extraction.
We can reformat the warning or error messages were we expect them
(`try ... catch => error('Our own error/warning message format')`)
but this won't work for warnings & errors where we don't expect them.

**Comment by HenkMutsaerts** [comment]
> Yep, the format is the main issue regarding the warning/error extraction.
> We can reformat the warning or error messages were we expect them
> (`try ... catch => error('Our own error/warning message format')`)
> but this won't work for warnings & errors where we don't expect them.

This is already the case!

**Comment by MichaelStritt** [comment]
> 
> 
> > Yep, the format is the main issue regarding the warning/error extraction.
> > We can reformat the warning or error messages were we expect them
> > (`try ... catch => error('Our own error/warning message format')`)
> > but this won't work for warnings & errors where we don't expect them.
> 
> This is already the case. `xASL_Iteration` line 367 catches errors, in `ME.getReport()` or `ME.message`. We could store these somewhere directly, according to the format @MichaelStritt use in your `xASL_test_LogTracking` function?
> 
> I have now changed `xASL_Iteration` such that it reports the module name and the subject index and name.

Great changes 👍 

Didn't know that you wrote something to catch the messages already. 

If Maurice wants some "live" feedback here, we could use the "append" option and write those to a tsv file or something like that. At least that's how I would solve this. I personally don't know if its that useful for clinical users and everybody else probably can read log files. In addition I'd personally rather focus on getting v1.6.0 ready instead of stuff like this.

**Comment by HenkMutsaerts** [comment]
> Didn't know that you wrote something to catch the messages already.
> 
Thanks! Paul Groot our IT guy wrote this, credits go to him ;)

The "append" option sounds good, we could create an issue for this in the future ;)
