### ISSUE TITLE
Manual calculation of mean lesion CBF does not correspond to the mean lesion CBF value the population module produces

### ISSUE THREAD

**Issue by IWamelink** [ExploreASL/ExploreASL#1654]
@HenkMutsaerts 
### Description

When using the rLesion_T1_sub-x and the qCBF_sub-x files to manually calculate the mean CBF value in the lesion I obtain a value different than that the population module produces.

==> mean (qCBF [ rLesion_T1 == 1] ) = 87 while in the mean_qCBF_standardspace_lesions file this value is 73. These values should be the same.
Does ExploreASL use WM or GM segmentations into account when working with the lesion_T1 masks? 

### Release notes
Nothing. Done in #1503

**Comment by IWamelink** [comment]
I tested computing the mean CBF value in Python as well as Matlab. The mean_CBF value I get in Python is equal to the one Matlab produces, but not equal to the one the population pipeline produces.

I used the following Matlab code:

qcbf = xASL_io_Nifti2Im('/derivatives/ExploreASL/Population/qCBF_sub-IM1392_1_ASL_1.nii', [121 145 121]);
mask = xASL_io_Nifti2Im('/derivatives/ExploreASL/Population/rLesion_T1_1_sub-IM1392_1.nii',[121 145 121]);

VoxelSize = [1.5 1.5 1.5];
MinVoxels = 1000/prod(VoxelSize);

qcbf(qcbf <0) = NaN;

xASL_stat_ComputeMean(qcbf, mask(:,:,:,1), MinVoxels, 0, 1)
nanmean(qcbf(logical(mask(:,:,:,1))))

**Comment by jan-petr** [comment]
Thanks for checking this @IWamelink 
I've moved the comments to the issue #1503 where I'm currently dealing with the Lesion calculations in the Population module
