### ISSUE TITLE
Update ADNI import

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#166]

**Comment by MichaelStritt** [comment]
Hey @jan-petr 
my regular expressions maybe aren't the most elegant ones, but most of them seem to work.
I'm still struggling with the **token visit aliases**. How can I do this for date strings like below?
```
ExploreASL_Import(ExploreASL_ImportConfig('...\Test_Runs\ADNI'),false,true);
--> Initializing ExploreASL v1.2.2...
ExploreASL initialized <--
Checking permissions: 100%

Matching files:
    '002_S_0000\Accelerated_Sagittal_MPRAGE\2000-01-01_13_23_38.0\S111111'
    '002_S_0000\Accelerated_Sagittal_MPRAGE\2001-02-02_09_39_37.0\S222222'
    '002_S_0000\Axial_3D_PASL__Eyes_Open_\2000-01-01_13_23_38.0\S111111'
    '002_S_0000\Axial_3D_PASL__Eyes_Open_\2001-02-02_09_39_37.0\S222222'
    '002_S_0000\Sagittal_3D_FLAIR\2000-01-01_13_23_38.0\S111111'
    '002_S_0000\Sagittal_3D_FLAIR\2001-02-02_09_39_37.0\S222222'

#=6
Reference to non-existent field 'tokenVisitAliases'.

Error in ExploreASL_Import (line 301)
        IDrow(iV) = find(cellfun(@(y) strcmp(y,visitIDs{iV}), imPar.tokenVisitAliases(:,1)));
```

I was thinking of something like this, but I guess that's not correct.
```
imPar.tokenVisitAliases = {'^(\d{4}.*)$','_1'; ^(\d{4}.*)$','_2'; '^(\d{4}.*)$','_3'};
```
Can you help me here?

**Comment by HenkMutsaerts** [comment]
* Your regexps look good, perhaps you don't need to repeat the '^' so often?
* Not sure if your tokens work, shouldn't e.g. the complete ASL_series regexp be also in the token description?
So e.g. 
> imPar.tokenScanAliases = {'ADNI_ASL_series,'ASL4D'; % and the same for the other scantypes
* tokenVisitAliases -> do you always have S11111 or S22222? Then it simple:
> imPar.tokenVisitAliases = {'^S11111$','_1'; ^S222222$','_2'};
And last two folder layers:
> imPar.folderHierarchy = {... ... '^.*$', '^(S\d*)'};
> imPar.tokenOrdering = [1 4 0 2]; % subject visit session scantype

You could also use the date(s), but this is probably too much variation to capture.
* Also, don't you want the subject token to be:
> imPar.folderHierarchy = {'^(\d{3})_S_\d{4}.*',... ... ...}
? If the S_0000 can be omitted, I don't know, I would adapt this to how they address the subject IDs in the metadata

**Comment by MichaelStritt** [comment]
Hey @HenkMutsaerts thanks for the quick response :)

I thought of this...

> imPar.tokenScanAliases = {'ADNI_ASL_series,'ASL4D'; % and the same for the other scantypes

...too but it weirdly didn't work and I couldn't find out why.

This right here...

> tokenVisitAliases -> do you always have S11111 or S22222

... isn't always the case. These folders always seem to start with `S` and then there are five numbers. But I thought the visit folders are the ones with the date? Otherwise I maybe can use something like this...

`imPar.tokenVisitAliases = {'^S\d{5}$','_1'; '^S\d{5}$','_2', ...};`

I'll give it a try and let you know if it works later, thanks again 👍

**Comment by HenkMutsaerts** [comment]
Well _imPar.tokenVisitAliases = {'^S\\d{5}$','_1'; '^S\\d{5}$','_2', ...};_ won't work since these are not mutually exclusive. How could the script figure out which one is which? The simplest solution here, which I always used, is to go through the folders, sort them on data, and rename these folders according to the visits they ought to be. We could incorporate this in ExploreASL_Import if it works nicely?

**Comment by MichaelStritt** [comment]
I tried to do this using the **dates** right now, seems actually pretty straight forward (as long as I got this right and the visit folder does not have to be the one directly including the DICOM files). I debugged the code and got to this point in **ExploreASL_Import**:

```
visitIDs{iV}
ans = '2017-01-01_01_01_01.0'
```

```
imPar.tokenVisitAliases(:,1)
ans = 3×1 cell array
          {'^(2017.*)'}
          {'^(2018.*)'}
          {'^(2019.*)'}
```

But in this part after line 297, there always seems to be a problem:

```
visitIDs  = unique(vVisitIDs);
% sort by output
if length(visitIDs)>1
    for iV=1:length(visitIDs)
        IDrow(iV) = find(cellfun(@(y) strcmp(y,visitIDs{iV}), imPar.tokenVisitAliases(:,1)));
    end
    visitIDs = visitIDs(IDrow);
end
nVisits = length(visitIDs);
```

Are we comparing the strings directly? It seems that the script tries to compare `'^(2017.*)'` with `'2017-01-01_01_01_01.0'` e.g. but it does not actually use regular expressions. I think it should look more like the one in line 377:

```
regexp(visitIDs{iVisit},imPar.tokenVisitAliases(:,1),'once')
```

Is that an error in the script or am I just expecting a different behavior here?

**Comment by HenkMutsaerts** [comment]
Are the scans always in the same year for the same visit? Then you can use year as visit indeed. Are you saying the token doesn't work or the output? It should always convert to _1 _2 _3 _n according to the current legacy file system, we need to move this to bids still.
