### ISSUE TITLE
Population group mask goes wrong

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1666]
### Description

Population group mask goes wrong, it removes the back of the brain and creates a far too stringent mask.

### Tasks

- [x] Susceptibility group masking should mask Threshold*max(intensities(:))) instead of Threshold*sortedIntensities (percentile). The latter doesn't work with the dummy susceptibility mask for 3D spiral (which is a brainmask)
- [x] Which masks are used for ROI values (e.g., also for GM or WM values?)

### Release notes

Nothing. Report with #870. Fixes a bug in mask creation.

**Comment by MDijsselhof** [comment]
My results now (with ADC):

ICA PCA
![image](https://github.com/ExploreASL/ExploreASL/assets/75380250/e2f0f289-5d8b-4806-a95b-273f53e70d22)

Masked:
![image](https://github.com/ExploreASL/ExploreASL/assets/75380250/7a2ed89d-880f-4289-9f78-781b855d4a3c)

Unmasked:
![image](https://github.com/ExploreASL/ExploreASL/assets/75380250/87089382-31a1-4801-ad68-ef7978eb70ec)
