### ISSUE TITLE
M0 issue on reprocessing

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1700]
### Description

When x.M0 = "Absent", if you only delete the lock directories without deleting the ASL_1 directory before re-running the ASL Module, the processing will be different because it with have already detected an M0.nii file in the ASL_1 folder.

We need to detect x.M0 absent and then remove the M0.nii file while cleaning.

### Release notes

Nothing. Duplicate

**Comment by HenkMutsaerts** [comment]
Duplicate with #1744
