### ISSUE TITLE
Create xASL_system for more robust CLI/system calls

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#172]
Inspired by issue 88 and xASL_adm_UnixPath, I suggest we create a single xASL_system function that can always be used to include:

* WSL support
* Deployment support (but with/without compilation should work similarly)
* escaping whitespace & other (semi-)illegal characters (both in Windows & Unix-like)
* other functionality in xASL_adm_UnixPath
* Solve for xASL_SysMove the following comment to issue 88: https://github.com/ExploreASL/ExploreASL/issues/88#issuecomment-701207115
* Add Linux initialization such as `source ~./bashrc` that may initialize some things needed for e.g., git to run properly (if another git version is specified in this startup script that is then not found by Matlab when performing system calls, e.g., for git pulling from Matlab).

See also [HERE](https://superuser.com/questions/279008/how-do-i-escape-spaces-in-command-line-in-windows-without-using-quotation-marks)

**Comment by MichaelStritt** [comment]
Hey, so I was interested in this issue, since I don't think it should be that big of a deal. I wrote the following test script and ran tests on windows and linux. As you can see, the paths contain whitespaces. Otherwise I just strictly used forward slashes, since Matlab can handle this on both unix and windows.

```
if isunix
    root = '/home/michael/Documents';
elseif ispc
    root = 'M:/SoftwareDevelopment/MATLAB/m.stritt/Test_Runs';
end

% Test with correct paths
source = fullfile(root,'copy_test/with whitespace/i_am_a_file.txt');
destination = fullfile(root,'copy_test/without_whitespace/i_am_a_file.txt');
xASL_system('copy', source, destination, false)

% Test with existing file
source = fullfile(root,'copy_test/without_whitespace/i_am_a_file.txt');
destination = fullfile(root,'copy_test/with whitespace/i_am_a_file.txt');
xASL_system('move', source, destination, true)

% Copy the file again
source = fullfile(root,'copy_test/with whitespace/i_am_a_file.txt');
destination = fullfile(root,'copy_test/without_whitespace/i_am_a_file.txt');
xASL_system('copy', source, destination, false)

% Test without force should result in warning
source = fullfile(root,'copy_test/with whitespace/i_am_a_file.txt');
destination = fullfile(root,'copy_test/without_whitespace/i_am_a_file.txt');
xASL_system('copy', source, destination, false)
```

I used the following minimal script, which seems to work as intended. The only thing that does not work as intended is **xASL_exist**. It seems that it can't handle spaces on linux and that it sometimes returns 2 (and not true) if a file exists.

```
function xASL_system(command, source, destination, bForce)
    
    % Check if source exists
    if ~isfile(source) % xASL_exist does not seem to be able to do this with spaces
        error('Source file does not exist...');
    end

    % Check if destination exists
    destination_exists=isfile(destination);

    % Check if file does not exist already or if it should be overwritten
    if ~destination_exists || bForce        
        switch command
           case 'move'
              movefile(source,destination);
           case 'copy'
              copyfile(source,destination);
           otherwise
              warning('No known command...')
        end
    else
        warning('Trying to move/copy with existing destination and without force...')
    end
```

**Comment by HenkMutsaerts** [comment]
@MichaelStritt So you already wrote xASL_system, but didn't commit it (or without referring to this issue)?

**Comment by MichaelStritt** [comment]
Hey @HenkMutsaerts , no I haven't commited it yet. I wanted to wait for your feedback first. My implementation almost seems too easy. But this could be a good thing, because the original Matlab **movefile** and **copyfile** functions are probably the most robust ones.

**Comment by MichaelStritt** [comment]
And as you can see above, it uses isfile since xASL_exist did not work as expected.

**Comment by HenkMutsaerts** [comment]
Sorry but this is not what I meant, this perhaps only partly solves our troubles (also check xASL_Sysmove which already does a better job than `copyfile` and `movefile`. The point is that Matlab's native functions are not always most efficient for all OSes.

**Comment by MichaelStritt** [comment]
> 
> 
> Sorry but this is not what I meant, this perhaps only partly solves our troubles (also check xASL_Sysmove which already does a better job than `copyfile` and `movefile`. The point is that Matlab's native functions are not always most efficient for all OSes.

Always funny how you find these old commits after more than half a year 😄 You already told me that a while ago, which is why I deleted the commit/branch shown above. I don't know how you want to fix it, so maybe you have to do it yourself. I wouldn't focus on these optimization things right now, since we have more than enough other things to do.
