### ISSUE TITLE
Problem with input paths

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#173]
This warning is produced on many places...

Warning: PathIn was not a string 
> In xASL_exist (line 43)
  In xASL_im_ClipExtremes (line 94)
  In xASL_vis_CreateVisualFig (line 232)
  In xASL_wrp_VisualQC_Structural>CreateVisual (line 216)
  In xASL_wrp_VisualQC_Structural>xASL_wrp_VisualCheckCollective_Structural (line 164)
  In xASL_wrp_VisualQC_Structural (line 78)
  In xASL_module_Structural (line 487)
  In xASL_Iteration>runIteration (line 361)
  In xASL_Iteration (line 100)
  In ExploreASL_Master (line 102)
  In xASL_qc_TestExploreASL (line 323)

**Comment by HenkMutsaerts** [comment]
This bug is introduced by issue 143, will fix this.

**Comment by jan-petr** [comment]
The referenced commit above has fixed this issue because there were problems with checking xASL_exist for the case where InputIm was a matrix and not a path.
