### ISSUE TITLE
Register MindBoggle atlas to ExploreASL template

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#1743]
(HJ saved mTrial doc here: /XploreLab/Projects_1_Active/ASPIRE/Github/ASPIRE_AtlasReport_open issues.docx)

It seems that at least two volumes contained in the xASL repository are not aligned well.

We suspect that the mean and CoV values ([https://github.com/ExploreASL/ExploreASL/tree/feature-%231314_ReferenceAtlas/Maps/Templates](https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FExploreASL%2FExploreASL%2Ftree%2Ffeature-%25231314_ReferenceAtlas%2FMaps%2FTemplates&data=05%7C02%7Ch.j.mutsaerts%40amsterdamumc.nl%7C4ebc7c0d187a4012fba008dcb09ec986%7C68dfab1a11bb4cc6beb528d756984fb6%7C0%7C0%7C638579444922064843%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=X%2BBACIFvtCY0pbQpkGWFyHo9kxLQr0JEc4tVYozpZ4I%3D&reserved=0)) are not aligned properly with the mindboggle atlas ([https://github.com/ExploreASL/ExploreASL/blob/main/External/Atlases/Mindboggle_OASIS_DKT31_CMA.nii.gz](https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FExploreASL%2FExploreASL%2Fblob%2Fmain%2FExternal%2FAtlases%2FMindboggle_OASIS_DKT31_CMA.nii.gz&data=05%7C02%7Ch.j.mutsaerts%40amsterdamumc.nl%7C4ebc7c0d187a4012fba008dcb09ec986%7C68dfab1a11bb4cc6beb528d756984fb6%7C0%7C0%7C638579444922078678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=BAlo4%2BlMU5MoMdcuInYFa4ltr5fVW6Uz%2F40h%2Bv4JuVg%3D&reserved=0)). Could you please look into it?  and provide corrected template maps in the repository, if this is the solution to this issue. 

(It may also be that both are not well aligned with the MNI template which is used as standard input for xASL, see attached notes. Anyway, all three volumes well aligned would be crucial.

Indeed, the MindBoggle atlas was not perfectly aligned. I tried to find the priors used to create the atlas but couldn't find them (only in a different space). I have now used SPM's old normalize (=affine+DCT) to non-linearly register the MindBoggle atlas to our CAT12/IXI space (using the pGM map).

See below on the right the original registration of ASL to MindBoggle, left the new one.

<img width="860" alt="image" src="https://github.com/user-attachments/assets/51302468-5509-4e4b-9306-63ec67ccdd17">

I modified the MindBoggle atlas accordingly, with nearest-neighbor interpolation. See #1314

One other thing that I think about: the atlas is in 1.5 mm definition, whereas ASL is in ~ 4 mm definition. Should the atlas be smoothed to ASL resolution before the ROIs can be defined? Check what we do in xASL_stat_GetROIstatistics, because we already extrapolate the ROIs to have sufficient WM content.

- [x] Check what went wrong
- [x] Register MindBoggle
- [x] Answer questions in the e-mail
- [x] Save MindBoggle
- [x] Check if ROI extrapolation in `xASL_stat_GetROIstatistics` works fine with these thin/narrow ROIs

Slice 75, pseudo-CBF on background: before PVC extrapolation:
<img width="404" alt="image" src="https://github.com/user-attachments/assets/5bc34917-67f1-40b4-936f-f153da1f157e">
After PVC extrapoltion:
<img width="401" alt="image" src="https://github.com/user-attachments/assets/f847927f-96bf-4619-941b-f6a9e596fb1f">

This seems to work fine, though the included WM could be increased.
If we look at all ROIs together, after WM expansion for PVC, but before masking out the FoV/susceptibility/vascular masks, it looks like this:

<img width="1202" alt="image" src="https://github.com/user-attachments/assets/357e6bbc-300a-4264-b661-4cb9a4cc6663">

So while this is not perfectly aligned, note that after this there will be an intersection with pvGM (PVC==0) or PVC (PVC==2).

We will fix this in #1799.

ANSWERS JAN
Jan agrees with the alignment. (Rest is moved to #1799)

### Release notes
Nothing to report

**Comment by jan-petr** [comment]
1. Yes, it looks better aligned.
2. Keep the atlas in original resolution. Smoothing can happen in the population module right before we apply it, but not on the original.
3. Currently, we use c1t1 in original resolution to evaluate ASL. This is wrong, we need to use the smoothed PVGM. We have an issue for that and we need to finalize this. For most atlases, this is not a problem as they have very thick regions. For Mind-boggle, we might need to enlarge it as you said - but only before application. We should do that in a separate issue though.
4. All the other unfinished things you propose need to happen in a separate issue. Currently, we still work with C1t1 and not pvGM in standard space, so this expansion can wait until that is finalized.
