### ISSUE TITLE
Remove WMH lesions from (deep) WM masks in ROI calculations

### ISSUE THREAD

**Issue by MDijsselhof** [ExploreASL/ExploreASL#1745]
### Description
Currently, WMH lesions are present inside the (deep) WM masks used for Population module ROI analyses. However, users might want to exclude WMH lesions in these masks, or perhaps determine ROI values for only WMH lesions. In `xASL_stat_GetROIstatistics.m`, an option to exclude WMH or calculate for specifically WMH might use something like:
1. If WM is in the mask name -> remove WMH lesions inside WM mask (so for deepWM by default, or WM)
2. Calculate ROI in masks without and with WMH lesions in (deep) WM
3. Calculate ROI in masks only inside WMH lesions 

Henk-Jan: I was mistaken, we do remove WMH lesions already from both the subject-wise pvGM & pvWM:
left & right column are before & after WMH subtraction, lower row is twice the same pvWMH
slice 75
<img width="675" alt="image" src="https://github.com/user-attachments/assets/85338af6-a454-465a-898a-a7a03e7dedd6">
This is the deep WM template mask (WM expansion doesn't affect this mask)
<img width="401" alt="image" src="https://github.com/user-attachments/assets/1070a92c-85dd-436a-a4eb-f902f607c68b">
Then here we have the deep WM mask (left), the individual WM mask (middle) and the resulting mask (right)
<img width="1104" alt="image" src="https://github.com/user-attachments/assets/38fb2bf2-a377-40ab-9871-0d84e34b6162">

So the WMH are already removed from the WM mask.
Also, see here the deep WM template mask projected over the subject session CBF map:
<img width="1197" alt="image" src="https://github.com/user-attachments/assets/a21c7447-2d9f-4b4a-87fd-fc4b59421250">
And now the same after the subject-specific WM masking, note that the WMH are taken out and also the susceptibility area is masked out:
<img width="1200" alt="image" src="https://github.com/user-attachments/assets/10ad8c60-0add-4b29-97aa-d9a817a1621f">

### How to test

See test subject in `~/r-divi/RNG/Projects/ExploreASL/Insight46/insight46/Testing/ExploreASLWMHLesions/`

### Release notes

Required: summarize the changes for the release notes here

**Comment by HenkMutsaerts** [comment]
Fixed in #1314
