### ISSUE TITLE
Reading Gzipped Nii produces warning

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#177]
Three errors are produced:

1. 
Warning: The following error occurred converting from char to nifti:
Error reading header file "Corrupt". 
> In xASL_adm_ZipFileNameHandling (line 77)
  In xASL_adm_UnzipNifti (line 83)
  In xASL_io_ReadNifti (line 50)
  In xASL_io_Nifti2Im (line 58) 
Corrupt NIfTI: T1.nii
Trying to replace by GZ counterpart

2.
Warning: The following error occurred converting from char to nifti:
Error reading header file "Corrupt". 
> In xASL_adm_ZipFileNameHandling (line 77)
  In xASL_adm_UnzipNifti (line 83)
  In xASL_io_ReadNifti (line 50)
  In xASL_io_Nifti2Im (line 58) 
Corrupt NIfTI: T1.nii
Trying to replace by GZ counterpart
.nii & .nii.gz counterparts differed in their image matrix
Warning: Could not load T1.nii 
> In xASL_io_Nifti2Im (line 61) 
Message: Two files with same name, but different image: 
 T1.nii 
 T1.nii.gz
Warning: Cannot find image size T1.nii 
> In xASL_io_Nifti2Im (line 86) 
Something went wrong opening NifTI

3. 
xASL_io_SaveNifti('T1.nii','T1.nii.gz',im,[],1);
Warning: Invalid folder of file: T1.nii.gz 
> In xASL_io_SaveNifti (line 54) 
>>

**Comment by HenkMutsaerts** [comment]
The second option seems better as you explicitly test for it inside the function, using _fileparts_ and the _xASL_adm_UnixPath_ functionality if needed (which may need to be replaced by the _xASL_system_)

**Comment by jan-petr** [comment]
Fixed this issue in the adm-unzip that was called during reading. And also fixed a similar issue while saving.

**Comment by HenkMutsaerts** [comment]
Looks good, do we need to test this still?

Detail: are `pwd` & `pwd()` always equal?

**Comment by jan-petr** [comment]
You've already tested that - I first made the edit and then you started running your testing ;)

For specific cases - I have ran some dedicated smaller tests.

Yes - pwd and pwd() should be equal.
