### ISSUE TITLE
Population mask and tissue input check

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#1801]
### Description

Population module tissue masking and atlases sometimes creates an error when mask and tissue input doesn't match. This should be catched and correctly reported. And not crashing the code.

![image](https://github.com/user-attachments/assets/2d32fec8-102e-4ed8-90af-669e8c3fab7c)

### Tasks

- [x] Inform Mathijs

### Release notes
Nothing to report. Report along with #1753

**Comment by MDijsselhof** [comment]
Change text into (I would remove the first sentence):

When ROI atlases are provided in x.S.Atlases, their tissue types 
need to be provided as well, with either option 'GM', 'WM', 'WB' (GM+WM).
E.g., when not provided, these default to:
x.S.Atlases = ['TotalGM', 'DeepWM']
x.S.TissueMasking = ['GM', 'WM']

Also, this is currently not a warning but just text. so I would change the code to:

    warning('%s\n', 'When custom ROI atlases are provided in x.S.Atlases, their tissue types.', 'When custom ROI atlases are provided in x.S.Atlases, their tissue types need to be provided as well, with either option ''GM'', ''WM'', ''WB'' (GM+WM).');
    fprintf('%s\n', 'E.g., when not provided, these default to:');
    fprintf('%s\n', 'x.S.Atlases = [''TotalGM'', ''DeepWM'']');
    fprintf('%s\n\n', 'x.S.TissueMasking = [''GM'', ''WM'']');

**Comment by MDijsselhof** [comment]
Getting an error: 
![{D5FE0AD2-6B84-41BB-B055-46A7E81D26C6}](https://github.com/user-attachments/assets/af1d3722-4dfe-40b5-93bf-78b8b873dcbb)
