### ISSUE TITLE
Testing release-#1.3.0

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#181]
/TestDataSets/Philips_2DEPI_Segmentation_2D_T2_SPM_HiQ/102/ASL_1/ASL4D.json skips MoCo because of these fields:

"motion_correction":0,
"realign_ASL":0,

which make it seem as if the pipeline is not completely finished. Is this on purpose or can we delete these fields?

**Comment by HenkMutsaerts** [comment]
Siemens3DGRASE_Structural_AlreadyDone_HiQ gives the following warnings:

030_CreateBiasfield was performed
Loading & saving individual parameter files...100%Warning: Parms.RepetitionTime had multiple values 
> In xASL_stat_GetDICOMStatistics (line 97)
  In xASL_module_Population (line 131)
  In xASL_Iteration>runIteration (line 361)
  In xASL_Iteration (line 100)
  In ExploreASL_Master (line 143)
  In xASL_qc_TestExploreASL (line 323)
  In xASL_qc_TestExploreASL_HM (line 53) 

Printing summary of ASL4D DICOM values
Loading & saving individual parameter files...100%Warning: Parms.RepetitionTime had multiple values 
> In xASL_stat_GetDICOMStatistics (line 97)
  In xASL_module_Population (line 131)
  In xASL_Iteration>runIteration (line 361)
  In xASL_Iteration (line 100)
  In ExploreASL_Master (line 143)
  In xASL_qc_TestExploreASL (line 323)
  In xASL_qc_TestExploreASL_HM (line 53)

**Comment by HenkMutsaerts** [comment]
Siemens3DGRASE_Structural_AlreadyDone_HiQ gives the following warning:

Siemens M0 scan (not Philips), so no M0 scale slope assumed
x.Q.TissueT1 did not exist, default=1240 used
Warning: Multiple M0 TRs found: 5390  5500, 5390 used 
> In xASL_quant_M0 (line 113)
  In xASL_wrp_ProcessM0 (line 160)
  In xASL_module_ASL (line 361)
  In xASL_Iteration>runIteration (line 361)
  In xASL_Iteration (line 100)
  In ExploreASL_Master (line 132)
  In xASL_qc_TestExploreASL (line 323)
  In xASL_qc_TestExploreASL_HM (line 53) 
Single 3D M0 readout assumed

**Comment by jan-petr** [comment]
Wasn't me who did these...

The subject moved a lot and has quite high vascular artifacts, so can be an issue with MoCo, but it should still work.

Similar with Realign_ASL - it has T2 with thick slices, but the co-reg should still work.

You can put them both to 1 and see what this does. Or have you put them to 0 just so that this option can be tested?

Altogether, it does test something and produces CBF values, so we can keep these things off for testing purposes as well. And change the QC so that it produces 1 and not 0 as completely finished (the bug is rather there).

> /TestDataSets/Philips_2DEPI_Segmentation_2D_T2_SPM_HiQ/102/ASL_1/ASL4D.json skips MoCo because of these fields:
> 
> "motion_correction":0,
> "realign_ASL":0,
> 
> which make it seem as if the pipeline is not completely finished. Is this on purpose or can we delete these fields?

**Comment by jan-petr** [comment]
> Siemens M0 scan (not Philips), so no M0 scale slope assumed

That's just harmless info. But I don't see that it has any special value, so I would skip it if you agree.

**Comment by jan-petr** [comment]
> x.Q.TissueT1 did not exist, default=1240 used

Yes. TissueT1 is neither in the global JSON or in the ASL JSON - so OK to report that warning.

**Comment by jan-petr** [comment]
But I found another really weird thing in the code - see below:

> fprintf('%s\n','x.Q.TissueT1 did not exist, default=1240 used');
> x.Q.TissueT1 = 800; % 800 ms for WM, average of frontal & occipital WM from Lu et al., JMRI 2005 & 3 studies they refer to

You claim to assign 1240, but in fact you assign 800 ms like for WM. Which is fine if we count the WM T1 for M0, but we use TissueT1 as a value for the CBF quantification as well, and most global JSONs have GM T1 as Tissue T1. 

So we have to separate TissueT1 for CBF quant and for M0 relaxation correction - this is rather essential and potentially a huge bug in our quantification process!!

**Comment by jan-petr** [comment]
The real warning

> Warning: Multiple M0 TRs found: 5390 5500, 5390 used

Is not a bug in the code, but in the test dataset - two TRs were in the JSONs, so it took the shorter and correctly reported a warning. I have deleted the second TR from the datasets and pushed the change.

This will fix this warning, but please read also all my comments above!

**Comment by HenkMutsaerts** [comment]
* `realign_ASL/MoCo` option -> I'm fine with changing `xASL_module_ASL` to store this status file even if it skips this step, that will be consistent with saving the status files when skipping FLAIR processing
* `Siemens M0 scan (not Philips), so no M0 scale slope assumed:`
What do you mean by "skip it", do you mean that we remove the warning or ignore the warning? Appropriate warnings are good, the point is that it is nice to be able to scroll through the diary output without seeing warnings when the test is sufficient.
* `Yes. TissueT1 is neither in the global JSON or in the ASL JSON - so OK to report that warning:`
This was not my question indeed, I pointed to the `Multiple M0 TRs found`
* Good point indeed, I suggest to:
A) rename x.Q.TissueT1 to x.Q.T1_GM
B) add x.Q.T1_WM
C) check that the warnings & user input of the M0 quantification method is based on either GM or WM
* * Actually the M0 quantification & image processing are two different functions, that may be independent. We have the choice for the new masked M0 processing or the older unmasked processing, for which you should correct incomplete saturation with WM or GM T1, respectively. So perhaps we do have to link the quantification & image processing.
We could still keep them unlinked, e.g. by getting the M0 bias field from the WM but restoring the signal around the GM to what it was before the processing (but after T1 GM correction) but this would be very susceptible to registration etc, so using the WM for both quantification & processing is probably more reproducible.
* `I have deleted the second TR from the datasets and pushed the change` Thanks!

**Comment by jan-petr** [comment]
> * `realign_ASL/MoCo` option -> I'm fine with changing `xASL_module_ASL` to store this status file even if it skips this step, that will be consistent with saving the status files when skipping FLAIR processing

OK. Will you do that then?

> * `Siemens M0 scan (not Philips), so no M0 scale slope assumed:`
>   What do you mean by "skip it", do you mean that we remove the warning or ignore the warning? Appropriate warnings are good, the point is that it is nice to be able to scroll through the diary output without seeing warnings when the test is sufficient.

First - this isn't warning, just an information, as nothing is wrong. So we either accept this as an information and do nothing about it (i.e. keep as is or slightly change the text). Or we remove this line from the output as this isn't important and might be only confusing and distracting.

> * Good point indeed, I suggest to:
>   A) rename x.Q.TissueT1 to x.Q.T1_GM
>   B) add x.Q.T1_WM
>   C) check that the warnings & user input of the M0 quantification method is based on either GM or WM
> * * Actually the M0 quantification & image processing are two different functions, that may be independent. We have the choice for the new masked M0 processing or the older unmasked processing, for which you should correct incomplete saturation with WM or GM T1, respectively. So perhaps we do have to link the quantification & image processing.
>     We could still keep them unlinked, e.g. by getting the M0 bias field from the WM but restoring the signal around the GM to what it was before the processing (but after T1 GM correction) but this would be very susceptible to registration etc, so using the WM for both quantification & processing is probably more reproducible.

This whole thing - we still need to address this - I am just keeping it here for the reference, so that I could answer the other questions.

**Comment by HenkMutsaerts** [comment]
* `realign_ASL/MoCo` Just fixed this, last time testing but this should be fine

* `Siemens M0 scan (not Philips), so no M0 scale slope assumed:` thought you meant that this was a warning, fine to keep this as information, or to remove it if this is confusing. I couldn't find it now in the functions so leave this to you.

* Just tested on `Linux Matlab 2014` as well, works fine.
We just keep getting the warning in CAT12 that the input parameter `CSF` doesn't exist, you know how to easily address this right?

**Comment by HenkMutsaerts** [comment]
One additional issue: we still have this very low CBF from the `Philips_2DEPI_Lesion_NoFLAIR_NoM0_HiQ`, I thought you fixed this by adding another dataset that didn't have low CBF?

**Comment by jan-petr** [comment]
To sum up:

* Henk fixed MoCo
* Jan removed the Siemens no M0 message as superfluous
* CAT12 CSF input missing is a new issue.
* Low values in Philips Testdata is a new issue.
The remaining problem is:

x.Q.TissueT1 = 800; % 800 ms for WM, average of frontal & occipital WM from Lu et al., JMRI 2005 & 3 studies they refer to

You claim to assign 1240, but in fact you assign 800 ms like for WM. Which is fine if we count the WM T1 for M0, but we use TissueT1 as a value for the CBF quantification as well, and most global JSONs have GM T1 as Tissue T1.

Good point indeed, I suggest to:
A) rename x.Q.TissueT1 to x.Q.T1_GM
B) add x.Q.T1_WM
C) check that the warnings & user input of the M0 quantification method is based on either GM or WM
Actually the M0 quantification & image processing are two different functions, that may be independent. We have the choice for the new masked M0 processing or the older unmasked processing, for which you should correct incomplete saturation with WM or GM T1, respectively. So perhaps we do have to link the quantification & image processing.
We could still keep them unlinked, e.g. by getting the M0 bias field from the WM but restoring the signal around the GM to what it was before the processing (but after T1 GM correction) but this would be very susceptible to registration etc, so using the WM for both quantification & processing is probably more reproducible.

**Comment by jan-petr** [comment]
New issue created for the last point.
