### ISSUE TITLE
Low mean CBF values in TestDataSet

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#184]
In test subject Philips_2DEPI_Lesion_NoFLAIR_NoM0_HiQ has too low values
* Check the partial volume correction
* Check about the small FOV

### Release notes
Skip PVC in Population statistics, when this does not make sense for a given ROI.

### Special note
Remove 0-masking in Philips_2DEPI_Lesion_NoFLAIR_NoM0_HiQ in TestDataSets

**Comment by HenkMutsaerts** [comment]
Update: the image voxel CBF values in GM are correct, though still the global GM CBF estimates are too low, so this really needs to be checked.

**Comment by MDijsselhof** [comment]
I think the issue is that the ROI quantification is not also masked by the FOV, therefore only half of the brain has values while the whole ROI is used for calculating the mean.

**Comment by MDijsselhof** [comment]
I suggest multiplying the x.WB mask with FoV at all times, what do you think?

**Comment by jan-petr** [comment]
Yes. That is a good solution to me. Also - please try to re-run the same thing also with native-processing turned on and see what are the mean CBF values in the native processing. Because we might need to do the same thing for native processing to ensure that it follows a similar procedure. But it is possible that the FOV multiplication was already there.

A question for Henk - was the initial logic meant like this, or was the CBF image supposed to be set to NaN everywhere outside the FoV?

**Comment by MDijsselhof** [comment]
I've hardcoded the vector to include all masks, the resulting values are:

![image](https://user-images.githubusercontent.com/75380250/113002697-56977d80-9172-11eb-934f-21156322654e.png)

Henk-Jan, Jan told me you could look into the reason why x.S.bmasking is set to 0 in this case.

**Comment by MDijsselhof** [comment]
Quick fix: remove _bMasking=0_ from datapar

**Comment by jan-petr** [comment]
I have recreated the branch so that we don't have several commits for a single change.

I have copied the commits - with some modifications - see the comments below.

**Comment by jan-petr** [comment]
@MDijsselhof FYI:
I have excluded zeros from Mean computation, but also from SpatialCoV computation.

I have done that on mask, rather than on the imCBF image as past that point, imCBF is masked and no NaNs should be there anymore - this wouldn't be a problem for the mean calculation but could be for PVC.

**Comment by jan-petr** [comment]
I have closed the PR and will create a new one, because I have recreated the branch.

**Comment by jan-petr** [comment]
The issue was the bMasking was set to 0, that includes tissue specific masking as well. In that case, both GM and WM is set to 1 everywhere. But then you can't really run PVC with such settings because the output doesn't make any sense.

So I have fixed the code so that it would, for certain scenarios, check and skip PVC calculation - these scenarios include WB ROI, and no tissue masks used.

**Comment by jan-petr** [comment]
> In test subject Philips_2DEPI_Lesion_NoFLAIR_NoM0_HiQ has too low values
> 
> * Check the partial volume correction
> * Check about the small FOV

### Release notes
Skip PVC in Population statistics, when this does not make sense for a given ROI.

### Special note
Remove 0-masking in Philips_2DEPI_Lesion_NoFLAIR_NoM0_HiQ in TestDataSets

**Comment by HenkMutsaerts** [comment]
One thing that I believe is important, is that we do not merge this commit in R1.6.0 but in a separate hotfix. The point is that our quantification will change a lot with this small commit, but not so much with all other commits in R1.6. So it makes more sense to separate this commit, then it is easier to see if the effects of the other R1.6 commits on quantification.

**Comment by jan-petr** [comment]
As said above. This shouldn't affect the quantification at all. I have removed options that were not really used. Only the QC_CBF will be affected, but none of the Results. And it will skip calculation of PVC2 for some cases, but for cases where it makes no sense.

So we should indeed be careful that it doesn't change the results, but I assume it won't. So lets just run 10-TestDatasets before and after merging it to check if all is good.
