### ISSUE TITLE
BIDS2xASL conversion

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#189]
At the start of `ExploreASL_Master->ExploreASL_Initialize`, it should call a separate function that checks if there is a `/raw` BIDS folder (i.e. containing NIfTIs and DICOMs, and having BIDS folder names), and converts this to folder `/derivatives/ExploreASL_analysis`. This should create a copy and may issue errors/warnings if data are incomplete.
Further BIDS validation will not be implemented on this point but added later.

I will test this with the 5 [BIDS example datasets](https://github.com/patsycle/bids-examples/tree/BEP005).
The JSON files can stay as they are, these are handled by `xASL_adm_Load2Parms.m`.

**Comment by HenkMutsaerts** [comment]
Per BIDS, we should have:
/sourcedata/
/rawdata/
/derivatives/ExploreASLanalysis

for now, we could copy data from /rawdata/ to /derivatives/ExploreASLanalysis, but for later we could try symbolic links. Though, we would have to check if these can be used and overwritten by actual files, when they are processed by ExploreASL.

**Comment by HenkMutsaerts** [comment]
Currently, adding ASL to BIDS Matlab to help parsing:
https://github.com/ExploreASL/bids-matlab/commits/feature-%23ASL_BIDS

**Comment by HenkMutsaerts** [comment]
### Parameters translation table:

| **BIDS**                  | **ExploreASL legacy**                                |
|-------------------------------|------------------------------------------------------|
| [MRAcquisitionType PulseSequenceType ]                  | x.Sequence                                          |
| MRAcquisitionType                  | x.readout_dim                                          |
| Manufacturer                  | x.Vendor                                          |
| RepetitionTimePreparation                  | RepetitionTime ??                                         |
| ArterialSpinLabelingType                  | x.Q.LabelingType                                         |
| PostLabelingDelay                  | x.Q.Initial_PLD                                         |
| LabelingDuration                  | x.Q.LabelingDuration                                         |
| BackgroundSuppressionNumberPulses                  | x.Q.BackgroundSuppressionNumberPulses                                         |
| BackgroundSuppressionPulseTime                  | x.Q.BackgroundSuppressionPulseTime                                         |
| BackgroundSuppression == off                  | x.Q.BackgroundSuppressionNumberPulses == 0                                         |

### @jan-petr, where should we get these from:
* x.Q.PresaturationTime?
* x.Q.SliceReadoutTime?
* AcquisitionVoxelSize?

### M0Type -> I will parse specifically

**Comment by HenkMutsaerts** [comment]
Current issues found:

_3D spiral_

```
Error using xASL_wrp_Quantify (line 236)
Unknown LabelingType, needed for quantification

Error in xASL_module_ASL (line 409)
        xASL_wrp_Quantify(x);

Error in xASL_Iteration>runIteration (line 361)
				[result, x] = jobfn(x); % [result, x] = jobfn(x, job_ex);

Error in xASL_Iteration (line 100)
	[bAborted, xOut] = runIteration(dbSettings);

Error in ExploreASL_Master (line 141)
        [~, x] = xASL_Iteration(x,'xASL_module_ASL');
```


For all: need to automatically detect readout type:
```
Warning: No x.Sequence defined 
> In xASL_adm_DefineASLSequence (line 37)
  In xASL_module_Population (line 59)
  In xASL_Iteration>runIteration (line 361)
  In xASL_Iteration (line 100)
  In ExploreASL_Master (line 152) 
If there are multiple sequence types, this needs to be implemented yet here
Otherwise, please define x.Sequence
Setting x.Sequence=3D spiral to fool the pipeline here
```

_Philips_PCASL_2DEPI:_

Something wrong with T1w segmentation?


_multiple instances:_

```
ERROR: Job iteration terminated!

ans =

Reference to non-existent field 'RepetitionTime'.

Error in xASL_quant_M0 (line 119)
        TR = M0_parms.RepetitionTime; % This will be either the separate M0-scan value or the ASL scan value (if UseControlAsM0)


Error in xASL_wrp_ProcessM0 (line 160)
M0_im = xASL_quant_M0(xASL_io_Nifti2Im(x.P.Path_rM0), x);


Error in xASL_module_ASL (line 359)
            xASL_wrp_ProcessM0(x);

Error in xASL_Iteration>runIteration (line 361)
				[result, x] = jobfn(x); % [result, x] = jobfn(x, job_ex);

Error in xASL_Iteration (line 100)
	[bAborted, xOut] = runIteration(dbSettings);

Error in ExploreASL_Master (line 141)
        [~, x] = xASL_Iteration(x,'xASL_module_ASL');
```

_and for TopUp:
environment-specific:_

`Warning, FSL folder not found!`

_And:_

`Warning: TotalReadoutTime JSON field missing, skipping TopUp `

_And the same bug that Mathijs found:_
```
  In xASL_fsl_TopUp>ObtainTopUpParms (line 507)
  In xASL_fsl_TopUp (line 126)
  In xASL_module_ASL (line 210)
  In xASL_Iteration>runIteration (line 361)
  In xASL_Iteration (line 100)
  In ExploreASL_Master (line 141) 

ERROR: Job iteration terminated!

ans =

Undefined function or variable 'iROI'.

Error in xASL_fsl_TopUp (line 148)
    [Fpath, Ffile] = xASL_fileparts(PathsORI{iROI});

Error in xASL_module_ASL (line 210)
        bSuccess = xASL_fsl_TopUp(x.SESSIONDIR, 'asl', x, x.P.Path_ASL4D);

Error in xASL_Iteration>runIteration (line 361)
				[result, x] = jobfn(x); % [result, x] = jobfn(x, job_ex);

Error in xASL_Iteration (line 100)
	[bAborted, xOut] = runIteration(dbSettings);

Error in ExploreASL_Master (line 141)
        [~, x] = xASL_Iteration(x,'xASL_module_ASL');
```

**Comment by HenkMutsaerts** [comment]
`TotalAcquiredVolumes	OPTIONAL, but RECOMMENDED when not all 3D volumes are provided by the scanner`

This BIDS parameter should become REQUIRED, 1) we need this for quantification in some cases (e.g. for GE, as GE sums instead of averages the raw magnitude reconstruction signal), and 2) it can be more confusing to the user to assure if "all volumes are provided by the scanner" than to find the number of acquired volumes.

**Comment by HenkMutsaerts** [comment]
@jan-petr When you test this, start with `/ExploreASL/Development/BIDS/BIDS_fullPipelineTest`.
When you adapt a few paths you should be able to run BIDS2Legacy & ExploreASL serially.

**Comment by HenkMutsaerts** [comment]
@jan-petr  Very nice! Though `xASL_test_BIDSFlavorsFull` will be less necessary in the near future; when we add import to `ExploreASL_Master`, the test script will then just call `ExploreASL_Master` to do the import, conversion and processing, right?

Or, we should copy some of `xASL_test_BIDSFlavorsFull` to `ExploreASL_Master`?

**Comment by jan-petr** [comment]
> @jan-petr Very nice! Though `xASL_test_BIDSFlavorsFull` will be less necessary in the near future; when we add import to `ExploreASL_Master`, the test script will then just call `ExploreASL_Master` to do the import, conversion and processing, right?

True - but it is still helpful to check also the middle steps - because we have the conversion and reference ready - so we cane easily pick errors in the middle. And it is important to keep BIDS conversion working and not only the final legacy output.
 
> Or, we should copy some of `xASL_test_BIDSFlavorsFull` to `ExploreASL_Master`?

We can later copy some of its functionality. But as above - this will work for now for legacy, but it is especially the middle step BIDS that we need to keep in good condition for the future.

**Comment by MichaelStritt** [comment]
@jan-petr & @HenkMutsaerts do you need me to run another test tonight? Is there anything I can help with?

**Comment by jan-petr** [comment]
> @jan-petr & @HenkMutsaerts do you need me to run another test tonight? Is there anything I can help with?

I will fix a few small things. Then we need to rebase this branch (PAR-REC error, Phoenix UTF error etc) and start testing again.

**Comment by jan-petr** [comment]
@HenkMutsaerts You got one thing wrong. The function xASL_bids_parms2BIDS is for converting legacy to BIDS and vice versa - that is fine. But xASL_adm_LoadParms operates on Legacy only! It is only reading the DataParms.m or DataParms.json and keeps everything strictly to Legacy - and this is then directly loaded and used in the quantification functions! Therefore, in xASL_adm_LoadParms, you shouldn't rename anything! The only renaming that was there was between the old and new version of Legacy - it was not for BIDS. I thus have to revert all these edits and write them to the xASL_bids_parms2BIDS.m only.

**Comment by jan-petr** [comment]
@MichaelStritt I am going through your logged errors - very useful! I will try to fix as much of them as possible. Some need also an update of the flavors database - I will do that as well. You can re-run the test tonight. And I will try to fix everything till tomorrow. So tomorrow, you would be able to clone again the flavors, re-run the import and test again with rebase branch with all other errors from other branches fixed.

**Comment by jan-petr** [comment]
Remaining known errors:
- SliceReadoutTime needs to be fixed from vector to scalar. But not in loadparms, but before each its use - we will need it as a vector for MultiBand!!
- All errors reported by Michael
- TotalAcquiredNumber in flavors
- Doesn't work correctly with asl_M0_ap.nii (it converts the one in fmap but not in perf directory).

**Comment by HenkMutsaerts** [comment]
Again: can you please commit a bit more specific, the "Fixed JSON conversions..." contains a lot of things, including that my SliceReadoutTime parsing is completely removed. And then you add it in another commit; makes it confusing. Please, if you change the SliceReadoutTime behavior, do this in a single commit rather than distributed over multiple commits, that I have to search what happened ;)

Also: the parsing of SliceReadoutTime was at a single location but is now at multiple locations, is its parsing similar at every location? Then I would suggest creating a separate function; or adding some comments, before we know it the whole code becomes a convoluted jungle ;)

Otherwise, very good of course ;)

**Comment by jan-petr** [comment]
Regarding SliceReadoutTime - sorry, this was more complicated - it wasn't a parsing issue, so I had to remove the whole parsing as not necessary. SliceReadoutTime can simply be a vector or scalar, and this doesn't have to be parsed. When applied - there's not really a single function that can be written for that as every application is slightly different. We have to decide case-by-case how to apply it differently as a scalar or as a vector. That's why it's on several locations. And that's why the parsing and application step was split into two.

**Comment by jan-petr** [comment]
@HenkMutsaerts Can you fix the following? M0 from the perf directory is not copied when it looks like this "sub-Sub1_dir-ap_m0scan". This is the case for Philips_PCASL_3DGRASE_R5.4_TopUp dataset.

@MichaelStritt I have fixed big part of the errors - so a re-run is on the schedule (excluding the PAR-REC data yet) to find out what errors were not solved. Thanks :)

**Comment by HenkMutsaerts** [comment]
For the `SliceReadoutTime`, I still think there is a lot of redundancy, and it becomes quite difficult to read what is being done with this parameter throughout the pipeline. I would put this parsing in a separate function, though we might call it from different locations.

**Comment by HenkMutsaerts** [comment]
@jan-petr What is this `xASL_bids_Config`? It looks like this is information needed for parsing BIDS right? That should be moved to `bids-matlab` then. We should only do the conversion from BIDS to legacy here.

Likewise, `bids-matlab/bids+/layout` probably fails to recognize `Philips_PCASL_3DGRASE_R5.4_TopUp/../perf/sub-Sub1_dir-ap_m0scan`; also are you sure that this is BIDS compliant? This `dir-ap` is not needed in the filename as you have this in the JSON sidecar as well. The issue is that `bids-matlab/bids+/layout`: line 393, assumes no `dir-(ap|pa)`. We can add this if needed, but it should be added then to the original `bids-matlab` repository, which just converted this file to a schema design... never a dull moment:)
Can we put this on my list to fix later in a separate issue?

**Comment by jan-petr** [comment]
> For the `SliceReadoutTime`, I still think there is a lot of redundancy, and it becomes quite difficult to read what is being done with this parameter throughout the pipeline. I would put this parsing in a separate function, though we might call it from different locations.

Sure. Essentially, the parameter can be either a vector or a single number. These are then applied differently in ASL and M0 quantification. The easiest will be to turn it to a vector at the start of ASL module and then always apply as a vector.

However, things now work, so I would merge this commit and make this a new issue. 

Let me know if you want to fix it here/new issue. And if schedule to 1.5.0 or 1.6.0.

**Comment by jan-petr** [comment]
> @jan-petr What is this `xASL_bids_Config`? It looks like this is information needed for parsing BIDS right? That should be moved to `bids-matlab` then. We should only do the conversion from BIDS to legacy here.

Nono - xASL_bids_Config is not for parsing BIDS, but for DICOM2BIDS conversion = the import. So I would keep it in xASL. I would not move the import of DICOM->BIDS to bids-matlab as it has quite a lot of xASL functions and rather different structure = a lot of work.
 
> Likewise, `bids-matlab/bids+/layout` probably fails to recognize `Philips_PCASL_3DGRASE_R5.4_TopUp/../perf/sub-Sub1_dir-ap_m0scan`; also are you sure that this is BIDS compliant? This `dir-ap` is not needed in the filename as you have this in the JSON sidecar as well. The issue is that `bids-matlab/bids+/layout`: line 393, assumes no `dir-(ap|pa)`. We can add this if needed, but it should be added then to the original `bids-matlab` repository, which just converted this file to a schema design... never a dull moment:)
> Can we put this on my list to fix later in a separate issue?

Yes. Pretty sure that this is BIDS compatible. Maybe not strictly required here, but totally compatible. Made a new issue out of that #353 . It can wait for the official BIDS2Legacy conversion - so till 1.6.0.

**Comment by HenkMutsaerts** [comment]
You mean you use xASL_bids_Config here inversely? That sounds good. Though I would make the function a bit more specific, Config is very generic. Also, we should discuss if we change the requirement mode of NSA in BIDS?

**Comment by jan-petr** [comment]
SliceReadoutTime proper parsing in a single function instead of at every application has a new issue #356.

"Though I would make the function a bit more specific, Config is very generic." Not sure I understand, you want to change the function name?! I am fine with that.

"Also, we should discuss if we change the requirement mode of NSA in BIDS?" New name and definition in negotiation with BIDS. There's a new issue for this #357.

**Comment by HenkMutsaerts** [comment]
>> SliceReadoutTime proper parsing in a single function instead of at every application has a new issue #356.

Nice!

>> "Though I would make the function a bit more specific, Config is very generic." Not sure I understand, you want to change the function name?! I am fine with that.

Yes, just to keep function names self-explanatory

>> "Also, we should discuss if we change the requirement mode of NSA in BIDS?" New name and definition in negotiation with BIDS. There's a new issue for this #357.

Nice!

**Comment by HenkMutsaerts** [comment]
Just see my edits of the issue names, to make them a bit more self-explanatory

**Comment by HenkMutsaerts** [comment]
@HenkMutsaerts: I need to rewrite/clean some header(s)
