### ISSUE TITLE
Comparing BIDS folders

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#193]
Function that compares two BIDS folders with several subfolders and studies and prints the differences. Specifically:
* It goes through all folders and subfolders in the first path and checks if there's an existing counterpart.
* It checks as well all possible extra files and directories in the second path if they are in the first path and reports them.
* My idea was that if it finds that two directories exist in both paths, then it iteratively calls the same function to check if their content is the same as well - that should make the programming easier.
* It checks if the list of files exist in both directories and reports the missing/extra files.
* If both files exist and are JSONs or NIIs or TSV, then loads them and compare the content.
* It can probably just output differences on the screen, but you might think of a more smart aggregating of the outputs in the function output so that they can be gathered through the iterative call and a sum returned by the parent function.

Take the BIDS as the use-case - i.e. focus on things that are in BIDS (NII, JSON, TSV), but probably no need to check the other file types. But you don't need to have any really BIDS specific functionality - it doesn't need to check the quality of the data, just the presence and similarity - i.e. doesn't need to interpret BIDS>

**Comment by MichaelStritt** [comment]
Hey @jan-petr do you want to give this function a try? I've tested the functionality with a few datasets. I had to use the (newer) Matlab function ```isfile``` since **xASL_exist** didn't behave as intended, but besides that it should be fine.

**Comment by jan-petr** [comment]
Great. Some small comments to be implemented:

* printReport seemed to me more of an OPTIONAL parameter. I have thus defined this formally in the header and assigned a default value if not assigned (this one I already did that in the recent commit).
* Seems that directory ending with '/' is not taken - can you check if the last character of input-path is '/' and automatically remove?
* This notation is not really working with Linux, simple '*' is probably enough. There's a function xASL_adm_GetFileList that can help just in case and it also removes the '..' directories. No need to use it, just in case other stuff fails.
Error using dir
Characters adjacent to a ** wildcard must be file separators.
Error in xASL_bids_compareStructures (line 73)
    filesA = dir(fullfile(pathDatasetA, '**\*.*'));
* dir is also working differently with Linux. Both folder names and file names are assigned to 'name' instead of 'folder', 'folder' is always empty - see examples below. Either use the xASL_adm_GetFileList which works rather consistently on all platforms, or try to use some ispc() cases - but that might prove to be more work and less consistent across OS at the end :(
name: '..'
     folder: ''
       date: '10-Nov-2020 20:47:01'
      bytes: 0
      isdir: 1
    datenum: 7.3811e+05
AND
 name: 'dataset_description.json'
     folder: ''
       date: '28-Oct-2020 22:34:43'
      bytes: 384
      isdir: 0
    datenum: 7.3809e+05
AND
name: 'sub-Sub1'
     folder: ''
       date: '10-Nov-2020 20:46:27'
      bytes: 0
      isdir: 1
    datenum: 7.3811e+05
* Can you make it work recursively (perhaps as optional parameter) - so that it checks larger file structures and goes deeper inside the BIDS structure.
* Can you have the 'thresh' as an optional parameter on input of the main function
* For the JSON files - can you actually read them and compare if fields are missing/present and values identical or not and then report differences, rather than plain txt difference. Because JSON files can be identical even if the order is different.

**Comment by MichaelStritt** [comment]
Hey @jan-petr 
I should have some time today. I'll work on it right away 👍 

>     * Seems that directory ending with '/' is not taken - can you check if the last 
>     character of input-path is '/' and automatically remove?

Sure!

>     * This notation is not really working with Linux, simple '_' is probably enough. 
>       There's a function xASL_adm_GetFileList that can help just in case and it also 
>       removes the '..' directories. No need to use it, just in case other stuff fails.
>
>       Error using dir
>       Characters adjacent to a ** wildcard must be file separators.
>       Error in xASL_bids_compareStructures (line 73)
>       filesA = dir(fullfile(pathDatasetA, '***._'));
> 
>     * dir is also working differently with Linux. Both folder names and file names are 
>     assigned to 'name' instead of 'folder', 'folder' is always empty - see examples below. 
>     Either use the xASL_adm_GetFileList which works rather consistently on all platforms, 
>     or try to use some ispc() cases - but that might prove to be more work and less consistent 
>     across OS at the end :(

Sorry, I didn't think about that. I was working on windows and I didn't check if it works on linux, too. The nice thing about **dir** is that it works recursively. I first tried a version using **xASL_adm_GetFileList**, but there you have to program the recursive part yourself.

>     * Can you make it work recursively (perhaps as optional parameter) - 
>     so that it checks larger file structures and goes deeper inside the BIDS structure.

So this should actually work with **dir**, but I'll try it on my virtual linux later and will test if I can make it work on both. Otherwise I'll re-implement it using **xASL_adm_GetFileList** and some for loops to walk through sub-directories.

>     * Can you have the 'thresh' as an optional parameter on input of the main function

No problem at all. Maybe we can use a more sophisticated approach here, too. At least RMS error or something.

>     * For the JSON files - can you actually read them and compare if fields are missing/present and values 
>     identical or not and then report differences, rather than plain txt difference. Because JSON files can be 
>     identical even if the order is different.

Sure, I can use the ExploreASL JSON read function and just compare the fields.

I'll make a list of all the points and work on it this morning.

**Comment by jan-petr** [comment]
Hi @MichaelStritt,

I see that the '/' and RMS is already implemented. Great.
For the search path, adding:
_filesA = dir(fullfile(pathDatasetA, '**','\*.\*'));_
on line 92 works just fine. Sorry, I have tried only '\*' before and that's why I didn't get the recursive stuff - I agree that it is more elegant the way you have it... Though there are more things to fix for Linux - I'll try to test something, but I won't touch the implementation not to generate conflicts.

thanks.

**Comment by MichaelStritt** [comment]
Hey @jan-petr, 
have you seen this error before?
```
Error using spm_jsonread
Input must be a string.
Error in xASL_import_json (line 63)
jsonData = spm_jsonread(DataParFile);
Error in xASL_bids_compareStructures>checkFileContents (line 192)
                jsonA = xASL_import_json(currentFileA);
Error in xASL_bids_compareStructures (line 142)
    identical = checkFileContents(fileListA,fileListB,pathDatasetA,pathDatasetB,identical,printReport,thresh);
```
Tried to read the JSON files (109f447), but I seem to do something wrong.

**Comment by jan-petr** [comment]
Yes - that's because it was string, not char :) Sounds weird right :D

Line 92+93: filesA = dir(fullfile(pathDatasetA, '**','*.*'));
Line 192+193: jsonA = xASL_import_json(char(currentFileA));

**Comment by jan-petr** [comment]
Sorry
filesA = dir(fullfile(pathDatasetA, '**','\*.\*'));

**Comment by MichaelStritt** [comment]
Oh sorry, stupid me. I tried to explicitly convert them to strings 👍

**Comment by jan-petr** [comment]
spm_jsonread is a MEX, so it won't easily handle these simple conversion that normal .m file probably wouldn't complain about...
BTW: we can change the xASL_import_json as well:
put 
if isstring(DataParFile)
DataParFile = char(DataParFile);
end
on line 57...

**Comment by jan-petr** [comment]
Last small thing - can you please move the file to the Functions folder. The Development/BIDS folder is not on the path. And the function is working rather good, so not 'development' material anymore...

**Comment by MichaelStritt** [comment]
> BTW: we can change the xASL_import_json as well:
> put
> if isstring(DataParFile)
> DataParFile = char(DataParFile);
> end
> on line 57

Good idea! I'll do a quick fix in develop. A separate branch for this would probably be overkill.

**Comment by jan-petr** [comment]
Yes. Separate branch doesn't make sense. But you can do the fix in this branch as well. We'll merge very soon anyway.

**Comment by MichaelStritt** [comment]
Hey @jan-petr, I think it's ready to be tested again.
Right now, most of the differences are only printed out to the console.
I can add more information to the **result** structure if necessary.

**Comment by jan-petr** [comment]
Works perfectly now. Thanks.

I did some minor things in reporting and will commit the change soon:
* Stating that there are no missing files.
* Reporting only different files.
* Small change in the reporting style.
* No need to check if the JSON fields are the same, because in the other branch of IF, we anyway go through all the shared fields. So I have split the list to shared and missing and compared shared (that's the same as if there's no difference).
* Made a difference between missing in source and missing in target.
* It reported 'It seems we are comparing neither numbers nor text ...' too often - I have fixed that.

**Comment by MichaelStritt** [comment]
Great, if you want we can do the merge after your mentioned next commit.

**Comment by jan-petr** [comment]
A few more things (almost ready with the commit now and will create the PR afterwards):
* renamed some variables. It was me now, or Henk in the review anyway :D
* compareFieldLists takes two identical lists - it can have only one. Plus it was called for each field in the list, but with the full list :D

**Comment by jan-petr** [comment]
@MichaelStritt Can you check my latest edits and quickly check if this works for you on Windows as well? thanks
