### ISSUE TITLE
Advanced DICOM2BIDS import

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#194]
Add these features to the DICOM2BIDS import:
* (already part of issue 223) use Phoenix protocol 
* use Philips XX import
* Automatic detection M0 image
* scanner exam card export (need to write a reader)

**Comment by HenkMutsaerts** [comment]
Why don't we create these as separate issues?

**Comment by MichaelStritt** [comment]
I'm creating a separate issue #223 for the phoenix protocol reading now.

**Comment by jan-petr** [comment]
Yes. Closing and adding as separate issues...
