### ISSUE TITLE
All contributors

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#196]
Add [all contributors](https://github.com/all-contributors/all-contributors) to `README.md`.

@MichaelStritt: do you want to do this? Looks pretty cool!

**Comment by MichaelStritt** [comment]
Ok, I've tested it in a private repository. The bot seems to work fine. I'll install it for ExploreASL now.

**Comment by MichaelStritt** [comment]
@all-contributors please add @HenkMutsaerts for design,content,mentoring

**Comment by MichaelStritt** [comment]
@all-contributors please add @HenkMutsaerts for design, content, mentoring

**Comment by MichaelStritt** [comment]
@all-contributors please add @jan-petr for content, mentoring, design

**Comment by MichaelStritt** [comment]
@all-contributors please add @MichaelStritt  for content, documentation

**Comment by MichaelStritt** [comment]
@all-contributors please add @pfcgroot for code, content
@all-contributors please add @pvdemael for code, ideas
@all-contributors please add @luislorenzini for code, tool
@all-contributors please add @MauricePasternak for code, design
@all-contributors please add @sandeepganji for content, ideas

**Comment by MichaelStritt** [comment]
@all-contributors please add @pfcgroot for code, content

**Comment by MichaelStritt** [comment]
@all-contributors please add @pvdemael for code, ideas

**Comment by MichaelStritt** [comment]
@all-contributors please add @luislorenzini for code, tool

**Comment by MichaelStritt** [comment]
@all-contributors please add @MauricePasternak for code, design

**Comment by MichaelStritt** [comment]
@all-contributors please add @sandeepganji for content, ideas

**Comment by MichaelStritt** [comment]
@all-contributors please add @pvdemael for code, ideas

**Comment by MichaelStritt** [comment]
@all-contributors please add @luislorenzini for code, tool

**Comment by MichaelStritt** [comment]
@all-contributors please add @MauricePasternak for code, design

**Comment by MichaelStritt** [comment]
@all-contributors please add @sandeepganji for content, ideas

**Comment by MichaelStritt** [comment]
@all-contributors please add @jozsait for code, maintenance

**Comment by MichaelStritt** [comment]
@all-contributors please add @DaveThoma5 for data, ideas

**Comment by MichaelStritt** [comment]
@all-contributors please add @MDijsselhof for content
