### ISSUE TITLE
Add new DICOM tags to DCMTK import

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#226]
Add the following tags to the DCMTK  or make sure they are already read:
* AcquisitionContrast (0008,9209)
* ComplexImageComponent (0008,9208) 
* Private (0019,109C) GELabelingType string
* PulseSequenceName (0018, 9005)
* InversionTime (0018,0082) (units ms)
* Private (0043,10A5) GELabelingDuration
* Private (2001,1008)  PhilipsNumberTemporalScans
* Private (2005,1429) PhilipsLabelControl
* (0020,0100)	IS	TemporalPositionIdentifier - integer
* Private (0029,1020) - PhoenixProtocol

**Comment by jan-petr** [comment]
All the specified fields added, as they might be really helpful according to GSP flavors.

Note that only reading of these from DICOM with DCMTK/DICOMINFO should be there (properly tested with DCMTK), but the tags are not yet used for the import to BIDS.

@MichaelStritt @HenkMutsaerts It would be cool if you could test this. At least basically.

Simply use xASL_io_DcmtkRead('filename.dcm') on a single file for testing.

**Comment by MichaelStritt** [comment]
Testing results:

- AcquisitionContrast (0008,9209)
    - Tested on GSP/Utrecht Ingenia dataset, seems to work fine 👍 
- ComplexImageComponent (0008,9208)
    - Tested on GSP/Utrecht Ingenia dataset, seems to work fine 👍 
- Private (0019,109C) GELabelingType string
    - Tested on GSP/VUmc case with GE_Discovery_MR750, seems to work fine 👍 
- PulseSequenceName (0018, 9005)
    - Tested on GSP/Utrecht Ingenia dataset, seems to work fine 👍 
- InversionTime (0018,0082) (units ms)
    - Tested on GSP/Utrecht Ingenia dataset, seems to work fine 👍 
- Private (2001,1008) PhilipsNumberTemporalScans
    - Tested on GSP/VUmc Philips QASPER case, seems to work fine 👍 
- (0020,0100) IS TemporalPositionIdentifier - integer
    - Tested on GSP/VUmc Philips QASPER case, seems to work fine 👍 
- Private (0029,1020) - PhoenixProtocol
    - Tested on some ADNI cases, seems to work fine 👍 
- Private (0043,10A5) GELabelingDuration
    - Sorry, I don't have test data for this, I think. This tag was missing in all GE datasets I checked so far.
- Private (2005,1429) PhilipsLabelControl
    - I found a dataset which should have this tag and I get an error from DCMTK.
    - Will send the dataset to Jan per E-Mail.

```
Error using xASL_adm_Hex2Num (line 84)
xASL_adm_Hex2Num: Even number of characters is required for a HEX number.
Error in xASL_io_DcmtkRead (line 67)
num = xASL_adm_Hex2Num(header.(listConvert{iField}),typeConvert{iField},endianConvert(iField));
```

**Comment by jan-petr** [comment]
Thanks. This is a superb testing!! I have several GE datasets in the flavors and GELabelingDuration worked very good with them.

I will check the dataset from you for PhilipsLabelControl. That seems to be a problem not with DCMTK but with a later parsing of the data - sometimes, the text is stored as HEX and needs to be explicitly converted to FLOAT, INT or CHAR...

**Comment by jan-petr** [comment]
Error fixed. The trouble was that some fields are saved as characters in hex.
'\68\70\89\9a', so they need to be read and converted from HEX to decimal and then either converted to a number or to a string.

However, PhilipsLabelControl field sometimes comes as hex saved in string, but sometimes as a normal string. In that case, it's hard to convert it and has to be simply taken as it is.

Error fixed in the last commit.

**Comment by MichaelStritt** [comment]
Great work 👍 
That fix was fast ;)
