### ISSUE TITLE
CAT12 warnings - Non-existent field cm

### ISSUE THREAD

**Issue by MauricePasternak** [ExploreASL/ExploreASL#228]
[CAT12 Failure - Non-existent field cm.txt](https://github.com/ExploreASL/ExploreASL/files/5555646/CAT12.Failure.-.Non-existent.field.cm.txt)

Furthermore, the program attempts to re-start CAT12 but enters into some sort of infinite loop. A SIGKILL signal does not stop it.

**Comment by MauricePasternak** [comment]
[CAT12-StuckIssue-ExploreASLv1.4.0.log](https://github.com/ExploreASL/ExploreASL/files/5914010/CAT12-StuckIssue-ExploreASLv1.4.0.log)
[CAT12-StuckIssue-ExploreASLv1.2.1.log](https://github.com/ExploreASL/ExploreASL/files/5914011/CAT12-StuckIssue-ExploreASLv1.2.1.log)

Please take a look at this issue again. Newer versions of ExploreASL/CAT12 have some sort of internal error occurring that prevents CAT12 from completing certain T1w Philips (maybe other vendors too?) images. In fact, as mentioned before, CAT12 enters some sort of stall that prevents it from exiting.

**Comment by HenkMutsaerts** [comment]
This was partly fixed by #305
