### ISSUE TITLE
Automatic generation of article methods section

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#229]
Would be great - similar to fMRIprep - to have some sort of copy of the BIDS input and image processing parameters provenance to the methods section of the eventual paper, together with the references used.
Disclaimer: automatically generated methods part, so will be flagged up by plagiarism detection methods, similar to fMRIprep.

### Release notes
Nothing. Moved to #1225

**Comment by MichaelStritt** [comment]
I think I need an example here. What do you want to do?

**Comment by maartenhammer** [comment]
Include in #1225

**Comment by maartenhammer** [comment]
Duplicate issue
