### ISSUE TITLE
Population modules analysis masks - minor errors

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#252]
Several minor bugs in the population module in creation of the templates.

- Main problem is that xASL_adm_GetFileList returns a cell array and not char array. And only some functions can handle it.
- Some other minor problems with Atlas name definitions.

**Comment by jan-petr** [comment]
Two errors fixed. The name 'MaskSusceptibility_nXXX' was only used in CreateMask and not in the main Population module. Besides it should be nXXX and not just XXX. Finally, I need to disable the skipping of incomplete scans...

**Comment by jan-petr** [comment]
Comment from @HenkMutsaerts 
Looks good, but then the option should have a more specific name at the beginning of the pipeline:

x.bSkipTemplateCreationWhenMissingScans

Inside xASL_wrp_CreatePopulationTemplates we can then use the x as well, not having to create the “isfield” statement in xASL_module_Population (I would like to keep the modules simple). But this would actually complicate feature#179, where I’m already changing this function; and Reinoud’s group is using this function for creating vascular territory atlases.

Actually, I suggest disabling this feature by default. I believe we should then print in the NIfTI filename the n of the included subjects/sessions (rather than the total), this would be better; but then we should first delete the existing template NIfTI. And we should change this again in the CreateMasks script :)
Do you agree?

**Comment by jan-petr** [comment]
> Comment from @HenkMutsaerts
> Looks good, but then the option should have a more specific name at the beginning of the pipeline:
> x.bSkipTemplateCreationWhenMissingScans

Yes - this sounds as a reasonable name - I will fix it everywhere.
 
> Inside xASL_wrp_CreatePopulationTemplates we can then use the x as well, not having to create the “isfield” statement in xASL_module_Population (I would like to keep the modules simple). But this would actually complicate feature#179, where I’m already changing this function; and Reinoud’s group is using this function for creating vascular territory atlases.

Solution is very simple. We can simply make sure to initialize the field before calling the function, so we don't need the if statement. The reason why I didn't do this before is that the defaulting is also inside the function, so I didn't want to have two times assigning a default value. But that's probably fine. I will implement it in a next commit - check if you like my solution.

> Actually, I suggest disabling this feature by default. I believe we should then print in the NIfTI filename the n of the included subjects/sessions (rather than the total), this would be better; but then we should first delete the existing template NIfTI. And we should change this again in the CreateMasks script :)

OK. Then we make sure to fix the defaults on both locations. OK to delete the existing NiFTIs and replacing them. But no need to change this in createmasks, because there we don't operate with a specific number of scans - we take any number in the filename. If you agree with this one - who implements this last one?

**Comment by HenkMutsaerts** [comment]
I will do the last change, which is in issue 179, where we do take a specific number (so I will have to revert this again :)

**Comment by jan-petr** [comment]
OK. So what is the plan? This issue is finalized? If yes, then please re-approve the PR and I will merge it to develop. Then I will rebase the corrections to 179 and you will fix it there?

**Comment by jan-petr** [comment]
All these edits were manually ported to issue 179. This issue is thus closed. The branch and PR is deleted without merging.
