### ISSUE TITLE
xASL_import_json Matlab-version bug

### ISSUE THREAD

**Issue by MDijsselhof** [ExploreASL/ExploreASL#254]
In xASL_import_json.m, a small bug results in an empty array from which the Matlab version in numbers would be generated. Therefore VersionMatlab>2015 will always remain 0,'&&' remains false and an error is given, terminating ExploreASL at data_par.json reading phase.

Can be fixed by implementing:

% Get Matlab version
VersionMatlab = version;
VersionMatlab_location = strfind(VersionMatlab,'R');
VersionMatlab = str2num(VersionMatlab(1,VersionMatlab_location+1:VersionMatlab_location+4));
% Input has to be a character array
 if VersionMatlab>2015 && isstring(DataParFile) % isstring is introduced in 2016b
     DataParFile = char(DataParFile);
 end

**Comment by HenkMutsaerts** [comment]
Nice! I would make a bit more specific title, see what I changed.
Now you assigned me, but I would also assign yourself (I did this for you) and try to create a branch to fix this yourself ;)
Note that Github uses MarkDown language, which is nice for layout, e.g.:

>> Can be fixed by implementing:

`% Get Matlab version`
`VersionMatlab = version;`
`VersionMatlab_location = strfind(VersionMatlab,'R');`
`VersionMatlab = str2num(VersionMatlab(1,VersionMatlab_location+1:VersionMatlab_location+4));`
`% Input has to be a character array`
`if VersionMatlab>2015 && isstring(DataParFile) % isstring is introduced in 2016b`
`DataParFile = char(DataParFile);`
`end`

**Comment by MichaelStritt** [comment]
There's also the option to use:

`[v d] = version` with d[end-4:end] or something like that. Probably the shortest solution.
You can also do `version('-date')`.
