### ISSUE TITLE
Invalid JSON arrays

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#266]
`DataParTemplate.json` put arrays in strings and the JSON import functions dealt with this.

"M0PositionInASL4D": “[1,2]”, should be changed to "M0PositionInASL4D": [1,2], (numeric array)
"SESSION": "{'ASL_1','ASL_2'}", should be changed to "SESSION": [“ASL_1”,”ASL_2”], (string array)

Put warning with old legacy format, and change JSON import functions accordingly

### Release note
Fix incorrect entries of cell array in datapar.json. This can be reported together with #62 that fixes the corresponding functions.

**Comment by jan-petr** [comment]
> Put warning with old legacy format, and change JSON import functions accordingly

This is done in issue #62

**Comment by jan-petr** [comment]
I have checked TestDataSet, 10TestDataSets, and Flavors, and only found the incorrect format in the DataParTemplate.json.

I have fixed it there and #62 should report any other incorrect use of it.
