### ISSUE TITLE
Single function for user to create average maps

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#27]
For CICERO specifically, but also for other users, it would be useful to have a single function with a *tsv-file* as input, that contains the subjects/sessions from which an average map will be created.
### Input should be
* name (of the *tsv-file*)
* participants/sessions (inside the *tsv-file*)
* prefix of the filetype to make an average map of (e.g. *qCBF*)

**Comment by jan-petr** [comment]
@HenkMutsaerts This issue has some double entries. And it should also be closed, right?

**Comment by HenkMutsaerts** [comment]
Yes good point. Weird. Let's see upon merging what went wrong here
