### ISSUE TITLE
Release-#1.4.0

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#271]
Please put all the issues you found while testing here, then we can decide which to fix or move to another issue.

* Still need to adapt the CHANGES.md (and copy to the release 1.4.0);
* The 3D-spiral dataset gives a warning that no susceptibility mask was found, this is not a big deal but a 3D-spiral dataset doesn't need any susceptibility masking, so let's create a dummy susceptibility mask for 3D-spiral, which removes the warning and facilitates a group analyses with different sequences (and combining susceptibility masks). We can make a new issue for this, doesn't need fixing now.

**Comment by HenkMutsaerts** [comment]
These are my results (Mac Matlab 2016b, non-compiled)

ans =

  11×11 cell array

  Columns 1 through 4

    'Data'                   'mean_qCBF_TotalGM'    'median_qCBF_TotalGM'    'median_qCBF_DeepWM'
    'GE_3Dspiral_T1pre…'    '66.1269'              '52.909'                 '32.0549'           
    'Philips_2DEPI_FEA…'    '38.9252'              '27.6176'                '6.8646'            
    'Philips_2DEPI_FLA…'    '41.6188'              '31.7837'                '13.7852'           
    'Philips_2DEPI_FLA…'    '47.3714'              '42.4144'                '20.0441'           
    'Philips_2DEPI_Les…'    '8.1482'               '14.1722'                '2.9892'            
    'Philips_2DEPI_Seg…'    '45.7088'              '41.0562'                '9.5318'            
    'Philips_3DGRASE_F…'    '35.2804'              '26.2958'                '7.4991'            
    'Philips_3DGRASE_M…'    '32.0097'              '24.2742'                '8.5359'            
    'Siemens3DGRASE_St…'    '37.6956'              '37.2872'                '21.7901'           
    'Siemens_2DEPI_noB…'    '67.6964'              '50.7845'                '13.4269'           

  Columns 5 through 9

    'CoV_qCBF_TotalGM'    'GMvol'           'WMvol'           'CSFvol'          'PipelineCompleted'
    '0.29717'             '0.64003'         '0.50514'         '0.43311'         [                1]
    '0.71526'             '0.5348'          '0.459'           '0.40565'         [                1]
    '0.37746'             '0.54416'         '0.39225'         '0.35606'         [                1]
    '0.43006'             '6.982311e-01'    '5.827513e-01'    '2.224146e-01'    [                1]
    '0.8953'              '0.70982'         '0.51364'         '0.19391'         [                1]
    '0.36809'             '8.166902e-01'    '4.595792e-01'    '1.516160e-01'    [                1]
    '0.64909'             '0.57156'         '0.52818'         '0.42069'         [                1]
    '0.43319'             '0.72393'         '0.55204'         '0.35635'         [                1]
    '0.78873'             '0.51909'         '0.46579'         '0.40537'         [                1]
    '0.31648'             '0.6857'          '0.60644'         '0.30949'         [                1]

  Columns 10 through 11

    'TC_ASL_Registration'    'TC_M0_Registration'
    [             0.9010]    [            0.9357]
    [             0.7289]    [            0.8168]
    [             0.9023]    [            0.9478]
    [             0.8136]    [            0.8451]
    [             0.7593]    [            0.8910]
    [             0.8540]    [            0.8046]
    [             0.8575]    [            0.7543]
    [             0.8407]    [            0.8937]
    [             0.6915]    [            0.4987]
    [             0.8764]    [            0.9588]

**Comment by jan-petr** [comment]
11×11 cell array

  Columns 1 through 7

    {'Data'             }    {'mean_qCBF_TotalGM'}    {'median_qCBF_Tot…'}    {'median_qCBF_Dee…'}    {'CoV_qCBF_TotalGM'}    {'GMvol'       }    {'WMvol'       }
    {'GE_3Dspiral_T1p…'}    {'66.2454'          }    {'52.8948'          }    {'32.0227'          }    {'0.29713'         }    {'0.63886'     }    {'0.50159'     }
    {'Philips_2DEPI_F…'}    {'39.3773'          }    {'27.8056'          }    {'6.648'            }    {'0.71147'         }    {'0.5348'      }    {'0.45899'     }
    {'Philips_2DEPI_F…'}    {'41.6369'          }    {'31.8638'          }    {'13.9268'          }    {'0.37768'         }    {'0.5441'      }    {'0.39224'     }
    {'Philips_2DEPI_F…'}    {'47.4323'          }    {'42.4156'          }    {'20.0787'          }    {'0.42932'         }    {'6.982309e-01'}    {'5.827514e-01'}
    {'Philips_2DEPI_L…'}    {'8.148'            }    {'14.1724'          }    {'2.9922'           }    {'0.89532'         }    {'0.70979'     }    {'0.51361'     }
    {'Philips_2DEPI_S…'}    {'45.8145'          }    {'41.1036'          }    {'9.5134'           }    {'0.36747'         }    {'8.166902e-01'}    {'4.595792e-01'}
    {'Philips_3DGRASE…'}    {'35.3354'          }    {'26.3589'          }    {'7.5394'           }    {'0.6501'          }    {'0.57092'     }    {'0.52783'     }
    {'Philips_3DGRASE…'}    {'32.1226'          }    {'24.2851'          }    {'8.5947'           }    {'0.43015'         }    {'0.72393'     }    {'0.55204'     }
    {'Siemens3DGRASE_…'}    {'37.6936'          }    {'37.2867'          }    {'21.7901'          }    {'0.78873'         }    {'0.51909'     }    {'0.46579'     }
    {'Siemens_2DEPI_n…'}    {'67.6801'          }    {'50.7835'          }    {'13.433'           }    {'0.31649'         }    {'0.68569'     }    {'0.60643'     }

  Columns 8 through 11

    {'CSFvol'      }    {'PipelineCompleted'}    {'TC_ASL_Registra…'}    {'TC_M0_Registrat…'}
    {'0.43298'     }    {[                1]}    {[           0.9007]}    {[           0.9355]}
    {'0.4057'      }    {[                1]}    {[           0.7301]}    {[           0.8164]}
    {'0.35616'     }    {[                1]}    {[           0.9024]}    {[           0.9479]}
    {'2.224147e-01'}    {[                1]}    {[           0.8158]}    {[           0.8455]}
    {'0.19396'     }    {[                1]}    {[           0.7593]}    {[           0.8910]}
    {'1.516160e-01'}    {[                1]}    {[           0.8543]}    {[           0.8042]}
    {'0.42193'     }    {[                1]}    {[           0.8573]}    {[           0.7543]}
    {'0.35635'     }    {[                1]}    {[           0.8418]}    {[           0.8938]}
    {'0.40537'     }    {[                1]}    {[           0.6915]}    {[           0.4987]}
    {'0.30951'     }    {[                1]}    {[           0.8764]}    {[           0.9588]}

**Comment by jan-petr** [comment]
Same results. No error. One those warnings you talked about... We're good to merge AFAIC

**Comment by MichaelStritt** [comment]
I compiled ExploreASL on Linux and generated a new docker image. Since I have to test it on a virtual ubuntu on my local machine, I only ran the External/TestDataSet. Everything seemed fine. 
I added a description of the current release procedure for the docker image in the Deploy repository: https://github.com/ExploreASL/Deploy/blob/master/README.md

**Comment by HenkMutsaerts** [comment]
FOR MATTHIJS TO EDIT:


# ExploreASL v1.4.0

----
## Versions included software
Versions included & used third-party tools (see /External/README_SPM.txt):

SPM12 7219 
CAT12 r1615 
LST 2.0.15

----
## Feature improvements (still backward compatible)
#20 Implement BASIL -> changed order quantification/masking, and always save resampled PWI4D for quantification, facilitating BASIL



----
## Work in progress

### ASL-BIDS
#193 Comparing BIDS folders (for testing purpose)
#226 Add new DICOM tags to DCMTK import

### Compilation/stand-alone version

----

## Bug Fixes
#191 WMH warning when no FLAIR analyzed -> this warning is now removed if no FLAIR was present in the data
#248 Temporary fix native space processing -> in Population module
#252 Population modules analysis masks - minor errors
#267 Error in reading JSONs from EPAD

----

## Documentation
#196 All contributors -> all contributors are now automatically added to the main README.md
#217 Documentation improvements
#219 Add user to documentation

## Testing

**Comment by MDijsselhof** [comment]
My results are the same (Windows R2020b):

11×11 cell array

  Columns 1 through 8

    {'Data'             }    {'mean_qCBF_TotalGM'}    {'median_qCBF_Tot…'}    {'median_qCBF_Dee…'}    {'CoV_qCBF_TotalGM'}    {'GMvol'       }    {'WMvol'       }    {'CSFvol'      }
    {'GE_3Dspiral_T1p…'}    {'66.2491'          }    {'52.8934'          }    {'32.0222'          }    {'0.29713'         }    {'0.63909'     }    {'0.50155'     }    {'0.43404'     }
    {'Philips_2DEPI_F…'}    {'39.0898'          }    {'27.6463'          }    {'6.7338'           }    {'0.71322'         }    {'0.53519'     }    {'0.45879'     }    {'0.40549'     }
    {'Philips_2DEPI_F…'}    {'41.7876'          }    {'31.7406'          }    {'13.6872'          }    {'0.3785'          }    {'0.54277'     }    {'0.39193'     }    {'0.3545'      }
    {'Philips_2DEPI_F…'}    {'47.3822'          }    {'42.4146'          }    {'20.0689'          }    {'0.42963'         }    {'6.982300e-01'}    {'5.827403e-01'}    {'2.224218e-01'}
    {'Philips_2DEPI_L…'}    {'8.1514'           }    {'14.1829'          }    {'3.0157'           }    {'0.89547'         }    {'0.70923'     }    {'0.51359'     }    {'0.19465'     }
    {'Philips_2DEPI_S…'}    {'45.659'           }    {'41.0387'          }    {'9.5524'           }    {'0.36904'         }    {'8.166885e-01'}    {'4.595793e-01'}    {'1.516163e-01'}
    {'Philips_3DGRASE…'}    {'35.1559'          }    {'26.2654'          }    {'7.47'             }    {'0.64308'         }    {'0.5713'      }    {'0.52755'     }    {'0.42186'     }
    {'Philips_3DGRASE…'}    {'32.0837'          }    {'24.2606'          }    {'8.5611'           }    {'0.42989'         }    {'0.72393'     }    {'0.55204'     }    {'0.35635'     }
    {'Siemens3DGRASE_…'}    {'37.6642'          }    {'37.3073'          }    {'21.8064'          }    {'0.78818'         }    {'0.51909'     }    {'0.46579'     }    {'0.40537'     }
    {'Siemens_2DEPI_n…'}    {'67.484'           }    {'50.4959'          }    {'13.3998'          }    {'0.31815'         }    {'0.68994'     }    {'0.59741'     }    {'0.31379'     }

  Columns 9 through 11

    {'PipelineCompleted'}    {'TC_ASL_Registra…'}    {'TC_M0_Registrat…'}
    {[                1]}    {[           0.9008]}    {[           0.9355]}
    {[                1]}    {[           0.7296]}    {[           0.8164]}
    {[                1]}    {[           0.9009]}    {[           0.9478]}
    {[                1]}    {[           0.8143]}    {[           0.8455]}
    {[                1]}    {[           0.7596]}    {[           0.8910]}
    {[                1]}    {[           0.8538]}    {[           0.8047]}
    {[                1]}    {[           0.8580]}    {[           0.7542]}
    {[                1]}    {[           0.8420]}    {[           0.8940]}
    {[                1]}    {[           0.6915]}    {[           0.4986]}
    {[                1]}    {[           0.8749]}    {[           0.9588]}

**Comment by HenkMutsaerts** [comment]
@jan-petr do you want to redesign the master branch before or after closing this issue (and milestone 1.4.0)?

**Comment by jan-petr** [comment]
We first redesign master. Then we do cleaning and tagging of the rest (unless of super high priority).
