### ISSUE TITLE
M0PositionInASL4D can be zero

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#272]
Maurice: x.M0PositionInASL4D isn't clear in what its default value should be if the parameter is present (and the GUI always spits it out). I assumed a default value of 0 is sufficient to indicate that this should be skipped. Could a 2-3 line condition be introduced to omit M0 extraction out of the ASL volume if that parameter's value is 0? I prefer a 0 over an empty vector since the other possible values are integers as well. In xASL_module_ASL.m, something like:

    % make sure to split the M0 from the ASL time-series if needed
    if x.M0PositionInASL4D ~= 0
        xASL_io_SplitASL_M0(x.P.Path_ASL4D, x.M0PositionInASL4D);
    end

**Comment by HenkMutsaerts** [comment]
Yes we can do this, good idea!

**Comment by HenkMutsaerts** [comment]
I would argue against this in general. 0 is a value that is used quite a lot, so 'undefined' or 'empty' should rather be []. I don't know how this is in JSON, if we can't do "[]" because it has to be numeric, then I would go for NaN, if it has to be integer, then I would go for 9999, which is more often used as "missing value". @jan-petr do you agree?

**Comment by MichaelStritt** [comment]
@HenkMutsaerts @jan-petr 

We could also implement a few lines of code in **json_read** to convert every char array which is exactly **'NaN'** to a Matlab **NaN**. This would be very clear and can be checked easily. I'd have to change this in the current mTRIAL interface, too, so let me know what we're going to do. I could write the part in the **json_read** if you want.

**Comment by HenkMutsaerts** [comment]
Yes, good idea, unless there is already something more standardized practice in JSONs?

**Comment by MichaelStritt** [comment]
Hm... JSON is JavaScriptObjectNotation, so I guess the correct way of doing this would be to use `null`.
- [JSON Objects](https://www.w3schools.com/js/js_json_objects.asp)
- [McKeeman](https://www.crockford.com/mckeeman.html)

**Comment by HenkMutsaerts** [comment]
So perhaps we can internally convert `null` to NaN or [] (depending on the field)?
How does SPM_jsonread react on `null`?

**Comment by MichaelStritt** [comment]
> So perhaps we can internally convert null to NaN or [] (depending on the field)?

That shouldn't be a problem at all.

> How does SPM_jsonread react on null?

I can give that a try. I think the json reader just reads the plain text, so it will probably be read as the char array `'null'`.

**Comment by MichaelStritt** [comment]
Just tested this:

```
file = '.\m.stritt\TestFile.json';
[x] = xASL_import_json(file);
```

With:
```
{
"x": [{
"name": "ExampleDataSet",
"subject_regexp": "^Sub-\\d{3}$",
"Quality": 0,
"Test": null,
"S":
{"Atlases": ["Hammers","Mindboggle_OASIS_DKT31_CMA"]}
}]
}
```

The resulting struct had `x.Test = []`, so we can test it with `isempty(x.Test)`.

**Comment by MichaelStritt** [comment]
So I would change the code to:

```
% make sure to split the M0 from the ASL time-series if needed
if ~isempty(x.M0PositionInASL4D)
    xASL_io_SplitASL_M0(x.P.Path_ASL4D, x.M0PositionInASL4D);
end
```

And by default we should set `x.M0PositionInASL4D = []`. Additionally, we should probably set `x.M0` to `null / []` if `x.M0PositionInASL4D = 1` and write down everything in the DataParTemplate.

**Comment by HenkMutsaerts** [comment]
@MichaelStritt nice! I like that we can use the JSON default for isempty/missing value and this nicely syncs with Matlab's `isempty == []`

Do you want to change this? Note that setting `x.M0` to `null/[]` is illegal, `x.M0` needs to be specified irrespective of `x.M0PositionInASL4D`. This is confusing I understand, `x.M0PositionInASL4D` just moves image volume(s) out of ExploreASL, but this doesn't mean that you have to use them (e.g. if you have a dummy image you would just remove it but still don't use it; or if you don't have means to quantify the M0 but do want to process it). Anyway, all this will probably improve with my BIDS2legacy issue.

**Comment by MichaelStritt** [comment]
@HenkMutsaerts sounds good, I can change that. We should document that in the `DataParTemplate` though. So on default `x.M0PositionInASL4D=[]` and if `x.M0PositionInASL4D` is not empty, we have `x.M0 = 'separate_scan'` ?

**Comment by HenkMutsaerts** [comment]
Nice! I just wouldn't enforce `x.M0 = 'separate_scan'`, as splitting an image from the ASL series doesn't mean that you want to use it as M0; these often coincide, but they don't have to. E.g., some early Siemens 2D EPI PASL provide a first dummy image, which you want to split off, but not use as M0 (you probably have these as well in early ADNI?)

**Comment by MichaelStritt** [comment]
> Nice! I just wouldn't enforce `x.M0 = 'separate_scan'`, as splitting an image from the ASL series doesn't mean that you want to use it as M0; these often coincide, but they don't have to. E.g., some early Siemens 2D EPI PASL provide a first dummy image, which you want to split off, but not use as M0 (you probably have these as well in early ADNI?)

Ah okay, so if you set `x.M0PositionInASL4D=1` e.g., you still can use `x.M0 = 'UseControlAsM0'`?

**Comment by HenkMutsaerts** [comment]
Great, just a minor suggestion: you state that you can still use 
`x.M0 as 'separate_scan' or 'UseControlAsM0'`
but there is also a third option to use x.M0 as single numerical value. So perhaps replace the text by:
`Note that the x.M0PositionInASL4D parameter is independent from the x.M0 parameter choice.`

**Comment by MichaelStritt** [comment]
> `Note that the x.M0PositionInASL4D parameter is independent from the x.M0 parameter choice.` If this is ready, go ahead and create a PR!

You're right, that definitely sounds better and is more on point 👍 
PR should already exist.
