### ISSUE TITLE
ExploreASL_GUI-Update_Jan_2021

### ISSUE THREAD

**Issue by MauricePasternak** [ExploreASL/ExploreASL#274]
Time for a much-needed update.

Some of the major changes, apart from aesthetics, include:

- The ability to stop processing mid-way
- Processing in the ASL_Module now gives feedback to which runs completed a step
- Updated Modification Jobs Prior/Post run
    -  Alter participants.tsv --> Alters the participants.tsv file in a given study with metadata present in container. A useful addition for cases where copying only certain rows from a very large metadata spreadsheet would be very tedious.
    - Change Json Sidecars --> Allows the user to batch-edit the json sidecars of a given study, making modifications as necessary. Batch-editing can be done manually or instructions (in the form of a spreadsheet) loaded in from a file
    - Merge Study Directories --> Allows the user to create a common directory from several studies, merging all the files, folders, etc. Can be done with symlinks instead to save diskspace.
- The ability to reorganized directory levels of a study to make it compatible with the Import Module (i.e. can pull apart a directory subject_visit into SUBJECT/subject/VISIT/visit)

**Comment by HenkMutsaerts** [comment]
Nice, though please merge squashed, add the issue number, and sign your merge ;)
Just follow our GitHub flow, and ask us if needed; just to keep overview.
You can reuse an issue though, you merge, close the issue for e.g. 1.5.0, and re-open it later for 1.6.0, and so on.

**Comment by HenkMutsaerts** [comment]
We decided to remove /External/ExploreASL_GUI and keep this in a /ExploreASL/ExploreASL_GUI repository forked from /MauricePasternak/ExploreASL_GUI.
