### ISSUE TITLE
Option to run DICOM2BIDS & BIDS2Legacy in ExploreASL Master

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#290]
An option to run DICOM2BIDS & BIDS2Legacy in ExploreASL Master would help to get rid of the additional compiled ExploreASL_Import and other users, which don't use the mTRIAL format, would be able to use the import functionality in the docker as well.

**Comment by HenkMutsaerts** [comment]
Nice idea, I'm working on the "BIDS2Legacy", though this should be called "raw2derivatives" when we have the full BIDS reading implementation

**Comment by MichaelStritt** [comment]
Okay, I created a feature branch. Let's focus on CLI first. I'll try it with one of the GE datasets from the flavor database 👍

**Comment by MichaelStritt** [comment]
@HenkMutsaerts & @jan-petr: Would you be interested in checking out my first ideas on the implementation?
I talked with Henk about using an input parser for the input and since we have to change `ExploreASL_Master` anyway,
why not do this properly? 
The only thing we maybe could get rid of though - **and this might be a controversial opinion** - is the matlab `questdlg` box. 
If you disagree with this, we could alternatively implement a `questdlg` box within `convertParsedInput`.

**Comment by MichaelStritt** [comment]
@jan-petr & @HenkMutsaerts would be really cool to have some feedback on this 488bc86, because I'd have some time to work on it this week.

**Comment by jan-petr** [comment]
Is questdlg box the interactive input? If yes, then I agree to get rid of it - we don't really need such functionality. Henk, do you agree?

Regarding process array - There are two steps in DCM2BIDS I would separate them: DCM2NII, NII2BIDS.

Doesn't exploreASL itself has options for running submodules struct/ASL/pop?

Otherwise it looks good.

**Comment by MichaelStritt** [comment]
> Regarding process array - There are two steps in DCM2BIDS I would separate them: DCM2NII, NII2BIDS.

Sounds good, modularity is always a good thing. We probably have to rewrite some parts of `xASL_bids_TestBidsConversion` to do this, right?

> Doesn't ExploreASL itself have options for running submodules struct/ASL/pop?

Yes, right now this can be done using the iModules argument. A good alternative would be to combine the ProcessArray (former ProcessData) and iModules to a ProcessArray. Could be something like:

```
ProcessArray = [DCM2NII, NII2BIDS, BIDS2RAW, STRUCTURAL, ASL, POPULATION]
```

Maybe everything binary and **not** decimal (1, 2, 3) for the last three.

> Otherwise it looks good.

:)

**Comment by MichaelStritt** [comment]
### Agreements ABBA meeting

```matlab
ImportArray = [DCM2NII, NII2BIDS, BIDS2Legacy]
ProcessArray = [STRUCTURAL, ASL, POPULATION]
```

```matlab
ImportArray = 1 => [1 1 1] & [0] = [0 0 0]
ProcessArray = 1 => [1 1 1] & [0] = [0 0 0]
```

- Get rid of the `ProcessData` & `iModules` argument
- Get rid of `questdlg`, add CLI dialog though

```
ExploreASL(); -> only initalization
ExploreASL(‘/path2json.json’); -> load data only 
     & says what to do if you want to import array/processarray
ExploreASL(‘path2json.json’,[ImportArray],[ProcessArray]);
```

**Comment by MichaelStritt** [comment]
### Full run (Windows, GE_PCASL_2DEPI_volunteer)

```matlab
>> [x] = ExploreASL_Master('.\TEST',1,1,1,1,1);
ExploreASL will run the import workflow and will run the processing pipeline...
...
==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath                            ...t\TEST\GE_PCASL_2DEPI_volunteer\derivatives\ExploreASL\DataPar.json
Run DCM2NII                            1
Run NII2BIDS                           1
Run BIDS2LEGACY                        1
Run Structural Module                  1
Run ASL Module			       1
Run Population Module	               1
SkipPause                              1
iWorker                                1
nWorkers                               1
==============================================================================================
ExploreASL v1.4.0 initialized ... 
Automatically defining sessions...
==================================== Additional Settings =====================================
1 scans - 0 exclusions, resulting in 1 scans of: 
Longitudinal timePoint 1 = 1 scans - 0 exclusions = 1 scans
ASL sessions: 1

Ancillary data, sets: 3 sets are defined for 1 "SubjectsSessions"
Set 1 = "LongitudinalTimePoint" options "TimePoint_1", codes for paired data
Set 2 = "SubjectNList" options "SubjectNList", codes for paired data
Set 3 = "Site" options "SingleSite", codes for two-sample data

x.D.ROOT				M:\SoftwareDevelopment\MATLAB\m.stritt\TEST\GE_PCASL_2DEPI_volunteer\derivatives\ExploreASL
x.DELETETEMP			        1 (delete temporary files)
x.Quality				1 (0 = fast try-out; 1 = normal high quality)

==============================================================================================


Running xASL_module_Structural ...   
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
...
Job-iteration 1 stopped at 19-Mar-2021 16:04:20 and took 1 seconds
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++100%
xASL_module_Structural completed
...
Running xASL_module_ASL ...   
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting xASL_module_ASL_<SESSION> at 19-Mar-2021 16:04:21
...
Job-iteration 1 stopped at 19-Mar-2021 16:12:57 and took 85 seconds
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++100%
xASL_module_Population completed
Many thanks for using ExploreASL, please don't forget to cite https://pubmed.ncbi.nlm.nih.gov/32526385/
Note that ExploreASL is a collaborative effort.
Therefore, please don't hesitate to contribute by feedback, adding code snippets, or clinical experience!
```

**Comment by MichaelStritt** [comment]
### Initialization (Windows)

```matlab
>> [x] = ExploreASL_Master('.\m.stritt\TEST',0,0,1,1,1);
ExploreASL will not run the import workflow and will only run the initialization...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath				M:\SoftwareDevelopment\MATLAB\m.stritt\TEST
Run DCM2NII				0
Run NII2BIDS			        0
Run BIDS2LEGACY			        0
Run Structural Module	                0
Run ASL Module			        0
Run Population Module	                0
SkipPause				1
iWorker					1
nWorkers				1
==============================================================================================
ExploreASL v1.4.0 initialized ... 
```

**Comment by MichaelStritt** [comment]
### Some alternative tests

```
>> [x] = ExploreASL_Master('.\TEST',[0 0 0],[0 0 0],1,1,1);
ExploreASL will not run the import workflow and will only run the initialization...
```

```
>> [x] = ExploreASL_Master('-\TEST',[0 0 0],[1 0 0],1,1,1);
You are trying to process a dataset, without providing a DataPar file or running the import workflow...
ExploreASL will not run the import workflow and will only run the initialization...
```

```
>> [x] = ExploreASL_Master('.\TEST',[1 0 0],[0 0 0],1,1,1);
ExploreASL will run the import workflow and will only run the initialization...
```

### No sourcedata in folder

```
>> [x] = ExploreASL_Master('.\TEST',[0 0 0],[0 0 0],1,1,1);
ExploreASL will not run the import workflow and will only run the initialization...
```

### JSON file does not exist

```
>> [x] = ExploreASL_Master('.\TEST\test.json',[0 0 0],[0 0 0],1,1,1);
DataPar file/folder does not exist, ExploreASL will only be initialized...
ExploreASL will not run the import workflow and will only run the initialization...
```

**Comment by jan-petr** [comment]
Very good - a huge amount of work. It looks perfect - the input arguments and their listing on screen.

A few minor comments:
- Where does v1.4.0 comes from on the initial screen? It should read it from the VERSION1.5.0 file instead of hard-coding it. I think that error is there for some time and would be nice to fix here.
- `warning('Call import scripts here? But then we should make sure not to call ExploreASL_Initialize within the import sripts of Jan!!!');` in `ExploreASL_Initialize`. Agree, can you please fix this in the import scripts?
- `x.ImportArray(2)==1, warning('Not yet implemented...');` in `ExploreASL_Initialize`: Can you please add the relevant call to NII2BIDS
- `warning('Running DCM2BIDS, not DCM2NII...');` in `ExploreASL_Initialize`: It is calling the DCM2NII, not the other one, right?
-  `ExploreASL_Initialize`: we check for the existence of `x,'DataParPath'` on line 70, but use this field already on line 66.

**Comment by MichaelStritt** [comment]
> Where does v1.4.0 comes from on the initial screen? It should read it from the VERSION1.5.0 file instead of hard-coding it. I think that error is there for some time and would be nice to fix here.

I opened the branch before release 1.5.0, so it's already a little bit older. Therefore v1.4.0 should be correct and not hard-coded 👍 

> `warning('Call import scripts here? But then we should make sure not to call ExploreASL_Initialize within the import scripts of Jan!!!');` in `ExploreASL_Initialize`. 
> Agree, can you please fix this in the import scripts?

Oh sorry, I have to remove the warning. Already did that. I added an input option called `bInitialize` to `xASL_bids_TestBidsConversion` and also added the option to insert an `x` struct.

> * `x.ImportArray(2)==1, warning('Not yet implemented...');` in `ExploreASL_Initialize`: Can you please add the relevant call to NII2BIDS

That's the thing. Right now I'm still using `xASL_bids_TestBidsConversion` in step one which does both DCM2NII and NII2BIDS, right? Have you already separated the script so that we have DCM2NII and NII2BIDS? Sorry if that's potentially a stupid question and I just have overlooked the functions somewhere.

> `warning('Running DCM2BIDS, not DCM2NII...');` in `ExploreASL_Initialize`: It is calling the DCM2NII, not the other one, right?

See the comment above 👍 

> `ExploreASL_Initialize`: we check for the existence of `x,'DataParPath'` on line 70, but use this field already on line 66.

That's be beauty of input parsing :) these lines at the start of the script should do that:

```matlab
    % Define input parser
    p = inputParsing(varargin{:});

    % Convert parsed input
    parameters = convertParsedInput(p.Results);

    % Store parsed input
    x = storeParsedInput(parameters);
```
