### ISSUE TITLE
xASL_str2num & other bugs

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#291]
`str2num` with two input arguments is not backward compatible, I wrote `xASL_str2num` for this, which we should use instead when using a second input argument (i.e. for determining the number of floating values). @MichaelStritt perhaps you reverted this accidentally?

Also, `xASL_str2num` can process cells containing strings/numbers.

**Comment by MichaelStritt** [comment]
> `str2num` with two input arguments is not backward compatible, I wrote `xASL_str2num` for this, which we should use instead when using a second input argument (i.e. for determining the number of floating values). @MichaelStritt perhaps you reverted this accidentally?

I remember that Jan and me were working on some other parts of the workflow, where we changed str2num to xASL_str2num. I'm not 100% sure what went wrong here. Let's hope it's fixed now.
