### ISSUE TITLE
EPAD_Manage_PEPolar_Parms converting PhaseEncodingDirection in M0.json bug

### ISSUE THREAD

**Issue by MDijsselhof** [ExploreASL/ExploreASL#296]
In EPAD_Manage_PEPolar_Parms the phase encoding (PE) parameters for TopUp from the '_parms.mat' file (i.e. the suffix of the sidecar file that should accompany the NIfTI after ExploreASL_Import) if there is one. We assume that these are better than those inside the JSON, hence replace them. 
Currently, this is only performed for both ASL4D and RevPE files however not for M0. This results in an issue in xASL_fsl_TopUp when trying to find the value for 'PhaseEncodingDirection'.

Can be fixed by replacing  

(Line 78)
`if ~isempty(strfind(lower(jsonFile), 'asl')) || ~isempty(strfind(lower(jsonFile), 'func'))`
with :
(Line 78)
`if ~isempty(strfind(lower(jsonFile), 'asl')) || ~isempty(strfind(lower(jsonFile), 'm0')) || ~isempty(strfind(lower(jsonFile), 'func'))`

@HenkMutsaerts I don't know if I should add projects and milestone with this, could you add them?

**Comment by HenkMutsaerts** [comment]
@MDijsselhof why did you move this to me for reviewing? Perhaps you created a pull request, but then you have to link this to this issue (see at the right column for "Linked pull requests")
