### ISSUE TITLE
Move /CustomScripts/ to separate repository

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#299]
The CustomScripts (sub)folders contain scripts that belong to separate studies, and are not required for ExploreASL to run, and don't need our rigorous subversioning/Github workflow.

@jan-petr @MichaelStritt do you guys agree?

**Comment by MichaelStritt** [comment]
I agree 👍 We should probably remind the dev group of this change though, since this could affect a lot of people.
