### ISSUE TITLE
ASL registration using Affine and DCT registration

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#3]
The ASL can be sometimes deformed with respect to T1w (or with respect to MNI in case a direct ASL-MNI registration without T1w is done). In that case, you might want to do a affine or affine+DCT registration on top of the Rigid body registration.

**Comment by jan-petr** [comment]
TC check for confirming improved alignment of Affine and DCT has to be built in.

Clean all temporary files before ending the registration.
