### ISSUE TITLE
DCMTK won't run in ExploreASL_Import

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#30]
When running without the image processing toolbox, the compiled DCMTK package should run instead.
There seems to be an incorrect input parameter check

**Comment by MichaelStritt** [comment]
There still seems to be a problem. But the previous fix did improve the workflow up to a certain point.

![Annotation 2020-07-09 144039](https://user-images.githubusercontent.com/46593074/87041321-5a552f80-c1f2-11ea-8098-2325f6647d20.png)

**Comment by MichaelStritt** [comment]
works now!
