### ISSUE TITLE
xASL_adm_UnixPath: bug with Windows+WSL

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#305]
If `ispc` is true and WSL is present, `xASL_adm_Unix` is not functioning well.
I will make two changes:
* skipping this function if Windows & WSL are present, by default, unless this is specifically requested (i.e. when running `xASL_fsl_*` functions);
* the list of illegal characters should not include the colon ':' when `ispc` is true

**Comment by jan-petr** [comment]
I have fixed the names in the header. 

I have also changed the parameter admin - it should first properly initialize it, and then use it. It practically does the same, but it is easier to read and less prone to future errors.
