### ISSUE TITLE
xASL_adm_CleanUpBeforeRerun feeds cell instead of string to xASL_delete

### ISSUE THREAD

**Issue by MauricePasternak** [ExploreASL/ExploreASL#325]
Occurs in Section 3: "3) Remove lock files/folders for reprocessing"

At this block:

        LockedDir = xASL_adm_GetFileList(CurrentDir{iCurrent}, 'locked', 'FPListRec', [0 Inf], true);
        if isempty(LockedDir) % keep locked dir for mutex
            xASL_delete(CurrentDir{iCurrent});
        end

Since, xASL_delete expects a string, you can see the issue that happens, given:

```
CurrentDir =
  1×1 cell array
    {1×1 cell}
    
CurrentDir{iCurrent}
ans =
  1×1 cell array
    {'/home/mpasternak/Documents/Some_Study/Philips/2D_EPI/analysis/lock/xASL_module_ASL/Sub-001/xASL_module_ASL_ASL_1'}
```
I believe the intention was to delete `LockDir` instead?

**Comment by HenkMutsaerts** [comment]
No this was the right folder to delete, the check for `LockDir` is to ensure that this module was not locked by another parallel process. However, you are right that xASL_delete doesn't read cells but should have a path (char/string) as input.
I fix this now one two levels:

* xASL_delete: if this receives a cell it tries to deal with it, and issues a warning
* xASL_adm_CleanUpBeforeRerun: replacing {end+1} with (end+1) which should avoid the erroneous "cell-in-cell" structure.

**Comment by HenkMutsaerts** [comment]
@MauricePasternak can you check if this is now fixed (using branch `bug-#325_xASL_CleanUpBeforeRerun`)?

**Comment by MauricePasternak** [comment]
Since the whole thing is now in a try-catch block, the exception is caught, but comes from a different location now. This part:

```
elseif ~isempty(regexp(LockDirs2{iDir},'xASL_module_ASL'))
    % specify session ID
    if exist(LockDirs2{iDir}, 'dir')
        for iSession=1:nSessions
            CurrentDir(end+1) = xASL_adm_GetFileList(fullfile(LockDirs2{iDir}, SubjectID), ['^xASL_module_ASL_' SessionID{iSession} '$'], 'FPList', [0 Inf], true);
        end
    end
```
Has a bit of an issue, since `CurrentDir` is still an empty char array by that point. So the error that's caught has nothing to do with xASL_Delete. Instead, it just complains:

```
K>> CurrentDir
CurrentDir =
  0×0 empty char array
```

```
K>> CurrentDir(end+1) = xASL_adm_GetFileList(fullfile(LockDirs2{iDir}, SubjectID), ['^xASL_module_ASL_' SessionID{iSession} '$'], 'FPList', [0 Inf], true);
Conversion to char from cell is not possible.
```

**Comment by jan-petr** [comment]
Good catch Maurice. Henk has fixed the issue, but the CurrentDir was previously initialized as char, so it couldn't be re-typed to cell of strings. I have fixed the initialization.

But this brings us to a new issue - why do we need to have the whole thing in try-catch - it shouldn't crash. If a file is not found, it's not deleted. And all issues should be solved with the delete. The try-catch was probably masking many errors all the time. 
@HenkMutsaerts  shall we remove it?

@MauricePasternak Can you test the new version please?

**Comment by jan-petr** [comment]
@HenkMutsaerts The OriList was indeed originally meant to be a list of lists (cell of cells), because some of these outputs were 0x0 or 2x1, and those didn't work with (end+1) - so I had to fix that as well. I have removed the OriListTotal because of that as no longer needed.

**Comment by jan-petr** [comment]
Finally fixed and seems to work for me. @MauricePasternak - can you do the last check?

**Comment by HenkMutsaerts** [comment]
Fine to remove the try catch construction. Perhaps it should be cell in cell in some cases but not all?

**Comment by jan-petr** [comment]
OK. With the try-catch - we would have to test if there are no cases where this would be a problem.

There used to be cell-in-cell cases, but with your, and mine edits now, this is no longer needed, as we don't have to create a cells of cells, but rather concatenate all strings one after another, as in the cell-in-cell case, this was anyway done at the end. So this is fine now with respect to this.

**Comment by HenkMutsaerts** [comment]
As long as the checks and deleted stay different, eg sometimes the check is if the lock folder is there, and if it is not, it deletes the subfolder, which is another folder. So not all strings should be concatenated :)

**Comment by HenkMutsaerts** [comment]
Looks good, the only issue could be that `xASL_adm_GetFileList` gives a row of cells, whereas you now concatenate a column of the lists (`;` instead of `,`), so this may go wrong. Unless `xASL_adm_GetFileList` always gives a single cell output.

Should also still need testing.

**Comment by jan-petr** [comment]
> As long as the checks and deleted stay different, eg sometimes the check is if the lock folder is there, and if it is not, it deletes the subfolder, which is another folder. So not all strings should be concatenated :)

Yes, it is not strings that get concatenated. But cell arrays get concatenated. Instead of an array when each cell is another cell array, I take all cell arrays and concatenate them to a longer cell array - but of course not touching the strings inside.

**Comment by jan-petr** [comment]
> Looks good, the only issue could be that `xASL_adm_GetFileList` gives a row of cells, whereas you now concatenate a column of the lists (`;` instead of `,`), so this may go wrong. Unless `xASL_adm_GetFileList` always gives a single cell output.

Are you sure - I wasn't sure which of those two - column or row - is outputted, so I have tested it and it gave me a column. So unless the output differs on different occasions or unless I have messed something up, the ';' is correct.

**Comment by HenkMutsaerts** [comment]
Yes, you were correct, my mistake.

**Comment by HenkMutsaerts** [comment]
This PR/issue can be merged/closed
