### ISSUE TITLE
Parse warnings/errors

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#326]
### Rationale
When testing, especially when testing in parallel, it takes a lot of time to go through all log-files one-by-one. Rather, they should be read in, and their warnings and errors should be parsed.

In these log files, that were started inside ExploreASL using the Matlab `diary on` & `diary off` functionality:

### Warning
A warning contains `Warning:`, starts with `[` and ends with `]`. Then there are several references to the (sub-)functions that were responsible for this warning, starting with `In <a href=` and ending with `line \d*</a>)]`
Example:

```
[Warning: Registration off, spatial CoV detection unreliable] 
[> In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_wrp_RegisterASL>xASL_im_GetSpatialCovNativePWI', '/Users/henk/ExploreASL/ExploreASL/Modules/SubModule_ASL/xASL_wrp_RegisterASL.m', 645)" style="font-weight:bold">xASL_wrp_RegisterASL>xASL_im_GetSpatialCovNativePWI</a> (<a href="matlab: opentoline('/Users/henk/ExploreASL/ExploreASL/Modules/SubModule_ASL/xASL_wrp_RegisterASL.m',645,0)">line 645</a>)
  In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_wrp_RegisterASL', '/Users/henk/ExploreASL/ExploreASL/Modules/SubModule_ASL/xASL_wrp_RegisterASL.m', 392)" style="font-weight:bold">xASL_wrp_RegisterASL</a> (<a href="matlab: opentoline('/Users/henk/ExploreASL/ExploreASL/Modules/SubModule_ASL/xASL_wrp_RegisterASL.m',392,0)">line 392</a>)
  In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_module_ASL', '/Users/henk/ExploreASL/ExploreASL/Modules/xASL_module_ASL.m', 292)" style="font-weight:bold">xASL_module_ASL</a> (<a href="matlab: opentoline('/Users/henk/ExploreASL/ExploreASL/Modules/xASL_module_ASL.m',292,0)">line 292</a>)
  In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_Iteration>runIteration', '/Users/henk/ExploreASL/ExploreASL/Functions/xASL_Iteration.m', 361)" style="font-weight:bold">xASL_Iteration>runIteration</a> (<a href="matlab: opentoline('/Users/henk/ExploreASL/ExploreASL/Functions/xASL_Iteration.m',361,0)">line 361</a>)
  In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_Iteration', '/Users/henk/ExploreASL/ExploreASL/Functions/xASL_Iteration.m', 100)" style="font-weight:bold">xASL_Iteration</a> (<a href="matlab: opentoline('/Users/henk/ExploreASL/ExploreASL/Functions/xASL_Iteration.m',100,0)">line 100</a>)
  In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('ExploreASL_Master', '/Users/henk/ExploreASL/ExploreASL/ExploreASL_Master.m', 141)" style="font-weight:bold">ExploreASL_Master</a> (<a href="matlab: opentoline('/Users/henk/ExploreASL/ExploreASL/ExploreASL_Master.m',141,0)">line 141</a>)] 
```

### Error
An error starts with `ERROR: Job iteration terminated!` after which a similar syntax follows as with the warning, and it ends with `CONT: but continue with next iteration!
Example:

```
ERROR: Job iteration terminated!

ans =


Error using <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_module_Structural', '/Users/henk/ExploreASL/ExploreASL/Modules/xASL_module_Structural.m', 198)" style="font-weight:bold">xASL_module_Structural</a> (<a href="matlab: opentoline('/Users/henk/ExploreASL/ExploreASL/Modules/xASL_module_Structural.m',198,0)">line 198</a>)
piet

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_Iteration>runIteration', '/Users/henk/ExploreASL/ExploreASL/Functions/xASL_Iteration.m', 361)" style="font-weight:bold">xASL_Iteration>runIteration</a> (<a href="matlab: opentoline('/Users/henk/ExploreASL/ExploreASL/Functions/xASL_Iteration.m',361,0)">line 361</a>)
				[result, x] = jobfn(x); % [result, x] = jobfn(x, job_ex);

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_Iteration', '/Users/henk/ExploreASL/ExploreASL/Functions/xASL_Iteration.m', 100)" style="font-weight:bold">xASL_Iteration</a> (<a href="matlab: opentoline('/Users/henk/ExploreASL/ExploreASL/Functions/xASL_Iteration.m',100,0)">line 100</a>)
	[bAborted, xOut] = runIteration(dbSettings);

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('ExploreASL_Master', '/Users/henk/ExploreASL/ExploreASL/ExploreASL_Master.m', 106)" style="font-weight:bold">ExploreASL_Master</a> (<a href="matlab: opentoline('/Users/henk/ExploreASL/ExploreASL/ExploreASL_Master.m',106,0)">line 106</a>)
        [~, x] = xASL_Iteration(x,'xASL_module_Structural');

Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('ExploreASL', '/Users/henk/ExploreASL/ExploreASL/ExploreASL.m', 33)" style="font-weight:bold">ExploreASL</a> (<a href="matlab: opentoline('/Users/henk/ExploreASL/ExploreASL/ExploreASL.m',33,0)">line 33</a>)
x = ExploreASL_Master(var1, var2, var3, var4, var5, var6);


CONT: but continue with next iteration!
```

Important to note that we should delete the log-files before rerunning a test.

**Comment by MichaelStritt** [comment]
### How to run GetLogContent:

```
rootDir = '.\Test_Runs\TestDataSet';
[logContent] = xASL_qc_GetLogContent(rootDir);
Log file: xASL_module_Population.log
Log file: xASL_module_Structural.log
Log file: xASL_module_ASL.log
>> logContent

logContent =

  5×3 table

               Module                 Type         Content  
    ____________________________    _________    ___________

    'xASL_module_Population.log'    'Warning'    {10×1 cell}
    'xASL_module_Structural.log'    'Warning'    {19×1 cell}
    'xASL_module_Structural.log'    'Warning'    {19×1 cell}
    'xASL_module_Structural.log'    'Warning'    {19×1 cell}
    'xASL_module_Structural.log'    'Error'      {22×1 cell}
```

### How to run xASL_qc_RemoveLogFilesForRerun:

```
>> rootDir = 'M:\SoftwareDevelopment\MATLAB\m.stritt\Test_Runs\TestDataSet';
>> xASL_qc_RemoveLogFilesForRerun(rootDir);
Delete: xASL_module_Population.log
Delete: xASL_module_Structural.log
Delete: xASL_module_ASL.log
```

**Comment by HenkMutsaerts** [comment]
Very nice!

First review (will test tomorrow):

%        rootDir            - Case root directory (OPTIONAL)
-> OPTIONAL should always have a DEFAULT (in this case, it defaults to a user input).
-> Note that uigetdir requires JVM and will crash when using no GUI; see how I fixed this in the `ExploreASL_Initialize`, that you allow a Linux dialogue instead of GUI browser, if needed.

* I would output to JSON or TSV using our usual workflow, the Table is something Matlab specific, not sure if this easily saves to a JSON or TSV. We want it soon to be communicating back to GitHub so human readable/non-Matlab is probably preferred :)

* The `nargin <` should also have ` || isempty() as input check; such that you can input a third input argument without having to specify the second argument but omitting this by `[]`

* Better to use `xASL_adm_GetFileList` with `dir` option instead of `dir`, our xASL function has better cross-platform performance etc.

* `curFileArr` -> good practice these days to use full words, to increase code readability

* `contains(lower(` could be replaced by `regexpi`

* we try to avoid `break`,`continue` etc for readability for debugging, here it should be fine

* We may want to find a different prefix, `qc` is more used for visual/image quality control, whereas this is more `code/pipeline` quality control. Should we have a new prefix called `test`?

* Nice that you created `xASL_qc_RemoveLogFilesForRerun` ! Wasn't my intention, also this already happens inside `xASL_adm_CleanUpBeforeRerun`. It was more a caution warning :)

**Comment by MichaelStritt** [comment]
@HenkMutsaerts I tried to, but couldn't convert this warning/XML sort of text to something more readable. Maybe we can improve that in the future. You can export tsv & xlsx though and it automatically extracts the last file & line of the error / warnings. I think we can merge for now and improve after 1.5.0.

**Comment by jan-petr** [comment]
> @HenkMutsaerts I tried to, but couldn't convert this warning/XML sort of text to something more readable. Maybe we can improve that in the future. You can export tsv & xlsx though and it automatically extracts the last file & line of the error / warnings. I think we can merge for now and improve after 1.5.0.

Agree with that. I'll quickly check the code and test. But the results I saw before were very good.

**Comment by HenkMutsaerts** [comment]
@BeatrizPadrela @jan-petr Nice work! I would only make the %% 1. section title identical to the one shown in the header, that makes it easier for everyone. So in this case they should both probably be `1. Load all log-files` and the explanatory text within section 1 could be e.g., `Get all log-files within the root folder`

Also note that the commit is `unverified`
