### ISSUE TITLE
xASL_qc_TestExploreASL: include import

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#328]
### Rationale
For complete automatic testing, both the testdatasets and testing scripts should follow:
1. DICOM2BIDS
2. BIDS2Legacy
3. ExploreASL (Structural, ASL, and Population modules)

### How
For this to work, `xASL_qc_TestExploreASL` should incorporate the functionality of:
1. cloning the FlavorDatabase
2. DICOM2BIDS
3. BIDS2Legacy

(however B and C will be included in the `ExploreASL_Master` function, so we might wait for this to happen).
Then, `/Development/BIDS/BIDS_fullPipelineTest` could be removed

### Release notes
Nothing. Duplicate

**Comment by MichaelStritt** [comment]
**Note to myself:** This requires #290 to be merged first, otherwise we have to change all of this a second time.

**Comment by MichaelStritt** [comment]
> **Jan**: Check if this is valid, we probably don't need this anymore because we have the Flavors testing script. And the test-datasets need no import.

Yes, I think the best thing to do would be to update the fullBidsPipeline test with the updated ExploreASL calls after the merge of #290.

**Comment by MichaelStritt** [comment]
`xASL_test_IntegrationTesting` already runs the full pipeline from DICOM to derivatives. We should add dataPar.json files for the datasets without T1s though, so that we don't have to use the `UseMNIasStructural` option.
