### ISSUE TITLE
Import of PAR-REC is not working

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#334]
Dcm2nii imports PAR-REC parameters to JSON, but the old version of Import is still trying to convert it to parms.mat - this crashes the PAR-REC import.

It needs to be fixed and tested both for normal import and for BIDS import.

**Comment by HenkMutsaerts** [comment]
Looks good but please next time don't put 5 different edits in 1 commit, let's make a rule that a single commit is a single type of edit; that's much easier to review.

Also, the `tokenOld = imPar.tokenNew` stuff looks quite quick and dirty... can we do a better job here? Is it even necessary? And why? (as this probably has nothing to do with PARREC, but something you fixed in between? Then I cannot comment on it, perhaps there was a reason for not having it in this way in the first place, hence the rule to do a single type of edit per commit ;)

**Comment by jan-petr** [comment]
> Looks good but please next time don't put 5 different edits in 1 commit, let's make a rule that a single commit is a single type of edit; that's much easier to review.

Good point - could have been 2 commits.

> Also, the `tokenOld = imPar.tokenNew` stuff looks quite quick and dirty... can we do a better job here? Is it even necessary? And why? (as this probably has nothing to do with PARREC, but something you fixed in between? Then I cannot comment on it, perhaps there was a reason for not having it in this way in the first place, hence the rule to do a single type of edit per commit ;)

I have previously implemented JSONs to replace ExploreASL_ImportConfig. There, the tokens are given as [N,2] arrays. In JSONs, we provide this as [N*2,1] array - so it needs to be reformatted. I have done that previously and it worked, but I forgot that if this is called with a classical imPar with the cell array and not with imPar from JSON, then you don't do this re-ordering - so that's why this fix. So for the commit organization - functionally - this works :)

**Comment by HenkMutsaerts** [comment]
Let's also make our commits more specific, e.g. "#334 ExploreASL_ImportBIDS: Check missing parameters'
Now with every commit you have to get into the commit to see which file is changed. Do you agree this is a good rule?

Do we really need an error for `MRAcquisitionType`? Or would a warning be good enough? Errors break the whole thing... You don't want to import 100 subjects where 1 subject has this field missing?

**Comment by jan-petr** [comment]
Actually, my motivation was that I will either report an error or it will crash on its own :D

MRAcquision is rather important field. If you don't have it, you cannot decide if you need SliceTiming. 

But we have of course 2 options.
1) We report an error and end.
2) We make a warning, and then skip the slice-time check. At the end, BIDS-import will report that a REQUIRED field is missing. But nothing will crash during the import.

If you agree that option 2 is what we want, then I'll implement it (I slightly favor option 2 as well).

**Comment by HenkMutsaerts** [comment]
I would not do option 2, as we would allow incomplete datasets/imports. It then becomes a mess to find out what parts of the import script did or did not run (there will of course be more fields potentially missing where we need such option 2s).

So I agree that you can have an error and it crashes (option 1). But there should be a try-catch per scan (or subject/visit, but I think per scan is nice), which means that it will crash this scan that doesn't have the `MRAcquisition` field, nicely catches it and reports it to the screen/diary, and will continue with other scans. This is also where the new WarningErrorLogParser from Michael comes into place.
