### ISSUE TITLE
spm_jsonread cannot read special characters saved by spm_jsonwrite

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#339]
Philips_PCASL_2DEPI_Bsup_AD4
the ASL.json
The error is in saving - if saved in a different program, it works, if saved with spm_jsonwrite, then spm_jsonread cannot read it after itself. It is this character that breaks everything ö

**Comment by jan-petr** [comment]
The trouble is the spm_jsonread - it cannot nicely handle UTF-8 multibyte characters. It calculates wrongly the length of the file. It calculates it by the number of multi-byte characters in UTF-8, but then it looks only for that number of single-byte characters - obviously ending prematurely if there are more multi-byte characters.

**Comment by jan-petr** [comment]
To test - try to read JSON containing the text below before and after the fix:
{"P":"Kaööööööööööööööaaam"}

**Comment by jan-petr** [comment]
And @MichaelStritt, can you please compile this for Windows. 

Simply:
cd External/SPMmodified/src/
mex -O -largeArrayDims spm_jsonread.c jsmn.c -DJSMN_PARENT_LINKS

and copy the new mex file from the src dir to the SPM dir to replace the old one.

**Comment by MichaelStritt** [comment]
### JSON file

```
{"P":"Kaööööööööööööööaaam"}
```

### Before the fix

```
>> json = spm_jsonread('M:\SoftwareDevelopment\MATLAB\m.stritt\weird_file.json');
>> json
json = 
  struct with fields:
    P: 'KaÃ¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶aaam'
```

### After the fix

```
>> json = spm_jsonread('M:\SoftwareDevelopment\MATLAB\m.stritt\weird_file.json');
>> json
json = 
  struct with fields:
    P: 'KaÃ¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶aaam'
```

Hmm... I guess we don't necessariley need **ä ö ü** for xASL parameters, but we should probably still fix it :/

**Comment by MichaelStritt** [comment]
### JSON

```
{"P":"Kaööööööööööööööaaam",
"S": "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
"T": "1234567890",
"U": "!§$%&//(())==??{[]}\\"
}
```

### MATLAB

```
>> json = spm_jsonread('M:\SoftwareDevelopment\MATLAB\m.stritt\weird_file.json');
>> json

json = 
  struct with fields:
    P: 'KaÃ¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶aaam'
    S: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    T: '1234567890'
    U: '!Â§$%&//(())==??{[]}\'
```

Hmm... most of the symbols work :)

**Comment by jan-petr** [comment]
Very funny - this works totally different under Windows :D The MEX has not issue with reading it - probably the string functions behave differently.

But I would say that it works. Only Matlab has problems displaying it :)

Check if you have the correct encoding in Matlab
slCharacterEncoding()
ans = 'UTF-8'

If not, try to switch to UTF-8 and see if it displays correctly. 
If this still doesn't work, try one of these conversion functions: native2unicode
spm_jsonread seems to have read the correct multi-byte characters. Only Matlab has trouble displaying it as multi-byte and displays these weird single-byte versions.

**Comment by MichaelStritt** [comment]
Hey @jan-petr, I made another test. I used Notepad++ and explicitly saved the JSON with UTF8. For me this didn't change anything:

```
>> json = spm_jsonread('.\test_file_utf8.json');
>> json
json = 
  struct with fields:
    P: 'KaÃ¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶Ã¶aaam'
    S: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    T: '1234567890'
    U: '!Â§$%&//(())==??{[]}\'
```

I then used json_write:

```
>> json = struct;
>> json.A = 'ÄÄÄÖÖÖÜÜÜ';
>> json.B = '!§$%&/()=?{[]}\';
>> json.C = '1234567890?';
>> spm_jsonwrite('.\test_write.json',json);
```

Reading it again seems to work just fine:

```
>> json_read = spm_jsonread('M:\SoftwareDevelopment\MATLAB\m.stritt\test_write.json');
>> json_read
json_read = 
  struct with fields:
    A: 'ÄÄÄÖÖÖÜÜÜ'
    B: '!§$%&/()=?{[]}\'
    C: '1234567890?'
```

If I open the file using Notepad, I get some other weird encoding:

```
{"A":"���������",
"B":"!�$%&/()=?{[]}\\",
"C":"1234567890?"}
```

All in all, it should work perfectly fine, as long as we both read and write using spm json read & write.

If there would be a character like` Ä Ö Ü` or `§ `in a manually defined JSON, we could have some issue.
