### ISSUE TITLE
xASL_TrackProgress is computationally intensive if used too much

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#341]
Inserting `xASL_TrackProgress` in PVC (running it once for every kernel), took 26 seconds instead of 2.6 seconds that `xASL_im_PVCkernel` cost without this insertion. However, if running this progress tracker once for every "z-kernel" this was not a significant addition to the computation time.

Hence, we should go through our code and watch out for nested cases of `xASL_TrackProgress`, aimed to provide more accurate progress tracking, as this may slow down the code a lot.

### Release note: Reduce extensive usage of ExploreASL CLI progress tracker.

**Comment by jan-petr** [comment]
Maybe Mathijs and Michael can help here. Running the TestData with profile on and trying to identify computationally intensive use of TrackProgress and other I/O functions that shouldn't really take too much time.

**Comment by MichaelStritt** [comment]
Okay, so I made a quick index search. There are about 86 files which include `xASL_TrackProgress`. Speed optimization is always a good thing, so I'll try to run a few tests. The list below does not include scripts in Development.

## TestDataSet Low Quality Test Run

Format: script name - approximate number of calls within the test run

### Severe calls of xASL_TrackProgress (potentially a lot of time is lost here)

cat_vol_imcalc - 3*179+4*256 = 1817
spm_preproc_write8 - 256
cat_spm_preproc_write8 - 179+6 = 185
xASL_wrp_CleanUpWMH_SEGM - 366
cat_main_clean_gwc - 2*32+104 = 168
spm_preproc8 - 30
...

### Less important calls of xASL_TrackProgress (probably not much time lost here)

xASL_adm_CleanUpBeforeRerun - 1+7+9
spm_coreg - 2*6
spm_deformations - 1+1
xASL_im_CleanupWMHnoise - 2+1
cat_vol_sanlm - 1+1
cat_main_updateSPM - 6
cat_main_gintnorm - 7
xASL_im_FillNaNs - 3+3
cat_main_reportfig - 10
xASL_spm_reslice - 3
...


### Hard to determine number of calls

xASL_spm_reslice

**Comment by HenkMutsaerts** [comment]
@MichaelStritt 
Haha this function is only useful when inserted in a for loop :) so wouldn't remove it at all, just in some cases I have nested it to deep, leading to 1000s calls. 100 calls should be fine per loop

**Comment by MichaelStritt** [comment]
Talking about performance improvements, has anybody ever tried out [SPM CUDA](http://mri.ee.ntust.edu.tw/wp/?page_id=195)?

**Comment by HenkMutsaerts** [comment]
> Talking about performance improvements, has anybody ever tried out [SPM CUDA](http://mri.ee.ntust.edu.tw/wp/?page_id=195)?

Yes, didn't work out of the box. I can ask them again if they improved this recently, though.
