### ISSUE TITLE
Try-catch errors in ImportBIDS

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#346]
We have to convert import to a regular module so that it tries and catches errors and continues if something goes wrong. Though we have to figure out how to lock files for subjects as this has to be done in a different folder than for the processing.

Part of it was done already (try-catch), but we have to still convert it to a full module.

Duplicate - done already and the rest will be done i #799

**Comment by MichaelStritt** [comment]
I hope this commit 71bc87a can help with that a little bit. I think that could be a nice method to capture errors and warnings throughout the pipeline.

**Comment by MichaelStritt** [comment]
Besides the lock files thing, all of that should be there already.
