### ISSUE TITLE
Test/practice issue for Beatriz

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#348]
### Rationale

This is just meant for testing the ExploreASL Github workflow.

**Comment by BeatrizPadrela** [comment]
OK guys you can just ignore this, this was just for testing.
But I like the fact that Exploreasl now welcomes me personally :)

**Comment by jan-petr** [comment]
The branch looks deleted - and so is the commit then.

We can thus close this issue and then assist Beatriz if there are some more complex GitHub things to try.
