### ISSUE TITLE
xASL_Iteration - Reformat printing output for easier parsing

### ISSUE THREAD

**Issue by MauricePasternak** [ExploreASL/ExploreASL#349]
I have been brainstorming a method for robustly capturing errors from the GUI and attributing them to the right subject & run. Parsing log files is difficult (when should which log file be checked? since the logs are not overwritten, how can the right error be parsed?, etc).

The solution? Streams. Specifically piping STDOUT of ExploreASL to STDIN of a launched GUI worker. However, the worker would still need a good STDOUT statement occuring on a single line to gain awareness of what subject, run, etc. it is looking at currently.

The following block in xASL_Iteration.m is the ideal moment:

```
if ~AlreadyProcessed
    fprintf('\n%s\n',repmat('+',1,72)); % just draw a separator line
    fprintf('%s\n',['Starting ' x.MUTEXID ' at ' datestr(now)]);
    fprintf('\n');
end
```
 
But `x.MUTEXID` isn't clear at this time. For the Structural Module it states:

    xASL_module_Structural

For the ASL Module it states:

    xASL_module_ASL_<SESSION>

And for the Population Module it states:

    xASL_module_Population

The last one is actually a-okay. But the foremost 2 should be more detailed wrt Subject and Run. 

Can something other than x.MUTEXID be used in that location?

Ideally, the GUI would receive a STDOUT such that the following regex would immediately clarify the situation:

    xASL_module_(ASL|Structural|Population)(?:%%%([^#%&{}\\<>*?\/$!'":@+`|=]+))?(?:%%%([^#%&{}\\<>*?\/$!'":@+`|=]+))?\b

Where `%%%` is just some safe delimiter for the parts and `[^#%&{}\\<>*?\/$!'":@+`|=]+` is what is being captured (basically, any legal filepath characters).

For example, on the string: xASL_module_ASL%%%Subject_001%%%Afternoon_Run , it would extract ASL , Subject_001 , and Afternoon_Run

If this system was in play, the GUI would be able to use ExploreASL's STDOUT to latch onto a subject/run, listen for errors, and correctly attribute any captured errors to the approriate subject/run where they happened. This would avoid any necessity to parse log files and avoid other solutions that exhaust system resources altogether. In fact, this idea could also be expanded to have the GUI's textoutput be far more meaningful and precise.

**Comment by MichaelStritt** [comment]
@BeatrizPadrela: Let us know if you need help with one of your first issues. This is probably the one I'd start with, since it's a really nice learning example 👍

**Comment by MauricePasternak** [comment]
@BeatrizPadrela The biggest issues that I see are that:
1) The fprintf statements are separate. A single fprintf utilizing newline characters would be preferable, since STDOUT is fetched one fprintf at a time and parsing a single fprintf is easier than coordinating parsing between multiple fprintf.

2) You index as follows: `x.SESSIONS{1}`. This would be problematic if there is more than one run per subject.

**Comment by MichaelStritt** [comment]
Good idea 👍 

So right now we have something like:
```
Running Subject1 at Session1
Starting Structural_Module at 12:34:56
```

Maybe something like this?
```
=== Subject: Subject1, Session: Sessions1, Module: Structural_Module... (12:34:56) ===
```

This could be done like this:
```
fprintf('=== Subject: %s, Session: %s, Module: %s... (%s) ===\n',...
        x.SUBJECT, x.SESSIONS{...}, x.MUTEXID, datestr(now))
```

**Comment by MauricePasternak** [comment]
Yep, that would definitely work.

**Comment by BeatrizPadrela** [comment]
@MauricePasternak I did what you asked, I think it is okay now, what do you think?

**Comment by MauricePasternak** [comment]
The program will crash due to an indexing error coming from `x.SESSIONS{iIter}`. 

```
Index exceeds the number of array elements (1).

Error in xASL_Iteration>runIteration (line 333)
            fprintf('%s\n',['=== Subject: ' x.SUBJECT ', Session: ' x.SESSIONS{iIter} ', Module: ' datestr(now) ' ===']);
```

For example, consider this scenario:

- Running the Structural Module on a study with 2 subjects, both with only 1 run each named the default ASL_1.
- The first subject is already processed.

By the time you get to the print line, `iIter` will have a value of 2. But because x.SESSIONS is a single cell, that's an index error. In general `iIter` does not appear to be the right indexing variable to use here, even when running the ASL module (or Both) because its a reflection of the job iteration going on, not necessary the run being looked at. The indexing variable here should be a robust variable that is something like NaN when running the Structural or Population modules are being run and an accurate reflection of the run number when the ASL module is being run.

**Comment by BeatrizPadrela** [comment]
Hi Maurice,

In front of "Session:" do you want that it prints "ASL_1" of only "1" as the number of the session?  Can x.SESSIONS be "ASL_2" in any case? If there are two runs, will x.SESSIONS have "ASL_1" and "ASL_2" inside?

Thanks!

**Comment by MichaelStritt** [comment]
@BeatrizPadrela: We have some nice multi session datasets to play around [here](https://github.com/ExploreASL/TestDataSets). So if you want to test the updated print statement, you can always use them.

**Comment by BeatrizPadrela** [comment]
I think it is resolved now :)

**Comment by BeatrizPadrela** [comment]
This is good now :) Only writes the session for the ASL module, and I created a way to write the session that is based on the diaryFileEx
@MauricePasternak thoughts? :)

**Comment by MichaelStritt** [comment]
@BeatrizPadrela: If you tested it and it seems to work, I'd recommend to open a PR and put Henk & Maurice there as reviewers ;)
