### ISSUE TITLE
Improving parsing of errors and warnings from log files.

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#352]
Certain cases of errors and warnings are still not parsed optimally. See the examples below.
I understand that the warnings are too non-standardized, so we will need to check if this can be improved or not. If not, then the current state is also good.

### Release notes: Improve parsing of errors and warnings from log files in xASL_test_GetLogContent

(I think the title is already a pretty good release note :) )

**Comment by jan-petr** [comment]
Issue 1:

Message is 
'Job iteration terminated!', 
while it would be helpful to have
"Array dimensions must match for binary array op" or both.

Original log:

```
ERROR: Job iteration terminated!

ans =

    'Array dimensions must match for binary array op.
     
     Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_quant_M0', '/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_quant_M0.m', 150)" style="font-weight:bold">xASL_quant_M0</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_quant_M0.m',150,0)">line 150</a>)
                     NetTR = x.Q.LabelingDuration+x.Q.Initial_PLD+x.Q.SliceReadoutTime.*(SliceIM-1);
     
     Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_wrp_ProcessM0', '/home/janpetr/ExploreASL/ExploreASL/Modules/SubModule_ASL/xASL_wrp_ProcessM0.m', 160)" style="font-weight:bold">xASL_wrp_ProcessM0</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/Modules/SubModule_ASL/xASL_wrp_ProcessM0.m',160,0)">line 160</a>)
     M0_im = xASL_quant_M0(xASL_io_Nifti2Im(x.P.Path_rM0), x);
     
     Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_module_ASL', '/home/janpetr/ExploreASL/ExploreASL/Modules/xASL_module_ASL.m', 366)" style="font-weight:bold">xASL_module_ASL</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/Modules/xASL_module_ASL.m',366,0)">line 366</a>)
                 xASL_wrp_ProcessM0(x);
     
     Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_Iteration>runIteration', '/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_Iteration.m', 361)" style="font-weight:bold">xASL_Iteration>runIteration</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_Iteration.m',361,0)">line 361</a>)
     				[result, x] = jobfn(x); % [result, x] = jobfn(x, job_ex);
     
     Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_Iteration', '/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_Iteration.m', 100)" style="font-weight:bold">xASL_Iteration</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_Iteration.m',100,0)">line 100</a>)
     	[bAborted, xOut] = runIteration(dbSettings);
     
     Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('ExploreASL_Master', '/home/janpetr/ExploreASL/ExploreASL/ExploreASL_Master.m', 141)" style="font-weight:bold">ExploreASL_Master</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/ExploreASL_Master.m',141,0)">line 141</a>)
             [~, x] = xASL_Iteration(x,'xASL_module_ASL');
     
     Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('ExploreASL', '/home/janpetr/ExploreASL/ExploreASL/ExploreASL.m', 33)" style="font-weight:bold">ExploreASL</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/ExploreASL.m',33,0)">line 33</a>)
     x = ExploreASL_Master(var1, var2, var3, var4, var5, var6);'




```

**Comment by jan-petr** [comment]
Issue 2. 
Reports two warnings instead of one.
Message/file/line for warning 1:
- Warning: qnt_PLDslicereadout=0          65.5 
- unkown 
- unkown

Warning 2:
- unknown
- xASL_quant_SliceReadoutTime_ShortestTR
- 53









`[Warning: qnt_PLDslicereadout=0          65.5           131         196.5           262         327.5           393             0          65.5
131         196.5           262         327.5           393             0          65.5           131         196.5           262         327.5
393             0          65.5           131         196.5           262         327.5           393             0          65.5           131
196.5           262         327.5           393             0          65.5           131         196.5           262         327.5           393 is
outside of its valid range 5-400 ms] 
[> In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_quant_SliceReadoutTime_ShortestTR', '/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_quant_SliceReadoutTime_ShortestTR.m', 53)" style="font-weight:bold">xASL_quant_SliceReadoutTime_ShortestTR</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_quant_SliceReadoutTime_ShortestTR.m',53,0)">line 53</a>)
  In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_quant_M0', '/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_quant_M0.m', 141)" style="font-weight:bold">xASL_quant_M0</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_quant_M0.m',141,0)">line 141</a>)
  In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_wrp_ProcessM0', '/home/janpetr/ExploreASL/ExploreASL/Modules/SubModule_ASL/xASL_wrp_ProcessM0.m', 160)" style="font-weight:bold">xASL_wrp_ProcessM0</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/Modules/SubModule_ASL/xASL_wrp_ProcessM0.m',160,0)">line 160</a>)
  In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_module_ASL', '/home/janpetr/ExploreASL/ExploreASL/Modules/xASL_module_ASL.m', 366)" style="font-weight:bold">xASL_module_ASL</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/Modules/xASL_module_ASL.m',366,0)">line 366</a>)
  In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_Iteration>runIteration', '/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_Iteration.m', 361)" style="font-weight:bold">xASL_Iteration>runIteration</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_Iteration.m',361,0)">line 361</a>)
  In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_Iteration', '/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_Iteration.m', 100)" style="font-weight:bold">xASL_Iteration</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_Iteration.m',100,0)">line 100</a>)
  In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('ExploreASL_Master', '/home/janpetr/ExploreASL/ExploreASL/ExploreASL_Master.m', 141)" style="font-weight:bold">ExploreASL_Master</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/ExploreASL_Master.m',141,0)">line 141</a>)
  In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('ExploreASL', '/home/janpetr/ExploreASL/ExploreASL/ExploreASL.m', 33)" style="font-weight:bold">ExploreASL</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/ExploreASL.m',33,0)">line 33</a>)] `

**Comment by jan-petr** [comment]
Issue 3. That's a tricky one - I have simply pressed CTRL+C here :)
Anyway - it misses that the code was breaked and reports this as 5 different warnings:) Very non-essential to correctly recognize this, as this will not happen very often. But maybe it is easy to parse - you can check...

`{Operation terminated by user during <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_adm_OtherListSPM', '/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_adm_OtherListSPM.m', 43)" style="font-weight:bold">xASL_adm_OtherListSPM</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_adm_OtherListSPM.m',43,0)">line 43</a>)


In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_im_CenterOfMass', '/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_im_CenterOfMass.m', 36)" style="font-weight:bold">xASL_im_CenterOfMass</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_im_CenterOfMass.m',36,0)">line 36</a>)
    OtherList = xASL_adm_OtherListSPM(OtherList, false);

In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_wrp_LinearReg_T1w2MNI', '/home/janpetr/ExploreASL/ExploreASL/Modules/SubModule_Structural/xASL_wrp_LinearReg_T1w2MNI.m', 84)" style="font-weight:bold">xASL_wrp_LinearReg_T1w2MNI</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/Modules/SubModule_Structural/xASL_wrp_LinearReg_T1w2MNI.m',84,0)">line 84</a>)
    xASL_im_CenterOfMass(x.P.Path_T1, OtherList, 15); % 15 mm minimal offset == always apply realignment if slightly off

In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_module_Structural', '/home/janpetr/ExploreASL/ExploreASL/Modules/xASL_module_Structural.m', 205)" style="font-weight:bold">xASL_module_Structural</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/Modules/xASL_module_Structural.m',205,0)">line 205</a>)
    xASL_wrp_LinearReg_T1w2MNI(x, x.bAutoACPC);

In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_Iteration>runIteration', '/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_Iteration.m', 361)" style="font-weight:bold">xASL_Iteration>runIteration</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_Iteration.m',361,0)">line 361</a>)
				[result, x] = jobfn(x); % [result, x] = jobfn(x, job_ex);

In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_Iteration', '/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_Iteration.m', 100)" style="font-weight:bold">xASL_Iteration</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/Functions/xASL_Iteration.m',100,0)">line 100</a>)
	[bAborted, xOut] = runIteration(dbSettings);

In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('ExploreASL_Master', '/home/janpetr/ExploreASL/ExploreASL/ExploreASL_Master.m', 106)" style="font-weight:bold">ExploreASL_Master</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/ExploreASL_Master.m',106,0)">line 106</a>)
        [~, x] = xASL_Iteration(x,'xASL_module_Structural');

In <a href="matlab:matlab.internal.language.introspective.errorDocCallback('ExploreASL', '/home/janpetr/ExploreASL/ExploreASL/ExploreASL.m', 33)" style="font-weight:bold">ExploreASL</a> (<a href="matlab: opentoline('/home/janpetr/ExploreASL/ExploreASL/ExploreASL.m',33,0)">line 33</a>)
x = ExploreASL_Master(var1, var2, var3, var4, var5, var6);
} `

**Comment by MichaelStritt** [comment]
So everything besides issue 2 should be fixed now. The script can find these "operations terminated by user" sections and it should be able to retrieve some error messages if they are there. Issue 2 seems a bit weird to me, since my linebreaks on windows look different. I updated the "Testing" repository and added some warnings/errors to test this.

Try something like this: `[logContent] = xASL_test_GetLogContent('...\Testing\UnitTesting\io_files',0,1,0);`

```
>> logContent
logContent =
  27×7 table
            Module              Subject       Type                                                      Message                                                                            File                               Line        Content  
    _______________________    _________    _________    ______________________________________________________________________________________________________    _____________________________________________________    _________    __________

    '\modules_log_test.log'    'unknown'    'Warning'    'Registration off, spatial CoV detection unreliableï¿½'                                                   'xASL_wrp_RegisterASL>xASL_im_GetSpatialCovNativePWI'    '645'        {6×1 cell}
    '\modules_log_test.log'    'unknown'    'Warning'    'Registration summarizing failed'                                                                         'xASL_module_Population'                                 '180'        {5×1 cell}
    '\modules_log_test.log'    'unknown'    'Warning'    'Couldnt find spatial CoV information! File missing, skipping..'                                          'xASL_qc_SortBySpatialCoV'                               '53'         {6×1 cell}
    '\modules_log_test.log'    'unknown'    'Warning'    'Operation terminated by user...'                                                                         'file_array/subsref'                                     '65'         {8×1 cell}
    '\modules_log_test.log'    'unknown'    'Error'      'Job iteration terminated!'                                                                               'xASL_module_Structural'                                 '198'        {5×1 cell}
    '\modules_log_test.log'    'unknown'    'Error'      'Job iteration terminated! -> Reference to non-existent field 'FIELD_THAT_DOES_NOT_EXIST'.'               'xASL_module_Structural'                                 '46'         {4×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'Empty protocol name(s) (0018,1030)'                                                                      'unknown'                                                'unknown'    {1×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'Unable to append protocol name (0018,1030) to filename (it is empty).'                                   'unknown'                                                'unknown'    {1×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'Empty protocol name(s) (0018,1030)'                                                                      'unknown'                                                'unknown'    {1×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'Unable to append protocol name (0018,1030) to filename (it is empty).'                                   'unknown'                                                'unknown'    {1×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'Chris Rorden's dcm2niiX version v1.0.20190902  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 (64-bit Linux)'    'unknown'                                                'unknown'    {1×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'Empty protocol name(s) (0018,1030)'                                                                      'unknown'                                                'unknown'    {1×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'Unable to append protocol name (0018,1030) to filename (it is empty).'                                   'unknown'                                                'unknown'    {1×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'unknown'                                                                                                 'ExploreASL_ImportBIDS>CatchErrors'                      '947'        {5×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'Empty protocol name(s) (0018,1030)'                                                                      'unknown'                                                'unknown'    {1×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'Unable to append protocol name (0018,1030) to filename (it is empty).'                                   'unknown'                                                'unknown'    {1×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'Unable to append protocol name (0018,1030) to filename (it is empty).'                                   'unknown'                                                'unknown'    {1×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'Empty protocol name(s) (0018,1030)'                                                                      'unknown'                                                'unknown'    {1×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'Unable to append protocol name (0018,1030) to filename (it is empty).'                                   'unknown'                                                'unknown'    {1×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'Unable to append protocol name (0018,1030) to filename (it is empty).'                                   'unknown'                                                'unknown'    {1×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'Chris Rorden's dcm2niiX version v1.0.20190902  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 (64-bit Linux)'    'unknown'                                                'unknown'    {1×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'Empty protocol name(s) (0018,1030)'                                                                      'unknown'                                                'unknown'    {1×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'Unable to append protocol name (0018,1030) to filename (it is empty).'                                   'unknown'                                                'unknown'    {1×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'Unable to append protocol name (0018,1030) to filename (it is empty).'                                   'unknown'                                                'unknown'    {1×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'unknown'                                                                                                 'ExploreASL_ImportBIDS>CatchErrors'                      '947'        {5×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'xASL_adm_Dicom2JSON: Multiple scale slopes exist for a single scan'                                      'xASL_bids_Dicom2JSON'                                   '510'        {5×1 cell}
    '\import_log_test.txt'     'unknown'    'Warning'    'xASL_adm_Dicom2JSON: Multiple scale slopes exist for a single scan'                                      'xASL_bids_Dicom2JSON'                                   '510'        {5×1 cell}

```

**Comment by MichaelStritt** [comment]
I also rewrote some code to make it backwards compatible. The code uses hard-coded `ExploreASL_Master` identifiers etc., so it won't work for other projects, just to let you know ;) I couldn't find a better way, since you kind of need an identifier for the start and end of each message.

Is it okay like this @jan-petr? Or do you need issue 2 to be fixed (then I would need the corresponding log file)?

**Comment by jan-petr** [comment]
> Is it okay like this @jan-petr? Or do you need issue 2 to be fixed (then I would need the corresponding log file)?

I couldn't reproduce the whole issue 2, because i has been fixed :) The first part of it is now correctly parsed and printed. So issue 2 is fine for me and you can proceed with PR. I'll review the PR once created...
