### ISSUE TITLE
Confusing explanation `DataParTemplate.m`

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#355]
`DataParTemplate.m` has some confusing statements as guideline for the `DataPar.json`. This needs to be checked, e.g., the following is probably wrong (line 22):

>> % Scalars can be inputted as scalars, but vectors need to be inputted as string, e.g. '[1 2]'

**Comment by MichaelStritt** [comment]
@HenkMutsaerts: You're right, this seems to be wrong.

We should add the atlas option as well...

`"Atlases": ["TotalGM","DeepWM","Hammers","HOcort_CONN","HOsub_CONN","Mindboggle_OASIS_DKT31_CMA"]`

...and here we don't use `'[1 2]'` and instead use `['abc','def','...']`.

**Comment by MichaelStritt** [comment]
@HenkMutsaerts: I added some information about quotation marks in JSON to the DaraParFile in 3008ec6. I also added a small section for the available atlases.

Checkout: [JSON-single-quotes-vs-double-quotes](https://js.plainenglish.io/the-real-difference-between-single-quotes-and-double-quotes-in-javascript-3d00bf720bcd)

> JavaScript Object Notation (JSON), the lightweight data storage format, only allows double quotes.
