### ISSUE TITLE
Single function for parsing SliceReadoutTime - called at multiple locations

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#356]
For the SliceReadoutTime, I still think there is a lot of redundancy, and it becomes quite difficult to read what is being done with this parameter throughout the pipeline. I would put this parsing in a separate function, though we might call it from different locations.

Essentially, the parameter can be either a vector or a single number. These are then applied differently in ASL and M0 quantification. The easiest will be to turn it to a vector at the start of ASL module and then always apply as a vector.

### Comment
This only internally changes how is the SliceTime handeled and where it is recalculated as a vector from a scalar. Only minor mention in the release text. However, this overlaps with another issue that was changing slice-readout times - so we can simply mention one common comment - see below.

### Release summary
Internally restructure SliceTime allowing ExploreASL now to work with multi-band 2D EPI as well or any other SliceTime order.

**Comment by HenkMutsaerts** [comment]
Yes, I just changed this issue name. It's not only scalar vs vector, it's conceptual the parsing of this parameter that is now at multiple locations; would be nice to make this a bit more transparent.

**Comment by jan-petr** [comment]
Agree. I have a solution for that and will quickly implement it. But I need to wait for the issue #189 to merge to develop. Or I would have to create a new branch from that and that would create a lot of duplicitous commits after the rebase and merging of #189.

**Comment by jan-petr** [comment]
Disregard that there are 4 commits. I made initially two, but with the same name, so I had to rename one. So there are 4 commits here in the issue, but in the branch, there are only 2 commits with the correct names.
