### ISSUE TITLE
Call ExploreASL without input parameters

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#380]
A recent fix for the compiled version introduced this error.

**Comment by HenkMutsaerts** [comment]
@MichaelStritt this is a mistake of an issue that was incorrectly closed ;) I would rather re-open this issue and fix this.
The `char()` is not required right, so I would just delete it? The script just becomes more bulky...

If you really want to keep it, then at least you have to fix the mistake on the first line you changed, you should be able to easily find it;)

**Comment by MichaelStritt** [comment]
> If you really want to keep it, then at least you have to fix the mistake on the first line you changed, you should be able to easily find it;)

Oh, yeah, typical copy paste mistake ;)

> The `char()` is not required right, so I would just delete it? The script just becomes more bulky...

Hmm... I know what you mean about code becoming "bulky" really fast, I'm just not sure if not parsing at all is the better option. It seems like the CLIs always pass strings as character arrays, so we should still be safe and we can just remove the line. I just thought it would be better regarding coding style to parse all variables instead of only parsing a subset. Just keep in mind that real parsing would be even more "bulky". It's an important part of the code and is allowed to need a few lines of code because of that ;)

Here's an example of how the Matlab people want us to do this:

```matlab
function test(filepath,argumentA)

  % Initialize input parser
  p = inputParser;
  
  % Update input parser (filepath)
  addRequired(p,'filepath',@ischar);
  
  % Set defaults, valid options and check
  defaultArgumentA = 'DefaultA';
  validArgumentsA = {'DefaultA','OptionA1','OptionA2'};
  checkArgumentA = @(x) any(validatestring(x,validArgumentsA));
  
  % Update input parser (argumentA)
  addOptional(p,'argumentA',defaultArgumentA,checkArgumentA)
  
  % Do the parsing
  parse(p,filepath,argumentA);
 
  % Print results
  disp(p.Results);

end
```

```matlab
>> test('thisIsMyPath','OptionA1');
    argumentA: 'OptionA1'
    filepath: 'thisIsMyPath'
```

**Comment by HenkMutsaerts** [comment]
Yes, you're right; though this "real parsing" could be grouped in separate parsing functions, as there will be many input argument parsing similarities between different functions, I would envision.
