### ISSUE TITLE
Error in moving and removing of files

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#398]
Recreating parameter file: M:\SoftwareDevelopment\MATLAB\m.stritt\TestBIDS\TmpConversion\Siemens_PCASL_multiTI\analysis\Sub1\T1w_1\T1w.json
Field ImageType contains empty fields, skipping
Der Befehl "mv" ist entweder falsch geschrieben oder konnte nicht gefunden werden. 
Der Befehl "rm" ist entweder falsch geschrieben oder konnte nicht gefunden werden. 
there seems to be a problem with the unix/windows command difference (rm, mv commands) and because of that some of the file are not found later on

**Comment by MichaelStritt** [comment]
Lines 101 and 102 of `xASL_bids_TestBidsConversion` seem to be the problem here.

**Comment by HenkMutsaerts** [comment]
Should be replaced by xASL_delete and xASL_Move

Happy to be learning German btw, hope there no version differences between the English and German windows :)

**Comment by MichaelStritt** [comment]
Nope, Matlab is in English but it calls dos with the system command and dos is in German 👍

**Comment by HenkMutsaerts** [comment]
So: 
* I will make the paths platform independent, by replacing `/` by `fullfile` parsing.
* Why are the paths not fully relative? The flavors are not predefined right?
* Very happy that you have a self-explanatory commit message! ;) This makes it much easier for me (and hopefully others too ;) to review
* I will improve the use of regular expressions in `xASL_adm_GetFileList` et al

**Comment by HenkMutsaerts** [comment]
> Nope, Matlab is in English but it calls dos with the system command and dos is in German 👍
> Edit: I can't change the dos language, sorry ;)

You know my opinion on this: every self-respecting international organization should have all IT in English ;)

**Comment by HenkMutsaerts** [comment]
I believe this is a more compact, readable, version, do you agree?

Most importantly is that the path definitions will work in all OSes because of the correct use of `fullfile`.

My remaining question is if it is correct that `nii_files` on line 78 is unused.

**Comment by MichaelStritt** [comment]
I just went through all those edits. They seem fine to me 👍 
I personally don't like renaming and other cosmetics too much during a release, to avoid bugs, but it's probably fine this time.
Can't really comment on the line 78 thing :/

**Comment by jan-petr** [comment]
78 - yes, that was unused, I have removed it.

Agree - in release branch, we should only fix errors and related comments, headers etc. We should not touch the code that is not wrong or associated with errors. 

Because then the release branch grows, errors slip in and we might need to test again and again :)

Anyway - I consider this issue closed :)
