### ISSUE TITLE
Colon is not allowed in filenames on windows

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#399]
Needs to be fixed in release v1.5.0 immediately

**Comment by MichaelStritt** [comment]
Maybe we shouldn't hard code line `454` in `xASL_qc_TestExploreASL` and we shouldn't use the colon symbol in the filename as well (see commit e048bbe): `PreviousSaveFile = fullfile(TestDirOrig, '2020-05-07_06:25_ResultsTable.mat');`

**Comment by HenkMutsaerts** [comment]
Yes, good idea! One thing I use often is HHhMM, e.g. 14h20. What do you think of the following format to make it more readable:

'2020-05-07__06h25__Results.mat'

**Comment by MichaelStritt** [comment]
Sure, sounds good to me. We have to use something else than `matlab.lang.makeValidName`, which replaces the "-" symbol, but that shouldn't be a problem. I changed the format in d8439b4 and added a few lines to look for previous tables.

**Comment by jan-petr** [comment]
Looks all good to me. I am closing this issue if nobody objects.
