### ISSUE TITLE
Testing of TestDataSets returns n/a for GM and WM volume

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#400]
The whole column in GM and WM volume in the results table of xASL_qc_TestExploreASL is n/a

And remove warning: "Warning: Trailing tab on header; temporary ExploreASL fix, this could be removed"

The reason was that a string "GM_volume_(L)" was saved, but during loading, all special characters are converted to HEX string, and this was no longer recognized when loading and putting the results together.

**Comment by HenkMutsaerts** [comment]
Looks good, ready for PR.
However, is the behavior of the conversion of special characters to the HEX string correct?

**Comment by jan-petr** [comment]
Correct is a relative word... Inside the function (spm_load), it calls a function that ensures that all read fields are in a format that can be used for variable name in Matlab. So removing '(' etc and replacing them with a HEX string that is allowed to be used in a variable name. We don't need this behavior here, but it's part of the function...

**Comment by jan-petr** [comment]
This doesn't work with the old pre-processed TestDataSets because they still contain the 'Volume_(L)' field. We will now always write 'volume_L', but we fix the read that it is able to find all the old options from already processed files - that is 'volume_L', 'volume_(L)' and volume_0x28L0x28...
