### ISSUE TITLE
xASL_stat_MedianNan error if only NaNs

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#406]
The function xASL_stat_MedianNan crashes if an input consisting of only NaNs in provided.

Fix this case by outputting a NaN scalar.

**Comment by HenkMutsaerts** [comment]
Looks great. I would only avoid using variables called `x` as this is a major variable used throughout ExploreASL, so could be confused when debugging. I will create a separate issue for this now.
