### ISSUE TITLE
CAT version_matlab missing in compiled mode

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#408]
### Release summary
Skip missing fields in CAT during reports in compiled ExploreASL

**Comment by HenkMutsaerts** [comment]
Nice, does `version_matlab(1:dotIndex(1)+1)` work with all ways that Matlab can call it's version?
I thought we created a separate function for this, to extract either the 8, 9, etc, or 2016, 2017, etc (so the number or the year)? Or perhaps this is not needed, if this always goes right?

**Comment by MichaelStritt** [comment]
Yep, I was thinking the same thing. I couldn't find out why the matlab version was not set in this CAT specific struct at this part of the workflow though. If you want we can change this later on to another function, but for the moment I think this works fine. It seems at least pretty robust to me, since the version information starts with a number followed by a dot, so this should work for 9.6, 9.7, etc. but also 10.1 or whatever.
