### ISSUE TITLE
Rename Atlas MNI to MNI_Structural

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#410]
Discussion in #396:

Long story short, we can easily change this. Check out the [definition in xASL_init_FileSystem](https://github.com/ExploreASL/ExploreASL/blob/develop/Functions/xASL_init_FileSystem.m). We only have to change `line 196` from `x.P.Atlas.MNI` to `x.P.Atlas.MNI_Structural`.

### Release Note
Not necessary to be mentioned, since this only reverts changes from #56 which wasnt in 1.4.0

**Comment by MichaelStritt** [comment]
@jan-petr: do you want to change this or should I do this?

**Comment by MichaelStritt** [comment]
@jan-petr: Just did a rerun of one of the datasets in the population module. I used these atlas settings:

```
{"x":{"subject_regexp":"^sub-.*$",
"bUseMNIasDummyStructural":1.000000000000,
"Quality":1.000000000000,
"DELETETEMP":1.000000000000,
"S":{
    "Atlases": ["MNI_Structural", "DeepWM", "Mindboggle_OASIS_DKT31_CMA"]
}}}
```

Everything seemed to work fine 👍 
I definitely have to fix the number of digits in the JSONs though :)

**Comment by jan-petr** [comment]
Michael, I find a bit confusing that the variable name in MNI_Structural and the filename MNI_structural. Can you please synchronize this everywhere in the code.

**Comment by HenkMutsaerts** [comment]
@MichaelStritt in `Development/ExploreASL_make_standalone/ConvertNiiGz2Mat.m`
Why did you hardcode files to convert from .nii(.gz) to .mat?
This seems to work with Windows only (very easy to make these paths relative & OS-independent, so I can also compile ExploreASL on macOS (if I even need to run this function :)
Also: not all .nii(.gz) should be converted to .mat:

As code should be read-only, the .nii.gz can either:
1. have a .mat sidecar that is opened by Matlab
2. copied to the data analysis folder and unzipped there.

For those with the second case, just make sure that you are not unnecessary creating .mat files? :)

**Comment by MichaelStritt** [comment]
> @MichaelStritt in `Development/ExploreASL_make_standalone/ConvertNiiGz2Mat.m`
> Why did you hardcode files to convert from .nii(.gz) to .mat?
> This seems to work with Windows only (very easy to make these paths relative & OS-independent, so I can also compile ExploreASL on macOS (if I even need to run this function :)
> Also: not all .nii(.gz) should be converted to .mat:
> 
> As code should be read-only, the .nii.gz can either:
> 
>     1. have a .mat sidecar that is opened by Matlab
> 
>     2. copied to the data analysis folder and unzipped there.
> 
> 
> For those with the second case, just make sure that you are not unnecessary creating .mat files? :)

I didn't write this part. You changed this after my internship in 2018. I was really confused what you're doing there to be honest.

**Comment by HenkMutsaerts** [comment]
OK apologies;)
