### ISSUE TITLE
Delete Analysis folder after import to BIDS

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#411]
We have 4 folders after pre-processing the data for ExploreASL:
Sourcedata folder, Analysis folder, Rawdata folder (BIDS), and finally derivatives folder (Legacy)

This analysis folder should be deleted after the conversion to bids and legacy, as it is a temporary folder.

Also - make sure that NIFTIs from analysis are moved to rawdata and not copied - to make it faster.

To sum up - do the following modifications in ExploreASL_ImportBIDS (should be all between lines ~280-890):
1. Make sure data are moved instead of copied from analysis to rawdata.
2. Point 1 - sometimes, NII is loaded, modified and saved (typically when Philips scalings are applied). In that case, keep the load+save, but delete the NII in the analysis folder.
3. JSONs are always loaded, modified and saved, so simply just delete the analysis one.
4. After this is all done - delete also the subfolders and subject folders.
5. At the end - delete the analysis folder
6. Test with flavors that rawdata is correctly done and analysis folder completely removed.

### Release notes
DICOM 2 BIDS import deletes temporary folders.

**Comment by MichaelStritt** [comment]
@jan-petr: Hey Jan, do you know if there is a good flavor to test the changes in 2f8c80a?
I'm a bit unsure about the path definitions in lines 443, 859 & 863 and the fullBIDSPipeline test doesn't seem to work properly right now.

**Comment by jan-petr** [comment]
Perfect. I have tested it and it works! I only had to change the xASL_Move. Because xASL_Copy automatically zipped files if the destination was .nii.gz, but Move wasn't doing that. Yet :)

You can test with xASL_test_BIDSFlavorsFull(pathExploreASL,pathTest,[0 1 0 0 0 0 0]); from BIDS_FullPipelineTest - this worked fine for me in this branch - maybe you need to update the flavors themselves.

One small thing needs to be finished: There's an import-log and import-summary files that should be saved somewhere. Though I am not sure where because they don't belong to the BIDS-rawdata. So perhaps the root folder.

**Comment by MichaelStritt** [comment]
@jan-petr: Hm... hard to say what the best option is. Normally I'd say we can do in derivatives whatever we want, but that doesn't exist at this point.

8f8c953 should copy the import logs to the study root for now.

**Comment by jan-petr** [comment]
> @jan-petr: Hm... hard to say what the best option is. Normally I'd say we can do in derivatives whatever we want, but that doesn't exist at this point.
> 
> [8f8c953](https://github.com/ExploreASL/ExploreASL/commit/8f8c953093ed7457faa18eb4d7c09a12a3d4d077) should copy the import logs to the study root for now.

Yes, we can't copy the import logs to rawdata, because that's BIDS and has to stay 100% BIDS at all times. Study root is a good location ;)

**Comment by jan-petr** [comment]
Sorry. I haven't noticed that you already made that change... Then we should be ready for testing right?!

Can you create a PR, I will test and approve...
