### ISSUE TITLE
Update Function Headers

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#423]
- `xASL_adm_DocCrawler` requires functions with a really strict **header format**. Some headers need to be updated.
- Additionally, some headers lack required IO information. I'll try to improve this as well within this issue.
- Also I'd like to remove `DATAPAR.md` from the main repository, because there's also a version in the Documentation repo.

**Comment by MichaelStritt** [comment]
@HenkMutsaerts & @jan-petr 

Please check out the issue description above.

These functions are missing major information and I could need some help adding the missing information:

- `xASL_adm_DefineASLResolution`
- `xASL_im_Smooth3D`
- `xASL_im_dilateROI`
- `xASL_qc_ComputeNiftiOrientation`
- `xASL_wrp_DARTELSaveIntermedTrans`
- `xASL_wrp_GSSaveIntermedTrans`

For the website the most important thing would be to add at least a one line description. For the users some description of IO parameters would be nice.

**Comment by jan-petr** [comment]
OK. I will take care of this. I will fill in all that seems to be missing and you can control after me later if that is fine with the docucrawler. Do we have a simple template that would document how this should look like, how to number sections in the code ( 1) or 1.), how to number examples etc?

**Comment by MichaelStritt** [comment]
> OK. I will take care of this. I will fill in all that seems to be missing and you can control after me later if that is fine with the docucrawler. Do we have a simple template that would document how this should look like, how to number sections in the code ( 1) or 1.), how to number examples etc?

That would be awesome 👍 

So right now it just extracts the header using the `help` function and then searches for the tags which have to be exactly:

```
FORMAT: ...
INPUT: ...
OUTPUT: ...
DESCRIPTION: ...
EXAMPLE: ...
```

Right now I only store the content of the FORMAT text and the DESCRIPTION text in the markdown files. That should be enough for the Documentation website, otherwise it looks a bit overfilled.

You're basically doing almost everything perfect already and I can easily fix the ones where something is missing. Just some of the older scripts are a bit cryptic for me and it would take me a long time to find them out by doing sherlock holmes work 👍

**Comment by MichaelStritt** [comment]
@jan-petr: Maybe we should add `xASL_im_ResampleIM` to the list, since it's not that clear to me how to use it, especially for Henks change request regarding #384.

**Comment by jan-petr** [comment]
Remaining headers to fix:
`xASL_adm_DefineASLResolution`
`xASL_im_Smooth3D`
`xASL_im_dilateROI`
`xASL_qc_ComputeNiftiOrientation`
`xASL_wrp_DARTELSaveIntermedTrans`
`xASL_wrp_GSSaveIntermedTrans`

**Comment by jan-petr** [comment]
Remaining headers to fix:
`xASL_adm_DefineASLResolution`
`xASL_im_Smooth3D`
`xASL_im_dilateROI`
`xASL_qc_ComputeNiftiOrientation`

**Comment by jan-petr** [comment]
Remaining headers to fix:
`xASL_adm_DefineASLResolution`
`xASL_im_Smooth3D`
`xASL_im_dilateROI`

**Comment by jan-petr** [comment]
Remaining headers to fix:
xASL_im_Smooth3D
