### ISSUE TITLE
HotFix request - Consistent naming for MNI Structural atlas

### ISSUE THREAD

**Issue by MauricePasternak** [ExploreASL/ExploreASL#439]
Within xASL_module_Population.m , the variable x.S.Atlases is:

    {'TotalGM'                   }
    {'DeepWM'                    }
    {'MNI_Structural'            }
    {'Hammers'                   }
    {'HOcort_CONN'               }
    {'HOsub_CONN'                }
    {'Mindboggle_OASIS_DKT31_CMA'}

Meanwhile the atlas filename is MNI_structural.nii.gz

Not sure which one you want to settle on, but the difference is naming is preventing that atlas from being included in the analysis while running the Population module. For what it's worth, the published version of the GUI currently outputs `MNI_structural` when creating the DataPar file. If you settle on the titlecase convention, please let me know as well.

**Comment by MichaelStritt** [comment]
Did this occur in the v1.5.0 release version? Compiled or normal? We actually wanted to change both filename and variable name to **MNI_Structural**, to be consistent there. I did this in 0d816a43fbb7d4d330cc4c7e79ac942d437e727a.

**Comment by MichaelStritt** [comment]
Oh, I see the issue. I thought I definitely committed it, but it seems something went wrong when I renamed the files in [the folder](https://github.com/ExploreASL/ExploreASL/tree/main/External/SPMmodified/MapsAdded). That was a last minute change request shortly before the release...
@jan-petr: can we make a hotfix for this? We only need to rename `MNI_structural.jpg`, `MNI_structural.nii.gz`, `MNI_structural.nii.mat` & `MNI_structural.tsv` to `..._Structural`.

**Comment by jan-petr** [comment]
Yes. I remember. No worries, but we indeed better make a hotfix! @MichaelStritt - you'll take care of it?
Just branch from 'main' and commit the change and I'll quickly try to review it.

**Comment by jan-petr** [comment]
Do we need to recompile all?

**Comment by MichaelStritt** [comment]
> Do we need to recompile all?

I guess so :(

**Comment by jan-petr** [comment]
's not a big deal. Just that our Windows server is and will be totally down for a couple of days, so lets hope that the Mac will run.

**Comment by MichaelStritt** [comment]
I'll compile Linux and Windows. v1.5.0 was the first version with a compiled Mac version, so if it's there a few days later it shouldn't be that big of a problem.

**Comment by jan-petr** [comment]
ok.

**Comment by MichaelStritt** [comment]
By the way, I found my bug. My `git config --global core.ignorecase` was set to `true` on default!?!
Even after setting `git config --global core.ignorecase false` it didn't seem to work, so I used `git mv`.
