### ISSUE TITLE
Quantification at 7T

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#442]
Add all the necessary options and default values to make quantification at 7T possible:

- Set default T1blood for 7T, and also for 1.5T based on field strength (previously it was only for 3T at default). :+1: 
- Calculate T1blood based on Hct using B0 - previously default 3T was used for all. :+1:
- Create warnings when non-3T scanner is used and we don't have the non-3T defaults in the code - can create a lot of warnings, but it would have been wrong to use 3T without a warning. We might only check that some fields can be unused - so no need to warn on them. :+1:
- Tissue T1GM of 1240 has a wrong reference in DataParTemplate.md and is possibly incorrect for 1.5T, though this default is not used in the code - has to be updated for other B0 as well.

#### Release notes
Added default T1-time values for different field- strengths.

**Comment by HenkMutsaerts** [comment]
> * Calculate T1blood based on Hct using B0 - previously default 3T was used for all. 👍
I wonder if this is what we need. We should assume 3T and issue a warning when not 3T.
> * Create warnings when non-3T scanner is used and we don't have the non-3T defaults in the code - can create a lot of warnings, but it would have been wrong to use 3T without a warning. We might only check that some fields can be unused - so no need to warn on them. 👍
Also here, the warning should be when non-3T, not for the non-3T defaults.
> * Tissue T1GM of 1240 has a wrong reference in DataParTemplate.md and is possibly incorrect for 1.5T, though this default is not used in the code - has to be updated for other B0 as well.
With B0 you mean field strength here?
