### ISSUE TITLE
BIDS dataset_description defaults

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#443]
While doing BIDS import and creating of dataset_description.json, we need to make sure that all required fields are filled.

We need to:

1. Update xASL_bids_config that it contains the definitions according to https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html (Verified)
2. Prepare a function that checks the newly created `dataset_description.json`. This is now existing and called xASL_bids_CreateDatasetDescriptionTemplate (Done in #361)
3. Make sure that ExploreASL_ImportBIDS uses this function and doesn't fill in non-sense text. (Done in this issue).
4. Make sure that Flavors are updated accordingly (Not done, as they are anonymized, so random text is fine)
5. Update `xASL_bids_DRO2BIDS` accordingly (Done already)

### Release notes
Glue to #361 - Improve BIDS import.

**Comment by MichaelStritt** [comment]
### Note
Check out the following commit which seems related af8c4d4.

**Comment by jan-petr** [comment]
> ### Note
> Check out the following commit which seems related [af8c4d4](https://github.com/ExploreASL/ExploreASL/commit/af8c4d4e529ea87582f903e01b5ee1044799f919).

Yes - that commit prepared that function, and this issue implemented it for ExploreASL_ImportBIDS
