### ISSUE TITLE
Provide all atlas options in DataParTemplate

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#452]
List all atlas options in the DataParTemplate.m file and provide a bit of information about them

I have added the descriptions, but this needs to be checked and all my comments below about the current atlases answered - there are some doubts about the atlas integrity.

### Release note
Provided descriptions of available atlas options.

**Comment by jan-petr** [comment]
@HenkMutsaerts Why is total GM, total WM and Whole brain in the External/SPMmodified/MapsAdded completely identical?

**Comment by jan-petr** [comment]
@HenkMutsaerts And why we don't allow to include deepWM and Parenchym narrow?

**Comment by jan-petr** [comment]
LabelTerritories.nii is messed up

**Comment by HenkMutsaerts** [comment]
> @HenkMutsaerts Why is total GM, total WM and Whole brain in the External/SPMmodified/MapsAdded completely identical?

`xASL_stat_GetROIStatistics`  assumes that we process the GM, in which case we use the whole brain mask (inside totalGM) and mask/perform PVC with subject GM.

In the case WM or wholebrain is requested/detected, it does the same but replaces the individual GM for masking/PVC internally (line 570) by the subject-specific WM or subject-specific GM+WM. In all three cases, we don't use an ROI that is more specific than the subject-specific pGM/pWM, so we use totalGM/totalWM/whole-brain as dummy mask. 

Perhaps this coding can be improved, I just thought of something generalizable and this was the best I could come up with at the time :)

**Comment by HenkMutsaerts** [comment]
> LabelTerritories.nii is messed up, and its description needs to be added to the DataParTemplate.m

Why is it messed up? Should be per labeled vessel I believe

**Comment by HenkMutsaerts** [comment]
> @HenkMutsaerts And why we don't allow to include deepWM and Parenchym narrow?

How do you mean that we don't allow them? You can use them as "ROI" atlas, in the same way as MNI_Structural etc. Perhaps they are not added yet to the `x.S.Atlas` options that Michael created, is that what you mean?

`ParenchymNarrow` has a special function in the pipeline, seems that it is used in:
`xASL_adm_PreparePediatricTPM`
`xASL_wrp_RegisterASL`
`xASL_wrp_CreateBiasfield`

This mask usage could be cleaned up perhaps.

**Comment by jan-petr** [comment]
> > @HenkMutsaerts And why we don't allow to include deepWM and Parenchym narrow?
> 
> @jan-petr How do you mean that we don't allow them? You can use them as "ROI" atlas, in the same way as MNI_Structural etc. Perhaps they are not added yet to the `x.S.Atlas` options that Michael created, is that what you mean?
> 
> `ParenchymNarrow` has a special function in the pipeline, seems that it is used in:
> `xASL_adm_PreparePediatricTPM`
> `xASL_wrp_RegisterASL`
> `xASL_wrp_CreateBiasfield`
> 
> This mask usage could be cleaned up perhaps.

Yes - that's what I meant. So I have added TotalWM - this is thus answered for me.

**Comment by jan-petr** [comment]
> > LabelTerritories.nii is messed up, and its description needs to be added to the DataParTemplate.m
> 
> @jan-petr Why is it messed up? Should be per labeled vessel I believe

Sorry. That was my viewer. I have inspected it more carefully and with a different colormap and it is fine.

**Comment by jan-petr** [comment]
> > @HenkMutsaerts Why is total GM, total WM and Whole brain in the External/SPMmodified/MapsAdded completely identical?
> 
> @jan-petr `xASL_stat_GetROIStatistics` assumes that we process the GM, in which case we use the whole brain mask (inside totalGM) and mask/perform PVC with subject GM.
> 
> In the case WM or wholebrain is requested/detected, it does the same but replaces the individual GM for masking/PVC internally (line 570) by the subject-specific WM or subject-specific GM+WM. In all three cases, we don't use an ROI that is more specific than the subject-specific pGM/pWM, so we use totalGM/totalWM/whole-brain as dummy mask.
> 
> Perhaps this coding can be improved, I just thought of something generalizable and this was the best I could come up with at the time :)

OK. This makes sense :) We can perhaps improve this in the feature. But fine for now.
