### ISSUE TITLE
Reference testing values of xASL_qc_TestExploreASL 

### ISSUE THREAD

**Issue by MDijsselhof** [ExploreASL/ExploreASL#455]
Edit by Jan: In order to easily compare results of xASL_qc_TestExploreASL a reference result table should be added to the repository and automatically compared with the current results inside `xASL_qc_TestExploreASL` and a single value pass/no pass outputted at the end to allow a quick assessment if the results are equal (within 0.1%) tolerance to the previous run.

### Release note
Automatically compare results of TestDataSets with a saved reference results.

**Comment by HenkMutsaerts** [comment]
Nice, if you copy this from the Matlab command Window, it will automatically get a nice layout to facilitate readability.
Also, I would save this to a file as well, so you can subtract with the new values when testing, and get an overview of the relative changes (e.g. in percentages).

`xASL_qc_TestExploreASL` should be able to output these to a file.

Note also that it is good to add software versions that you used (short about computer, Windows/OS version, Matlab/MCR version, ExploreASL version).
