### ISSUE TITLE
Improving the header of xASL_adm_GetList

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#457]
Making clear the FPListRec option

### Release notes
Clarifying the information in header of xASL_adm_GetList

**Comment by BeatrizPadrela** [comment]
@HenkMutsaerts what do you think? :)

**Comment by MichaelStritt** [comment]
I think there was an issue with the commit/push, so there's nothing for Henk to review ;)

**Comment by BeatrizPadrela** [comment]
@HenkMutsaerts what do you think? :) I just add "it goes inside every subfolder of strDirectory." in line 20.
I commited it before without the number of the issue, that's why it didn't appear here and why you only see the change "it" in the code, which I added today when commiting again. Now it's solved! :D

**Comment by HenkMutsaerts** [comment]
@BeatrizPadrela Looks good! This issue would belong to the label documentation as well, I added this. You can create a pull request with the branch, for me to review!
