### ISSUE TITLE
 error in Compiling ExploreASL

### ISSUE THREAD

**Issue by sandeepganji** [ExploreASL/ExploreASL#46]
Compiling ExploreASL
{Error using <a href="matlab:matlab.internal.language.introspective.errorDocCallback('ExploreASL_make_standalone', '~\Development\ExploreASL_make_standalone\ExploreASL_make_standalone.m', 223)" style="font-weight:bold">ExploreASL_make_standalone</a> (<a href="matlab: opentoline('~\Development\ExploreASL_make_standalone\ExploreASL_make_standalone.m',223,0)">line 223</a>)
Error: The specified file <Modules\SubModule_Structural> was not found. If you wrapped the file name with double quotes, try replacing
the double quotes with single quotes and rerun the command.

**Comment by sandeepganji** [comment]
The issue is coming from the ExploreASL_make_standalone.m file. The paths for 'SubModule_Structural', 'SubModule_ASL', 'SubModule_Population', 'isnear','AtlasesNonCommercial' are not appended by the ExploreASLPath.

Adding that fixed the compilation error.

**Comment by HenkMutsaerts** [comment]
Great, in which version did you notice this? In the master version or (also) in the develop branch?
Also: please assign somebody to this issue, label it and put a milestone in (I now did this for you :)

**Comment by sandeepganji** [comment]
Found that in Release version 1.1.2.

**Comment by MichaelStritt** [comment]
I see the problem. Will fix it in a second. Wanted to merge my other branch anyway.

**Comment by HenkMutsaerts** [comment]
@MichaelStritt Can you put this in a separate branch, so we can merge this irrespective of your branch, let's keep things separated for overview ;)
