### ISSUE TITLE
Create an error when JSON has illegal format

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#466]
When the DataPat.json has an illegal format, it crashes Matlab instead of giving an error. For example inside the json, if we have "Quality"=1, instead of "Quality":1, Matlab crashes when running ExploreASL_Master.
So a good idea is to create an understandable error if the JSON has some problems, instead of just crashing the program.

**Comment by MichaelStritt** [comment]
You could write a simple `try-catch-statement` around `spm_jsonread` and then return the message:

```matlab
try
    spm_jsonread('your file');
catch ME
    fprintf('your message including this text %s', ME.message);
end
```

But where would you want to use this? Just as a user? Or as some kind of JSON validator?
I personally wouldn't label this as a **bug**, since there's actually nothing wrong with the code ;)

**Comment by jan-petr** [comment]
> But where would you want to use this? Just as a user? Or as some kind of JSON validator?
> I personally wouldn't label this as a **bug**, since there's actually nothing wrong with the code ;)

Not sure if this is going to help. As it is indeed not reporting an error that can be caught. Error would be fine... But it really creates a seg-fault and crashes the whole Matlab. So not a benign error that can be ignored or caught, but a big bug in the JSON reader.

**Comment by MichaelStritt** [comment]
Ah okay, sorry, I didn't get that from Beatriz explanation :)

**Comment by MichaelStritt** [comment]
People should use the GUI if the don't know how JSON works. We should add a JSON validator to the GUI?

**Comment by jan-petr** [comment]
I have submitted a new version that fixes the "=" in place of ":". But if a "," is there, then the program still crashes. People simply have to use valid JSONs :D

@MichaelStritt can you please compile the Windows version? It's without DCMTK, so easy - see the last line of mex/xasl_mex_compileAll... Thanks

**Comment by MichaelStritt** [comment]
### Compile

```
>> cd(fullfile(pathXASL,'External','SPMmodified','src'))
>> mex -O -largeArrayDims spm_jsonread.c jsmn.c -DJSMN_PARENT_LINKS
Building with 'Microsoft Visual C++ 2015 (C)'.
MEX completed successfully.
```

### Test


#### Correct JSON
```
>> json = spm_jsonread('M:\SoftwareDevelopment\MATLAB\m.stritt\Server_xASL\DataParameters.json');
>> json
json = 
  struct with fields:
    x: [1×1 struct]
```

#### Incorrect JSON
```
{
"x": [{
		"name": "ExampleDataSet",
		"subject_regexp": "^Sub-\\d{3}$",
		"Quality"= 0
	}]
}
```

For me Matlab still crashes. It really is invalid JSON though...
