### ISSUE TITLE
DRO (M0, Control & Label)

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#467]
Hey @jan-petr,

I think I made a small mistake in [this script](https://github.com/ExploreASL/ExploreASL/blob/develop/Functions/xASL_bids_DRO2BIDS.m). If I understand Aarons [documentation](https://asldro.readthedocs.io/en/stable/usage/series-asl.html) correctly, then the first dimension of the ASL NIFTI is the M0 scan, the second are the control and the third are the label scans.

Until now I just copy pasted the ground truth M0 and imported the 4D ASL NIFTI as a "normal" ASL.

```matlab
% Rename ASL
xASL_Move(fullfile(perfDirectory,'001_asl.json'),fullfile(perfDirectory,[droSubject,'_asl.json']));
xASL_Move(fullfile(perfDirectory,'001_asl.nii.gz'),fullfile(perfDirectory,[droSubject,'_asl.nii.gz']));
xASL_Move(fullfile(perfDirectory,'001_aslcontext.tsv'),fullfile(perfDirectory,[droSubject,'_aslcontext.tsv']));

% Add M0 from ground_truh
xASL_Move(fullfile(groundTruthDirectory,'002_ground_truth_m0.json'),fullfile(perfDirectory,[droSubject,'_m0scan.json']));
xASL_Move(fullfile(groundTruthDirectory,'002_ground_truth_m0.nii.gz'),fullfile(perfDirectory,[droSubject,'_m0scan.nii.gz']));
```

Do you know if I understood this correctly now or do we need to ask Aaron?

I guess I can just remove the M0 part, but how do I tell the import workflow about this M0/Control/Label structure?

**Comment by MichaelStritt** [comment]
Alternatively we can split the ASL NIFTI into a M0 and an ASL NIFTI, if that's better for ExploreASL.

**Comment by MichaelStritt** [comment]
@jan-petr: So as expected, there are some warnings because of the missing M0 file now. Besides that, the code should work as intended.

```
>> UnitTest = xASL_ut_UnitTest_function_BIDS2Legacy(TestRepository);
dataset_description.json is missing the following RECOMMENDED fields: 
HEDVersion, DatasetType, License
Warning: Missing: sub-Sub1_m0scan.nii.gz 
> In bids.layout>parse_perf (line 395)
  In bids.layout>parse_subject (line 198)
  In bids.layout (line 151)
  In xASL_bids_BIDS2Legacy (line 92)
  In xASL_ut_UnitTest_function_BIDS2Legacy (line 49) 
Warning: Missing: sub-Sub1_m0scan.json 
> In bids.layout>parse_perf (line 404)
  In bids.layout>parse_subject (line 198)
  In bids.layout (line 151)
  In xASL_bids_BIDS2Legacy (line 92)
  In xASL_ut_UnitTest_function_BIDS2Legacy (line 49) 
Converting from BIDS to Legacy: .\Testing\UnitTesting\working_directory\test_patie100%
Warning: Missing: .\UnitTesting\working_directory\test_patient\derivatives\ExploreASL\sub-Sub1\ASL_1\M0.nii 
> In xASL_bids_parseM0 (line 61)
  In xASL_bids_BIDS2Legacy (line 255)
  In xASL_ut_UnitTest_function_BIDS2Legacy (line 49) 
M0 parsed for .\UnitTesting\working_directory\test_patient\derivatives\ExploreASL\sub-Sub1\ASL_1\ASL4D.nii.gz
```

**Comment by MichaelStritt** [comment]
### Minor test

```
>> [x] = ExploreASL_Master(path, [0 0 0 1], 0);
```

![image](https://user-images.githubusercontent.com/46593074/116421170-e5b1b700-a83e-11eb-92cc-2017e672e22e.png)


![image](https://user-images.githubusercontent.com/46593074/116421609-4a6d1180-a83f-11eb-8837-f772b7bc81ea.png)


@jan-petr: Should `BIDS2Legacy` of `ExploreASL` split the `ASL` into separate `ASL4D` and `M0` scans, or is it correct like this? I probably still have to fix the `studyPar.json`.

**Comment by jan-petr** [comment]
> ### Minor test
> Run `BIDS2Legacy` on results of `xASL_bids_DRO2BIDS`:
> 
> ```
> >> [x] = ExploreASL_Master(path, [0 0 0 1], 0);
> ```
> 
> ![image](https://user-images.githubusercontent.com/46593074/116421170-e5b1b700-a83e-11eb-92cc-2017e672e22e.png)
> 
> ![image](https://user-images.githubusercontent.com/46593074/116421609-4a6d1180-a83f-11eb-8837-f772b7bc81ea.png)
> 
> @jan-petr: Should `BIDS2Legacy` of `ExploreASL` split the `ASL` into separate `ASL4D` and `M0` scans, or is it correct like this? I probably still have to fix the `studyPar.json`. Do I need to remove `M0Type` from the asl.json? Or do I just have to change it from `Separate` to something else? I only found `M0` but not `M0Type` in the BIDS specification.
> 
> Edit: This is kind of related to #474, right?

BIDS2Legacy does split ASL to ASL and M0 and saves ASL to ASL_Source. Using the same function like in ASL module. I found it a bit superfluous to call it in the BIDS2Legacy, but there it can take proper use of the ASL_context file.

So yes - it does the splitting. It is related to #474 - so the splitting happens correctly, but not for the parameters in JSONs, which is in 95% cases not a problem.
