### ISSUE TITLE
Splitting ASL split also JSONs

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#474]
The function xASL_io_SplitASL back-ups the ASL4D to ASL4D_Source and splits it to ASL and M0, also removing dummy scans from ASL.

The same logic has to be applied also to certain JSON fields of ASL4D that potentially also need to be split. 

The following fields need to be checked:
EchoTime, FlipAngle, RepetitionTimePreparation, PostLabelingDelay, VascularCrushingVENC, LabelingDuration

1. If these are a scalar, just copy the scalar. 
2. If these are a vector, they should always have the same length as the sequence (not having it is a major error in JSON) - we split them to ASL and M0 using the same indexes as done for the NIfTIes. 
3. Note that the fields don't have to be always present.If missing simply skip the field.

It would be good to load the list of fields to check from xASL_bids_Config() - like we did for dataset description. You can create a list called something like FieldsNumberArray - see if you can come up with some reasonable name that fits with the rest of the config file.

Note that for most datasets, we usually provide a scalar only. Still, this is a critical bug for the BIDS->Legacy for some datasets - like for example your DRO, without this, it will have incorrect TR for M0 and ASL and the quantification will be off.

**Comment by HenkMutsaerts** [comment]
@jan-petr Do you want to move this part to the import part from BIDS to legacy, to make it easier for the user to check? (now this is all called halfway the processing pipeline, which is less "transparent").

Also, these "source" or "backup" copies should be removed when we always enforce having `/rawdata` as well, as `/rawdata` will have the original NIfTIs, and the folder `/derivatives/ExploreASL` should have only derivatives :)
This saves disk space and is more "transparent" to the user. Shall we make this a new BIDS/import issue?
