### ISSUE TITLE
Study folder cannot have space in the name

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#475]
If the study folder has a space in the name, then ExploreASL crashes inside the CAT segmentation.

The reason is that cat_main.m at line 954 works with relative rather than absolute paths. Reading NIfTI with a relative path leads to calling a xASL_adm_UnzipNifti that on line 48 gets the current path and escapes special characters - which is fine when used for command-line calls, but not fine as internal Matlab functions won't work with these escaped filenames.

Solution:
1. Remove this Linux escaping as not necessary in xASL_adm_UnzipNifti 
2. Rework the cat_main part of code to work with absolute and not relative paths

I will do both 1 and 2 to avoid future errors, but either of those would be enough.

Or do you think that this could be problematic for other functions? @MichaelStritt @HenkMutsaerts 
I mean - step 2 is definitively helpful and should be done. Step 1 - it actually solves my case when tested on Linux, so I was a bit wondering why it is there in the first place when it was really counter-effective, but maybe you know of an example where this help and you can revert my changes in 1.

### Release notes
Fix error with studies that have a special character in their name.

**Comment by MichaelStritt** [comment]
> Or do you think that this could be problematic for other functions? @MichaelStritt @HenkMutsaerts
> I mean - step 2 is definitively helpful and should be done. Step 1 - it actually solves my case when tested on Linux, so I was a bit wondering why it is there in the first place when it was really counter-effective, but maybe you know of an example where this help and you can revert my changes in 1.

Hm... I don't have an example in mind right now... Neither do I know why the bug was there in the first place. I just tested with the TestDataSet with spaces in the directory name and got a nice error :/

```
ERROR: Job iteration terminated!
ans =
    'Error using xASL_SysMove (line 68)
     Error moving .\m.stritt\TestDataSet Name With Spaces\analysis\Sub-001\T1_temp.nii to .\m.stritt\TestDataSet Name With Spaces\analysis\Sub-001\T1.nii: Syntaxfehler.
     Error in xASL_Move (line 78)
     			xASL_SysMove(SrcPath, DstPath, bOverwrite);
```

**Comment by jan-petr** [comment]
> > Or do you think that this could be problematic for other functions? @MichaelStritt @HenkMutsaerts
> > I mean - step 2 is definitively helpful and should be done. Step 1 - it actually solves my case when tested on Linux, so I was a bit wondering why it is there in the first place when it was really counter-effective, but maybe you know of an example where this help and you can revert my changes in 1.
> 
> Hm... I don't have an example in mind right now... Neither do I know why the bug was there in the first place. I just tested with the TestDataSet with spaces in the directory name and got a nice error :/
> 
> ```
> ERROR: Job iteration terminated!
> ans =
>     'Error using xASL_SysMove (line 68)
>      Error moving .\m.stritt\TestDataSet Name With Spaces\analysis\Sub-001\T1_temp.nii to .\m.stritt\TestDataSet Name With Spaces\analysis\Sub-001\T1.nii: Syntaxfehler.
>      Error in xASL_Move (line 78)
>      			xASL_SysMove(SrcPath, DstPath, bOverwrite);
> ```

Ohoh - not good. Can you try to fix the Windows side of this problem? Once you're done, I'll try to run a full test with a similar dataset.

**Comment by jan-petr** [comment]
Tested on test-data-set on Linux and it was running from start to end without errors on Linux.

**Comment by HenkMutsaerts** [comment]
> 1. Remove this Linux escaping as not necessary in `xASL_adm_UnzipNifti`

@jan-petr My only worry is if it still behaves correctly in WSL. But if these paths only move through Matlab itself and are not needed, then you can probably delete it as you say.

**Comment by MichaelStritt** [comment]
Okay, so the problem seems to be that `SysMove` just can't handle paths with spaces on Windows. It only read the path to the first space and probably reads the remaining path as additional arguments.

```
SrcPath =
    'M:\SoftwareDevelopment\MATLAB\m.stritt\Test Data Set\analysis\Sub-001\ASL_1\mean_PWI_Clipped_temp.nii'
DstPath =
    'M:\SoftwareDevelopment\MATLAB\m.stritt\Test Data Set\analysis\Sub-001\ASL_1\mean_PWI_Clipped.nii'
bOverwrite =
     1
>> xASL_SysMove(SrcPath, DstPath, bOverwrite);
Error using xASL_SysMove (line 68)
Error moving M:\SoftwareDevelopment\MATLAB\m.stritt\Test Data Set\analysis\Sub-001\ASL_1\mean_PWI_Clipped_temp.nii 
          to M:\SoftwareDevelopment\MATLAB\m.stritt\Test
Data Set\analysis\Sub-001\ASL_1\mean_PWI_Clipped.nii: Syntaxfehler.
```

**Comment by MichaelStritt** [comment]
Sorry, I made a mistake in the last commit message and had to use force-push once.

There's actually a pretty easy fix on windows. I have to do something similar in a python script. If your path contains spaces you need `" "` around it.

### Initial test

```
>> source = 'M:\SoftwareDevelopment\MATLAB\m.stritt\Folder With Spaces\fileA.json';
>> dest = 'M:\SoftwareDevelopment\MATLAB\m.stritt\Folder With Spaces\fileB.json';
>> xASL_SysMove(source, dest, 1);
```

**Comment by MichaelStritt** [comment]
### TestDataSet on Windows

```
>> [x] = ExploreASL_Master('.\m.stritt\Test Data Set\analysis\DataParameters_LowQ.json', 1, 1);


--> Initializing ExploreASL v1.5.1...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  
==============================================================================================


ExploreASL initialized <--
Automatically defining sessions...
-------------------------------------------
ExploreASL will run with following settings:

Root folder = M:\SoftwareDevelopment\MATLAB\m.stritt\Test Data Set\analysis

1 scans - 0 exclusions, resulting in 1 scans of: 
Longitudinal timePoint 1 = 1 scans - 0 exclusions = 1 scans
ASL sessions: 1

Ancillary data, sets:
3 sets are defined for 1 "SubjectsSessions":
Set 1 = "LongitudinalTimePoint" options "TimePoint_1", codes for paired data
Set 2 = "SubjectNList" options "SubjectNList", codes for paired data
Set 3 = "Site" options "SingleSite", codes for two-sample data
x.DELETETEMP = 1 (delete temporary files)
x.Quality    = 0 (0 = fast try-out; 1 = normal high quality)

---------------------------------------------

...

Job-iteration 1 stopped at 13-Apr-2021 16:54:37 and took 165 seconds
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++100%
xASL_module_Population completed
Many thanks for using ExploreASL, please don't forget to cite https://pubmed.ncbi.nlm.nih.gov/32526385/
Note that ExploreASL is a collaborative effort.
Therefore, please don't hesitate to contribute by feedback, adding code snippets, or clinical experience!
```

No bugs here 👍
