### ISSUE TITLE
Restructure x fields

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#480]
Optimize x struct fields. Proposed fields:

- x.opts or x.settings: ExploreASL arguments and derivatives
- x.data: dataset specific fields
- x.vis: colormaps etc.
- x.tools: toolbox specific fields
- x.atlas: atlas specific fields
- x.study: study specific fields
- x.module.(structural/asl/population)
- ...

Add description for each field to documentation website

**Edit 28.05.2021**: The fields I started with are...

- x.opts (input arguments and their derivatives)
- x.dir (directories)
- x.settings (mostly booleans for pipeline settings and some other stuff)
- x.dataset (dataset related fields)
- x.tools (right now there's not much in there besides the spm version)

**Comment by MichaelStritt** [comment]
Since we want to release within the next two weeks, I'd move this to v1.7.0. Changes like these could lead to unexpected bugs within the pipeline.

**Comment by HenkMutsaerts** [comment]
> Optimize x struct fields. Proposed fields:
> 
> * x.opts or x.settings: ExploreASL arguments and derivatives
> * x.data: dataset specific fields
> * x.vis: colormaps etc.
> * x.tools: toolbox specific fields
> * x.atlas: atlas specific fields
> * x.study: study specific fields
> * x.module.(structural/asl/population)
> * ...
> 
> Add description for each field to documentation website
> 
> **Edit 28.05.2021**: The fields I started with are...
> 
> * x.opts (input arguments and their derivatives)
> * x.dir (directories)
> * x.settings (mostly booleans for pipeline settings and some other stuff)
> * x.dataset (dataset related fields)
> * x.tools (right now there's not much in there besides the spm version)

* Is `x.dir` the dataset-related folders (currently in `x.P`)? Or environment/ExploreASL-related folders (currently in `x.D`)?
* Should `x.tools` be `external`?
* What is the difference between `x.opts` and `x.settings`? Input arguments travel through the pipeline right?
