### ISSUE TITLE
ExploreASL_Initialize: Fix cross-platform indentation bug

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#494]
### Description

The indentation of the settings seems different regarding cross-platform use.

### Requirements

Make it look like this...

```
==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath			test
Import Modules			test
Process Modules			test
bPause				test
iWorker				test
nWorkers			test
==============================================================================================
```

... on every OS.

### How to test

Run ExploreASL_Initialize with different import settings on different OSs.

### Release notes

Fix cross-platform ExploreASL settings design.

**Comment by MichaelStritt** [comment]
### Test on Windows

```
>> [x] = ExploreASL_Master('M:\SoftwareDevelopment\MATLAB\m.stritt\TestDataSet\analysis\DataParameters_LowQ.json', [1 1 1 1], [1 1 1], 0, 1, 1);
ExploreASL will run the import workflow and will run the processing pipeline...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath        ...evelopment\MATLAB\m.stritt\TestDataSet\analysis\DataParameters_LowQ.json
Import Modules     DCM2NII NII2BIDS ANONYMIZE BIDS2LEGACY
Process Modules    Structural ASL Population
bPause             0
iWorker            1
nWorkers           1
==============================================================================================
```

**Comment by MichaelStritt** [comment]
### Test on virtual Ubuntu

```
>> [x] = ExploreASL_Master('/home/michael/Documents/TestSubFolder/TestDataSet/analysis/DataParameters_LowQ.json', [1 1 1 1], [1 1 1], 0, 1, 1);
ExploreASL will run the import workflow and will run the processing pipeline...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath        ...el/Documents/TestSubFolder/TestDataSet/analysis/DataParameters_LowQ.json
Import Modules     DCM2NII NII2BIDS ANONYMIZE BIDS2LEGACY
Process Modules    Structural ASL Population
bPause             0
iWorker            1
nWorkers           1
==============================================================================================
```

**Comment by MichaelStritt** [comment]
ExploreASL_Initialize, line 659:

```
fprintf('%s\n',[num2str(x.nTotalSubjects) ' scans - ' num2str(x.nExcluded) ' exclusions, resulting in ' num2str(x.nSubjects) ' scans of: ']);
```

You also wanted to change this @HenkMutsaerts ?

**Comment by MDijsselhof** [comment]
Regarding the problems with running all sessions of all scans, the input is 90 subjects each with 10 sessions, therefore a total of 90 scans. Output of the Population Stats folder for CBF values for each ROI is limited to 90 scans, in our case the result is only of subjects 1-9 sessions 1-10 instead of 1-90 sessions 1-10. The directory I'm working in to test this issue is /lood_storage/divi/Projects/ExploreASL/ABBA/NOMARED/derivatives/Test_vascular_territories/. This directory contains only one patient but also has as output of the population module stats only ASL_1 instead of all 10 sessions.

 the original command I run is: 

``ExploreASL_Master('DataPar_loc',[0 0 0 0], [0 0 1], 0, 1, 1)`` 

However, if I try to define the sessions in the DataPar.json, I get the following error when processing the ASL module (see first image):

![image](https://user-images.githubusercontent.com/75380250/114569773-8b78f980-9c75-11eb-9d33-00758d82807a.png)

In which I have used this DataPar.json (second image):

![image](https://user-images.githubusercontent.com/75380250/114569907-ad727c00-9c75-11eb-974b-6b620268e537.png)

**Comment by MDijsselhof** [comment]
A small comment, ExploreASL sees only 9 sessions when providing the DataPar as shown above, however if I modify the session line from 
``"SESSIONS": "{'ASL_1' 'ASL_2' 'ASL_3' 'ASL_4' 'ASL_5' 'ASL_6' 'ASL_7' 'ASL_8' 'ASL_9' 'ASL_10'}",``
to
``"SESSIONS": "{'ASL_1' 'ASL_2' 'ASL_3' 'ASL_4' 'ASL_5' 'ASL_6' 'ASL_7' 'ASL_8' 'ASL_9' 'ASL_10' }",``
It sees 10, not sure what happens there or what I'm doing wrong except for that space at the end.

**Comment by MichaelStritt** [comment]
Hm... the first bug seems to be related to the **population log file (diary)**. 
@HenkMutsaerts: we probably should open a separate issue for this, right?

**Comment by MichaelStritt** [comment]
> A small comment, ExploreASL sees only 9 sessions when providing the DataPar as shown above, however if I modify the session line from
> `"SESSIONS": "{'ASL_1' 'ASL_2' 'ASL_3' 'ASL_4' 'ASL_5' 'ASL_6' 'ASL_7' 'ASL_8' 'ASL_9' 'ASL_10'}",`
> to
> `"SESSIONS": "{'ASL_1' 'ASL_2' 'ASL_3' 'ASL_4' 'ASL_5' 'ASL_6' 'ASL_7' 'ASL_8' 'ASL_9' 'ASL_10' }",`
> It sees 10, not sure what happens there or what I'm doing wrong except for that space at the end.

I think correct JSON notation would be...
```
"SESSIONS": ["ASL_1", "ASL_2", "ASL_3", "ASL_4", "ASL_5", "ASL_6", "ASL_7", "ASL_8", "ASL_9", "ASL_10"]
```

... can you give this a try? Would be interesting to see what happens 👍

**Comment by MDijsselhof** [comment]
> > A small comment, ExploreASL sees only 9 sessions when providing the DataPar as shown above, however if I modify the session line from
> > `"SESSIONS": "{'ASL_1' 'ASL_2' 'ASL_3' 'ASL_4' 'ASL_5' 'ASL_6' 'ASL_7' 'ASL_8' 'ASL_9' 'ASL_10'}",`
> > to
> > `"SESSIONS": "{'ASL_1' 'ASL_2' 'ASL_3' 'ASL_4' 'ASL_5' 'ASL_6' 'ASL_7' 'ASL_8' 'ASL_9' 'ASL_10' }",`
> > It sees 10, not sure what happens there or what I'm doing wrong except for that space at the end.
> 
> I think correct JSON notation would be...
> 
> ```
> "SESSIONS": ["ASL_1", "ASL_2", "ASL_3", "ASL_4", "ASL_5", "ASL_6", "ASL_7", "ASL_8", "ASL_9", "ASL_10"]
> ```
> 
> ... can you give this a try? Would be interesting to see what happens 👍

No this gives an automatic error saying: 

``Dynamic parameter SESSINO contains unsupported value type: char!``

**Comment by MichaelStritt** [comment]
@jan-petr: We should use the correct notation for the subjeCts, too, right? Did this work before the #290 merge?

@MDijsselhof: Can you try to debug? 

I'm not sure if the session bug is linked to the diary one or not. I don't have a unit test for the individual modules right now, but we can create them based on the DRO dataset within the Testing repository.

**Comment by MDijsselhof** [comment]
Apologies, I didn't see the '' and used ', your suggestion :
``"SESSIONS": ["ASL_1", "ASL_2", "ASL_3", "ASL_4", "ASL_5", "ASL_6", "ASL_7", "ASL_8", "ASL_9", "ASL_10"]``
works Michael!

**Comment by MichaelStritt** [comment]
Perfect, but you stumbled upon a bug that we should definitely fix! The way you described the `"SESSIONS"` is still documented within the templates. I'll quickly change that 👍

**Comment by MDijsselhof** [comment]
It may be a lack of understanding on my side when to use ' or ", however when looking at the examples in DataParTemplate.m only ' is used, while DataParTemplate.json and all other study-specific modified DataPar.json's use ''. So maybe change that in DataParTemplate.m and update the tutorial?

**Comment by MichaelStritt** [comment]
You're totally right. It is confusing. Jan and I discussed getting rid of the `DataParTemplate.m`. We should stick to the `JSON` version and move all the useful comments and examples from the `DataParTemplate.m` to a nice markdown file, which will be integrated in the documentation website.

**Comment by MichaelStritt** [comment]
The other bugs are gone, too? Then @HenkMutsaerts could probably start to review.

**Comment by MDijsselhof** [comment]
Still working on the 'diary' and population module issue, but maybe its better to create a specific issue?

**Comment by MDijsselhof** [comment]
> You're totally right. It is confusing. Jan and I discussed getting rid of the `DataParTemplate.m`. We should stick to the `JSON` version and move all the useful comments and examples from the `DataParTemplate.m` to a nice markdown file, which will be integrated in the documentation website.

Is it possible to have text in jsons without reading this as variables and such? For example in Matlab you would use % before text.

**Comment by MichaelStritt** [comment]
> Still working on the 'diary' and population module issue, but maybe its better to create a specific issue?

I think so, can you create one?

> It may be a lack of understanding on my side when to use ' or " ...

Within `JSON` I always recommend using `"`. What helped me a lot was [this tutorial](https://www.w3schools.com/js/js_json_intro.asp). `JSON` comes from JavaScript and is almost part of the language there.

**Comment by MichaelStritt** [comment]
### JSON [Syntax](https://www.w3schools.com/js/js_json_syntax.asp)

![image](https://user-images.githubusercontent.com/46593074/114673909-fc1c2680-9d06-11eb-8c0b-6be19321052f.png)

**Comment by MichaelStritt** [comment]
> 
> 
> > You're totally right. It is confusing. Jan and I discussed getting rid of the `DataParTemplate.m`. We should stick to the `JSON` version and move all the useful comments and examples from the `DataParTemplate.m` to a nice markdown file, which will be integrated in the documentation website.
> 
> Is it possible to have text in jsons without reading this as variables and such? For example in Matlab you would use % before text.

Nope, there are no [comments](https://stackoverflow.com/questions/244777/can-comments-be-used-in-json) in `JSON`. It's not a programming text, so there's actually no need for it. We should do this within a separate file.

**Comment by MDijsselhof** [comment]
> ### JSON [Syntax](https://www.w3schools.com/js/js_json_syntax.asp)
> ![image](https://user-images.githubusercontent.com/46593074/114673909-fc1c2680-9d06-11eb-8c0b-6be19321052f.png)

Ah this makes it clear!

**Comment by MDijsselhof** [comment]
> > > You're totally right. It is confusing. Jan and I discussed getting rid of the `DataParTemplate.m`. We should stick to the `JSON` version and move all the useful comments and examples from the `DataParTemplate.m` to a nice markdown file, which will be integrated in the documentation website.
> > 
> > 
> > Is it possible to have text in jsons without reading this as variables and such? For example in Matlab you would use % before text.
> 
> Nope, there are no [comments](https://stackoverflow.com/questions/244777/can-comments-be-used-in-json) in `JSON`. It's not a programming text, so there's actually no need for it. We should do this within a separate file.

Okay thanks!

**Comment by MDijsselhof** [comment]
The 'diary' issue is gone, but the population module still only calculates ROI's for the amount of subjects instead of all subjects all sessions, so I'll create a new issue.
