### ISSUE TITLE
option to save as jpeg or png in-addition to PDF files for output

### ISSUE THREAD

**Issue by sandeepganji** [ExploreASL/ExploreASL#50]
This would allow for creating images that can then be converted to DICOM, which can be pushed to PACS/Scanner/other tools.

**Comment by HenkMutsaerts** [comment]
But this is already there, all the images in the PDF are compiled from JPG images. Check the subfolders of the Population folder

**Comment by HenkMutsaerts** [comment]
@sandeepganji Can I close this?
