### ISSUE TITLE
ASL Folder Naming - Import Module

### ISSUE THREAD

**Issue by amahroo** [ExploreASL/ExploreASL#504]
Hi, I'm trying to import ASL data. I have three folders:

1. ASL_con control images)
2. ASL_lab (label images)
3. ASL_diff (differenced images)

The nifti conversion works all right, but when I try to run BIDS conversion it throws an error and I think it is looking specifically for 'ASL4D.json' file and **not** for the name I used i.e, ASL_con.

I'm working with develop branch.

Error: 

Error using fileread (line 23)
Could not open file C:\Users\amahroo\Desktop\Fraunhofer_Mevis\TRABIT\Secondments\mediri\example_studies\single_PLD_study\analysis\Sub1\ASL_con_1\ASL4D.json. No such file or directory.

Error in ExploreASL_ImportBIDS>ExploreASL_ImportBIDS_NII2BIDS_Subject (line 1127)
            jsonDicom = spm_jsonread(fullfile(inSessionPath,[aslLabel '.json']));

Error in ExploreASL_ImportBIDS (line 320)
        ExploreASL_ImportBIDS_NII2BIDS_Subject(imPar,bidsPar,studyPar,listSubjects,iSubject);

**Comment by MichaelStritt** [comment]
Since we work with the encoded images now, I'd close this issue :)
