### ISSUE TITLE
Compilation error for ExploreASL 1.5.1

### ISSUE THREAD

**Issue by sandeepganji** [ExploreASL/ExploreASL#512]
Hi guys,

Getting the following error when compiling the ExploreASL v1.5.1 on Windows 10 using Matlab2020a.

Error message
`Error using xASL_adm_MakeStandalone (line 143)`
`filename is empty in push_back_into_extra_files at`
`b:\matlab\standalone\compiler\include\settingsinternalclasses.hpp(113).`
`Error in ExploreASL_compile (line 32)`
`    xASL_adm_MakeStandalone('F:\ExploreASL\v151_MCR');`

Code used for compiling
`cd F:\ExploreASL\v1.5.1;`
`ExploreASL_Initialize;`
`cd F:\ExploreASL\v1.5.1\Development\ExploreASL_make_standalone;`
`xASL_adm_MakeStandalone('F:\ExploreASL\v151_MCR');`

Suggestions?
-SG

**Comment by MichaelStritt** [comment]
I sometimes had the problem that it wouldn't compile properly without this dummy SPM compilation, but that should be on default as well... hm...
You probably searched for the error code as well, but there isn't that much to find...

I tried to reproduce the error using my Matlab 2019a on Windows:

Checking out main...
![image](https://user-images.githubusercontent.com/46593074/116508453-b4c69600-a8c1-11eb-9448-b4a503a5b95b.png)

Running the compilation script...
![image](https://user-images.githubusercontent.com/46593074/116508550-e93a5200-a8c1-11eb-8c89-32c16f0d4253.png)

... there are the usual change notification handle warnings, but other than that everything seems fine ...

![image](https://user-images.githubusercontent.com/46593074/116509119-0a4f7280-a8c3-11eb-9f72-0a7a28b21a4e.png)

Is it possible that there is a weird file within the search path of the compilation that does break the recursive search of Matlab? So maybe a similar bug like [this one](https://de.mathworks.com/matlabcentral/answers/115961-why-i-am-getting-error-in-compiling)? Do you want to try again with a freshly cloned repository?

**Comment by sandeepganji** [comment]
I tried with the freshly downloaded release. The xASL_latest_SPM_Dummy compiled properly.
Its the main ExplorerASL that is failing.

**Comment by MichaelStritt** [comment]
It seems like there's already a bug in the spm compilation. I don't get all these weird warnings about basic functions like `regress`, `histeq`, `nanmean` etc.

I didn't implement the dummy spm compilation, but I remember that @HenkMutsaerts added that part after he experienced some weird compilation issues on Mac os in 2019.

Did you read this part of the log file though?

```
"zeta" are excluded from packaging for the MATLAB Runtime 
environment according to the MATLAB Compiler license. 
Either remove the file or function from your code, or use the 
MATLAB function "isdeployed" to ensure the function is not 
invoked in the deployed component.
```

Is it possible that the newer compilers do not allow to compile certain functions that you were able to compile before? That would be pretty bad :(

**Comment by sandeepganji** [comment]
After commenting most/all of my `pathdef` paths, I got the ExplorerASL to compile.
It may be worthwhile to mention it somewhere.

**Comment by HenkMutsaerts** [comment]
> After commenting most/all of my `pathdef` paths, I got the ExplorerASL to compile.
> It may be worthwhile to mention it somewhere.

Can you show which paths these were? We can indeed remove them, which happens in `ExploreASL_Initialize`.
