### ISSUE TITLE
Skipping missing files in BIDS folder comparison

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#535]
When comparing BIDS folders, it does not report files/directories that are in Reference but missing in Source. I.e. if the BIDS conversion completely fails and doesn't write anything, it is not reported on screen.

**Comment by MichaelStritt** [comment]
### Initial test

![image](https://user-images.githubusercontent.com/46593074/116875829-d6a27e80-ac1b-11eb-89bb-7d6dccba14be.png)

### Results

```
>> [identical,results] = xASL_bids_CompareStructures(dir_A,dir_B,1,[],[],0);
Dataset:		patient_A
Missing:		\why_is_this_directory_not_in_a
Missing:		i_am_a_file_missing_in_a.json
Dataset:		patient_B
Missing:		\why_is_this_directory_not_in_b
Missing:		i_am_a_file_missing_in_b.json
File:			sourceStructure.json
			Missing field: I_Am_A_Field_Thats_Not_In_A
File:			studyPar.json
			Extra field: I_Am_A_Field_Thats_Not_In_B
```

**Comment by MichaelStritt** [comment]
@jan-petr: please tell me that that's not an os related issue :(

**Comment by jan-petr** [comment]
Sorry, not OS related :D We simply call it with wrong options from the testing script :D Will fix this.

**Comment by jan-petr** [comment]
> Sorry, not OS related :D We simply call it with wrong options from the testing script :D Will fix this in #514 so that we can properly test it there.

**Comment by jan-petr** [comment]
OK. Taking this back. The option for extra output was deactivated in #514, but that wasn't the problem.
See the weird output I'm getting:
![errorComparison](https://user-images.githubusercontent.com/29886537/116969486-a2c86700-acb6-11eb-9be3-70ce55bbcad6.png)

**Comment by jan-petr** [comment]
The correct screenshot :)
![errorComparison](https://user-images.githubusercontent.com/29886537/116969584-ce4b5180-acb6-11eb-8a67-45f5b500eff0.png)

**Comment by MichaelStritt** [comment]
Hm... okay, so you only get the warnings for the missing **source** but not for the missing **reference** files, right?

**Comment by jan-petr** [comment]
Yes, missing reference is not reported - I have noticed that when the entire rawdata wasn't created during import, it didn't report that. 
And as a second thing - it reports the source file as missing - while it should be missing/extra and not twice missing.

You can try at AMC, and I will try in the afternoon as well.

**Comment by MichaelStritt** [comment]
Working on it right now, will let you know 👍

**Comment by MichaelStritt** [comment]
Okay, I'm not sure if I found **the** bug, but I found **a** bug 👍 

This...
```matlab
    % Get files and folders of datasets A and B
    filesA = dir(fullfile(pathDatasetA, '**','*.*'));
    filesB = dir(fullfile(pathDatasetB, '**','*.*'));
```
... works really nicely on windows with Matlab 2019a.
I thought _they surely wouldn't change the "dir" behavior_, [but they did](https://www.mathworks.com/matlabcentral/answers/32038-can-you-use-dir-to-list-files-in-subfolders)...

And I know that I could have written everything using `xASL_adm_GetFileList.m` or something like that, but I wasn't that used to some of theses script at the point where I wrote this script.

**Comment by jan-petr** [comment]
> Okay, I'm not sure if I found **the** bug, but I found **a** bug 
> 
> This...
> 
> ```matlab
>     % Get files and folders of datasets A and B
>     filesA = dir(fullfile(pathDatasetA, '**','*.*'));
>     filesB = dir(fullfile(pathDatasetB, '**','*.*'));
> ```
> 
> ... works really nicely on windows with Matlab 2019a.
> I thought _they surely wouldn't change the "dir" behavior_, [but they did](https://www.mathworks.com/matlabcentral/answers/32038-can-you-use-dir-to-list-files-in-subfolders)...
> 
> And I know that I could have written everything using `xASL_adm_GetFileList.m` or something like that, but I wasn't that used to some of theses script at the point where I wrote this script.
> 
> Edit: Long story short: dir doesn't work recursively on Matlab 2016a, which is installed at AMC.

Let that be a lesson for you!! Just joking :) No worries, these things happen - great that you have found that so quickly. I will check and test it all.

**Comment by jan-petr** [comment]
I found the bug responsible for my error :)
xASL_bids_CompareStructures, line 104. I have called it on `rawdata`, so the results are equal for both source and reference - that is the thing likely causing my problem.

Is it possible to fix this, or is there some special reason to have this like it is.

**Comment by MichaelStritt** [comment]
> 
> 
> I found the bug responsible for my error :)
> xASL_bids_CompareStructures, line 104. I have called it on `rawdata`, so the results are equal for both source and reference - that is the thing likely causing my problem.
> 
> Is it possible to fix this, or is there some special reason to have this like it is.

Ahhh I get it, it doesn't work if both have the exact same name :)
I can add a check for that.
