### ISSUE TITLE
Rounding issue when saving JSONs

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#541]
`Siemens_PCASL_2DEPI_AD` - We are again facing this issue with incorrect rounding while writing SliceTiming. Is the problem also in Windows? Or is it a problem in the reference rather than the source?

### Release notes
Nothing. Failed to reproduce.

**Comment by MichaelStritt** [comment]
@jan-petr: I see what you mean. The thing is that we "remove" the zeros of the number, but if the last digit is not a zero, this won't work. That's some really weird rounding behavior. Do you know why we have `...000001` or `...000002` all the time?

![image](https://user-images.githubusercontent.com/46593074/124612887-fbf97600-de72-11eb-9467-b4977161c2c3.png)
