### ISSUE TITLE
ASL split handling of ASLcontext.tsv

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#542]
ASL4D_aslContext.tsv seems to be ignored during ASL splitting. This is fine as this information is duplicit and should also be present in the JSONs in the Legacy files. However, when the ASL4D is split and saved to ASL4D_Source, then the aslContext.tsv should also be renamed to _source as it matches to the original and not the split version anymore.

Also, for maximum clarity and transparency - after splitting, the field `"M0Type":"Included",` is correctly changed to 
`"M0Type":"Separate"` for ASL, however, it incorrectly stays `"M0Type":"Included",` for M0 where such field shouldn't be defined. Moreover, we have functions that check the format of all fields according to the BIDS format. It is true that this is the legacy format, but there is no reason, why we shouldn't make sure that the JSON is in perfect BIDS already.

1. Make sure that aslContext.tsv is renamed to _Source.
2. Make sure that on re-run, aslContext is taken from the _Source version.
3. Remove the field `M0Type` from the M0.json after splitting.
4. Call functions ` jsonM0Write = xASL_bids_VendorFieldCheck(jsonM0Write);` and `jsonM0Write = xASL_bids_JsonCheck(jsonM0Write,'M0');` before saving the split M0.json to check the fields.
5. Assign the correct IntendedFor field in M0.json referencing the ASL file - again, not need, but good to still BIDS compliant.

### Release note
Split ASL to ASL and M0 - archive aslContext.tsv and correct M0.json - to be merged with the similar issue for release notes.

**Comment by MichaelStritt** [comment]
@jan-petr: Would you do this there 5efafa2 ?

**Comment by jan-petr** [comment]
Yes - there. See _parms.mat - that should also be archived in a similar way and then deleted etc - so you want to copy a similar behavior. Except that you really only archive it from ASL4D_aslcontext.tsv to ASL4D_Source_asLcontext.tsv, but you don't make a copy to ASL4D, because you only want the original and won't need the copy...

**Comment by MichaelStritt** [comment]
Note for me / to do:

- Make sure that on re-run, aslContext is taken from the _Source version.

**Comment by MichaelStritt** [comment]
@jan-petr: Can you have another careful look and maybe test it again?
I tested the functionality using the `BIDS_fullBIDSPipeline` test and dataset `GE_PCASL_3Dspiral_Product_pharma`.
I revamped the script a bit, but I haven't tested the rerun thing though.
