### ISSUE TITLE
ExploreASL GUI in Python

### ISSUE THREAD

**Issue by MauricePasternak** [ExploreASL/ExploreASL#55]

**Comment by HenkMutsaerts** [comment]
## Short notes of our the ExploreASL_GUI kickoff meeting
>Present: Vera Keil, Maurice Pasternak, Michael Stritt, Jan Petr, Henk Mutsaerts

* Development stages:
    * A) Co-development (current stage)
    * B) developer testing (developers test non-compiled version)
    * C) user testing (e.g. Vera Keil tests compiled version)

* ToDo Henk
    * Allow choosing to run individual submodules (e.g. by adding 11, 12, 13, 14, etc for structural submodules to the current iModule option)
    * test "weights" for each submodule -> compute the percentage length for x.Quality=0 & x.Quality=1, by adding tic toc throughout & writing this to a script, after running the individual submodules
    * Create metadata parameter file (JSON), where each option should have childs:
        * data format (numerical/dropdown box (ordinal)/string/checkbox (Boolean)

* To be added:
    * Submodules
    * Lock file management
    * Progress visualization
    * Compilation
    * Multi-OS support

**Comment by MauricePasternak** [comment]
I believe it is time to launch this. I've tested it on my datasets and the TestDataSet that comes with ExploreASL (very glad it has FLAIR for last-minute troubleshooting).

In a recent and important update, it is independent from the MATLAB Engine API, making compilation a reality. At startup, the program calls out for matlabroot. If that variable is not present, the program will not start. You can verify this by trying the program on a machine lacking an activated MATLAB.

Of the to-do list, it should have: 

- Submodules
- Lock file management (it will be located under "Modify for Re-run" in the Executor)
- Progress visualization and error management (though the latter should be expanded for the sake of developers...because it's free of the Engine API, it cannot visualize pipeline print output until the process finishes through stdout. I will create a separate issue for how this can be elegantly addressed from your end.)
- Multi-OS support (so long as a call to the system produces the key words: Darwin, Linux, Windows).

Regarding compilation; I am able to freeze-compile it on Windows and package it into an installer. The installer ends up at 85MB and when unpacked, the "frozen" source code + binaries is 344 MB. I have not bothered to optimize imports, so we should be able to bring those numbers down if needed. The freeze-compiler (PyInstaller) must be run separately on each operating system to create system-specific binaries. The python code, however, is obviously agnostic to OS and will work on any OS so long as it has Python and the necessary libraries present (ex. PySide2, seaborn, numpy, etc.). 

I would consider this the dev version and I'm sure there will be suggestions for how to change it for the consumer version.
