### ISSUE TITLE
Add x.MakeNIfTI4DICOM option to DataParTemplate.m

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#559]
### Release Notes
Add x.MakeNIfTI4DICOM option to DataParTemplate.m; this creates a CBF copy that is optimized for DICOM creation/PACS export

### Was requested by @sandeepganji

I tested this by adding this parameter to the `DataPar` file of the testdataset and this works like a charm!

**Comment by sandeepganji** [comment]
Hi Henk, can you send me the *HiQ.json file for the test data?

**Comment by MichaelStritt** [comment]
> 
> 
> Hi Henk, can you send me the *HiQ.json file for the test data?

Sorry, probably a stupid addition, but you know how to change the [quality settings](https://exploreasl.github.io/Documentation/latest/Tutorials-QC/) in the JSON file, right?

**Comment by sandeepganji** [comment]
figured it out :)
