### ISSUE TITLE
Hadamard_Import&Decoding

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#567]
### Description

Decoding and subtraction adapted to Hadamard encoded data.

### Requirements
Issues to solve: 
1. Modify the import to have the new field for the sub-bolus duration, and a new field for Hadamard type (natural - default, or Walsh). #639 
2. Instead of subtracting control-Label, we want to calculate the perfusion-weighted image (PWI.nii), based on the decoding defined in the import. #640
3. Once we have the PWI, we'll need to script a new script to quantify multi-PLD quantification. #641

### Flow chart of what will change in the pipeline

![imagem](https://user-images.githubusercontent.com/73699072/127197856-9cb014ce-58ad-4c7b-95f1-9f2d209cdad6.png)

**Comment by HenkMutsaerts** [comment]
@BeatrizPadrela Are #640 and #641 duplicates?

**Comment by BeatrizPadrela** [comment]
> @BeatrizPadrela Are #640 and #641 duplicates?

No, the first one is for the subtraction and the second one is for the CBF quantification, that is done inside the ASL module (step 8 of xASL_module_ASL), where we have the xASL_wrp_Quantify function. And inside xASL_wrp_Quantify we have this part here for quantification (will add this info to #641):
![image](https://user-images.githubusercontent.com/73699072/124501963-d1e87b00-ddc2-11eb-89fe-ae92de541764.png)
