### ISSUE TITLE
FSL configuration optimization

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#569]
### Description

Some small changes to improve the FSL detection and execution:

1. The settings are `x.FSLdir` but `x.RootFSLDir` - easy to make a typo there - change to `Dir` or `dir` everywhere 👍🏼 
2. If we are below FSL version 6.0, issue a warning 👍🏼 
3. Change BASIL quantification `x.bUseBasilQuantification` to true in 1 TestDataSet case 👍🏼 
4. xASL_wrp_Quantify - line 78 add a warning for `x.bUseBasilQuantification` so that's clear that a `BASIL` `PWI4D.nii` 👍🏼 

By Henk: I removed the `RootFSLdir` comments, this should always be the same as `FSLdir` unless you use WSL.
By Henk: `PWI4D.nii`is only deleted at ASL module step 9: `xASL_wrp_VisualQC_ASL`
By Henk: `"bUseBasilQuantification": 1` is now added to `Philips_2DEPI_Lesion_NoFLAIR_NoM0_HiQ` & `Philips_3DGRASE_FLAIR_M0_2ndRun_HiQ`

### Release notes

* Minor fix in setting up FSL, issuing a warning when FSL version <6, and testing `bUseBasilQuantification` in both a 2D and 3D ASL dataset

**Comment by HenkMutsaerts** [comment]
Yes, though we need to know if this is HZDR or usecase-specific, or FSL version specific. I've only worked with `FSL 6.x` if I'm correct. Did you find this testing TopUp (previous usecase)?

**Comment by HenkMutsaerts** [comment]
* If we are below FSL version 6.0, issue a warning
