### ISSUE TITLE
Release v1.6.0 Testing

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#570]
### Release v1.6.0

Release issue to document testing and bug fixing. Check out the GitHub wiki workflow for the [drafting of a new release](https://github.com/ExploreASL/ExploreASL/wiki/Drafting-a-new-Release).

### Testing

Check out branch `release-v1.6.0-#570`. **Reminder**: Please make sure that your flavor library is up-to-date!

#### Run TestDataSets & UnitTesting

- linux: @MDijsselhof 👍
- windows: @jan-petr 
- macOS: @HenkMutsaerts 

#### Run full BIDS pipeline tests

- linux: @jan-petr 👍
- windows: @MichaelStritt  👍 
- macOS: @HenkMutsaerts 

### Additional testing

In addition to these tests it would be really helpful to test if all of the import functionality works. We started to write some predefined tests for that, but they don't take into account every possible option. Questions we should ask ourselves:

(1) Can I run the full pipeline (DCM->BIDS->Legacy & Processing) ( 👍 for Linux)
(2) Can I use a specific dataPar.json and run the import pipeline (DCM->BIDS->Legacy & Processing with specific dataPar.json) ( 👍 for Linux)
(3) Do all the atlases work?  ( 👍 for Linux)
(4) Does ExploreASL reinitialize correctly?  ( 👍 for Linux)
(5) Is it possible only to initialize ExploreASL? ( 👍 for Linux)
(6) Is it possible to only load a dataset? ( 👍 for Linux)

It's pretty tough to test all of that for every OS, so testing in the team could be helpful. In addition, we can see if everybody understood how to use the new import ;)

### Documentation

Document who will update the `VERSION_1.6.0` and the `CHANGES.md` file using the **release notes** of each individual issue.

- `CHANGES.md`: @jan-petr 👍
- `VERSION.md`: @MichaelStritt 
- `CHANGES.md`: @jan-petr - include all commits from #570

**Comment by MichaelStritt** [comment]
## full BIDS pipeline test (Windows)

- You can find the table here: [logContent.xlsx](https://github.com/ExploreASL/ExploreASL/files/6463767/logContent.xlsx)
- I tried to write out the most important warnings for each vendor below
- No errors 👍 

### GE

I only saw warnings related to the missing T1w scans, so they should be fine 👍 

### Philips

In addition to the warnings below, there were the warnings about missing T1w scans.

Philips_PCASL_2DEPI_Bsup_AD1: `Warning: Replacing the x-struct SliceReadoutTime`

Philips_PCASL_2DEPI_Bsup_AD2 & 4: `TE of ASL and M0 were unequal! Check geometric distortion`

Philips_PCASL_2DEPI_Bsup_AD4: `Overwriting x.Q.LabelingEfficiency=0.6889, with x.LabelingEfficiency=0.83`

Philips_PCASL_2DEPI_GBM: `Registration off, spatial CoV detection unreliable`

Philips_PCASL_2DEPI_PARREC: `WM T1 set to 900 ms for 3T`

Philips_PCASL_2DEPI_dummyMultiPLD: `Multiple PLDs detected, selecting maximal value`

Philips_PCASL_2DEPI_dummyQUASAR: `Multiple PLDs detected, selecting maximal value`

Philips_PCASL_2DEPI_pharma: `Warning: Replacing the x-struct SliceReadoutTime`

Philips_PCASL_2DEPI_pharma2: `TE of ASL and M0 were unequal! Check geometric distortion`

Philips_PCASL_2DEPI_volunteer3: `Registration off, spatial CoV detection unreliable`

Philips_PCASL_3DGRASE_R5.4_TopUp: `No TopUp found with same acquisition parameters as output image, skipping TopUp`

Philips_PCASL_3DGRASE_R5.4_TopUp: `TE of ASL and M0 were unequal! Check geometric distortion`

### Siemens

Siemens_PASL_2DEPI_ADNI2_B15_941_S_4764: `Inconsistent SliceTiming between slices`

Siemens_PASL_2DEPI_noBsup_AD: `Registration off, spatial CoV detection unreliable`

Siemens_PASL_3DGRASE_Prisma_Bsup_AD2: `WM T1 set to 900 ms for 3T`

Siemens_PASL_3DGRASE_Prisma_Bsup_AD3: `Matrix is close to singular or badly scaled. Results may be inaccurate`

Siemens_PASL_3DGRASE_Prisma_Bsup_AD3: `Matrix is singular to working precision`

Siemens_PASL_3DGRASE_Prisma_Bsup_AD3: `This image cannot be sorted, skipping`

### Evaluation

@jan-petr: Could you check if some of these are problematic?

**Comment by jan-petr** [comment]
Yes. These are all fine. Import wise :) We have to work on it a bit that all is set correctly and that they go through the pipeline without errors, but these are all data problems, not bugs in code. @MichaelStritt If the comparison to reference is fine (except rounding errors in 1 slice-timing), then you can tick this off. I'll run the flavors for Unix now.

**Comment by MichaelStritt** [comment]
I reran the comparison script 👍 

You will see this...

```matlab
File:	dataset_description.json
	Different value: BIDSVersion (1.6.0 vs 1.5.0)
Warning: Different file content: dataset_description.json    
> In xASL_bids_CompareStructures>printDifferencesAsWarnings (line 217)
```

... for every dataset, but that was to be expected 👍 

I found these ones right here...

```matlab
Dataset: Siemens_PASL_2DEPI_ADNI2_B15_941_S_4764
File:	\sub-Sub1\anat\sub-Sub1_FLAIR.json
	Different value: SliceTiming (check arrays)
	[0.0000, 81.3281, 122.6560, 0.1719, 81.4844, 122.8130, 0.3281, 81.6563, 122.9840, 0.4844 ...]
	[0.0000, 81.3281, 122.6560, 0.1719, 81.4844, 122.8120, 0.3281, 81.6562, 122.9840, 0.4844 ...]

Dataset: Siemens_PASL_2DEPI_ADNI2_B17_941_S_5193
File:	\sub-Sub1\anat\sub-Sub1_FLAIR.json
	Different value: SliceTiming (check arrays)
	[0.0000, 81.3203, 122.6480, 0.1641, 81.4844, 122.8130, 0.3203, 81.6484, 122.9770, 0.4844 ...]
	[0.0000, 81.3203, 122.6480, 0.1641, 81.4844, 122.8120, 0.3203, 81.6484, 122.9770, 0.4844 ...]

Dataset: Siemens_PCASL_2DEPI_AD
File:	\sub-Sub1\perf\sub-Sub1_asl.json
	Different value: SliceTiming (check arrays)
	[0.0000, 0.0300, 0.0600, 0.0875, 0.1175, 0.1475, 0.1775, 0.2075, 0.2350, 0.2650 ...]
	[0.0000, 0.0300, 0.0600, 0.0875, 0.1175, 0.1475, 0.1775, 0.2075, 0.2350, 0.2650 ...]

```

... but it seems like there is only a minor rounding difference?
I checked out the first two files and they seemed to be almost exactly the same.

**Comment by BeatrizPadrela** [comment]
### Additional testing

**1.  Using the FlavorDatabase/GE_PCASL_3Dspiral_volunteer, all the import's steps work:**
sourcedata->analysis folder [dcm2niix]
`[x]=ExploreASL_Master('/scratch/bestevespadrela/FlavorDatabase/GE_PCASL_3Dspiral_volunteer/sourceStructure.json',[1 0 0 0],0)`
analysis folder is deleted ->rawdata [nii2bids]
`...,[0 1 0 0],0)`
anonymize/deface
`...,[0 0 1 0],0)`
rawdata->derivatives with datapa.json
`...,[0 0 0 1,0)`
all steps work!

also ...,[1 1 1 1],1), performs the import module correctly and starts the processing pipeline with no errors!

**2. If we provide a DataPar.json in the same directory where the sourceStructure.json is,** 
just a simple datapar.json with an additional line, like "S":{"Atlases":["TotalGM","TotalWM","DeepWM","Hammers","HOcort_CONN","HOsub_CONN","Mindboggle_OASIS_DKT31_CMA"]}
we can see that ExploreASL is able to find it and when the derivatives folder is created, the DataPar.json is the same as the one we provided before (instead of the basic one that is automatically created).

3. Do all the atlases work?
(still running)

**Comment by jan-petr** [comment]
> Different value: BIDSVersion (1.6.0 vs 1.5.0)

I was just testing you if you do things properly :D I have updated the Flavors.

The other thing is just a rounding difference. Funny that I see it for a different dataset :)

Though note that the SliceTiming numbers for `Siemens_PASL_2DEPI_ADNI2_B17_941_S_5193` are totally off. They should be constantly rising and below 1s:
`[[0,0.0425,0.08499999999,0.1275,0.17,0.21249999999,0.2525,0.295,0.33749999999,`
The reference seems to be fine, so this looks like an error in the printing in the comparison script...

**Comment by jan-petr** [comment]
Perfect @BeatrizPadrela - you can tick these off in the main comment at the top (for Linux...). We can quickly try these under Windows, but we probably don't have to run the additional tests for MacOS, right?

**Comment by jan-petr** [comment]
@MichaelStritt `xASL_test_BIDSFlavorsFull(pathExploreASL, pathTest, [0 0 0 0 0 1 0], x);` Running processing on Flavors keeps asking me for path to DataParFile - that's weird right?

**Comment by MichaelStritt** [comment]
> @MichaelStritt `xASL_test_BIDSFlavorsFull(pathExploreASL, pathTest, [0 0 0 0 0 1 0], x);` Running processing on Flavors keeps asking me for path to DataParFile - that's weird right?

That's weird. Normally this should only happen, if ExploreASL does not find either sourceStructure or dataPar JSON.

**Comment by jan-petr** [comment]
Problem with case in filename in the testing script - fixed...

**Comment by MichaelStritt** [comment]
> The other thing is just a rounding difference. Funny that I see it for a different dataset :)
> 
> Though note that the SliceTiming numbers for `Siemens_PASL_2DEPI_ADNI2_B17_941_S_5193` are totally off. They should be constantly rising and below 1s:
> `[[0,0.0425,0.08499999999,0.1275,0.17,0.21249999999,0.2525,0.295,0.33749999999,`
> The reference seems to be fine, so this looks like an error in the printing in the comparison script...

I checked it manually. It seems like the sum of the differences of all these values comes up to `0.001`.
In 3d1362a I added a separate threshold which defaults to `0.01`. I didn't expect differences in this size.

**Comment by jan-petr** [comment]
OK. The difference is fixed, but why the comparison script prints:
`[0.0000, 81.3281, 122.6560, 0.1719, 81.4844, 122.8130, 0.3281, 81.6563, 122.9840, 0.4844 ...]`
when the real content is 
`[0,0.0425,0.08499999999,0.1275,0.17,0.21249999999,0.2525,0.295,0.33749999999,`?

**Comment by MichaelStritt** [comment]
@BeatrizPadrela told me about some issues with the manually defined dataPar.json in combination with the import workflow.

### My test

```
>> source = '.\Server_xASL\New_TestData\GE_PCASL_3Dspiral_volunteer\sourceStructure.json';
>> [x] = ExploreASL_Master(source, 1, 1, 0);
ExploreASL will run the import workflow and will run the processing pipeline...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath         ...rver_xASL\New_TestData\GE_PCASL_3Dspiral_volunteer\sourceStructure.json
Import Modules      DCM2NII NII2BIDS ANONYMIZE BIDS2LEGACY
Process Modules     Structural ASL Population
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.6.0 initialized ... 

Matching files:
    'Sub103\ASL'
    'Sub103\T1w'

#=2
Running import (i.e. dcm2niiX)
==============================================================================================
Importing subject=Sub103_1:   
>>> Subject=Sub103, visit=1, session=1, scan=ASL4D

...

Creating default dataPar.json since file was not found...
Overwriting x.DataParPath...
ExploreASL will run the processing pipeline...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath         ...estData\GE_PCASL_3Dspiral_volunteer\derivatives\ExploreASL\dataPar.json
Import Modules         
Process Modules     Structural ASL Population
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.6.0 initialized ... 
Automatically defining sessions...
==================================== Additional Settings =====================================
1 scans - 0 exclusions, resulting in 1 scans of: 
Longitudinal timePoint 1 = 1 scans - 0 exclusions = 1 scans
ASL sessions: 1

Ancillary data, sets: 3 sets are defined for 1 "SubjectsSessions"
Set 1 = "LongitudinalTimePoint" options "TimePoint_1", codes for paired data
Set 2 = "SubjectNList" options "SubjectNList", codes for paired data
Set 3 = "Site" options "SingleSite", codes for two-sample data
x.D.ROOT            M:\SoftwareDevelopment\MATLAB\m.stritt\Server_xASL\New_TestData\GE_PCA ...
                    ... SL_3Dspiral_volunteer\derivatives\ExploreASL
x.DELETETEMP        1 (delete temporary files)
x.Quality           0 (0 = fast try-out; 1 = normal high quality)

==============================================================================================
```

... debug point ...

```
111     if x.ProcessModules(1)==1
K>> x.S.Atlases
ans =
  7×1 cell array

    {'TotalGM'                   }
    {'TotalWM'                   }
    {'DeepWM'                    }
    {'Hammers'                   }
    {'HOcort_CONN'               }
    {'HOsub_CONN'                }
    {'Mindboggle_OASIS_DKT31_CMA'}
```
...

**Comment by MichaelStritt** [comment]
> 
> 
> OK. The difference is fixed, but why the comparison script prints:
> `[0.0000, 81.3281, 122.6560, 0.1719, 81.4844, 122.8130, 0.3281, 81.6563, 122.9840, 0.4844 ...]`
> when the real content is
> `[0,0.0425,0.08499999999,0.1275,0.17,0.21249999999,0.2525,0.295,0.33749999999,`?

I think those are the slice timings of the FLAIR JSON, not the ASL JSON.
![image](https://user-images.githubusercontent.com/46593074/117965916-9c279880-b323-11eb-940b-55393b983803.png)

**Comment by jan-petr** [comment]
> > OK. The difference is fixed, but why the comparison script prints:
> > `[0.0000, 81.3281, 122.6560, 0.1719, 81.4844, 122.8130, 0.3281, 81.6563, 122.9840, 0.4844 ...]`
> > when the real content is
> > `[0,0.0425,0.08499999999,0.1275,0.17,0.21249999999,0.2525,0.295,0.33749999999,`?
> 
> I think those are the slice timings of the FLAIR JSON, not the ASL JSON.
> ![image](https://user-images.githubusercontent.com/46593074/117965916-9c279880-b323-11eb-940b-55393b983803.png)

Aha :) That makes sense :) We're bug free then :)

**Comment by MichaelStritt** [comment]
@jan-petr & @HenkMutsaerts: We had a minor bug in `ExploreASL_Initialize`. We user to overwrite the sub-struct S from the import workflow. I think this commit b7f45de  shouldn't break anything.

**Comment by jan-petr** [comment]
> @jan-petr & @HenkMutsaerts: We had a minor bug in `ExploreASL_Initialize`. We used to overwrite the sub-struct S from the import workflow. I think this commit [b7f45de](https://github.com/ExploreASL/ExploreASL/commit/b7f45de2f9089eaf93129c5e475473d129770e44) shouldn't break anything.

Looks good.

**Comment by jan-petr** [comment]
TestDataSet is being processed on Windows, so I'll create the changes.md in the meantime...

**Comment by MichaelStritt** [comment]
Sadly the atlases still don't work on linux if you also run the import workflow. We're trying to find a fix right now.

**Comment by MichaelStritt** [comment]
### Re-Test

So I checked the bug from @BeatrizPadrela again, but for me everything seems to work on linux. I guess there's a bug in her JSON. I'll try to figure it out with her later, so we can make sure there are no bugs left.

I tested it with the version before commits cafc14f and b7f45de.

![image](https://user-images.githubusercontent.com/46593074/118018231-d448ce80-b357-11eb-9d00-455d201e76a8.png)

![image](https://user-images.githubusercontent.com/46593074/118018281-e0cd2700-b357-11eb-885f-390a1c6ca1c5.png)

Everything seems to be fine to me and the atlases are there:

![image](https://user-images.githubusercontent.com/46593074/118018480-225dd200-b358-11eb-9d2c-35045c58b36b.png)

![image](https://user-images.githubusercontent.com/46593074/118018435-107c2f00-b358-11eb-9256-0846d95c5cfa.png)

![image](https://user-images.githubusercontent.com/46593074/118018380-fe01f580-b357-11eb-8e8d-5f8fa50f1844.png)

**Comment by MDijsselhof** [comment]
Linux results (2016b):

![xASLv1_6](https://user-images.githubusercontent.com/75380250/118024168-a6b35380-b35e-11eb-8fa4-e08a16644db7.png)

**Comment by jan-petr** [comment]
Some errors in the processing of Flavors on Linux - not critical as these do not necessarily need to run all, but still needs to be checked:
Philips_PCASL_3DGRASE_functional
Siemens_PASL_3DGRASE_Prisma_Bsup_AD3
Siemens_PCASL_multiTI
Siemens_PCASL_volunteer

**Comment by jan-petr** [comment]
TestDataSets have some issues with ASL4D.mat reading - seems to be an issue with Windows, when Matlab is run over Citrix and Linux network disks. Will check if this can be solved, or if this combination is simply broken...

**Comment by MichaelStritt** [comment]
> TestDataSets have some issues with ASL4D.mat reading - seems to be an issue with Windows, when Matlab is run over Citrix and Linux network disks. Will check if this can be solved, or if this combination is simply broken...

Yeah... I really think we should use nifti, json & tsv whenever it's possible. Atleast they don't differ based on matlab or os version. But I understand that this probably doesn't help here :D

**Comment by jan-petr** [comment]
It is SPM and motion correction for SPM. They use .mat unfortunately...
Which is even more weird as it is really their code not working, not ours...

**Comment by MichaelStritt** [comment]
> It is SPM and motion correction for SPM. They use .mat unfortunately...
> Which is even more weird as it is really their code not working, not ours...

Do you want me to run the testdatasets on a normal windows server instead?
Or is this about linux server over citrix on windows?

**Comment by jan-petr** [comment]
It's Matlab running on a windows server through Citrix, executed from Windows with mounted linux disks :) So horribly slow and unstable. And very often it cannot access files that has just written to the disk. I will try to investigate this, you probably do not need to re-run it, because it works in most of the datasets without an issue...

**Comment by MichaelStritt** [comment]
Okay, just in case this is helpful: I had some issues with saving mat files for some project at university. Playing around with the mat file save options helped there (change the mat file version: -v7.3, -v6 or compressed vs. nocompression). But if it is access related, that is a whole other story.

**Comment by jan-petr** [comment]
> Linux results (2016b):
> 
> ![xASLv1_6](https://user-images.githubusercontent.com/75380250/118024168-a6b35380-b35e-11eb-8fa4-e08a16644db7.png)

Looks all good, same as in 1.5.0, I'm ticking that off. @MDijsselhof do you remember the issue with one of the Philips datasets - our solution was that the mean shouldn't be calculated right? So the empty value in mean is fine because that is after PVC?!

**Comment by jan-petr** [comment]
> Okay, just in case this is helpful: I had some issues with saving mat files for some project at university. Playing around with the mat file save options helped there (change the mat file version: -v7.3, -v6 or compressed vs. nocompression). But if it is access related, that is a whole other story.

Good idea. Thought the problem is really unstable - it works for certain datasets, but not for all. So it's not mat writing that is broken (I think), but the rights - but in a very very weird way...

**Comment by MDijsselhof** [comment]
> Linux results (2016b):
> 
> ![xASLv1_6](https://user-images.githubusercontent.com/75380250/118024168-a6b35380-b35e-11eb-8fa4-e08a16644db7.png)

Results from GetLogContent.m: 

![Screenshot from 2021-05-13 11-18-34](https://user-images.githubusercontent.com/75380250/118105716-09e3cb00-b3dd-11eb-971c-61cbe36748d6.png)

**Comment by MichaelStritt** [comment]
> 
> 
> > Okay, just in case this is helpful: I had some issues with saving mat files for some project at university. Playing around with the mat file save options helped there (change the mat file version: -v7.3, -v6 or compressed vs. nocompression). But if it is access related, that is a whole other story.
> 
> Good idea. Thought the problem is really unstable - it works for certain datasets, but not for all. So it's not mat writing that is broken (I think), but the rights - but in a very very weird way...

Hm... but do you think it's really problematic for the release if it's that specific?

**Comment by jan-petr** [comment]
Nono - not problematic in general. But very annoying for me personally :) The file seems to be really corrupt, so perhaps the writing is really wrong. But I would have to locate where this is saved, because the whole thing stops working only for some datasets, but works for most datasets at the same time.

**Comment by HenkMutsaerts** [comment]
> @jan-petr & @HenkMutsaerts: We had a minor bug in `ExploreASL_Initialize`. We used to overwrite the sub-struct S from the import workflow. I think this commit [b7f45de](https://github.com/ExploreASL/ExploreASL/commit/b7f45de2f9089eaf93129c5e475473d129770e44) shouldn't break anything.

Nice, yes would still be nice to standardize this somehow

**Comment by HenkMutsaerts** [comment]
> It's Matlab running on a windows server through Citrix, executed from Windows with mounted linux disks :) So horribly slow and unstable. And very often it cannot access files that has just written to the disk. I will try to investigate this, you probably do not need to re-run it, because it works in most of the datasets without an issue...

Not sure if we need to put time in this. The Citrix shouldn't matter, but the access issue is of course horribly annoying. This is why I wrote `xASL_adm_CheckPermissions`, you could try inserting this somewhere to see if it solves something, it should be working on different OSes.

**Comment by MichaelStritt** [comment]
> 
> 
> > @jan-petr & @HenkMutsaerts: We had a minor bug in `ExploreASL_Initialize`. We used to overwrite the sub-struct S from the import workflow. I think this commit [b7f45de](https://github.com/ExploreASL/ExploreASL/commit/b7f45de2f9089eaf93129c5e475473d129770e44) shouldn't break anything.
> 
> Nice, yes would still be nice to standardize this somehow

We reverted the commit yesterday @HenkMutsaerts. It was only a mistake in the JSON file.
