### ISSUE TITLE
Restructuring JSON importing for BIDS

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#572]
### Description

We need to restructure the functions for NII2BIDS import of JSON to make it easy to be called externally for the purpose of correcting JSONs for OASIS.

### Requirements

- For OASIS: Go through all directories and check all JSON files and modify them in the following way:
  - For structural files. Correct JSONs using the following: :+1: 
     - jsonAnat = xASL_bids_JsonBIDSifyAnat(jsonAnat); **Note this additional function now with different name** 
     - jsonAnat = xASL_bids_VendorFieldCheck(jsonAnat);
     - jsonAnat = xASL_bids_JsonCheck(jsonAnat,'');
  - For ASL files: :+1: 
     - Complete insides of xASL_imp_NII2BIDS_SubjectSessionRun have to be used, copy pasted to the OASIS script, and called for each session and filenames changed in the code - but only in the code, not in the subfunctions.

- To prepare for this
   - Fix issue #603 to have ExploreASL version used for import  :+1:
   - Put the RepetitionTime extra field check inside a new function xASL_bids_JsonBIDSify and add an 'anat' option there :+1: 
   - Put all the JSON checking and manipulation to a subfunction for ASL and M0 :+1: 
   - Make sure that the IntendedFor and other parameters are correctly assigned :+1: 
    
### How to test
- Run the Flavors import+check :+1: 
- Use this to correct OASIS data - continue in #619

### Release notes
Restructured JSON handling during NiFTI to BIDS import

**Comment by jan-petr** [comment]
Note that we had to resolve conflicts with the previous version, so we have recreated the branch and cherry-picked the commits. And then the commits had to be signed again - that's the reason for duplicit and unsigned commits appearing above. But the branch itself is fine.
