### ISSUE TITLE
CICERO requests

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#575]
### Description

* Create Flip function, that will flip a NIfTI left-right:
IN = 4V_ICA_L.nii (allow list)
OUT = 4V_ICA_L_flippedLeftRight.nii
Function = xASL_im_FlipNiftiLeftRight
Uses = xASL_im_Flip
* Allow custom ROIs (e.g. vascular territory 4V_ICA_L.nii) as ROI input to obtain CBF or sCoV, also function to allow combining regions (perhaps exists already?)

### Requirements

Optional: add feature requirements here

### How to test

Optional: add description about how to test here

### Release notes
#575 Simplification/revamp of some scripts that check image flips and report on them

**Comment by jan-petr** [comment]
@HenkMutsaerts Please check the whole branch - there are unnecessary merge commits that are not even signed.
