### ISSUE TITLE
Avoid ExploreASL searching in directories higher up

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#578]
### Description

When starting ExploreASL with a certain path, it will also start looking in paths above it for `/rawdata` folders or `dataPar.json`. This creates the danger of starting to import or process a dataset that was already done. See printscreen below.

### Requirements

ExploreASL should only go down, not up, for trying to find the correct folder.

### Release notes

Avoid ExploreASL searching in directories higher up than the specified folder.

**Comment by HenkMutsaerts** [comment]
See the screendump below, where ExploreASL doesn't only search within subfolders of `Tryout` (and may give a warning or error as it doesn't find the correct folder), it goes up!


### Printscreen
ExploreASL_Master('/Users/henk/ExploreASL/OSIPI_TF6.1/Tryout',[0 0 0 1]);
ExploreASL will run the import workflow and will run the initialization...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath         /Users/henk/ExploreASL/OSIPI_TF6.1/Tryout
Import Modules         BIDS2LEGACY
Process Modules       
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.6.0 initialized ... 
There is no dataPar.json file in the study root directory. Default settings will be used...
Warning: Missing:
/Users/henk/ExploreASL/OSIPI_TF6.1/Population_based/rawdata/sub-Dataset001/perf/sub-Dataset001_aslcontext.tsv 
> In bids.layout>parse_perf (line 340)
  In bids.layout>parse_subject (line 198)
  In bids.layout (line 151)
  In xASL_bids_BIDS2Legacy (line 98)
  In xASL_imp_BIDS2Legacy (line 46)
  In ExploreASL_ImportMaster (line 43)
  In ExploreASL_Master (line 74) 
Warning: M0Type field missing in sub-Dataset001_asl.json 
> In bids.layout>parse_perf (line 348)
  In bids.layout>parse_subject (line 198)
  In bids.layout (line 151)
  In xASL_bids_BIDS2Legacy (line 98)
  In xASL_imp_BIDS2Legacy (line 46)
  In ExploreASL_ImportMaster (line 43)
  In ExploreASL_Master (line 74) 
Converting from BIDS to Legacy: /Users/henk/ExploreASL/OSIPI_TF6.1/Population_bas100%
Warning: Field M0Type missing in
/Users/henk/ExploreASL/OSIPI_TF6.1/Population_based/derivatives/ExploreASL/sub-Dataset001/ASL_1/ASL4D.json 
> In xASL_bids_parseM0 (line 94)
  In xASL_bids_BIDS2Legacy (line 267)
  In xASL_imp_BIDS2Legacy (line 46)
  In ExploreASL_ImportMaster (line 43)
  In ExploreASL_Master (line 74) 
M0 parsed for /Users/henk/ExploreASL/OSIPI_TF6.1/Population_based/derivatives/ExploreASL/sub-Dataset001/ASL_1/ASL4D.nii.gz
Creating default dataPar.json since file was not found...
Overwriting x.DataParPath...
ExploreASL will load the dataset...

**Comment by jan-petr** [comment]
Fixing the bug also inside the ImportMaster - it checked if it is a file, but haven't verified if this is a file/folder - folders are also reported as file. Now it checks for file specifically.

I know that there's the just also above, but it is useful to have it on all layers to have perfect modularity.

**Comment by jan-petr** [comment]
Added a further commit so that it allows both the option of providing the dataset_description.json. But also the 1.6.0 option of dataPar.json.

Extremely important because the dataset_description.json might be nice for calling directly on BIDS input (that Henk correctly noted is missing). But the other option (dataPar.json) is also needed, because we had it in the complete workflow of DICOM->BIDS->Legacy and we shouldn't take it out. Or the direct BIDS option would break the DICOM option.

Now both are there and we should try to find a better solution in 1.7.0

**Comment by jan-petr** [comment]
I have tested the following combinations:

- `ExploreASL('/pet/projekte/asl/data/BIDS/TmpConversion/GE_PCASL_3Dspiral_WIP_volunteer/rawdata/dataset_description.json',[0 0 0 1],0)`

- `ExploreASL('/pet/projekte/asl/data/BIDS/TmpConversion/Siemens_PASL_2DEPI_noBsup_AD2/rawdata/dataset_description.json',[0 0 0 1],1)`

- `ExploreASL('/pet/projekte/asl/data/BIDS/TmpConversion/Siemens_PASL_2DEPI_noBsup_AD2/sourceStructure.json',[1 1 0 1],1)`

- `ExploreASL('/pet/projekte/asl/data/BIDS/TmpConversion/Siemens_PASL_2DEPI_noBsup_AD2/sourceStructure.json',[0 1 0 1],1)`

- `ExploreASL('/pet/projekte/asl/data/BIDS/TmpConversion/Siemens_PASL_2DEPI_noBsup_AD2/sourceStructure.json',[1 0 0 0],0)`
`ExploreASL('/pet/projekte/asl/data/BIDS/TmpConversion/Siemens_PASL_2DEPI_noBsup_AD2/sourceStructure.json',[0 1 0 1],1)`

- `ExploreASL('/pet/projekte/asl/data/BIDS/TmpConversion/Siemens_PASL_2DEPI_noBsup_AD2/sourceStructure.json',[1 0 0 0],0)`
`ExploreASL('/pet/projekte/asl/data/BIDS/TmpConversion/Siemens_PASL_2DEPI_noBsup_AD2/studyPar.json',[0 1 0 1],1)`

**Comment by jan-petr** [comment]
It should now all work, and I made an issue #583 for properly testing all this using an updated testing script.
