### ISSUE TITLE
Confusing warning for running ExploreASL('path', [0 0 0 1], 0)

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#579]
### Description

Incorrect warning `Data loading requested but no output structure defined`

### Requirements

This message should only be displayed when ExploreASL is run for loading data only, so e.g. `ExploreASL('path', 0, 0)`. Now I tested it e.g. with `ExploreASL('path', [0 0 0 1], 0)` and it gave this warning inappropriately (which is confusing to the user). Also for `ExploreASL` without arguments this should not be issued.

### Release notes

Confusing warning removed and isolated only for the case where running `ExploreASL('path', 0, 0)`.

**Comment by MichaelStritt** [comment]
We should check if this is fixed by #588

**Comment by HenkMutsaerts** [comment]
This seems fixed indeed.
