### ISSUE TITLE
Run TestFlavors using ExploreASL_Master

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#583]
### Description

We need to test the ExploreASL_Master that it is able to handle correctly all the different inputs from DICOM->BIDS->Legacy->Processing but only BIDS->Legacy->Processing. Currently, we call the subfunctions in testing, but we should call the Master script with different settings.

### How to test
All these combinations should work with different inputs:

- `ExploreASL('/pet/projekte/asl/data/BIDS/TmpConversion/Siemens_PASL_2DEPI_noBsup_AD2/sourceStructure.json',[1 1 0 0],0)`
`ExploreASL('/pet/projekte/asl/data/BIDS/TmpConversion/Siemens_PASL_2DEPI_noBsup_AD2/rawdata/dataset_description.json',[0 0 0 1],1)`

- `ExploreASL('/pet/projekte/asl/data/BIDS/TmpConversion/Siemens_PASL_2DEPI_noBsup_AD2/sourceStructure.json',[1 1 0 1],1)`

- `ExploreASL('/pet/projekte/asl/data/BIDS/TmpConversion/Siemens_PASL_2DEPI_noBsup_AD2/sourceStructure.json',[1 0 0 0],0)`
`ExploreASL('/pet/projekte/asl/data/BIDS/TmpConversion/Siemens_PASL_2DEPI_noBsup_AD2/sourceStructure.json',[0 1 0 1],1)`

- `ExploreASL('/pet/projekte/asl/data/BIDS/TmpConversion/Siemens_PASL_2DEPI_noBsup_AD2/sourceStructure.json',[1 0 0 0],0)`
`ExploreASL('/pet/projekte/asl/data/BIDS/TmpConversion/Siemens_PASL_2DEPI_noBsup_AD2/studyPar.json',[0 1 0 1],1)`

### Release notes

Required: Proper testing of flavors using ExploreASL_Master.

**Comment by MichaelStritt** [comment]
Maybe we should wait with this until we finished #588

**Comment by MichaelStritt** [comment]
Initial idea: d4df0ca

**Comment by MichaelStritt** [comment]
Full pipeline working example: [here](https://github.com/ExploreASL/ExploreASL/blob/feature-%23588_BIDS_DirectoryInput/Testing/xASL_test_IntegrationTesting.m)

**Comment by MichaelStritt** [comment]
The integration testing script basically works pretty well right now. The one thing missing right now is the setting: `defaultDataPar.x.bUseMNIasDummyStructural = 1;`
