### ISSUE TITLE
Assigning "weights" to .STATUS files

### ISSUE THREAD

**Issue by MauricePasternak** [ExploreASL/ExploreASL#59]
![ExploreASL_GUI_temp](https://user-images.githubusercontent.com/57411571/88448303-7835ad80-ce0a-11ea-81b0-cfb8d468cc4d.png)

I have implemented a "watcher" system that will allow the GUI to have insight into the progress during an ExploreASL run. It works even under parallel-processing conditions without any fear of window freezing. Verification through more complex combinations of study number and cores has yet to be confirmed. 

As discussed on July 23rd's meeting, for providing more accurate progress bar visual feedback to the user, we could implement a "weights" system for each status bar. 

To recap, idea is:

1) every .STATUS file will have associated with it some positive integer representation of the amount of processing power that went to complete said task. The integer value for a particular value is not as important as it's magnitude relative to other STATUS files. 

2) prior to MATLAB starting up, the GUI will interpret the expected number of STATUS files that should appear. The sum of the expected value for all STATUS files in all subjects/sessions will become the hidden maximum value of the progress bar. From there, it's simply a matter of incrementing the progressbar by whatever value a completed STATUS file is worth.

So my requests would be: if I could receive a list of all the STATUS filenames that may be generated. And for each file:
- it's weight
- the preferred description to appear in the text output window (see GUI screenshot), as currently only the file's basename is printed out
- and if it's not too much to ask...a brief description of what conditions could influence whether that STATUS file will appear or not, as this would greatly help with point #2 above.

**Comment by HenkMutsaerts** [comment]
Henk will insert tic-toc & make an overview

**Comment by HenkMutsaerts** [comment]
@MauricePasternak I assume we can close this issue, as I've edited the ExecutorTranslators directly in your #55?

**Comment by MauricePasternak** [comment]
Yep, I believe we are good on this end.
