### ISSUE TITLE
Remove the bClone2Source option in Import

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#602]
### Description

Do we still need `xASL_imp_DCM2NII_Subject_CopyTempDir`? Copying to a `source` directory does not seem to make sense anymore, but maybe I'm wrong. @HenkMutsaerts found this during the ABBA meeting. Can you help here @jan-petr ?

### Requirements

Remove the bClone2Source option and all related functions.

### How to test

Re-run Flavors

### Release notes

Remove option for cloning the NIfTI output after import as BIDS directory fulfills the function of a read-only archive.

**Comment by jan-petr** [comment]
I have checked that - I have created that function but I just copy pasted code that was there already. I do not think I was the one creating the original. It seems to be all related to the bClone2Source parameter that clones the NIfTIs after import. I think that the original function was to clone all after import as the analysis folder was then modified by processing and we wanted to have a clean copy right after import. This doesn't make any sense anymore as everything is stored in BIDS which acts as a read-only archive of freshly imported data by itself. 

So I propose to remove this bClone2Source option and all related functions. Any further comments to this @MichaelStritt @HenkMutsaerts ?

**Comment by MichaelStritt** [comment]
> This doesn't make any sense anymore as everything is stored in BIDS which acts as a read-only archive of freshly imported data by itself.

Agree. That's what Henk and I found out as well.

**Comment by jan-petr** [comment]
@MichaelStritt I have also renamed the import submodule 'Anonymize' to 'Deface'. Historically, we wanted to have both anonymization and defacing, but only defacing is implemented now. And any other anonymization really does not make much sense because private fields are removed already when going to BIDS.

I have tried to fix all the function names, messages, and comments. Any other idea what to fix? We should also port all these to the documentation - @MichaelStritt can you please do that?

**Comment by MichaelStritt** [comment]
> I have tried to fix all the function names, messages, and comments. Any other idea what to fix? We should also port all these to the documentation - @MichaelStritt can you please do that?

The documentation should mostly adapt automatically. We need to change a few lines in the tutorials, but that's not that much work and does not need to be done within the ExploreASL repository.

**Comment by jan-petr** [comment]
> > I have tried to fix all the function names, messages, and comments. Any other idea what to fix? We should also port all these to the documentation - @MichaelStritt can you please do that?
> 
> The documentation should mostly adapt automatically. We need to change a few lines in the tutorials, but that's not that much work and does not need to be done within the ExploreASL repository.

Yes - that's what I wanted to say :) The tutorial :) I have updated it myself now - simply using web-GUI and committing to master. I guess that there's nothing wrong with that approach, right @MichaelStritt ?

**Comment by MichaelStritt** [comment]
> 
> 
> > > I have tried to fix all the function names, messages, and comments. Any other idea what to fix? We should also port all these to the documentation - @MichaelStritt can you please do that?
> > 
> > 
> > The documentation should mostly adapt automatically. We need to change a few lines in the tutorials, but that's not that much work and does not need to be done within the ExploreASL repository.
> 
> Yes - that's what I wanted to say :) The tutorial :) I have updated it myself now - simply using web-GUI and committing to master. I guess that there's nothing wrong with that approach, right @MichaelStritt ?

Sure, as long as you don't run mike to deploy the github pages, that's totally fine.
