### ISSUE TITLE
Participants.tsv in BIDS format

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#611]
### Description

The current participants.tsv matches ASL and not BIDS format.

### Requirements

- The filename should start with minuscule `p` - this needs to be corrected everywhere - also in ExploreASL, not only in import. 
- Also, the subject notation must follow BIDS: [bids definition](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#participants-file)
- Change also the current notation to BIDS and make sure that the reading is also backwards compatible.
- What about `Participant_id` given and session not? Treat it like the same for all sessions?!

### Release notes

Adapt participants.tsv to BIDS format

**Comment by MichaelStritt** [comment]
> Change also the current notation to BIDS and make sure that the reading is also backwards compatible.

@jan-petr: Do you want PathTSV in `xASL_init_LoadMetadata.m` to read both version?

> What about Participant_id given and session not? Treat it like the same for all sessions?!

@jan-petr: What did you have in mind here? Would you do some sort of validation within the ExploreASL pipeline?
