### ISSUE TITLE
ASLCheck- and M0check-files missing session name

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#618]
### Description

Certain files in the ASLCheck and M0check directories have only subject name and not session name in their filename. 

### Requirements

This is true for all M0check files and only for a half of ASLcheck files. This can be easily fixed by copying what is done for the ASLcheck files to all of them. See the screenshots below to see this.

### How to test

Run on a single dataset to see that this is fixed.

### Release notes

Add session name to all M0Check and ASLCheck QC files in the Population folder.

**Comment by jan-petr** [comment]
![image](https://user-images.githubusercontent.com/29886537/120294199-42811100-c2c6-11eb-8414-15a2462ddc42.png)

![image](https://user-images.githubusercontent.com/29886537/120294269-52005a00-c2c6-11eb-8d55-f1c306286c3d.png)

**Comment by HenkMutsaerts** [comment]
Yes it looks like this should be consistent. Not sure if the `ASL_1` is omitted if there is only one session though, or if it is always missing in some examples?

**Comment by jan-petr** [comment]
See my fix - it is rather simple, but effective. It makes the filename longer, so we could go later for a more complex strategy...

**Comment by jan-petr** [comment]
Also - I made a small fix that the master script will work with `DataPar.json` and not only `DataPar.json` as this would be bad for many people to notice. And I have improved the warning that now explains this better.
