### ISSUE TITLE
Session warning in population module

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#625]
### Description

I ran a DRO dataset from rawdata (`[x_dro] = ExploreASL_Master(path_dro, [0 0 0 1], 1);`) and encountered these warnings in the population module:

![image](https://user-images.githubusercontent.com/46593074/120646389-c6c7c580-c479-11eb-8760-8f78223a1861.png)

### Requirements

Optional: add bug requirements here

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here

**Comment by HenkMutsaerts** [comment]
Can you put the DRO example data on the Flux server (or you can send it to me to as this is probably quite lightweight); then I can debug this.

**Comment by MichaelStritt** [comment]
### xASL_stat_PrintStats (line 184)

```matlab
Computing ROI data: 100%
Warning: Could not find session for sub-Sub1_ASL_1 
> In xASL_stat_PrintStats (line 184)
  In xASL_wrp_GetROIstatistics (line 139)
  In xASL_module_Population (line 231)
  In xASL_Iteration>runIteration (line 394)
  In xASL_Iteration (line 100)
  In ExploreASL_ProcessMaster (line 89)
  In ExploreASL_Master (line 105) 

Warning from xASL_stat_PrintStats (line 184)
                warning(['Could not find session for ' x.S.SUBJECTID{iSubjSess}]);

K>> SubjectExpression
SubjectExpression =
    'sub-.*(|_\d*)'

K>> x.S.SUBJECTID{iSubjSess}
ans =
    'sub-Sub1_ASL_1'

K>> [startIndex, endIndex] = regexp(x.S.SUBJECTID{iSubjSess}, SubjectExpression)
startIndex =
     1
endIndex =
    14

K>> SubjectID = x.S.SUBJECTID{iSubjSess}(startIndex:endIndex)
SubjectID =
    'sub-Sub1_ASL_1'

K>> SessionID = x.S.SUBJECTID{iSubjSess}(endIndex+1:end)
SessionID =
  1×0 empty char array

K>> x.S.SUBJECTID{iSubjSess}(endIndex:end)
ans =
    '1'
```

**Comment by MichaelStritt** [comment]
@HenkMutsaerts: It seems as if the index is just incorrect. 

Here ...
```
K>> SessionID = x.S.SUBJECTID{iSubjSess}(endIndex:end)
```

would work just fine in comparison to ...
```
K>> SessionID = x.S.SUBJECTID{iSubjSess}(endIndex+1:end)
```

... but I don't understand how this changed.

**Comment by jan-petr** [comment]
Be careful there - endIndex:end will work only for single digit session number - it would be cool to make it work for double digit, while we're at it ;)

**Comment by MichaelStritt** [comment]
> Will try to fix that - funny that it is like this - how could have that been working for other datasets?? Have anybody investigated when was this changed?

That's exactly what I was asking myself. I think it would be better not to constantly read text and interpret it using regular expressions. Maybe we can make it a bit easier by having something like a `currentSession` field within `x.dataset`.

**Comment by jan-petr** [comment]
Good point Michael. But it works with assembled input from GetRoiStatistics, so to keep modularity, lets not change that now....

Anyway, the root of the problem is not a minor change in indices, the root of the problem is not the code itself, but the fact that our automatic subjectExpression is now so general that it includes also the 'ASL_1' as subjectID and there's nothing left for sessionID :) I am making a fix that will address that robustly...

**Comment by jan-petr** [comment]
I have fixed the sessionID problem. 
It now breaks `x.S.SUBJECTID{iSubjSess}` == `sub-Sub0004_ASL_1` to `sub_Sub0004` and `ASL_1`.

However, it crashes a few lines below:
![image](https://user-images.githubusercontent.com/29886537/122022459-e5f21b80-cdc6-11eb-9f1a-f9d36cdb0fb2.png)

**Comment by jan-petr** [comment]
For Henk - this is a general problem. Not only for DRO. I have encountered it also for
ExploreASL('./BIDS/TmpConversion/Philips_PCASL_2DEPI_GBM',[1 1 0 1],1); from the flavors. After BIDS2Legacy, you can put quality to 0.

**Comment by HenkMutsaerts** [comment]
> > Will try to fix that - funny that it is like this - how could have that been working for other datasets?? Have anybody investigated when was this changed?
> 
> That's exactly what I was asking myself. I think it would be better not to constantly read text and interpret it using regular expressions. Maybe we can make it a bit easier by having something like a `currentSession` field within `x.dataset`.

We have `x.SESSIONS` defined already throughout the pipeline, this is done in `ExploreASL_Initialization`. The point is that in the population module you want to analyze whatever exists in the population folder, which can be different from what was processed before. This is why we run the regular expression. @MichaelStritt learn your regular expressions, they are very useful ;)

**Comment by MichaelStritt** [comment]
> The point is that in the population module you want to analyze whatever exists in the population folder, which can be different from what was processed before. 

Ah, okay. Not my usual use-case. You don't need to defend regular expressions every time. I do use them whenever I need to and everybody has their own coding style.
