### ISSUE TITLE
BIDS2Legacy incomplete information when crashing

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#627]
### Description

If a BIDS dataset is invalid, `BIDS2Legacy` may crash. However, the reason why it crashes - e.g., "`BackgroundSuppression` field is missing" - is catched and not shown to the user . It is helpful to the user to show the reason why this function crashed. Also, when this part crashes, it's useful to show a message if the BIDS validator was run.

### How to test

Remove a BIDS fiels and BIDS2Legacy should crash and show you why it crashed.

**Comment by MichaelStritt** [comment]
I need more information about the bug. If I remove the `BackgroundSuppression` field within the rawdata/perf asl.json, then `xASL_bids_BIDS2Legacy` does not crash. As far as I know, `xASL_bids_BIDS2Legacy` does not validate the JSONs again. The JSONs are mostly copied (`xASL_bids_BIDS2xASL_CopyFile`). The validation mostly happens in `xASL_imp_NII2BIDS_SubjectSessionRun` (`xASL_bids_BIDSifyASLJSON` etc.). 
We can add additional validation to `xASL_bids_BIDS2Legacy` though. Which `bids-matlab` functions do we have to use for that?
