### ISSUE TITLE
BIDS2Legacy incorrectly parses sessions/runs

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#628]
### Description

@BeatrizPadrela found out with converting `rawdata` to `derivatives` for the `AFIVASC` study, that sessions and runs were mixed up or even skipped.

### How to test

@BeatrizPadrela Can you please carefully compare the NIfTI or JSON content of `rawdata` with `derivatives`.

### Release notes

Fix parsing sessions and runs for converting `rawdata` to `derivatives`

**Comment by MichaelStritt** [comment]
Awesome. Maybe it could be helpful to generate a complex test dataset with multiple sessions/runs for the testing database.

**Comment by BeatrizPadrela** [comment]
> Awesome. Maybe it could be helpful to generate a complex test dataset with multiple sessions/runs for the testing database.

I'll try that with the whole AFIVASC rawdata
