### ISSUE TITLE
Population folder created within BIDS2Legacy

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#630]
### Description

The population folders is being created when I run ExploreASL('rootfolder', [0 0 0 1],0)

**Comment by MichaelStritt** [comment]
Does this really happen during bids2legacy or during the re-initialization? Because of it's the latter, then we have to fix this within the initialization script instead **or** move the data specific initialization scripts to the part after the import master.

**Comment by MichaelStritt** [comment]
consensus abba meeting: We should move the creation of the population folder from the data independent settings to the data dependent settings or we just do it at the start of the pipeline. It's definitely in the wrong place right now.
