### ISSUE TITLE
Hadamard decoding: json fields for Hadamard/multiTE & multiPLD

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#639]
### Description

Modify the import so we can have the proper fields for Hadamard

### Requirements

**Updated studyPar.json:**
![image](https://user-images.githubusercontent.com/73699072/127283163-023ca05e-92c1-4f40-98da-21c04832ab57.png)

**What we need:**

1. TimeEncodedMatrixSize = 4,8,or 12 -> if not Hadamard, is set to 0; 👍
2. TimeEncodedMatrixType: ‘Hadamard’ or ‘Walsh’ → A warning should be provided if a string is not provided. (the warning issue is already done inside Amnah's function) 👍

More:
"HadamardNumberTI" (number of TIs) can be calculated by Number ofPLDs-1 afterwards.
"HadamardNumberTE" is also calculated afterwards, recognizing the number of unique TEs. 👍

**Additional fields to add to the beginning of the ASL module:** 
MultiPLD= 1 or 0
MultiTE = 1 or 0

 **"PostLabelingDelay" and "LabelingDuration":**
As discussed with Jan and Amnah, for the PLD we will only need to provide one number (600 e.g.) - both in the studyPar and in the ASL.json - and one value for the LabelingDuration, which represents the sub-bolus duration in Hadamard (1000 e.g.) with the PLD and sub-bolus duration we can create a vector with all the TIs:
->PostLabelingDuration=600
->LabelingDuration=1000

### Where to apply these changes

Inside xASL_imp_ShuffleTheDinamics function:
![image](https://user-images.githubusercontent.com/73699072/124520278-33710f80-ddec-11eb-9730-d3c7abc07abd.png)

![image](https://user-images.githubusercontent.com/73699072/124929676-fcc01280-e000-11eb-9d16-398f1e39eb6a.png)

### Release notes

Required: summarize the changes for the release notes here

**Comment by HenkMutsaerts** [comment]
> > "HadamardMatrix" has to be a string, containing the word "Natural" or "Walsh". A warning should be provided if a string is not provided.

Are you sure? If I'm correct, the technique should be `TimeEncoded` instead of `Hadamard`, and `Natural` should be `Hadamard`. So then it would be `TimeEncodingMatrix` containing either `Hadamard` or `Walsh`
