### ISSUE TITLE
Hadamard decoding: calculate the new PWI.nii

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#640]
### Description

Instead of subtracting control-Label, we want to calculate the perfusion-weighted image (pwi.nii), based on the decoding defined in the import.

### Requirements

![image](https://user-images.githubusercontent.com/73699072/129699644-09c814af-8534-4161-82db-f9e678784395.png)

![image](https://user-images.githubusercontent.com/73699072/129699100-192ed669-911a-45ae-90d7-cd85d22b4f45.png)

Some changes that are needed in the ASL module:
(for multiPLD case, see more info in #759 )
- Registration  (ASL module - step 3) 
-> xASL_wrp_RegisterASL:
  -- Step H: There's this Pairwise subtraction that creates this PWI_Clipped image. Jan checked that this PWI_Clipped image is only used in this function and in the Realign [this Clipped_ORI can be deleted in the future because is not used anywhere else]. So, since in this function we want to obtain a single volume:
  
  + If Hadamard: skip this pairwise subtraction and run the decoding function instead, and then average all the PLDs
  + if multiTE: use only the first TE (will just write as a comment, since this function is only for multiPLD changes)
  
  And after this, the PWI_Clipped is going to work irrespectively how the Clipped was created (bRegistrationCBF loop in the step H)

- Resampling  (ASL module - step 4) 
->xASL_wrp_ResampleASL: After step6 (check header) we need to change some things
  -- Step6: We need to create PWI4D, so:
  + for Hadamard: there's a single control, so we use it (the first of the block)
  + for multiTE: discard all but the first TE (this has to be addressed later)
  -- Step8: pair-wise subtraction: (for multiPLD case, see more info in #759 )
  + for Hadamard: Paired subtraction is not done, we use the decoding function.
  + for multiTE: same as Hadamard, using the decoding function.
  + Hadamard & multiTE: we save them as PWI4D. But then for the PWI, we average across repetitions but not across TEs/PLDs.

**Comment by BeatrizPadrela** [comment]
Okay basically, this is the place where we'll have to apply the subtraction for Hadamard (which is inside xASL_module_ASL -> in line 325 we have the xASL_wrp_ResampleASL -> in line 134 we have  xASL_quant_GetControlLabelOrder -> and in line 40 inside this function we start defining the control label images
![image](https://user-images.githubusercontent.com/73699072/123066628-86bc8880-d410-11eb-8d03-4aed623a59df.png)

**Comment by MichaelStritt** [comment]
@BeatrizPadrela: I recommend that we create a new branch from develop and just move the edits from the three changed files there. This way you can test all of this with the actual new import form #639.

**Comment by HenkMutsaerts** [comment]
@BeatrizPadrela @MichaelStritt @jan-petr What happens if we have multi-TE data with normal PCASL? That is actually more common than with Hadamard. This should be general/modular.

**Comment by HenkMutsaerts** [comment]
@jan-petr Also, Hadamard has multiple controls right, not only the first volume?
