### ISSUE TITLE
Hadamard: script for CBF quantification with Hadamard data

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#641]
### Description

Once we have the new PWI image we'll need to script a new script for the quantification of Hadamard data.
Basic Hadamard will be fixed in #978, so we only need to add the multi-TE functionality.

### Requirements

Create a new script for quantification of Hadamard data.

CBF quantification is performed inside the ASL module (step 8 of xASL_module_ASL), where we have the xASL_wrp_Quantify function. And inside xASL_wrp_Quantify we have this part here for quantification:
![image](https://user-images.githubusercontent.com/73699072/124502042-f6dcee00-ddc2-11eb-899d-662c059ebe09.png)

The xASL_quant_singlePLD is being adapted to MultiPLD (#867) , and after that I can adapt it to Hadamard 

### Release notes

Duplicate issue

**Comment by MichaelStritt** [comment]
@BeatrizPadrela & @jan-petr: Is someone still working on this or are we going to skip this one too? Because right now it seems to me like Jan is eager to start release testing, but there are open issues where I have no clue if they can/should be moved or not.
