### ISSUE TITLE
Improve warnings (data loading)

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#656]
### Description

> @HenkMutsaerts:  if in Develop branch, I enter "ExploreASL([],0,0) it should initialize (same as "ExploreASL"). But if I enter "ExploreASL('pathtoRootDataSet',0,0), it doesn't issue a warning if the dataset is missing & cannot be loaded.

### Requirements

So for the steps:
1. Initialize (run always)
2. Import (skipped for 0)
3. Load dataset (run always if first input argument is not empty)
4. Process dataset (skipped for 0)
Then here in part 3, we need a warning if the folder is not a folder, or if the dataPar file is missing, right? It may just fprintf the warning instead of a full warning

### Release notes

Improve warnings (data loading)

**Comment by HenkMutsaerts** [comment]
@MichaelStritt looks good! I would just make this a bit more modular, i.e. `ExploreASL_Initialize` should only process the "data loading" part after the import module is called (or skipped) in `ExploreASL_Master`. Then `ExploreASL_Initialize` is nicely divided in separate parts, for the initialization only/import/loading. Now it is a bit all over the place (at least it looks to me ;)

**Comment by MichaelStritt** [comment]
> I would just make this a bit more modular, i.e. ExploreASL_Initialize should only process the "data loading" part after the import module is called (or skipped) in ExploreASL_Master.

@HenkMutsaerts: Yes, but let's do this like we planned recently. Let's move lines 194-255 to a separate script after the import workflow. Jan wanted to wait until after the release, since right now everything seems to be pretty stable. Do you agree?
