### ISSUE TITLE
Structural info is not being printed on pdf Report

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#661]
### Description

Even with the T1w.nii and .json files, the pdf report pdf only has the ASL images. All of the steps seem to be completed in all of the modules, so must be an issue in the printing part (?)

![image](https://user-images.githubusercontent.com/73699072/122559796-14c6f680-d040-11eb-90af-dc26f308139b.png)

![image](https://user-images.githubusercontent.com/73699072/122559743-04af1700-d040-11eb-8c7c-e32c4f69afd2.png)

### Release Notes

Fix bug related to #480

**Comment by jan-petr** [comment]
Funny - is that appearing equally for ASL_2 and ASL_1? Is that also happening in studies with ASL_1 only?

**Comment by BeatrizPadrela** [comment]
> Funny - is that appearing equally for ASL_2 and ASL_1? Is that also happening in studies with ASL_1 only?

Yes, the same is happening for ASl1, ASL2 and ASL3, but maybe because we have the same T1 for the 3 of them?
For only 1 ASL, we'll see. I just created a folder with that example and started running it for 1 ASL only. I'll let you know :)

**Comment by BeatrizPadrela** [comment]
> > Funny - is that appearing equally for ASL_2 and ASL_1? Is that also happening in studies with ASL_1 only?
> 
> Yes, the same is happening for ASl1, ASL2 and ASL3, but maybe because we have the same T1 for the 3 of them?
> For only 1 ASL, we'll see. I just created a folder with that example and started running it for 1 ASL only. I'll let you know :)

/home/bestevespadrela/lood_storage/divi/Projects/ExploreASL/ABBA/AFIVASC/TestWith_1sub_1ses_1run/
something must be wrong

**Comment by BeatrizPadrela** [comment]
> > Funny - is that appearing equally for ASL_2 and ASL_1? Is that also happening in studies with ASL_1 only?
> 
> Yes, the same is happening for ASl1, ASL2 and ASL3, but maybe because we have the same T1 for the 3 of them?
> For only 1 ASL, we'll see. I just created a folder with that example and started running it for 1 ASL only. I'll let you know :)

![image](https://user-images.githubusercontent.com/73699072/122669308-fe927500-d1bc-11eb-8236-f2c7b38cd238.png)
something is wrong..

**Comment by MichaelStritt** [comment]
Similar problem when testing a single session (just the test dataset):

![image](https://user-images.githubusercontent.com/46593074/122723240-01e83800-d273-11eb-87b6-d67af6c08164.png)

**Comment by MichaelStritt** [comment]
@BeatrizPadrela: Let's fix this. I created the branch `bug-#661_Report`.

The main printing happens in `xASL_qc_CreatePDF`.

In line 75 we have `fg = spm_figure('Create','Graphics','visible','off');`. By changing this to `fg = spm_figure('Create','Graphics','visible','on');`, it's a lot easier to debug this. Maybe we can simplify the code. I started to work on this within another branch a while ago, but I never really finished it.

**Comment by BeatrizPadrela** [comment]
> @BeatrizPadrela: Let's fix this. I created the branch `bug-#661_Report`.
> 
> The main printing happens in `xASL_qc_CreatePDF`.
> 
> In line 75 we have `fg = spm_figure('Create','Graphics','visible','off');`. By changing this to `fg = spm_figure('Create','Graphics','visible','on');`, it's a lot easier to debug this. Maybe we can simplify the code. I started to work on this within another branch a while ago, but I never really finished it.

Ok perfect. Thanks for spotting the error. Let's work on this

**Comment by MichaelStritt** [comment]
That's not really the error, but that's where we have to look for it ;)

**Comment by MichaelStritt** [comment]
@jan-petr: In line 186 and following we have:

```matlab
%% 2) Print second column with image fields
%  First synchronize the text fields & image fields
ImFieldNames = fieldnames(x.Output_im);
```

For `x.Output_im` I get:

```console
K>> x.Output_im
ans = 
  struct with fields:
    ASL: {1×32 cell}
```

Should there be an `x.Output_im.Structural` field as well or is it correct like this?

**Comment by MichaelStritt** [comment]
@BeatrizPadrela: If you want to help finding the bug/debugging, you can simply remove the last two lock files within the ASL lock file directory and put a debug point in `xASL_qc_CreatePDF`. This way you can test this really fast ;)

**Comment by jan-petr** [comment]
The weird thing is that it is printed for other datasets for me...

@MichaelStritt The thing you mention above, you try this directly on the dataset from Beatriz? I think that we indeed ought to have the Structural in Output_im. Have you tried remove the Structural lock file as well `xASL_module_Structural/100_VisualQC_Structural.status` ?

**Comment by jan-petr** [comment]
`xASL_wrp_VisualQC_Structural.m` and `xASL_vis_AddIM2QC.m` should be adding these fields.

**Comment by BeatrizPadrela** [comment]
By debugging the `xASL_qc_CreatePDF`, I can tell that the problem here is (even before line 186) in line 93, where the outputFields only have ASL, because` OutputFields = fieldnames(x.Output);` and both `x.Output` and `x.Output_im` have only 1 field, the ASL field, like you said. We have to check the structural lock files as Jan mentioned. I'll try

**Comment by MichaelStritt** [comment]
> @MichaelStritt The thing you mention above, you try this directly on the dataset from Beatriz? 

I used the regular test dataset from ExploreASL

**Comment by MichaelStritt** [comment]
Maybe we can have a meeting tomorrow and find out the bug in your dataset @BeatrizPadrela?

**Comment by BeatrizPadrela** [comment]
> Maybe we can have a meeting tomorrow and find out the bug in your dataset @BeatrizPadrela?

Yes, let's do that!

**Comment by MichaelStritt** [comment]
Interesting... So I was processing Beatriz' AFIVASC dataset on the AMC server. I deleted derivatives completely and reprocessed it from rawdata. I encountered this warning:

```console
Cleaning up QC_Collection json: 100%
Warning: Detected deprecated fields in x.mat. Older version of ExploreASL was used to process this 
data previously. Field names fixed
> In xASL_adm_LoadX (line 82)
> In xASL_module_ASL (line 169)
...
Saving PWI & CBF niftis
print visual quality assurance checks
Warning: Detected deprecated fields in x.mat. Older version of ExploreASL was used to process this 
data previously. Field names fixed
> In xASL_adm_LoadX (line 82)
> In xASL_wrp_VisualQC_ASL (line 49)
...
Coverage of 95.2617
Collecting QC parameters...
Printing ExploreASL PDF report:
Warning: Detected deprecated fields in x.mat. Older version of ExploreASL was used to process this 
data previously. Field names fixed
> In xASL_adm_LoadX (line 82)
> In xASL_qc_CreatePDF (line 57)
...
```

That shouldn't happen if we process it with an up-to-date version. Seems like we save a parameter according to the old x struct format and load it and fix it? Needs some more debugging.
And I encounter the same problem, that the `x.Output.Structural` field is missing.

**Comment by MichaelStritt** [comment]
Hm... funny... if I remove the last two lock files of the structural module and do a rerun, I get the correct report. It seems like this step is just skipped our the `x.Output.Structural` field is removed during the normal (not rerun) execution.

![image](https://user-images.githubusercontent.com/46593074/122897585-6c1fdc00-d34a-11eb-85d0-e3d998c0d8f3.png)

**Comment by MichaelStritt** [comment]
@jan-petr: Maybe this is also related to the storing of x in the `x.mat` file? Because `xASL_qc_CreatePDF` reads it from the mat file?

I'm going to try another run (clean run, no rerun) and check what's going wrong in `xASL_wrp_VisualQC_Structural`.

**Comment by MichaelStritt** [comment]
Okay, so there is no `x.mat` within `sub-002` and the existing `x` does not have output fields.

![image](https://user-images.githubusercontent.com/46593074/122900990-6bd51000-d34d-11eb-8dad-2757a482fc32.png)

**Comment by MichaelStritt** [comment]
So for a clean run, we have the correct fields at the end of the script:

![image](https://user-images.githubusercontent.com/46593074/122906368-5f06eb00-d352-11eb-8db8-8736c31d15c5.png)

**Comment by MichaelStritt** [comment]
The PDF seems to be fine as well. Maybe we just overwrite that somewhere later on.

![image](https://user-images.githubusercontent.com/46593074/122906605-a1302c80-d352-11eb-8d98-5a2a4726ecef.png)

**Comment by MichaelStritt** [comment]
Okay, so somewhere in between we definitely overwrite `x.Output`

![image](https://user-images.githubusercontent.com/46593074/122907706-b3f73100-d353-11eb-9b84-7f20fe65e70f.png)
