### ISSUE TITLE
Print stats is not printing info for different runs

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#662]
### Description

The stats are not being printed for the runs, only for the subs/sessions.
The image below is from the test folder "lood_storage/divi/Projects/ExploreASL/ABBA/AFIVASC/TestWith_sub-002_2ses_6runs/" composed of 1 sub, and 2 sessions with 6 runs each.

![image](https://user-images.githubusercontent.com/73699072/122562197-180fb180-d043-11eb-8535-dfde9aa75846.png)

**Comment by HenkMutsaerts** [comment]
Like @MDijsselhof said, does this concern the structural derivatives only (e.g. volumetrics and ratio)? Then this makes sense, as each subject/session has a single T1w right? If this otherwise is correct for ASL, then this should be fine.

**Comment by jan-petr** [comment]
Yes, I agree. It is totally fine that T1w is printed only for ASL_1, as the same T1w is used for ASL_2, so it doesn't make sense to print the same statistics. But a question is - shall we a) leave it like that, shall we print a copy of the T1w results also for ASL_2-6, c) shall we suppress the printing of this for ASL_2-6 so that there's not so many empty lines?

Either way, I am moving this to 1.8.0.

**Comment by HenkMutsaerts** [comment]
Note that nomenclature and structure of such longitudinal/multiple runs will change a bit with BIDS in the future, so I wouldn't focus on this too fast

**Comment by jan-petr** [comment]
> Note that nomenclature and structure of such longitudinal/multiple runs will change a bit with BIDS in the future, so I wouldn't focus on this too fast

OK. If you say that it's not that important, then I am moving this back again to 1.8.0 :D

**Comment by BeatrizPadrela** [comment]
> > Note that nomenclature and structure of such longitudinal/multiple runs will change a bit with BIDS in the future, so I wouldn't focus on this too fast
> 
> OK. If you say that it's not that important, then I am moving this back again to 1.8.0 :D

Ok agree :) if we have the information we need, then there's no real problem

**Comment by jan-petr** [comment]
Beatriz notes this problem into the documentation and then closes the issue.

**Comment by MichaelStritt** [comment]
Maybe in combination with #481 we can improve the documentation regarding the atlases.

**Comment by MDijsselhof** [comment]
I've created an issue before #577  with a better description. I'm making this a duplicate!
