### ISSUE TITLE
Initialization should issue a warning if there are multiple dataPar*.json

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#666]
### Description

Initialization should issue a warning if there are multiple dataPar*.json in `/derivatives/ExploreASL`, and print which one it is using.
Or should it only issue the warning and request to move the other dataPar file out?

### Testing
/External/TestDataSet has this, when you skip the import and run the processing only.

### Release
Issue a warning when multiple dataPar*.json or studyPar*.json or sourcestructure*.json are present.

**Comment by jan-petr** [comment]
> ### Description
> Initialization should issue a warning if there are multiple dataPar*.json in `/derivatives/ExploreASL`, and print which one it is using.
> Or should it only issue the warning and request to move the other dataPar file out?
> 
> ### Testing
> /External/TestDataSet has this, when you skip the import and run the processing only.
