### ISSUE TITLE
bReproTesting is being added to main level of x

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#676]
### Description

Somewhere in the code, the field `bReproTesting` is added to the main level of the x struct. It should be part of `x.settings` though.

We encountered these warnings:

```console
Cleaning up QC_Collection json: 100%
Warning: Detected deprecated fields in x.mat. Older version of ExploreASL was used to process this 
data previously. Field names fixed
> In xASL_adm_LoadX (line 82)
> In xASL_module_ASL (line 169)
...
Saving PWI & CBF niftis
print visual quality assurance checks
Warning: Detected deprecated fields in x.mat. Older version of ExploreASL was used to process this 
data previously. Field names fixed
> In xASL_adm_LoadX (line 82)
> In xASL_wrp_VisualQC_ASL (line 49)
...
Coverage of 95.2617
Collecting QC parameters...
Printing ExploreASL PDF report:
Warning: Detected deprecated fields in x.mat. Older version of ExploreASL was used to process this 
data previously. Field names fixed
> In xASL_adm_LoadX (line 82)
> In xASL_qc_CreatePDF (line 57)
...
```

The field `bReproTesting` is part of these scripts:

* `xASL_module_Population`
* `xASL_wrp_LST_Segment_FLAIR_WMH`
* `xASL_init_DefineDataDependentSettings`
* `xASL_adm_LoadX`
* `xASL_adm_CompareDataSets`

There everything seems fine though. I believe we add the field somewhere using a `x.(fieldname)` construct, but it's hard to find something like this with text search.

### Requirements

n/a

### How to test

I encountered this error while running an afivasc dataset, but it probably happens every time.

### Release notes

Stop script from adding bReproTesting to main level of x struct.

**Comment by jan-petr** [comment]
True - can't see any x.bReproTesting, but I can't find any 'x.(' either. Will investigate, which dataset this happens in - all?

**Comment by MichaelStritt** [comment]
Hey @jan-petr, I just reran the `ABBA/AFIVASC/TestWith_1sub_1ses_1run` at AMC. The warning (`Detected deprecated fields in x.mat`) is still there. I'm trying to find out where it's coming from, but I could probably need some help.

**Comment by MichaelStritt** [comment]
Found it... needed a lot of manual step-by-step debugging. It happens in `xASL_module_ASL` line 200 within `xASL_adm_LoadParms`.

**Comment by MichaelStritt** [comment]
Check out a73e680601f86d8b1b8e44cccbfa2be3ff81b964 . I accidentally used the wrong issue number. We can fix that if necessary.
