### ISSUE TITLE
xASL_fsl_TopUp: Minor error

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#692]
### Description

xASL_fsl_TopUp reused a temporary variable which shouldn't have caused errors but it stopped the TopUp processing.

### Release notes

Required: summarize the changes for the release notes here

**Comment by jan-petr** [comment]
Your fix have probably solved the issue, but the real error was on line 206, where you were adding to a variable that might have been initialized differently. I have fixed that because that was prone to future errors - I have submitted to the EPAD branch as well.
