### ISSUE TITLE
Optimize data compression

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#696]
### Description

Right now it is possible to run each module separately. After each run, the data is only compressed if the population module was run. I think it would make sense to run `xASL_adm_GzipAllFiles` after calls like `x = ExploreASL(..., 0, [1 0 0])` or `x = ExploreASL(..., 0, [1 1 0])` as well, but not after each module. It could make sense to move population submodule number 9 to the master script as a separate part of the full workflow.

### Release notes

Required: summarize the changes for the release notes here

**Comment by HenkMutsaerts** [comment]
@MichaelStritt Yes, good idea. Some other programs compress by default after each (intermediate) output; we don't do this as it only costs extra time.

**Comment by MichaelStritt** [comment]
> 
> 
> @MichaelStritt Yes, good idea. Some other programs compress by default after each (intermediate) output; we don't do this as it only costs extra time.

Yeah, to clarify my idea: I wouldn't do this after each intermediate step. I'd do this at the end of ExploreASL_Master. This way we don't compress between Structural & ASL module e.g., but we do compress if somebody would only run the Structural module.

**Comment by HenkMutsaerts** [comment]
@MichaelStritt Yes good point, so this line would then just be added to the end of `ProcessMaster` right?

**Comment by MichaelStritt** [comment]
> 
> 
> @MichaelStritt Yes good point, so this line would then just be added to the end of `ProcessMaster` right?

Yes, I'd move it from the modules to the end of ProcessMaster.

**Comment by MichaelStritt** [comment]
@jan-petr: was there a reason why you moved this back to my bucket?
