### ISSUE TITLE
ASL context when DummyScanPositionInASL4D=1

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#699]
### Description

OASIS dataset: Siemens PASL 2D EPI
**Problem:** the first volume of the asl.nii (which we thought was an M0) seems to have a higher TR than the others and since there's no background suppression, this difference must be due to the different TRs. But, as we don't have the DICOMs, we don't know these parameters.
**Henk's help:** The first ASL was put in a Siemens fMRI protocol. fMRI usually starts with “dummy scans”, to avoid incomplete T1 saturation effects. 
So in this case, we have no background suppression and no M0. You use the mean control as M0. And you remove the first volume.
x.DummyScanPositionInASL4D = 1;

**Questions:**

- Does DummyScanPositionInASL4D work already? @MichaelStritt said that @jan-petr was trying to implement this.

- If yes, how should we define the ASL context? Should we use "m0scan" in the first position of the ASL context? Will ExploreASL listen to the dataPar.json instead of recognizing the first volume as m0scan?

**Comment by HenkMutsaerts** [comment]
Duplicate, addressed in #748
