### ISSUE TITLE
Testing BIDS import on macOS

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#706]
### Description

Will copy paste several warnings and errors here

**Comment by HenkMutsaerts** [comment]
Dataset Root        /Users/henk/ExploreASL/TmpConversion/GE_PCASL_2DEPI_volunteer
Import Modules      NII2BIDS 
Process Modules     
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.8.0_BETA initialized ... 
dataset_description.json is missing the following RECOMMENDED fields: 
HEDVersion
Warning: The following user defined and DICOM fields differ:
  SliceTiming TotalAcquiredPairs
 
> In xASL_bids_BIDSifyASLJSON (line 93)
  In xASL_imp_NII2BIDS_SubjectSessionRun (line 58)
  In xASL_imp_NII2BIDS_SubjectSession (line 60)
  In xASL_imp_NII2BIDS_Subject (line 81)
  In xASL_imp_NII2BIDS (line 73)
  In xASL_module_Import (line 199)
  In ExploreASL_ImportMaster (line 48)
  In ExploreASL_Master (line 71)
  In ExploreASL (line 14)
  In xASL_test_Flavors_DCM2BIDS (line 119)
  In xASL_test_Flavors (line 127)

**Comment by HenkMutsaerts** [comment]
Dataset Root        /Users/henk/ExploreASL/TmpConversion/GE_PCASL_3Dspiral_Product_pharma
Import Modules      NII2BIDS 
Process Modules     
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.8.0_BETA initialized ... 
dataset_description.json is missing the following RECOMMENDED fields: 
HEDVersion, DatasetType, License
NIfTI to BIDS module failed:
Reference to non-existent field 'ASLContext'.

**Comment by HenkMutsaerts** [comment]
xASL_Move: skip: destination exists: /Users/henk/ExploreASL/TmpConversion/GE_PCASL_3Dspiral_volunteer/temp/Sub103/T1w_1/T1w.json

**Comment by HenkMutsaerts** [comment]
Recreating parameter file: /Users/henk/ExploreASL/TmpConversion/Philips_PCASL_2DEPI_Bsup_AD1/temp/Sub1/ASL_1/ASL4D.json
Warning: xASL_adm_Dicom2JSON: xASL_io_DcmtkRead failed for
/Users/henk/ExploreASL/TmpConversion/Philips_PCASL_2DEPI_Bsup_AD1/sourcedata/Sub1/ASL/2.25.77984190786918344398378609716864087186-501-1-97t74k.dcm,
trying dicominfo 
> In xASL_bids_Dicom2JSON (line 186)
  In xASL_imp_DCM2NII_Subject_StoreJSON (line 38)
  In xASL_imp_DCM2NII_Subject (line 206)
  In xASL_imp_DCM2NII (line 252)
  In xASL_module_Import (line 193)
  In ExploreASL_ImportMaster (line 35)
  In ExploreASL_Master (line 71)
  In ExploreASL (line 14)
  In xASL_test_Flavors_DCM2BIDS (line 45)
  In xASL_test_Flavors (line 127) 
Message: Input should be a char (array)...
Warning: This DICOM file contains multiple values with the same name.  The last appearance is
kept. 
> In dicominfo>createMetadataStruct (line 534)
  In dicominfo>processMetadata (line 98)
  In dicominfo (line 67)
  In xASL_bids_Dicom2JSON (line 201)
  In xASL_imp_DCM2NII_Subject_StoreJSON (line 38)
  In xASL_imp_DCM2NII_Subject (line 206)
  In xASL_imp_DCM2NII (line 252)
  In xASL_module_Import (line 193)
  In ExploreASL_ImportMaster (line 35)
  In ExploreASL_Master (line 71)
  In ExploreASL (line 14)
  In xASL_test_Flavors_DCM2BIDS (line 45)
  In xASL_test_Flavors (line 127)

**Comment by HenkMutsaerts** [comment]
Dataset Root        /Users/henk/ExploreASL/TmpConversion/Philips_PCASL_2DEPI_Bsup_AD4
Import Modules      NII2BIDS 
Process Modules     
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.8.0_BETA initialized ... 
dataset_description.json is missing the following RECOMMENDED fields: 
HEDVersion
RWVSlope (1.1321) and RescaleSlopeOriginal (1) differ, using RWVSlope
RWVSlope (1.1321) and RescaleSlope (1) differ, using RWVSlope
Warning: Philips MR ScaleSlope was 1, could be a scale slope issue. 
> In xASL_adm_GetPhilipsScaling (line 136)
  In xASL_bids_BIDSifyASLJSON (line 50)
  In xASL_imp_NII2BIDS_SubjectSessionRun (line 58)
  In xASL_imp_NII2BIDS_SubjectSession (line 60)
  In xASL_imp_NII2BIDS_Subject (line 81)
  In xASL_imp_NII2BIDS (line 73)
  In xASL_module_Import (line 199)
  In ExploreASL_ImportMaster (line 48)
  In ExploreASL_Master (line 71)
  In ExploreASL (line 14)
  In xASL_test_Flavors_DCM2BIDS (line 119)
  In xASL_test_Flavors (line 127) 
Using DICOM (re)scale slopes 1.1321 * 1
Warning: The following user defined and DICOM fields differ:
  TotalAcquiredPairs
 
> In xASL_bids_BIDSifyASLJSON (line 93)
  In xASL_imp_NII2BIDS_SubjectSessionRun (line 58)
  In xASL_imp_NII2BIDS_SubjectSession (line 60)
  In xASL_imp_NII2BIDS_Subject (line 81)
  In xASL_imp_NII2BIDS (line 73)
  In xASL_module_Import (line 199)
  In ExploreASL_ImportMaster (line 48)
  In ExploreASL_Master (line 71)
  In ExploreASL (line 14)
  In xASL_test_Flavors_DCM2BIDS (line 119)
  In xASL_test_Flavors (line 127) 
RWVSlope (1.4796) and RescaleSlopeOriginal (1) differ, using RWVSlope
RWVSlope (1.4796) and RescaleSlope (1) differ, using RWVSlope
Warning: Philips MR ScaleSlope was 1, could be a scale slope issue. 
> In xASL_adm_GetPhilipsScaling (line 136)
  In xASL_bids_BIDSifyM0 (line 37)
  In xASL_imp_NII2BIDS_SubjectSessionRun (line 110)
  In xASL_imp_NII2BIDS_SubjectSession (line 60)
  In xASL_imp_NII2BIDS_Subject (line 81)
  In xASL_imp_NII2BIDS (line 73)
  In xASL_module_Import (line 199)
  In ExploreASL_ImportMaster (line 48)
  In ExploreASL_Master (line 71)
  In ExploreASL (line 14)
  In xASL_test_Flavors_DCM2BIDS (line 119)
  In xASL_test_Flavors (line 127) 
Using DICOM (re)scale slopes 1.4796 * 1
Missing Recommended ASL fields: SliceEncodingDirection, AcquisitionVoxelSize, LabelingOrientation

The field ArterialSpinLabelingType is PCASL, please check the dependencies below:
The recommended fields are missing: PCASLType, LabelingPulseAverageGradient, LabelingPulseMaximumGradient, LabelingPulseAverageB1, LabelingPulseDuration, LabelingPulseFlipAngle, LabelingPulseInterval

**Comment by HenkMutsaerts** [comment]
Dataset Root        /Users/henk/ExploreASL/TmpConversion/Philips_PCASL_2DEPI_GBM
Import Modules      NII2BIDS 
Process Modules     
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.8.0_BETA initialized ... 
dataset_description.json is missing the following RECOMMENDED fields: 
HEDVersion
xASL_Move: overwriting /Users/henk/ExploreASL/TmpConversion/Philips_PCASL_2DEPI_GBM/rawdata/sub-Sub0004/anat/sub-Sub0004_T1w.nii
NIfTI to BIDS module failed:
Inputs Must be Numeric.

**Comment by jan-petr** [comment]
@HenkMutsaerts - please pull #700, check the newest commits there and check whatsapp - the previous version of #700 had DCMTK for MacOS but it wasn't using it properly. This should be now fixed. If yes, please remove your comments above that are fixed.

**Comment by HenkMutsaerts** [comment]
Will reopen a similar issue later when needed
