### ISSUE TITLE
Incorrect flavor title

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#711]
### Description

All flavors should have the same format, like [vendor arterialspinlabelingtype readout type BsupYesNo study identifier].
Most of these have this, but this could be improved. What is more important, is that somehow the name can change through the BIDS test workflow, e.g., in `TmpConversion` and `TmpReference` there is a folder called `ASL_PASL_multiphase`, but this folder is not present in the `FlavorDatabase`?

### Requirements

* all flavors should have the same data set name format, for their root folder
* when copying or moving, the name of the data set root folder should not change

### Release notes

Duplicate - fixed in #178

**Comment by jan-petr** [comment]
Done. All flavors consistently renamed. Not sure what was wrong with the renamed folder, but this is not happening anymore...
