### ISSUE TITLE
Structural module: matrices multiplication is not working

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#713]
### Description

Fixing bugs originated from commits in #683 and #595 .

### Requirements

All three matrices must be int for the multiplication to work.
So if we just convert them to int, it works again

### How to test

Beatriz and Mathijs can check if their datasets are working now, Henk and Michael can check the code.

### Release notes

Fixing bugs originated from commits in #683 and #595 .

**Comment by HenkMutsaerts** [comment]
Dataset Root        /Users/henk/ExploreASL/TmpConversion/Siemens_PCASL_volunteer
Import Modules      NII2BIDS 
Process Modules     
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.8.0_BETA initialized ... 
dataset_description.json is missing the following RECOMMENDED fields: 
HEDVersion
Warning: The following user-defined/DICOM fields and DICOM-Phoenix fields differ:
  SoftwareVersions
 
> In xASL_bids_BIDSifyASLJSON (line 243)
  In xASL_imp_NII2BIDS_SubjectSessionRun (line 58)
  In xASL_imp_NII2BIDS_SubjectSession (line 60)
  In xASL_imp_NII2BIDS_Subject (line 81)
  In xASL_imp_NII2BIDS (line 73)
  In xASL_module_Import (line 199)
  In ExploreASL_ImportMaster (line 49)
  In ExploreASL_Master (line 70)
  In ExploreASL (line 14)
  In xASL_test_Flavors_DCM2BIDS (line 119)
  In xASL_test_Flavors (line 126) 
Missing Recommended ASL fields: SliceEncodingDirection, AcquisitionVoxelSize, LabelingOrientation

The field ArterialSpinLabelingType is PCASL, please check the dependencies below:
The recommended fields are missing: PCASLType, LabelingPulseAverageGradient, LabelingPulseMaximumGradient, LabelingPulseAverageB1, LabelingPulseDuration, LabelingPulseFlipAngle

**Comment by HenkMutsaerts** [comment]
This method is not able to find empty directories right now...
Undefined function or variable 'isfile'.

Error in xASL_bids_CompareStructures>compareTSV (line 548)
    if (isfile(currentFileA) && isfile(currentFileB)) % xASL_exist somehow didn't work here
    (again)

Error in xASL_bids_CompareStructures>checkFileContents (line 328)
            [differences,identical,dn] =
            compareTSV(differences,identical,bPrintReport,allFiles,iFile,dn,currentFileA,currentFileB);
            
Error in xASL_bids_CompareStructures (line 201)
    [identical,results.differences] =
    checkFileContents(fileListA,fileListB,pathDatasetA,pathDatasetB,identical,bPrintReport,detailedOutput,threshRmseNii);
    
Error in xASL_test_Flavors (line 136)
		xASL_bids_CompareStructures(fullfile(conversionPath, filenameCompare{iCompare},
                'rawdata'),...

**Comment by HenkMutsaerts** [comment]
Dataset: GE_PCASL_2DEPI_volunteer
This method is not able to find empty directories right now...
Dataset: GE_PCASL_3Dspiral_Product_pharma
This method is not able to find empty directories right now...
File:			/sub-11/perf/sub-11_asl.nii.gz
				RMSE of NIFTIs above threshold.
Warning: RMSE of NIFTIs above threshold: /sub-11/perf/sub-11_asl.nii.gz    
> In xASL_bids_CompareStructures>printDifferencesAsWarnings (line 217)
  In xASL_bids_CompareStructures (line 206)
  In xASL_test_Flavors (line 136) 

Dataset: GE_PCASL_3Dspiral_Product_volunteer
This method is not able to find empty directories right now...
File:			/sub-Sub1/perf/sub-Sub1_asl.json
				Different value: M0Type (Absent vs Included)
Warning: Different file content: /sub-Sub1/perf/sub-Sub1_asl.json    
> In xASL_bids_CompareStructures>printDifferencesAsWarnings (line 217)
  In xASL_bids_CompareStructures (line 206)
  In xASL_test_Flavors (line 136) 

Dataset: GE_PCASL_3Dspiral_WIP_pharma
This method is not able to find empty directories right now...
Dataset: GE_PCASL_3Dspiral_WIP_volunteer
This method is not able to find empty directories right now...
Dataset: GE_PCASL_3Dspiral_volunteer
This method is not able to find empty directories right now...
File:			/sub-Sub103/perf/sub-Sub103_asl.nii.gz
				RMSE of NIFTIs above threshold.
Warning: RMSE of NIFTIs above threshold: /sub-Sub103/perf/sub-Sub103_asl.nii.gz    
> In xASL_bids_CompareStructures>printDifferencesAsWarnings (line 217)
  In xASL_bids_CompareStructures (line 206)
  In xASL_test_Flavors (line 136) 

Dataset: Philips_PCASL_2DEPI_Bsup_AD1
This method is not able to find empty directories right now...
Dataset: Philips_PCASL_2DEPI_Bsup_AD2
This method is not able to find empty directories right now...
Dataset: Philips_PCASL_2DEPI_Bsup_AD3
This method is not able to find empty directories right now...
Dataset: Philips_PCASL_2DEPI_Bsup_AD4
This method is not able to find empty directories right now...
Dataset: Philips_PCASL_2DEPI_GBM
This method is not able to find empty directories right now...
Dataset:		rawdata_A
Missing:		/sub-Sub0004/perf
Missing:		/sub-Sub0004/anat/sub-Sub0004_T1w.json
Missing:		/sub-Sub0004/perf/sub-Sub0004_asl.json
Missing:		/sub-Sub0004/perf/sub-Sub0004_asl.nii.gz
Missing:		/sub-Sub0004/perf/sub-Sub0004_aslcontext.tsv
Warning: Missing folder /sub-Sub0004/perf   
> In xASL_bids_CompareStructures>printMissingAsWarnings (line 233)
  In xASL_bids_CompareStructures (line 205)
  In xASL_test_Flavors (line 136) 

Warning: Missing file /sub-Sub0004/anat/sub-Sub0004_T1w.json   
> In xASL_bids_CompareStructures>printMissingAsWarnings (line 240)
  In xASL_bids_CompareStructures (line 205)
  In xASL_test_Flavors (line 136) 

Warning: Missing file /sub-Sub0004/perf/sub-Sub0004_asl.json   
> In xASL_bids_CompareStructures>printMissingAsWarnings (line 240)
  In xASL_bids_CompareStructures (line 205)
  In xASL_test_Flavors (line 136) 

Warning: Missing file /sub-Sub0004/perf/sub-Sub0004_asl.nii.gz   
> In xASL_bids_CompareStructures>printMissingAsWarnings (line 240)
  In xASL_bids_CompareStructures (line 205)
  In xASL_test_Flavors (line 136) 

Warning: Missing file /sub-Sub0004/perf/sub-Sub0004_aslcontext.tsv   
> In xASL_bids_CompareStructures>printMissingAsWarnings (line 240)
  In xASL_bids_CompareStructures (line 205)
  In xASL_test_Flavors (line 136)

**Comment by MDijsselhof** [comment]
Structural is working for me now, but I do get another error: 
![image](https://user-images.githubusercontent.com/75380250/124917738-78679280-dff4-11eb-8edb-a540dc9ca8a6.png)

**Comment by MichaelStritt** [comment]
> 
> 
> Structural is working for me now, but I do get another error:
> ![image](https://user-images.githubusercontent.com/75380250/124917738-78679280-dff4-11eb-8edb-a540dc9ca8a6.png)

Is it possible that your JSON file is not valid BIDS? So the BackGorundSuppression value within `studyPar.json` is probably a string and not a boolean/integer.

**Comment by MDijsselhof** [comment]
Not sure what you mean but this is the dataPar (which used to work):

![image](https://user-images.githubusercontent.com/75380250/124925989-532b5200-dffd-11eb-95d9-b6922482b045.png)

Or do you mean the JSON sidecar of the ASL4D?

**Comment by MDijsselhof** [comment]
Okay so something may be going wrong in the BIDS2LEGACY as my rawdata is fine regarding the `"BackgroundSuppression":"true"` which should be `"BackgroundSuppression":"true"`

**Comment by HenkMutsaerts** [comment]
@MichaelStritt thanks for putting the function title in the commit message ;)

**Comment by HenkMutsaerts** [comment]
> `"BackgroundSuppression":"true"` which should be `"BackgroundSuppression":"true"`

This sounds very funny @MDijsselhof :)
