### ISSUE TITLE
Revamp x structure fields of import & processing

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#717]
### Description

* `x.opts` contains general parameters for initialization or running ExploreASL, not specific to import or processing
* `x.settings` contains settings specific to the processing (should not be used in import) Does it help to rename this to `x.Processing` or should these go to `x.modules.processing.settings`?

* `x.S` (statistics) should be initialized when starting the processing (begin of `ExploreASL_ProcessMaster`)
* `x.Q` (quantification) should be initialized when starting the processing (begin of `ExploreASL_ProcessMaster`)
* `x.P` (processing paths of the dataset) should be initialized when starting the processing (begin of `ExploreASL_ProcessMaster`)

* `x.dataset` should not be initialized when only initialising ExploreASL? Also, this should probably go under `x.opts`. 
* `x.dir` should be a subtract of `x.opts` to clarify that these directories are general (non-import/processing specific)
* `x.MyPath` should go under `x.opts` as this is a general option
* `x.subject_regexp`, `x.Quality`` and `x.DELETETEMP` are specific to processing, so should go to `x.module.process` and should not exist before data loading & processing

* `x.name` this is the same as `x.dataset` and can be removed I think
* `x.nSubjects` `x.nSessions` etc should go under `x.module.process`
* `x.SESSIONS` can go to x.module.process.SESSIONS, same for `x.SUBJECTS` but perhaps better to wait with this as this would be a huge change

**Comment by MichaelStritt** [comment]
> * `x.opts` contains general parameters for initialization or running ExploreASL, not specific to import or processing
> 
> * `x.settings` contains settings specific to the processing (should not be used in import) Does it help to rename this to `x.Processing` or should these go to `x.modules.processing.settings`?

I don't think we should have something like `x.modules.processing`. I'd rather just have:

- `x.module.import`
- `x.module.structural`
- `x.module.asl`
- `x.module.population`

> * `x.S` (statistics) should be initialized when starting the processing (begin of `ExploreASL_ProcessMaster`)
> * `x.Q` (quantification) should be initialized when starting the processing (begin of `ExploreASL_ProcessMaster`)
> * `x.P` (processing paths of the dataset) should be initialized when starting the processing (begin of `ExploreASL_ProcessMaster`)

Hm... I'm not sure if this works. We can make sure that they are only initialized within the data loading though. Within the data loading we load the dataPar.json, which can contain x.S or x.Q fields as far as I know.

> * `x.dataset` should not be initialized when only initialising ExploreASL? Also, this should probably go under `x.opts`. 

Hm... I don't see a problem with the initialization of some of these fields, but there's definitely room for improvement. I wouldn't put it in x.opts though. Right now x.opts only contains options of ExploreASL_Master and derivatives of these options. Let's keep that clean.

> * `x.dir` should be a subtract of `x.opts` to clarify that these directories are general (non-import/processing specific)

Disagree. Like I said above, I'd try to keep x.opts as clean as possible.

> * `x.MyPath` should go under `x.opts` as this is a general option

Agree, good idea 👍 

> * `x.subject_regexp`, `x.Quality`` and `x.DELETETEMP` are specific to processing, so should go to `x.module.process` and should not exist before data loading & processing

Disagree. Like I said above, I'd rather have `x.module.import`, `x.module.structural`, `x.module.asl`, & `x.module.population`. I'd put a dataset specific field like the subject regular expression to x.dataset. The problem is that this would have huge effects on the way that people write their dataPar.json, which is why we didn't change this before. The same goes for DELETETEMP. Otherwise I would move DELETETEMP to x.settings.

> * `x.name` this is the same as `x.dataset` and can be removed I think

I don't think that's the same.

> * `x.nSubjects` `x.nSessions` etc should go under `x.module.process`

Like above, I'd rather say those are dataset specific fields and should therefore go to x.dataset. They get called a million times within the pipeline though, which is why we hesitated to change them before.

> * `x.SESSIONS` can go to x.module.process.SESSIONS, same for `x.SUBJECTS` but perhaps better to wait with this as this would be a huge change

Again, I'd move this to x.dataset. This has nothing to do with pipeline or module settings. It's a property of the dataset and should go to x.dataset IMHO.

**Comment by HenkMutsaerts** [comment]
>> I don't think we should have something like x.modules.processing. I'd rather just have:

>> x.module.import
x.module.structural
x.module.asl
x.module.population

Also a good idea, though the structural, ASL and Population have overlapping parameters (corresponding mostly to the data but also some regarding the processing) whereas the Import is really separated; it makes sense to reflect this in the x structure. Where would you put all parameters that are there for all processing modules only?

**Comment by HenkMutsaerts** [comment]
>> x.S (statistics) should be initialized when starting the processing (begin of ExploreASL_ProcessMaster)
x.Q (quantification) should be initialized when starting the processing (begin of ExploreASL_ProcessMaster)
x.P (processing paths of the dataset) should be initialized when starting the processing (begin of ExploreASL_ProcessMaster)

>>  Hm... I'm not sure if this works. We can make sure that they are only initialized within the data loading though. Within the data loading we load the dataPar.json, which can contain x.S or x.Q fields as far as I know.

Yes good idea!

**Comment by HenkMutsaerts** [comment]
>> x.dir should be a subtract of x.opts to clarify that these directories are general (non-import/processing specific)
Disagree. Like I said above, I'd try to keep x.opts as clean as possible.

So you want two structures with general parameters? I would group them, I don't see the problem; all structures should be "as clean as possible"

**Comment by HenkMutsaerts** [comment]
>> x.name this is the same as x.dataset and can be removed I think

I don't think that's the same.

Then you can move `x.name` into `x.dataset`? Please either agree or come up with an alternative, I'm trying to help here ;)

What does `x.dataset` is then, should this contain raw data stuff?

**Comment by HenkMutsaerts** [comment]
>> x.nSubjects x.nSessions etc should go under x.module.process

>> Like above, I'd rather say those are dataset specific fields and should therefore go to x.dataset. They get called a million times within the pipeline though, which is why we hesitated to change them before.

Yes, good idea!

**Comment by HenkMutsaerts** [comment]
>> x.subject_regexp, x.Quality`` and x.DELETETEMPare specific to processing, so should go tox.module.process` and should not exist before data loading & processing
Disagree. Like I said above, I'd rather have x.module.import, x.module.structural, x.module.asl, & x.module.population. I'd put a dataset specific field like the subject regular expression to x.dataset. The problem is that this would have huge effects on the way that people write their dataPar.json, which is why we didn't change this before. The same goes for `DELETETEMP`. Otherwise I would move `DELETETEMP` to `x.settings`.

Same as above. I like your suggestion for the `x.subject_regexp`, but there are many parameters that apply to processing in general and not import; let's group these. The backward compatibility can be dealt with temporarily.

**Comment by HenkMutsaerts** [comment]
>> x.name this is the same as x.dataset and can be removed I think

> I don't think that's the same.

Then please give a bit more details in your answer as to why this is not the same.

**Comment by MichaelStritt** [comment]
> Then you can move `x.name` into `x.dataset`?

That would make more sense to me 👍

**Comment by MichaelStritt** [comment]
> 
> 
> > > x.subject_regexp, x.Quality`` and x.DELETETEMPare specific to processing, so should go tox.module.process`and should not exist before data loading & processing Disagree. Like I said above, I'd rather have x.module.import, x.module.structural, x.module.asl, & x.module.population. I'd put a dataset specific field like the subject regular expression to x.dataset. The problem is that this would have huge effects on the way that people write their dataPar.json, which is why we didn't change this before. The same goes for`DELETETEMP`. Otherwise I would move `DELETETEMP` to `x.settings`.
> 
> Same as above. I like your suggestion for the `x.subject_regexp`, but there are many parameters that apply to processing in general and not import; let's group these. The backward compatibility can be dealt with temporarily.

Hm... Maybe it would make sense to use something like x.settings.import & x.settings.processing then.

**Comment by HenkMutsaerts** [comment]
> > > > x.subject_regexp, x.Quality`` and x.DELETETEMPare specific to processing, so should go tox.module.process`and should not exist before data loading & processing Disagree. Like I said above, I'd rather have x.module.import, x.module.structural, x.module.asl, & x.module.population. I'd put a dataset specific field like the subject regular expression to x.dataset. The problem is that this would have huge effects on the way that people write their dataPar.json, which is why we didn't change this before. The same goes for`DELETETEMP`. Otherwise I would move `DELETETEMP` to `x.settings`.
> > 
> > 
> > Same as above. I like your suggestion for the `x.subject_regexp`, but there are many parameters that apply to processing in general and not import; let's group these. The backward compatibility can be dealt with temporarily.
> 
> Hm... Maybe it would make sense to use something like x.settings.import & x.settings.processing then.

good idea

**Comment by HenkMutsaerts** [comment]
After we find consensus, we can redraft this list of changes here. I agree that we can save the big ones for later (e.g. `x.SUBJECTS` and `x.SESSIONS`). There are many more x fields created throughout processing, we can move these later to either the `settings.processing` or the `dataset`. I like it that you separate `dataset` (which concerns the raw data and never changes) and `settings.processing` (which can change with different inputs). Likewise, we can add something like `results` to check the provenance/outcome of the pipeline (e.g. QC)

**Comment by MichaelStritt** [comment]
The other thing we have to be careful about is the fields that have this symbolic interpretation. I saw that when I moved some of them, but you probably knew about that before 😉

**Comment by MichaelStritt** [comment]
## Proposed changes

* Move `x.MyPath` to `x.opts.MyPath`
* Create `x.settings.import` & `x.settings.process`
* Initialize `x.S` & `x.Q` during data loading and not before that (no need to have them in every initialization)
* Move `x.subject_regexp` to `x.dataset.subjectRegexp`
* Move `x.Quality` to `x.settings.Quality`
* Move `x.DELETETEMP` to `x.settings.DeleteTemp`
* Move `x.name` to `x.dataset.name`
* Move `x.nSubjects` to `x.dataset.nSubjects`
* Move `x.nSessions` to `x.dataset.nSessions`
* Move `x.SESSIONS` to `x.dataset.SESSIONS`

Make sure that the *symbolic field* behavior for some of those fields still works as intended.
