### ISSUE TITLE
Add image paramater option dataPar.json for ROI analysis 

### ISSUE THREAD

**Issue by MDijsselhof** [ExploreASL/ExploreASL#729]
### Description

In the population module at step 7, 'get ROI statistics', CBF is hardcoded as the image input for ROI's analysis. This should be a variable and obtained from dataPar.json, in which the user can specify which image type will be analysed.

### Requirements

- [x] Make sure that inputDataStr and inputDataStr can be read from dataPar.json, or initialized to 'CBF' if empty at the start.
- [x] Add this to the Documentation

### Release notes

Duplicate. Done in #1197

**Comment by MichaelStritt** [comment]
Sounds good. I'd suggest to create a subfield. Something like `x.modules.population.modalityROI`
