### ISSUE TITLE
Minor bugs xASL_init_DataLoading

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#758]
### Description

`xASL_init_DataLoading`  line 28: `x.dir.dataPar` is not a dir but a file?

Also:

`Please insert the path to your study directory`

Should be 

`Please insert the path to your dataset root folder`

Also, when `datapar.json` is `dataParSomething.json`, and you enter the path at `Please insert the path to your dataset root folder`, this goes wrong -> better to give an error here instead, with an explanation of how to do it correctly.

### Requirements

Optional: add bug requirements here

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here

**Comment by MichaelStritt** [comment]
> `xASL_init_DataLoading`  line 28: `x.dir.dataPar` is not a dir but a file?

I don't regard this as a problem. Maybe dir isn't the perfect name, but it's common to use it for paths. There are like a hundred other fields that are just crammed in the main level which are way more disordered.
