### ISSUE TITLE
Adapting ExploreASL pipeline to multi-PLD data

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#759]
### Description
**Import module:**
Merging of multiple single-PLD files is done automatically according to file-placement in directories. 
Should provide option to disable merge if preferred, see issue #917.

Output: ASL4D (consisting of according to BIDS structure: PLD1(C-L,C-L,C-L)PLD2(C-L,C-L,C-L))

**ASL module:**
At the beginning of the module (after LoadParams in line 206): recognition of multi-TE, multi-PLD, time encoded (Hadamard)

- TopUp: no changes 👍
   -> check if it can be applied to more dimensions ( see issue #918)

- Motion correction:  👍 (ASL module - step 2) @BeatrizPadrela 
Default is `on`.
-> zigzag=false 
-> xASL_wrp_Realign_ASL: 
  -- bENABLE instead of bExecuteENABLE 👍
  -- bENABLE = 0 at the beginning of the function if multiPLD. Default bENABLE=1 👍
  --bZigZag defined at the beginning of the Realign function 👍

Check what others do in multi-PLD motion correction (see issue #919)

- Registration  (ASL module - step 3) @BeatrizPadrela 
-> xASL_wrp_RegisterASL:
  -- Step H: There's this Pairwise subtraction that creates this PWI_Clipped image. Jan checked that this PWI_Clipped image is only used in this function and in the Realign [this Clipped_ORI can be deleted in the future because is not used anywhere else]. So, since in this function we want to obtain a single volume:
  + if multi-PLD, we can run the Pairwise subtraction (since we have control and label images for each PLD) and take an average of all the PLDs (->later on we might want to do some extra-check because instead of average with all of the PLDs, we probably don't want to include the early PLDs but only the later ones that look like CBF) -> #914 
-We don't need to change this step, just test if it works
  
And after this, the PWI_Clipped is going to work irrespectively how the Clipped was created (bRegistrationCBF loop in the step H)

- Resampling  (ASL module - step 4) 
->xASL_wrp_ResampleASL:
  We currently use PWI (a 4 dimensional matrix), however we can also use PWI4D (containing all repeats). For now, insert warning that we use only PWI
  -- check if BASIL uses multiple repeats to optimise quantification (PVC) and implement that in future issue #920

  -- Step8: pair-wise subtraction: (discuss with @HenkMutsaerts)
  + for multiPLD: stays the same - subtracting controls and labels (Paired subtraction part). For the PWI, we need to calculate the mean across the repetitions and keep the PLDs separate (Average PWI part).
BASIL-> 4D PWI file, containing the repeats and PLD's. Basil inputs a txt file with the order of the volumes (PLD, Repetitions - check BIDS structure)

- Process M0 (ASL module - step 6) @MDijsselhof 
-> Acquired M0
-> Non-background suppressed mean control of the latest (or only) PLD 
     - include `fprintf` that the last average control image is used.
     - New issue to improve this (issue #921)
-> Pseudo M0: Mean control of the latest PLD.

- Quantification (ASL module - step 8) @MDijsselhof 
->xASL_wrp_Quantify -> Perform Quantification (step 8 of xASL_wrp_Quantify) -> xASL_quant_SinglePLD, line 131 -> xASL_quant_Basil
-> Check which outputs we want from Basil
-> Create config file

### How to test
With the multiPLD dataset we have

### Requirements

Optional: add feature requirements here

**Comment by MDijsselhof** [comment]
Current status per module step at the moment:

- Resample:
   - creation of PWI4D and PWI when performing multiPLD analysis
   - Save both for later use in following steps ASM module (PWI) or in BASIL quantification (PWI4D)

- Process M0:
   -    xASL_quant_M0 can't deal with a vector of ReadoutTime values

**Comment by BeatrizPadrela** [comment]
Nice!

**Comment by MDijsselhof** [comment]
Changes in the commit:

- xASL_qc_CollectQC_ASL.m 
     Added change in path to read imCBF image for BASIL results

- xASL_quant_BSupCalculation.m 
     Changed SignalPercentageVector to include sum of all PLD's (not tested and used yet for multi-PLD analysis)

- xASL_quant_Basil.m
     Changed several inputs to distinguish between PWI single-PLD (3D) and PWI multi-PLD (4D)
     Changed and added BASIL config options
- xASL_quant_MultiPLD.m 
     Added new function to distinguish between multi-PLD and single-PLD analysis and for use in later development of xASL multi-PLD analysis. Changed some input to enable multi-PLD BASIL quantification
- xASL_wrp_Quantify.m
     Added x as output for CBF_BASIL result paths for later use in other functions
- xASL_wrp_ResampleASL.m
     Rearranges the mean of multiple repeat ASL_im 4D data into 4D PWI data in which 4th dimension is the mean of the repeats for a PLD
- xASL_module_ASL.m
    Changed quantification to native space only for BASIL (single and multi-PLD)
    Changed input of xASL_wrp_VIsualQC_ASL to only single-delay data for the moment
