### ISSUE TITLE
Warning >MAT sidecar thrown while testing r1.2.0 on Windows

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#77]
## Jan can you check if we need to fix this:

Running SPM job 'Coregister: Reslice'

SPM12: spm_reslice (v7141)                         15:03:49 - 05/08/2020

Completed                               :          15:03:49 - 05/08/2020
Done    'Coregister: Reslice'
Done

xASL_Move: overwriting S:\gifmi\Projects\ExploreASL\ExploreASL_TestCases\ProcessedCases\Philips_2DEPI_Segmentation_2D_T2_SPM_LoQ\101\ASL_1\MaskASL.nii

------------------------------------------------------------------------------------------
Reslicing Mean_CBF_Template.nii to mean_PWI_Clipped.nii using Trilinear interpolation

Running SPM job 'Coregister: Reslice'

SPM12: spm_reslice (v7141)                         15:03:50 - 05/08/2020

Completed                               :          15:03:50 - 05/08/2020
Done    'Coregister: Reslice'
Done

Tanimoto Coeff=70.2
Standard space whole-brain spatial CoV estimated as = 53.5%
Skipping affine registration

4 registration iterations:
Iteration 1, Tanimoto coefficient = 50.1%
Iteration 2, Tanimoto coefficient = 64.9%
Iteration 3, Tanimoto coefficient = 69.9%
Iteration 4, Tanimoto coefficient = 70.2%

>> >>  **Warning: .MAT sidecar volumes contained illegal diagnonal. Deleting the sidecar 
> In xASL_adm_ManageMoCoMat (line 88)
  In xASL_io_ReadNifti (line 54)
  In xASL_wrp_ResampleASL (line 47)
  In xASL_module_ASL (line 288)
  In xASL_Iteration>runIteration (line 361)
  In xASL_Iteration (line 100)
  In ExploreASL_Master (line 132)
  In xASL_qc_TestExploreASL (line 293)
  In xASL_qc_TestExploreASL_HM (line 50)** 

------------------------------------------------------------------------------------------

**Comment by jan-petr** [comment]
I couldn't reproduce this on Linux. 
Can you run that again on Windows and send me the workspace from:
xASL_adm_ManageMoCoMat (line 88)

My suspicion is that this is related to the other issue and a zero matrix is simply read. So this is in effect a permission and reading issue - to be solved outside of these function...

**Comment by jan-petr** [comment]
Make sure that the .mat content is deterministic by saving some pre-defined values.
