### ISSUE TITLE
xASL_Move is deleting nifti files if the files are only being replaced

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#774]
### Description

The function is deleting both asl.nii and asl.nii.gz, when we want to save the corrected asl.nii after xASL_bids_BIDSifyASLNII

### Requirements

![image](https://user-images.githubusercontent.com/73699072/129549583-e948cb9f-543c-4ab4-aa9a-7cfd9582d00a.png)

![image](https://user-images.githubusercontent.com/73699072/129549633-14e422c3-40f2-40f3-a06d-9f91aafc57c1.png)

![image](https://user-images.githubusercontent.com/73699072/129549728-6935744b-bcea-4bfd-9a28-0383c2fab1e6.png)

1. Correctly manage zipping
2. Correctly manage unzipping
3. Don't overwrite or delete when moving to the same file :+1: 
4. Fix the header to reflect the zipping (we previously claimed that zipping is not handled, but it is) :+1: 

### Release notes

Correctly manage zipping when moving identical files.

**Comment by HenkMutsaerts** [comment]
This looks like good behavior of `xASL_Move`, which should not be used for moving a file to itself. `xASL_Move` (and many other ExploreASL functions) regard `asl.nii` and `asl.nii.gz` as the same file.

A probable good solution is to check at the beginning of `xASL_Move` if the origin and destination paths are the same (including `.nii` and `.nii.gz`). If they are the same, issue an `fprintf` warning, and zip if the destination if a `.nii.gz` but the origin is not.
