### ISSUE TITLE
Warning thrown while testing r1.2.0 

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#78]
## Jan can you check if we need to fix this
This warning is thrown quite a few times when testing on Windows, but this could be a read/write-access issue

Rigid-body registering mean_PWI_Clipped.nii to PseudoCBF.nii

Running SPM job 'Coregister: Estimate'

SPM12: spm_coreg (v6435)                           15:03:39 - 05/08/2020

Smoothing [3 3 3] into [1.73 1.73 1.73] FWHM resolution
Smoothing [3 3 3] into [1.73 1.73 1.73] FWHM resolution for scan 1
Registering scan 1...100%, 
Completed                               :          15:03:41 - 05/08/2020
>> >> Warning: Can not load
"S:\gifmi\Projects\ExploreASL\ExploreASL_TestCases\ProcessedCases\Philips_2DEPI_Segmentation_2D_T2_SPM_LoQ\101\ASL_1\ASL4D.mat" as
a binary MAT file. 
> In read_extras (line 25)
  In nifti (line 27)
  In spm_get_space (line 18)
  In spm_run_coreg (line 30)
  In cfg_run_cm (line 29)
  In cfg_util>local_runcj (line 1692)
  In cfg_util (line 959)
  In spm_jobman>fill_run_job (line 470)
  In spm_jobman (line 248)
  In xASL_spm_coreg (line 128)
  In xASL_wrp_RegisterASL (line 414)
  In xASL_module_ASL (line 267)
  In xASL_Iteration>runIteration (line 361)
  In xASL_Iteration (line 100)
  In ExploreASL_Master (line 132)
  In xASL_qc_TestExploreASL (line 293)
  In xASL_qc_TestExploreASL_HM (line 50) 
Done    'Coregister: Estimate'
Done

**Comment by HenkMutsaerts** [comment]
Seems that we should change in _SPM/read_extras.m_:

>>    try
        extras = load(mname);
    catch
        warning('Can not load "%s" as a binary MAT file.', mname);
    end

into

>>    try
        extras = load(mname, '-mat');
    catch ME
        warning('Sidecar "%s" seems to exist but cannot be loaded', name);
        fprintf('%s\n', 'Original warning was: ' ME.message]);
        fprintf('%s\n', 'Perhaps something wrong with read/write-access/permissions?');
    end

**Comment by jan-petr** [comment]
I wasn't able to reproduce this issue. And your fix looks OK. So I would say we can close this issue.
