### ISSUE TITLE
CustomScripts

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#8]
Scripts written for specific studies, mostly import-related. Can be re-used for other studies. Should be neglected by the main pipeline.

**Comment by MichaelStritt** [comment]
Hey @jan-petr & @HenkMutsaerts 
what do you think about merging branch `CustomScript-#8_Tamas`?
I think nothing's going on in there anymore and we should probably merge it before it gets too old 👍

**Comment by jozsait** [comment]
I am planning to work on CustomScript-#8_Tamas a bit in the following days

**Comment by HenkMutsaerts** [comment]
Closing this issue per #299.

**Comment by MichaelStritt** [comment]
@jozsait & @HenkMutsaerts: I moved the code changes from branch `CustomScript-#8_Tamas` to the `CustomScripts` repository and deleted the branch afterwards.
