### ISSUE TITLE
Release 1.8.0

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#805]
### Release v1.8.0

Release issue to document testing and bug fixing. Check out the GitHub wiki workflow for the [drafting of a new release](https://github.com/ExploreASL/ExploreASL/wiki/Drafting-a-new-Release).

### Testing

Document who is responsible for which tests here:

#### Run TestDataSets 👍

- linux: Jan 👍
- windows: Michael 👍
- macOS: Henk 👍

#### Run UnitTesting 👍

- linux: Jan 👍 
- windows: Michael 👍

#### Run full BIDS pipeline tests 👍

- linux: Jan 👍 BIDS all OK except Hadamard, BIDS2Legacy no errors, processing only reported errors #342 
- windows: Michael 👍
- macOS: Henk 👍

### Documentation

Document who will update the `VERSION_[x.x.x]` and the `CHANGES.md` file using the **release notes** of each individual issue.

- `CHANGES.md`: double-check Jan 👍
- `VERSION.md`: Michael 👍
- Docker + docu: Michael
- `CHANGES.md`: Michael - Michael add #805  👍
- Remove BASIL from TestDataSet: Jan 👍
- Retest TestDataSet for one last time: Jan 👍
- Afterwards Add Linux and Windows reference to testDataSet: Michael
- Compilation: Jan
- Upload Derivatives/Legacy reference to Flavors: Michal
- Do and tag release: Michael

**Comment by jan-petr** [comment]
@MichaelStritt 
- I made the pull of testing repository optional in Unit testing :+1: 
- If testing crashes half-way through, then it can't manage to recreate the `working_directory` - it would be nice to always delete the `working_directory` if existing on unit-test startup.
- Unit testing doesn't work - crashes in `xASL_bids_DRO2BIDS (line 101)`. ExploreASLversion was missing in call of `xASL_bids_CreateDatasetDescriptionTemplate` and also in `xASL_ut_function_xASL_bids_CreateDatasetDescriptionTemplate` on two lines. Difficult to add since you need to have the path to the ExploreASL/VERSION - that needs adding `x` to `xASL_bids_DRO2BIDS` perhaps...

**Comment by MichaelStritt** [comment]
@jan-petr 

> * I made the pull of testing repository optional in Unit testing 👍

Perfect 😃 I did some minor changes in the header 👍 

> * If testing crashes half-way through, then it can't manage to recreate the `working_directory` - it would be nice to always delete the `working_directory` if existing on unit-test startup.

Good point. I haven't had that problem before, but I added a few lines of code to fix this (I just delete the directory contents before each test run and then I make sure the directory exists afterwards).

> * Unit testing doesn't work - crashes in `xASL_bids_DRO2BIDS (line 101)`. ExploreASLversion was missing in call of `xASL_bids_CreateDatasetDescriptionTemplate` and also in `xASL_ut_function_xASL_bids_CreateDatasetDescriptionTemplate` on two lines. Difficult to add since you need to have the path to the ExploreASL/VERSION - that needs adding `x` to `xASL_bids_DRO2BIDS` perhaps...

I see the problem 🤔 I don't think we need the correct version for testing here though. I just added `1.2.3`. That should be fine 👍 We should rather focus on adding a few tests which utilize the DRO a bit heavier, since I read that Aaron was asking about this (September meeting planning and so on).

**Comment by jan-petr** [comment]
@MichaelStritt Very good. I agree about dummy x.Version in UT. But not in xASL_bids_DRO2BIDS - this function should contain the correct version, right? That's the real convertor, not just testing.

**Comment by MichaelStritt** [comment]
@jan-petr: I was testing what you wrote about the multi session import. So this is how I do it for ADNI right now:

### sourceStructure.json

```json
{
"folderHierarchy":["^sub-(.+)$","^(session_\\d{1}).+$","^(ASL|T1w|M0|T2|FLAIR)$","S.+$"],
"tokenOrdering":[1,2,0,3],
"tokenVisitAliases":["session_1","1","session_2","2","session_3","3","session_4","4","session_5","5"],
"tokenSessionAliases":["",""],
"tokenScanAliases":["^ASL$","ASL4D","^T1w$","T1w","^M0$","M0","^T2$","T2w","^FLAIR$","FLAIR"],
"bMatchDirectories":true
}
```

### Folder structure

![image](https://user-images.githubusercontent.com/46593074/131699931-4e847116-0791-412c-9ecd-aac6b7f98679.png)

### Test run

```
>> pathTest = '\Old_TestData\011_S_4105';
>> x = ExploreASL(pathTest,[1 1 0 1],0);

ExploreASL will run the import workflow and will load the dataset...
==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
Dataset Root        ...\Old_TestData\011_S_4105
Import Modules      DCM2NII NII2BIDS BIDS2LEGACY
Process Modules     
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.8.0 initialized ... 
================================== DICOM to NIFTI CONVERSION =================================

Matching files:
    'sub-001\session_1_2013-07-26_15_10_24.0\ASL\S196762'
    'sub-001\session_1_2013-07-26_15_10_24.0\FLAIR\S196758'
    'sub-001\session_1_2013-07-26_15_10_24.0\T1w\S196752'
    'sub-001\session_2_2015-07-29_12_17_39.0\ASL\S267385'
    'sub-001\session_2_2015-07-29_12_17_39.0\FLAIR\S267396'
    'sub-001\session_2_2015-07-29_12_17_39.0\T1w\S267391'

#=6
Running import (i.e. dcm2niiX)
==============================================================================================


...


================================== BIDS JSON Check Results ===================================
Missing recommended ASL fields:       SliceEncodingDirection, AcquisitionVoxelSize, LabelingOrientation

============================ BIDS to ExploreASL LEGACY CONVERSION ============================
Parsing BIDS scans: 100%
Note that any warnings may have only printed once if they were repeated for multiple scans
Always run your rawdata folder through the BIDS validator first and aim to avoid warnings
Converting from BIDS to Legacy: 011_S_4105 1100%
M0 parsed for 011_S_4105 ASL4D.nii ...
M0 parsed for 011_S_4105 ASL4D.nii ...
Creating dataPar.json since file was not found in derivatives directory...
Overwriting x.dir.dataPar...


Automatically defining sessions...
==================================== Additional Settings =====================================
2 scans - 0 exclusions, resulting in 2 scans of: 
Longitudinal timePoint 1 = 1 scans - 0 exclusions = 1 scans
Longitudinal timePoint 2 = 1 scans - 0 exclusions = 1 scans
ASL sessions: 1

Ancillary data, sets: 4 sets are defined for 2 "SubjectsSessions"
Set 1 = "session" options "ASL_1", codes for paired data
Set 2 = "LongitudinalTimePoint" options "TimePoint_1" & "TimePoint_2", codes for paired data
Set 3 = "SubjectNList" options "SubjectNList", codes for paired data
Set 4 = "Site" options "SingleSite", codes for two-sample data
x.D.ROOT            \Old_TestData\011_S_ ...
                    ... 4105\derivatives\ExploreASL
x.settings.DELETETEMP 1 (delete temporary files)
x.settings.Quality    1 (0 = fast try-out; 1 = normal high quality)

==============================================================================================
```

### Results

![image](https://user-images.githubusercontent.com/46593074/131700514-5e250e29-0717-4633-9ece-de9a098b3c9e.png)

![image](https://user-images.githubusercontent.com/46593074/131700584-ead3e34a-b6b5-40ee-b9e4-04d47ba5f696.png)

![image](https://user-images.githubusercontent.com/46593074/131700607-93865813-3bf7-4ea5-836a-8a686627d3d0.png)

**Comment by MichaelStritt** [comment]
@jan-petr 

> @MichaelStritt Very good. I agree about dummy x.Version in UT. But not in xASL_bids_DRO2BIDS - this function should contain the correct version, right? That's the real convertor, not just testing.

You're definitely right. I changed this in commit 1ae3f15 . I added a warning if no version was provided and also extracted the version for the ExploreASL_Master unit test. I guess we can just switch over to the new 2.3.0 version of the DRO really soon (not released yet), there we don't have to do any conversions as far as I know. I'm running the unit tests right now to see if everything works 😄

**Comment by MichaelStritt** [comment]
### My current unit testing results

```
====================================== TEST RESULTS ======================================

                        name                           unit           tests        passed
    ____________________________________________    __________    _____________    ______

    'xASL_adm_CatchNumbersFromString'               'function'    [1×3  struct]    true  
    'xASL_adm_CheckFileCount'                       'function'    [1×2  struct]    true  
    'xASL_adm_CompareLists'                         'function'    [1×2  struct]    true  
    'xASL_adm_CorrectName'                          'function'    [1×3  struct]    true  
    'xASL_adm_DeleteFileList'                       'function'    [1×2  struct]    true  
    'xASL_adm_OrderFields'                          'function'    [1×1  struct]    true  
    'xASL_bids_BIDS2Legacy'                         'function'    [1×2  struct]    true  
    'xASL_bids_CheckDatasetDescription'             'function'    [1×2  struct]    true  
    'xASL_bids_Config'                              'function'    [1×1  struct]    true  
    'xASL_bids_CreateDatasetDescriptionTemplate'    'function'    [1×2  struct]    true  
    'xASL_bids_JsonCheck'                           'function'    [1×3  struct]    true  
    'xASL_bids_VendorFieldCheck'                    'function'    [1×1  struct]    true  
    'xASL_io_ExportVTK'                             'function'    [1×5  struct]    true  
    'xASL_io_Nifti2Im'                              'function'    [1×1  struct]    true  
    'xASL_stat_PSNR'                                'function'    [1×2  struct]    true  
    'xASL_stat_QuantileNan'                         'function'    [1×1  struct]    true  
    'xASL_stat_StdNan'                              'function'    [1×3  struct]    true  
    'xASL_str2num'                                  'function'    [1×3  struct]    true  
    'xASL_test_GetLogContent'                       'function'    [1×2  struct]    true  
    'xASL_tsvRead'                                  'function'    [1×2  struct]    true  
    'xASL_tsvWrite'                                 'function'    [1×2  struct]    true  
    'xASL_ExploreASL_Master'                        'master'      [1×10 struct]    true  
    'xASL_module_ASL'                               'module'      [1×1  struct]    true  
    'xASL_module_Population'                        'module'      [1×1  struct]    true  
    'xASL_module_Structural'                        'module'      [1×1  struct]    true  

==========================================================================================
```

**Comment by jan-petr** [comment]
Thanks. I did a minor fix of the header - the classic line 4 ;)

**Comment by jan-petr** [comment]
Once we merge #810, I'll be happy

**Comment by MichaelStritt** [comment]
@jan-petr: I think there's a small bug in `xASL_bids_BIDS2Legacy`. Pops up immediately after starting the unit testing.

```
[UnitTests,UnitTestsTable] = xASL_test_UnitTesting(false);
...
```

```
Error using horzcat
Dimensions of arrays being concatenated are not consistent.
Error in xASL_bids_BIDS2Legacy (line 140)
        pathLegacy_SubjectVisit = fullfile(pathLegacy, [SubjectID '_' xASL_num2str(iVisit)]);
```

**Comment by MichaelStritt** [comment]
Fix related to #810 6ed6bd2 👍

**Comment by jan-petr** [comment]
a(22).tests(10) - failed = 'DRO 2.2.0 (Full pipeline, rawdata->results)'

**Comment by jan-petr** [comment]
See where the test failed. My fault?! You can see which line crashes and also how the filename differs...

![image](https://user-images.githubusercontent.com/29886537/132254093-d3e18688-2d1d-4c62-a7fe-23dd730fa98f.png)

**Comment by BeatrizPadrela** [comment]
ResultsTable = 

  Columns 1 through 9
```

    'Data'                   'mean_qCBF_TotalGM'    'median_qCBF_TotalGM'    'median_qCBF_DeepWM'    'CoV_qCBF_TotalGM'    'GMvol'     'WMvol'     'CSFvol'    'PipelineCompleted'
    'GE_3Dspiral_T1pre…'    '65.0911'              '52.4651'                '32.0559'               '0.29921'             [0.6400]    [0.5054]    [0.4330]    [                1]
    'Philips_2DEPI_FEA…'    '38.9729'              '27.6587'                '6.73'                  '0.71513'             [0.5349]    [0.4590]    [0.4056]    [                1]
    'Philips_2DEPI_FLA…'    '74.0946'              '56.3948'                '22.9226'               '0.33662'             [0.5442]    [0.3920]    [0.3561]    [                1]
    'Philips_2DEPI_FLA…'    '48.959'               '43.4651'                '20.3422'               '0.41853'             [0.6994]    [0.5816]    [0.2222]    [                1]
    'Philips_2DEPI_Les…'    'empty'                '14.4365'                '3.4282'                '0.89241'             [0.7096]    [0.5136]    [0.1942]    [                1]
    'Philips_2DEPI_Seg…'    '45.9512'              '41.1554'                '9.4098'                '0.36523'             [0.8167]    [0.4596]    [0.1516]    [                1]
    'Philips_3DGRASE_F…'    '35.1324'              '26.2474'                '7.6225'                '0.66049'             [0.5716]    [0.5282]    [0.4207]    [                1]
    'Philips_3DGRASE_M…'    '31.9461'              '24.3224'                '8.5892'                '0.43733'             [0.7239]    [0.5520]    [0.3564]    [                1]
    'Siemens3DGRASE_St…'    '37.6957'              '37.2872'                '21.7901'               '0.78873'             [0.5191]    [0.4658]    [0.4054]    [                1]
    'Siemens_2DEPI_noB…'    '67.5016'              '50.6498'                '13.4243'               '0.31698'             [0.6886]    [0.6030]    [0.3101]    [                1]
```

  Columns 10 through 11

    'TC_ASL_Registration'    'TC_M0_Registration'
    [             0.8995]    [            0.9315]
    [             0.7292]    [            0.8137]
    [             0.9194]    [            0.9479]
    [             0.8141]    [            0.8344]
    [             0.7443]    [            0.8897]
    [             0.8544]    [            0.8028]
    [             0.8568]    [            0.7545]
    [             0.8389]    [            0.8932]
    [             0.6915]    [            0.4987]
    [             0.8757]    [            0.9589]
