### ISSUE TITLE
Lighter Flavor testing

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#822]
### Description

The flavor testing script now unnecessary copies a lot of data, which burdens hard drives and doubles the testing time. We can at least avoid this for the `sourcedata`; for the `rawdata` and `derivatives`, the testing will have to unzip files which can be tricky.

### Requirements

Instead, we should:

1. Avoid copying `sourcedata`
2. Add folders that are created during testing to `.gitignore`
3. Rename `rawdata` and `derivates` references to `rawdataReference`
4. Update the testing script so that it works with that
5. Delete the temporary data at the end of testing

### Release notes

Duplicate.

**Comment by MichaelStritt** [comment]
99% of this is implemented in https://github.com/ExploreASL/ExploreASL/pull/835 . I'd close this issue.
