### ISSUE TITLE
BIDSifyAnatJSON crashes because of RepTime array

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#848]
### Description
For one of the TWINS datasets (EMI 301), there is an error in NII2BIDS. In xASL_bids_BIDSifyAnatJSON the code crashes because jsonOut.RepetitionTimePreparation is an array. We definitey need to check for that in the code and why that happens for this indiviudal dataset.

```matlab
	% If RepetitionTimePreparation is equal to RepetitionTime, then remove RepetitionTimePreparation
	if isfield(jsonIn,'RepetitionTime') && isfield(jsonIn,'RepetitionTimePreparation') &&...
			isnear(jsonIn.RepetitionTime,jsonIn.RepetitionTimePreparation)
		jsonOut = rmfield(jsonOut,'RepetitionTimePreparation');
	end
```

### Requirements

Optional: add bug requirements here

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Improve repetition time field checks and add a user warning.

**Comment by MichaelStritt** [comment]
We saw that we can fix it by creating a better `sourceStructure.json` or just by deleting additional DICOM data manually, we should add a check for that case though.
