### ISSUE TITLE
Warning in a testing dataset on quantified CBF values

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#85]
The following warning is issued. This needs to be checked as the ASL4D files contain directly the quantified CBF, so no quantification needs to be run, and the quantification (division by M0) is turned of anyway - so it is strange why such warning is issued.

Either the code needs to be changed or the params files.

Warning below
_xASL_Move: overwriting /home/janpetr/tmp/ExploreASL_TestCases1.0.0_Done/Philips_2DEPI_FLAIR_DisabledQuantification_M0_LoQ/Sub-001/ASL_1/rM0.nii
Quantifying ASL:   
Loading PWI & M0 images
M0 scan used_
_Delta TE between ASL 16.861ms & M0 17ms, for 2D_EPI, assuming T2star decay of arterial blood, factor applied to M0: 1.0029
Quantification CBF single PLD:
2D sequence, accounting for SliceReadoutTime
Using single-compartment CASL
Using DICOM (re)scale slopes 2.7968 * 0.00092466We skip the PWI/M0 division
 model with parameters:
LabelingDuration = 1650 ms, PLD (ms) = 1525 + 43.7647 ms*(slice-1)
labeling efficiency (neck*Bsup) = 0.85 * 0.83, 
assuming labda = 0.9, T1 arterial blood = 1650 ms
Warning: M0 division was disabled & CBF image had too high values_ 
> In xASL_wrp_Quantify (line 279)
  In xASL_module_ASL (line 377)
  In xASL_Iteration>runIteration (line 356)
  In xASL_Iteration (line 95)
  In ExploreASL_Master (line 129)
  In xASL_qc_TestExploreASL (line 292) 
mean whole image CBF normalized from 77755341.4997 to 10 mL/100g/min

**Comment by HenkMutsaerts** [comment]
* This warning is something I remember inserting, not sure if you remember? The warning itself is good that it is there, if the values are insanely high and the M0 division is turned off, then you want the user to check if the image should actually have been divided by M0 (explaining the high values).

* The error seems to be the ApplyQuantification value of [1 1 1 1 0], which indeed avoids M0 division, but still applies the scaleslopes to the ASL4D & M0 (check how this is described in DataParametersTemplate.m). The solution is to set ApplyQuantification to [0 0 0 0 0] for this one.

**Comment by HenkMutsaerts** [comment]
Do you want to check if you agree with how ApplyQuantification works throughout the pipeline?

**Comment by jan-petr** [comment]
I have checked for all occurences and it looks good. I haven't checked more deeply, where ApplyQuantification might be missing, but all it's correct use seem to be fine.

A few exceptions:
xASL_Module_ASL line 81: I would remove the ApplyQuantification(5) condition. I would prepare the M0 in all cases, and only skip it directly before the division.

xASL_wrp_Quantify line 68: Do you need to check for this, when this field is properly initialized xASL_Module_ASL at line 41. I would either remove this duplicate check, or extend it to the full version (preferably the first).

xASL_wrp_ProcessM0 line 92: That's about something else than scale slopes. I would leave that one there on all occasions, maybe except ApplyQuantification(4) == 0.

**Comment by HenkMutsaerts** [comment]
* xASL_Module_ASL line 81: agree, condition removed

* xASL_wrp_Quantify line 68: agree, removed. We need to check this in general, functions should be independent, wrappers may be dependent. This wrapper was already dependent, so no need to repeat the full version

* xASL_wrp_ProcessM0 line 92: agree, condition removed

I have also fully disabled the quantification for the Philips_2DEPI_FLAIR_DisabledQuantification_M0_LoQ, you want to test this?

Note that this is a checkout from the current develop, so might need cherry-picking when merging, with the new #143 history.

**Comment by jan-petr** [comment]
The branch was re-created from develop and cherry-picked the commits from the older version of the branch.
