### ISSUE TITLE
Update longitudinal registration

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#853]
### Description

Longitudinal registration had some old variable names and settings, I now updated these.

### Requirements

Optional: add feature requirements here

### How to test

set `x.modules.bRunLongReg` to true in `dataPar.json` and run the processing with at least two visits in legacy structure (`subject_1` & `subject_2`).

### Release notes

Bugfix: update longitudinal registration

**Comment by tininmartinez** [comment]
Hi guys,

I do not know if I am writing in the correct site, but I did not find any other place to ask for assistance. I have a problem with a longitudinal analysis with ExploreASL related with LongReg module.

First, I imported the data, set x.modules.bRunLongReg to true in dataPar.json and ran the processing with at least two visits in legacy structure (105_1 & 105_2) with the following command: ExploreASL('E:\ASL_Study\analysis\DataPar.json', 0, 1);

Then, I receive the following error:


ERROR: LongReg module terminated for subject 1: 105_1

ans =

    'Output argument "result" (and possibly others) not assigned a value in the execution with "xASL_module_LongReg" function.
     
     Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_Iteration>runIteration', 'E:\toolbox\ExploreASL\Functions\xASL_Iteration.m', 394)" style="font-weight:bold">xASL_Iteration>runIteration</a> (<a href="matlab: opentoline('E:\toolbox\ExploreASL\Functions\xASL_Iteration.m',394,0)">line 394</a>)
     				[result, x] = jobfn(x); % [result, x] = jobfn(x, job_ex);
     
     Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('xASL_Iteration', 'E:\toolbox\ExploreASL\Functions\xASL_Iteration.m', 100)" style="font-weight:bold">xASL_Iteration</a> (<a href="matlab: opentoline('E:\toolbox\ExploreASL\Functions\xASL_Iteration.m',100,0)">line 100</a>)
     	[bAborted, xOut] = runIteration(dbSettings);
     
     Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('ExploreASL_ProcessMaster', 'E:\toolbox\ExploreASL\ExploreASL_ProcessMaster.m', 93)" style="font-weight:bold">ExploreASL_ProcessMaster</a> (<a href="matlab: opentoline('E:\toolbox\ExploreASL\ExploreASL_ProcessMaster.m',93,0)">line 93</a>)
             [~, x] = xASL_Iteration(x,'xASL_module_LongReg');
     
     Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('ExploreASL_Master', 'E:\toolbox\ExploreASL\ExploreASL_Master.m', 85)" style="font-weight:bold">ExploreASL_Master</a> (<a href="matlab: opentoline('E:\toolbox\ExploreASL\ExploreASL_Master.m',85,0)">line 85</a>)
             x = ExploreASL_ProcessMaster(x); % Comentado compresión a Gzip
     
     Error in <a href="matlab:matlab.internal.language.introspective.errorDocCallback('ExploreASL', 'E:\toolbox\ExploreASL\ExploreASL.m', 14)" style="font-weight:bold">ExploreASL</a> (<a href="matlab: opentoline('E:\toolbox\ExploreASL\ExploreASL.m',14,0)">line 14</a>)
         x = ExploreASL_Master(varargin{:});'


CONT: but continue with next iteration!


Do anyone know how to solve it or what am I doing wrong?

Thanks in advance.,
Martin
