### ISSUE TITLE
shorter mcc folder naming

### ISSUE THREAD

**Issue by sandeepganji** [ExploreASL/ExploreASL#87]
It may better for avoid file path length errors to shorten the MCC output folder names and also document it in the wiki.

![Win10pro_Matlab2020a-2020-08-12-22-36-41](https://user-images.githubusercontent.com/12124746/90094073-9fd5b280-dcf2-11ea-9b92-6ac99e96b100.png)

**Comment by MichaelStritt** [comment]
Hey Sandeep, we had the same idea. The date versioning was pretty helpful for the development phase, but now we will use a simple format. Will be fixed as soon as we merge #32 (see commit 718c93b).

**Comment by MichaelStritt** [comment]
Should be solved with the recent squash merge of feature branch #32 into develop
