### ISSUE TITLE
xASL_wrp_LinearReg_T1w2MNI detecting ASL4D twice

### ISSUE THREAD

**Issue by BeatrizPadrela** [ExploreASL/ExploreASL#873]
### Description

In the xASL_wrp_LinearReg_T1w2MNI, which is needed for the registration, there are predefined paths of where the ASL4D.nii should be, and they it searches for other scans and identifies the ASL4D.nii again (line71) even if there's no dwi and func folders:

![image](https://user-images.githubusercontent.com/73699072/136060726-40dc67d2-a6b2-410f-a4f7-91c74a76e537.png)
![image](https://user-images.githubusercontent.com/73699072/136060899-ae63bd58-1c79-4c7d-81b9-98d711b878e8.png)
![image](https://user-images.githubusercontent.com/73699072/136062130-70140d07-e202-414c-910b-807457631ea5.png)

So what happens is that the ASL4D is registered twice to the T1, so the second time it becomes an image that is clearly not registered to the T1. Henk and I discovered this when I was trying to convert the CEST (as ASL4D) nifti to MNI space, because right after the registration (where other files that are in the subject's folder are also registered to the T1), the CEST image and the T1 weren't matching (when overlapped with fsl eyes).

 

### How to test

I tested it this way:
Creating the SubjectsFolders, where it looks for folders inside the Subject's folder and only keeps the ones that do exist.
![image](https://user-images.githubusercontent.com/73699072/136068668-a56832f4-4372-4583-8bb2-4dfe9c210a9a.png)

### Release notes

Avoid spurious double registration of ASL to T1w.

**Comment by MichaelStritt** [comment]
@BeatrizPadrela & @jan-petr: Is there more work to be done here? Does Beatriz code already work? Did you run some tests?

**Comment by jan-petr** [comment]
The issues wasn't that DWI and FUNC were added - this wasn't adding ASL twice. What was adding it twice was running it for all sessions and adding ASL4D.nii from the current session = twice for two session studies

But with the new edit e2a0815 - it will potentially add more files from ASL_1 directory?!

So I prefer to do this a232d7c to run DWI and FUNC on a single session. And make sure that for multi-session, we are adding ASL for each session and not always the same session.
