### ISSUE TITLE
Processing options from ASL4D.json not loaded in time

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#897]
### Description

xASL_module_ASL loads the dataPar.json with processing options. At line 86 initializes missing ones to default. And at line ~130 already checks some of them - notably the options checking if M0 is in ASL etc.

The issue is that certain options like "DummyScanPositionInASL4D" can be both in dataPar.json and in ASL4D.json. The ASL4D.json should have a priority, but the trouble is that it is loaded only too late at line 171 and thus is missing for the initial steps.

### Comments
This is fixed. We simply first loaded dataPar.json, then separated M0 from ASL and only then loaded ASL4D.json. So for this initial sorting - any special info from ASL4D.json was ignored. I now load this info and include it right at the start of the ASL module. I keep the previous loading also later in the code to be sure that we don't overwrite the ASL4D.json information with data extracted from previous x.mat - so that's why the loading is on two places now.

### Release notes

Load processing options from ASL4D.json in time.

**Comment by HenkMutsaerts** [comment]
@jan-petr can you remove this issue and the associated branch?
