### ISSUE TITLE
Do not use parfor in xASL_Iteration or elsewhere

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#902]
Remove use of parfor

Also `parfor` needs to be removed from:
* `/Functions/xASL_Iteration` line 243
* `/External/SPMmodified/toolbox/cat12/cat_surf_epivolsurf.m`
* `/External/SPMmodified/spm_dcm_fit.m`
* `/Development/StatsAnalysis/StatTestCompare/StatTrial.m`

### Release note
Stop using Distributed computing and Parallel Toolboxes and parfor.

**Comment by jan-petr** [comment]
@MichaelStritt I have no idea how to read this - can you please add a bit more details to the issue description.

**Comment by MichaelStritt** [comment]
> 
> 
> @MichaelStritt I have no idea how to read this - can you please add a bit more details to the issue description.

I used the GitHub feature where you create a new issue based on a comment 😆
You can nicely click on the comment though. 
I'm actually not so sure what Henk wants either 😉 

![image](https://user-images.githubusercontent.com/46593074/141679749-43ea4eef-5607-42c4-997a-ec7df9038480.png)

**Comment by MichaelStritt** [comment]
@HenkMutsaerts suggested to fade out the parfor support.
