### ISSUE TITLE
Revamp initialization structure of `xASL_module_ASL`

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#911]
### Description

Revamp initialization structure of `xASL_module_ASL`. 

### Requirements

The order of the initialization was wrong, causing default parameters to override `asl4d.json`. This is now fixed.
We now run the following initialization steps in `xASL_module_ASL`:

>> % A. Check if ASL exists, otherwise skip this module
% B. Manage mutex state — processing step
% C. Cleanup before rerunning
%
% D - ASL processing parameters
% D1. Load ASL parameters (inheritance principle)
% D2. Default ASL processing settings in the x.modules.asl field
% D3. Multi-PLD parsing
% D4. TimeEncoded parsing
% D5. Multi-TE parsing
%
% E - ASL quantification parameters
% E1. Default quantification parameters in the Q field
% E2. Define sequence (educated guess based on the Q field)
% F. Backward and forward compatibility of filenames
% G. Split ASL and M0 within the ASL time series
% H. Skip processing if invalid image

### How to test

Test by running `xASL_qc_TestExploreASL`. The results for macOS intel 2019a look good, except for `Philips_2DEPI_Lesion*`, which misses the PVC value because of the limited FoV. @jan-petr do you remember if we fixed this already?

<img width="827" alt="image" src="https://user-images.githubusercontent.com/27774254/141659292-3c727c92-1c96-49a7-a558-d864c0b300bc.png">

### Release notes

Revamp initialization structure of xASL_module_ASL to restore a correct order of all steps.

**Comment by HenkMutsaerts** [comment]
@MichaelStritt does this still work with the header style you need for the documentation?

**Comment by MichaelStritt** [comment]
> 
> 
> @MichaelStritt does this still work with the header style you need for the documentation?

Sure, this shouldn't break anything 👍
