### ISSUE TITLE
Make <ROOT> in xASL_Iteration BIDS compatible

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#915]
Yes and no. During the import the `<ROOT>` string is our BIDS dataset root. During processing, `<ROOT>` historically was the root of the ExploreASL legacy data. In theory we could change this for the processing, but that would require more extensive testing and right now everything seems to be stable.

_Originally posted by @MichaelStritt in https://github.com/ExploreASL/ExploreASL/pull/872#discussion_r748818891_

Henk suggested to add rawroot, sourceroot, etc. to xASL_Iteration, later on we update the full xASL pipeline

**Comment by HenkMutsaerts** [comment]
Duplicate with #1275
