### ISSUE TITLE
BIDS2Legacy issue with certain subject names

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#923]
### Description

BIDS2Legacy crashes for `Philips_PCASL_2DEPI_3.2.2.1_2` because it doesn't convert anything from BIDS.

- The issue is the name 'EMI_301' - the '_' is lost during the process...
- Dcm2niix still creates 'EMI_301' in `temp`.
- In rawdata, I already have 'sub_EMI301' and not 'sub_EMI_301' so later, BIDS2Legacy relies on information from sourcedata (wrongly) and doesn't find the subject in rawdata. 
- We need to skip the `_` and replace by an empty character in these places:
   - reading subject structure
   - DCM2NII
   - NII2BIDS
- Function `xASL_imp_CheckForAliasInVisit` inside `xASL_imp_NII2BIDS_Subject` seems to be doing that for me.
- At line 92, subjectName is still `EMI_301`, but `bidsLabel.subject = xASL_adm_CorrectName` shortens it to `EMI301`.

What I propose is that we need to remove all `_` in patient names systematically and also in session/visit names as these are also in BIDS.

### Release notes

Improve import modularity and BIDS format of subject IDs.

**Comment by MichaelStritt** [comment]
@jan-petr: Really? For me it only shows the differences of the `GeneratedBy` fields.

```
COMPARISON TABLE:
                flavor                 dataset              name                                            message                              
    _______________________________    _______    ________________________    ___________________________________________________________________

    'Philips_PCASL_2DEPI_3.2.2.1_2'    'Both'     'Different file content'    'Different file content: dataset_description.json'                 
    'Philips_PCASL_2DEPI_3.2.2.1_2'    'Both'     'Different file content'    'Different file content: \ExploreASL\dataset_description.json'     
    'Philips_PCASL_2DEPI_3.2.2.1_2'    'Both'     'Different file content'    'Different file content: \ExploreASL\sub-EMI301_1\ASL_1\ASL4D.json'
    'Philips_PCASL_2DEPI_3.2.2.1_2'    'Both'     'Different file content'    'Different file content: \ExploreASL\sub-EMI301_1\ASL_1\M0.json'   
    'Philips_PCASL_2DEPI_3.2.2.1_2'    'Both'     'Different file content'    'Different file content: \ExploreASL\sub-EMI301_1\FLAIR.json'      
    'Philips_PCASL_2DEPI_3.2.2.1_2'    'Both'     'Different file content'    'Different file content: \ExploreASL\sub-EMI301_1\T1.json'         

LOGGING TABLE:
```

**Comment by MichaelStritt** [comment]
@jan-petr: I can't reproduce the defect, not even on the AMC linux server.

![image](https://user-images.githubusercontent.com/46593074/141943365-e7313a26-92be-43ee-88a8-77126edf231d.png)

Are you sure your flavors were up-to-date?

**Comment by MichaelStritt** [comment]
While reading the sourcedata, the name in the overview field is still correct. If we use `-` instead of `_` we have to change it here too, though.

![image](https://user-images.githubusercontent.com/46593074/142389721-bb1fb7dc-a79b-4b19-b9a6-d531723acb25.png)

**Comment by MichaelStritt** [comment]
@jan-petr: For me it seems as if this isn't fully correct according to BIDS. At least the validation using bids-matlab regular expressions raises a warning if we use a dash within the subject `<label>`. I added an option ( c9a6dba ) for the dash replacement, so if you want, then we can add this in `xASL_imp_CheckForAliasInVisit` during `bidsLabel.subject = xASL_adm_CorrectName`, but at least for me this does not seem correct.

![image](https://user-images.githubusercontent.com/46593074/142394172-0e450e56-8c86-462f-ac48-a47899e002a3.png)

**Comment by MichaelStritt** [comment]
@jan-petr: to me it really seems like BIDS only allows letters and numbers in subject ids or do you see anything that shows the opposite?
