### ISSUE TITLE
xASL_SysMove - cmd line level error

### ISSUE THREAD

**Issue by MauricePasternak** [ExploreASL/ExploreASL#93]
When it happens: Near the start of the Population Module in the script file xASL_SysMove

Not a problem with the xASL_SysMove script itself. My interpretation is that Window's cmd line move command simply does not like filenames with the character '=' in them. This makes filepaths with basenames like "T1_n=6_bs-mean_temp.nii" fail on line 61 in xASL_SysMove. Verified by manually inputting that same command in the Windows cmd line and getting "'The syntax of the command is incorrect".

Using the old name format "T1_bs-mean_temp.nii" and changing the filename to that format no longer causes this problem. Workspaces from breakpoints immediately after line 61 attached. 

[ASLSysMove_Error.zip](https://github.com/ExploreASL/ExploreASL/files/5086365/ASLSysMove_Error.zip)

**Comment by MauricePasternak** [comment]
That fixed it insofar as the move command on Windows is concerned. Important note for future updates - Windows move doesn't work well with characters like "=".

Please be aware that a different bug appears downstream at line 323 within the xASL_wrp_CreatePopulationTemplates.m file that was altered. 'Undefined function or variable 'Sets2Check'

I see that the variable is attempted to be defined earlier in that script file but in some user cases, like mine, it will never be defined. Specifically, on line 118 in xASL_wrp_CreatePopulationTemplates.m, if bCompute4Sets is 0, then Sets2Check is will not have the opportunity to be defined. Should probably have an "else" statement around that area to define Sets2Check as an empty container if the variable does not exist.

**Comment by jan-petr** [comment]
Good work fixing this issue - but again - if we want to make it a hotfix 1.2.1, then we need to create a new hotfix branch and not merge to develop.
