### ISSUE TITLE
Remove legacy import

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#932]
### Description

When debugging the import module, I still find the old import. Even though this is in a folder that is not added/initialized by default, we probably came to the point where this is more confusing than helpful to the user. Users that want to keep using the old import may also want to use the older folder structure etc, so this is not compatible anymore in our newer versions of ExploreASL. I would remove the older import versions, internally we can still keep them for testing and comparing though.

### Requirements

Remove the legacy import
@MichaelStritt do you agree?

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here

**Comment by MichaelStritt** [comment]
Agree, users can download the old version so we can remove it from the new one.
