### ISSUE TITLE
ASL-BIDS parameters have wrong order of magnitude in JSON sidecars

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#96]
Try with the TestDataSet, which has a JSON sidecar with SliceReadoutTime == 43 ms.
This becomes 4*10^3 inside ExploreASL :)

**Comment by HenkMutsaerts** [comment]
## ToDo
* Jan: give a warning when parameter it's outside it's normal range
* Henk: change the sidecar JSONs from seconds to ms manually in TestDataSet
* Henk: check which users have used the _xASL_bids_DataPar2JSON.m_ function with incorrect conversion
* Jan: remove the explicit TE & TR conversion from seconds to ms, for both _xASL_bids_DataPar2JSON.m_ & _xASL_bids_InsertJSONFields.m_
* Jan: add xASL_bids_parms2JSON conversion in the xASL_bids_DataPar2JSON.m

**Comment by jan-petr** [comment]
## Finalized

## Done and needs to be checked (person to check and move to Finalized)
* Henk: give a warning when parameter it's outside it's normal range - check the range on line 54 of xASL_bids_parms2BIDS.
* Henk: Fixed an issue that parameters for converting from BIDS to xASL were missed if their name was also changed. line 141-146 of xASL_bids_parms2BIDS. This, however, had no previous consequences in old data, as this applied previously to zero cases.
* Henk: Line 213 of xASL_bids_parms2BIDS - for xASL output, we were moving wrong parameters to the x.Q - now the correct parameters are moved to Q and removed from the main structure. This might have had some consequences, but maybe the quantification scripts found the data correctly outside of Q.

## ToDo
* Henk: change the sidecar JSONs from seconds to ms manually in TestDataSet
* Henk: check which users have used the _xASL_bids_DataPar2JSON.m_ function with incorrect conversion
* Jan: remove the explicit TE & TR conversion from seconds to ms, for both _xASL_bids_DataPar2JSON.m_ & _xASL_bids_InsertJSONFields.m_
* Jan: add xASL_bids_parms2JSON conversion in the xASL_bids_DataPar2JSON.m

**Comment by jan-petr** [comment]
Oops - added another commit, but forgot to mention the issue number.

**Comment by HenkMutsaerts** [comment]
So we need to move your commit to here? I need to teach you how to undo your commit...

I found out that we have the same issue with the other parameters such as labeling duration/PLD, so we have to fix this as well in release 1.2.1
