### ISSUE TITLE
Incorrect sourceStructure.json warning 

### ISSUE THREAD

**Issue by MDijsselhof** [ExploreASL/ExploreASL#965]
### Description

Currently Matlab can crash if the `sourceStructure.json` isn't correct, however this does not provide an error or means to investigate where the crash originates. By implementing a warning stating `Reading sourceStructure.json, if Matlab crashes this file is not properly formatted` the user knows where to look.

### Release notes

Duplicate to #1159

**Comment by jan-petr** [comment]
I've changed a lot of warnings in spm_jsonread to make it clear that it was this function that crashed, and I also first output a text that spm_jsonread is reading a file and print this filename on screen.

That should hopefully fix the issue - can you please check this in branch #1159 that it correctly outputs the message before crashing Matlab in your case?
