### ISSUE TITLE
Clarify atlas references

### ISSUE THREAD

**Issue by HenkMutsaerts** [ExploreASL/ExploreASL#969]
### Description

I was getting a result from the `MNI_Structural` atlas for a colleague, from a 2019 analysis, and when searching for the reference, I got the following questions:

* is the MNI_Structural atlas replaced by the `Mindboggle` (free for commercial use)? If this is the case, I would still like to put the `MNI_Structural` atlas back for the academics, since it is more known than the `Mindboggle` atlas (unless the two are virtually identical)
* the references are not completely clear to me, also when comparing `https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Atlases` with `/External/Atlases/Documents/*`

### Requirements

Optional: add feature requirements here

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here

**Comment by MichaelStritt** [comment]
> is the MNI_Structural atlas replaced by the Mindboggle (free for commercial use)? 

Why would that be the case? We just added another atlas. We didn't replace one with the other.

> If this is the case, I would still like to put the MNI_Structural atlas back for the academics, since it is more known than the Mindboggle atlas (unless the two are virtually identical)

What do you mean with put it back? Was it gone? I never replaced anything there.

> the references are not completely clear to me, also when comparing https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Atlases with /External/Atlases/Documents/*

I mean, some stuff wasn't there before. I don't know who created the original atlases.

**Comment by HenkMutsaerts** [comment]
Apologies, I should we replaced the atlas, I see now that the `MNI_Structural` still exists.

**Comment by HenkMutsaerts** [comment]
I will fix this by:

* Move `/External/SPMmodified/MapsAdded/MNI_Structural.nii` to `/External/Atlases`
