### ISSUE TITLE
xASL_im_GetMeanControl

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#971]
### Description

- [x] xASL_im_GetMeanControl general function to create mean control from Hadamard, single PLD etc to a single function.
- [x] Fix header of GetControlLabelOrder function (note that this works also for multiPLD without changes needed.

-> inside the new xASL_quant_GetMeanControl function: 
- [x] for Hadamard - don't take only the 1st repetition, but all repetitions of control (which are later averaged)
- [x] for Hadamard - take only the first TE.

### Release notes

Mean control image creation in a separate function.

**Comment by BeatrizPadrela** [comment]
@jan-petr the code I've added, works for the repetitions of Controls and also for the first TE because the first volume of the control is also the first TE. What do you think?
