### ISSUE TITLE
Import and processing don't run together

### ISSUE THREAD

**Issue by jan-petr** [ExploreASL/ExploreASL#979]
### Description

I tried to run the import and processing of Philips Hadamard data, but running ExploreASL('pathHadamardPhilips,1,1) didn't do it.
But running ExploreASL(path,1,0) and then ExploreASL(path,0,1) worked perfectly.

### Requirements

Optional: add bug requirements here

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here

**Comment by MichaelStritt** [comment]
That's really weird. I may have to find out why it doesn't work on windows at all. Will check it out as soon as possible.

**Comment by MichaelStritt** [comment]
### Running it in one go

After data loading:

![image](https://user-images.githubusercontent.com/46593074/145688984-bf5546fe-b9bf-43fe-8965-e0345b86e034.png)

### Running import & processing separately

After data loading:

![image](https://user-images.githubusercontent.com/46593074/145689006-1956adf7-4a2d-4905-a98b-285d52f76ada.png)

**Comment by MichaelStritt** [comment]
@jan-petr: Maybe we just have to remove x.SESSION and x.SESSIONS after the import (before data loading) and check if it correctly puts them back in during the data loading?
