### ISSUE TITLE
xASL Report

### ISSUE THREAD

**Issue by MichaelStritt** [ExploreASL/ExploreASL#984]
### Description

I'm working on a more general population based report. I had some ideas and did an exemplary implementation. An Example is shown here: [xASL_report.pdf](https://github.com/ExploreASL/ExploreASL/files/7687469/xASL_report.pdf)

I know the images still have to be rotated and maybe we can get them to align a bit better, but in general I think a report over multiple pages could be super useful.

### How to test

- [ ] We should test subjects with one to five sessions, since it is supposed to cut off after four images at the moment.
- [ ] It is also supposed to skip missing images.
- [ ] It is also supposed to overwrite existing population based reports.

### Release notes

Duplicate. Now done in #1225

**Comment by maartenhammer** [comment]
Question about switching subject. 
The current function:
function [x, IsLoaded] = xASL_adm_LoadX(x, Path_xASL, bOverwrite) 
If you input a value in path_xasl (the location of x.mat) it will overwrite x.Output and x.IM_Output but not x.dir.Subject for example.  
So for example, you can have a struct where x.dir.SUBJECTDIR is sub1 and x.output.subject is sub 4 as x.dir.subjectDIR is never changed. 
I dont know if other values in the x structure are subject specific, but the function only replaces the x.output and x.im_output.

If the currently subject in memory x is different than the one you load, should it not also change all other references to subject and/or clear data related to different subjects. 
How is this handled when you go from one subject to the next in full pipeline? Does it fully clear all subject specific values?
